(function(){
'use strict';var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},e="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function ba(a,b){if(b){var c=e;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}
ba("String.prototype.repeat",function(a){return a?a:function(a){if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");var b=this;if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=b),a>>>=1)b+=b;return d}});function ca(){ca=function(){};e.Symbol||(e.Symbol=da)}var da=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function ea(){ca();var a=e.Symbol.iterator;a||(a=e.Symbol.iterator=e.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(this)}});ea=function(){}}function fa(a){var b=0;return ha(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ha(a){ea();a={next:a};a[e.Symbol.iterator]=function(){return this};return a}
ba("Array.from",function(a){return a?a:function(a,c,d){ea();c=null!=c?c:function(a){return a};var b=[],g=a[Symbol.iterator];if("function"==typeof g)for(a=g.call(a);!(g=a.next()).done;)b.push(c.call(d,g.value));else{g=a.length;for(var k=0;k<g;k++)b.push(c.call(d,a[k]))}return b}});
function ia(a,b){ea();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}ba("Array.prototype.keys",function(a){return a?a:function(){return ia(this,function(a){return a})}});
ba("Array.prototype.fill",function(a){return a?a:function(a,c,d){var b=this.length||0;0>c&&(c=Math.max(0,b+c));if(null==d||d>b)d=b;d=Number(d);0>d&&(d=Math.max(0,b+d));for(c=Number(c||0);c<d;c++)this[c]=a;return this}});
var ja={addc:"vec2 addc(vec2 a,vec2 b){\nreturn a+b;\n}\n",arccosc:"vec2 arccosc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=addc(multc(logc(tmp1),vec2(0.0,1.0)),vec2(pi*0.5,0.0));\nreturn erg;\n}\n",arccosf:"vec2 arccosf(float z){\nif(abs(z)<=1.)return vec2(acos(z),0.);\nelse if(z>1.)return vec2(0,log(z+sqrt(z*z-1.)));\nelse return vec2(pi, -log(-z+sqrt(z*z-1.)));\n}\n",arcsinc:"vec2 arcsinc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=multc(logc(tmp1),vec2(0.0,-1.0));\nreturn erg;\n}\n",
arcsinf:"vec2 arcsinf(float z){\nif(abs(z)<=1.)return vec2(asin(z),0.);\nelse if(z>1.)return vec2(pi*.5, -log(z+sqrt(z*z-1.)));\nelse return vec2(-pi*.5,log(-z+sqrt(z*z-1.)));\n}\n",arctan2c:"\n\n\n\nvec2 arctan2c(vec2 x,vec2 y){\nvec2 r=logc(divc(x+vec2(-y.y,y.x),sqrtc(multc(x,x)+multc(y,y))));\nreturn vec2(r.y, -r.x);\n}\n",arctan2cvec2:"vec2 arctan2cvec2(cvec2 v){\nreturn arctan2c(v.real,v.imag);\n}\n",arctan2vec2:"float arctan2vec2(vec2 v){\nreturn atan(v.y,v.x);\n}\n",arctanc:"vec2 arctanc(vec2 a){\nvec2 t1=logc(addc(multc(a,vec2(0.0,-1.0)),vec2(1.0,0.0)));\nvec2 t2=logc(addc(multc(a,vec2(0.0,1.0)),vec2(1.0,0.0)));\nvec2 erg=multc(subc(t1,t2),vec2(0.0,0.5));\nreturn erg;\n}\n",
blue:"vec3 blue(float f)\n{\nreturn vec3(0.,0.,clamp(f,0.,1.));\n}\n",cimag:"float imagc(vec2 a){\nreturn a.y;\n}\n",conjugate:"vec2 conjugate(vec2 a){\nreturn vec2(a.x, -a.y);\n}\n",copytexture_f:"#ifdef GL_ES\nprecision highp float;\n#endif\n\nuniform sampler2D sampler;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_FragColor=texture2D(sampler,cgl_pixel);\n}\n",copytexture_v:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_Position=vec4(aPos,1.);\ncgl_pixel=aTexCoord;\n}\n",
cosc:"vec2 cosc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat i= (imag1+imag2) /2.0;\nfloat r= (real1+real2) /2.0;\n\nreturn vec2(r,i);\n}\n",creal:"float realc(vec2 a){\nreturn a.x;\n}\n",dehomogenize:"vec2 dehomogenize(vec3 z){\nreturn vec2(z.x,z.y)/z.z;\n}\n",divc:"vec2 divc(vec2 a,vec2 b){\nreturn vec2(dot(a,b),dot(a,vec2(-b.y,b.x)))/dot(b,b);\n}\n",divfc:"vec2 divfc(float a,vec2 b){\nreturn a*vec2(b.x,-b.y)/dot(b,b);\n}\n",
expc:"vec2 expc(vec2 a){\nfloat n=exp(a.x);\nfloat r=n*cos(a.y);\nfloat i=n*sin(a.y);\nreturn vec2(r,i);\n}\n",float2color:"vec4 float2color(float f)\n{\nreturn vec4(f,f,f,1.);\n}\n",gray:"vec3 gray(float f)\n{\nf=clamp(f,0.,1.);\nreturn vec3(f,f,f);\n}\n",green:"vec3 green(float f)\n{\nreturn vec3(0.,clamp(f,0.,1.),0.);\n}\n",hsv2rgb:"vec3 hsv2rgb(vec3 c)\n{\nvec4 K=vec4(1.0,2.0/3.0,1.0/3.0,3.0);\nvec3 p=abs(fract(c.xxx+K.xyz) *6.0-K.www);\nreturn c.z*mix(K.xxx,clamp(p-K.xxx,0.0,1.0),c.y);\n}\n",
hue:"vec3 hue(float a){\nreturn hsv2rgb(vec3(a,1.,1.));\n}\n",imagc:"float imagc(vec2 a){\nreturn a.y;\n}\n",invc:"vec2 invc(vec2 a){\nfloat n=a.x*a.x+a.y*a.y;\nreturn vec2(a.x/n,-a.y/n);\n}\n",logc:"vec2 logc(vec2 a){\nfloat re=a.x;\nfloat im=a.y;\nfloat s=sqrt(re*re+im*im);\nfloat i=im;\nfloat imag=atan(im,re);\nif(i<0.0){\nimag+= (2.0*pi);\n}\nif(i==0.0&&re<0.0){\nimag=pi;\n}\nif(imag>pi){\nimag-= (2.0*pi);\n};\nfloat real=log(s);\n\nreturn vec2(real,imag);\n}\n",logr:"vec2 logr(float a){\nif(a>=0.)return vec2(log(a),0);\nelse return vec2(log(-a),pi);\n}\n",
mat2complex:"mat4 mat2complex(mat2 a)\n{\nreturn mat4(\nvec4(a[0][0],0,a[0][1],0),\nvec4(0,a[0][0],0,a[0][1]),\nvec4(a[1][0],0,a[1][1],0),\nvec4(0,a[1][0],0,a[1][1])\n);\n}\n",multc:"vec2 multc(vec2 a,vec2 b){\nreturn vec2(dot(a,vec2(b.x,-b.y)),dot(a,b.yx));\n}\n",negc:"vec2 negc(vec2 a){\nreturn vec2(-a.x,-a.y);\n}\n",powc:"vec2 powc(vec2 a,vec2 b){\nreturn(b.x==0. &&b.y==0.) ?vec2(1.,0.) : ((a.x==0. &&a.y==0.) ?vec2(0.) :expc(multc(logc(a),b)));\n}\n",powi:"float powi(float a,int b){\nif(mod(float(b),2.) < .5)\nreturn pow(abs(a),float(b));\nelse\nreturn sign(a)*pow(abs(a),float(b));\n}\n",
random:"uniform float rnd_;\n\nfloat last_rnd= .1231;\nfloat random(){\nfloat a=fract(132422.21*sin(dot(plain_pixel,343433.671228*vec2(.176574+last_rnd, .1131+rnd_))));\nfloat b=fract(last_rnd*2321.2312*sin(dot(plain_pixel+vec2(rnd_,last_rnd),plain_pixel) *43758.5453));\nlast_rnd=fract(rnd_ +last_rnd+a+b);\nreturn last_rnd;\n}\n",randomnormal:"float randomnormal(){\nreturn sqrt(-2. *log(random())) *cos(6.283185307179586*random());\n}\n",realc:"float realc(vec2 a){\nreturn a.x;\n}\n",red:"vec3 red(float f)\n{\nreturn vec3(clamp(f,0.,1.),0.,0.);\n}\n",
rgb2hsv:"vec3 rgb2hsv(vec3 c)\n{\nvec4 K=vec4(0.0, -1.0/3.0,2.0/3.0, -1.0);\nvec4 p=mix(vec4(c.bg,K.wz),vec4(c.gb,K.xy),step(c.b,c.g));\nvec4 q=mix(vec4(p.xyw,c.r),vec4(c.r,p.yzx),step(p.x,c.r));\n\nfloat d=q.x-min(q.w,q.y);\nfloat e=1.0e-10;\nreturn vec3(abs(q.z+ (q.w-q.y) / (6.0*d+e)),d/ (q.x+e),q.x);\n}\n",sinc:"\n\nvec2 sinc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat r= -(imag1-imag2) /2.0;\nfloat i= (real1-real2) /2.0;\n\nreturn vec2(r,i);\n}\n",
sqrtc:"vec2 sqrtc(vec2 a){\nreturn expc(multc(logc(a),vec2(0.5,0.0)));\n}\n",sqrtf:"vec2 sqrtf(float a){\nif(a>=0.)return vec2(sqrt(a),0.);\nelse return vec2(0.,sqrt(-a));\n}\n",standardFragmentHeader:"#ifdef GL_ES\nprecision highp float;\nprecision highp int;\n#endif\n\n#define pi 3.141592653589793\n\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\n",subc:"vec2 subc(vec2 a,vec2 b){\nreturn a-b;\n}\n",tanc:"vec2 tanc(vec2 a){\nvec2 s=sinc(a);\nvec2 c=cosc(a);\nreturn divc(s,c);\n}\n",vec2complex:"vec4 vec2complex(vec2 a)\n{\nreturn vec4(a.x,0.,a.y,0);\n}\n",
vshader:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\nuniform mat3 transformMatrix;\nvoid main(void){\ngl_Position=vec4(aPos,1.);\nplain_pixel=aTexCoord;\nvec3 r=transformMatrix*vec3(plain_pixel,1);\ncgl_pixel=r.xy/r.z;\n}\n"};var ka=!1,h,m,n,r,v=!1,na,w=!1,oa=!1,pa=1;
function qa(){function a(c){h.removeEventListener("webglcontextcreationerror",a,!1);c.statusMessage&&(b=c.statusMessage)}if(!ka){h=document.createElement("canvas");h.id="glcanvas";h.style.display="none";h.width=h.height=0;document.body.appendChild(h);m=document.createElement("canvas");m.id="tmpcanvas";m.style.display="none";m.width=m.height=0;document.body.appendChild(m);var b="Unknown";h.addEventListener("webglcontextcreationerror",a,!1);(n=h.getContext("webgl"))||(n=h.getContext("experimental-webgl"));
if(!n)throw new ra("Could not obtain a WebGL context.\nReason: "+b);h.removeEventListener("webglcontextcreationerror",a,!1);oa||(w=n.getExtension("OES_texture_float")&&n.getExtension("OES_texture_float_linear"),w||(console.error("Your browser does not suppert OES_texture_float, trying OES_texture_half_float..."),(v=(na=n.getExtension("OES_texture_half_float"))&&n.getExtension("OES_texture_half_float_linear"))||console.error("Your browser does not suppert OES_texture_half_float, will use 8-bit textures.")),
navigator.userAgent.match(/(iPad|iPhone)/i)&&(console.log("You are  using an iPhone/iPad."),w=v=!1,n.getExtension("OES_texture_half_float")&&n.getExtension("OES_texture_half_float_linear")&&n.getExtension("EXT_color_buffer_half_float")?v=!0:console.error("Your browser does not suppert writing to half_float textures, we will use 8-bit textures.")));ka=!0}};function sa(a){if(null==a||"object"!=typeof a)return a;if(a instanceof Array){var b=[];for(var c=0,d=a.length;c<d;c++)b[c]=sa(a[c]);return b}if(a instanceof Object){b={};for(c in a)a.hasOwnProperty(c)&&(0<="oper impl args ctype stack name arglist value real imag key obj body".split(" ").indexOf(c)&&(b[c]=sa(a[c])),a.modifs&&(b.modifs=a.modifs));return b}}
function ta(a,b){if(null==a||"object"!=typeof a)return a===b;if(a instanceof Array&&b instanceof Array){if(a.length!=b.length)return!1;for(var c=0,d=a.length;c<d;c++)if(!ta(a[c],b[c]))return!1;return!0}if(a instanceof Object&&b instanceof Object){c="oper impl args ctype stack name modifs arglist value real imag key obj body".split(" ");for(d=0;d<c.length;d++){var f=c[d];if(!ta(a[f],b[f]))return!1}return!0}return!1}function x(a){return-1===a.indexOf("$")?a:a.substr(0,a.indexOf("$"))}
function y(a){if("boolean"===a.ctype)return z.A;if("number"===a.ctype)return a=a.value,1E-5>Math.abs(a.imag)?(a.real|0)===a.real?z.u:z.f:z.h;if("list"===a.ctype){var b=a.value;if(0<b.length){for(var c=y(b[0]),d=1;d<b.length;d++)c=A(c,y(b[d]));if(c)return{type:"list",length:b.length,parameters:c}}}else if("string"===a.ctype||"image"===a.ctype)return z.image;console.error("Cannot guess type of the following type:");console.log(a);return!1}var ua=0;function B(){ua++;return"_h"+ua}
function va(a,b){if(a>h.width||b>h.height)h.width=Math.ceil(a),h.height=Math.ceil(b)}function wa(a,b,c){a=a.getInitialMatrix();b-=a.tx;c+=a.ty;return{x:(b*a.d-c*a.b)/a.det,y:-(-b*a.c+c*a.a)/a.det}}function xa(a){return wa(a,0,a.instance.canvas.clientHeight)}function ya(a){return wa(a,a.instance.canvas.clientWidth,a.instance.canvas.clientHeight)}var za=new Float32Array(1),Aa=new Int32Array(za.buffer);
function Ba(a){za[0]=a;a=Aa[0];var b=a>>16&32768,c=(a&2147483647)+4096;if(1199570944<=c)return 1199570944<=(a&2147483647)?2139095040>c?b|31744:b|31744|(a&8388607)>>13:b|31743;if(947912704<=c)return b|c-939524096>>13;if(855638016>c)return b;c=(a&2147483647)>>23;return b|(a&8388607|8388608)+(8388608>>>c-102)>>126-c}
function Ca(a){if(w)return new Float32Array(a);if(v){for(var b=new Uint16Array(a.length),c=0;c<a.length;c++)b[c]=Ba(a[c]);return b}b=new Uint8Array(a.length);for(c=0;c<a.length;c++)b[c]=255*a[c];return b}function Da(a){return w?new Float32Array(a):v?new Uint16Array(a):new Uint8Array(a)}function Ea(){return w?n.FLOAT:v?na.HALF_FLOAT_OES:n.UNSIGNED_BYTE}
function Fa(a){for(var b=[],c=0;c<a.length;c++)if(w)b.push(a[c]);else if(v){var d=a[c],f=(d&31744)>>10,g=d&1023;b.push((d>>15?-1:1)*(f?31===f?g?NaN:Infinity:Math.pow(2,f-15)*(1+g/1024):g/1024*6.103515625E-5))}else b.push(a[c]/255);return b}function Ga(a){for(var b=1;b<a;)b<<=1;return b};function Ha(a,b){a.canvaswrapper?b&&Ia(a.canvaswrapper,b):(a.canvaswrapper=new Ja(a,b||{R:!0,J:!1,repeat:!1}),a.ready||(console.error("Image not ready. Creating onload event."),a.whenReady(function(){a.generation=Math.max(a.generation,a.canvaswrapper.generation+1)})));return a.canvaswrapper}
function Ja(a,b){this.canvas=a;this.i=b;this.I=a.width;this.D=a.height;Ka(this);this.P=0;this.l=[];this.$=[];this.generation=-1;this.bindTexture();a.drawTo=this.drawTo.bind(this);a.readPixels=this.na.bind(this);a.cdyUpdate=this.pa.bind(this);a=Da(this.W*this.K*4);for(var c=0;2>c;c++)this.l[c]=n.createTexture(),n.bindTexture(n.TEXTURE_2D,this.l[c]),n.pixelStorei(n.UNPACK_ALIGNMENT,1),n.texImage2D(n.TEXTURE_2D,0,n.RGBA,this.W,this.K,0,n.RGBA,Ea(),a),b.J?n.texParameteri(n.TEXTURE_2D,n.TEXTURE_MIN_FILTER,
b.R?n.LINEAR_MIPMAP_LINEAR:n.NEAREST_MIPMAP_LINEAR):n.texParameteri(n.TEXTURE_2D,n.TEXTURE_MIN_FILTER,b.R?n.LINEAR:n.NEAREST),n.texParameteri(n.TEXTURE_2D,n.TEXTURE_MAG_FILTER,b.R?n.LINEAR:n.NEAREST),this.$[c]=n.createFramebuffer(),n.bindFramebuffer(n.FRAMEBUFFER,this.$[c]),n.framebufferTexture2D(n.FRAMEBUFFER,n.COLOR_ATTACHMENT0,n.TEXTURE_2D,this.l[c],0);this.Z=new La(ja.copytexture_v,ja.copytexture_f);b=n.createBuffer();n.bindBuffer(n.ARRAY_BUFFER,b);b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,
1,0]);a=n.getAttribLocation(this.Z.i,"aPos");n.enableVertexAttribArray(a);c=n.getAttribLocation(this.Z.i,"aTexCoord");n.enableVertexAttribArray(c);var d=new Float32Array([0,0,1,0,0,1,1,1]),f=b.byteLength;n.bufferData(n.ARRAY_BUFFER,f+d.byteLength,n.STATIC_DRAW);n.bufferSubData(n.ARRAY_BUFFER,0,b);n.bufferSubData(n.ARRAY_BUFFER,f,d);n.vertexAttribPointer(a,3,n.FLOAT,!1,0,0);n.vertexAttribPointer(c,2,n.FLOAT,!1,0,f)}
function Ia(a,b){var c=a.i;if(b&&(b.repeat!=c.repeat||b.J!=c.J||b.R!=c.R))for(a.i=b,c=0;2>c;c++)n.bindTexture(n.TEXTURE_2D,a.l[c]),b.J?n.texParameteri(n.TEXTURE_2D,n.TEXTURE_MIN_FILTER,b.R?n.LINEAR_MIPMAP_LINEAR:n.NEAREST_MIPMAP_LINEAR):n.texParameteri(n.TEXTURE_2D,n.TEXTURE_MIN_FILTER,b.R?n.LINEAR:n.NEAREST),n.texParameteri(n.TEXTURE_2D,n.TEXTURE_MAG_FILTER,b.R?n.LINEAR:n.NEAREST)}function Ka(a){a.W=Ga(a.I+a.I/2*(a.i.J&&a.i.repeat));a.K=Ga(a.D+a.D/2*(a.i.J&&a.i.repeat))}
Ja.prototype.bindTexture=function(){n.bindTexture(n.TEXTURE_2D,this.l[this.P])};Ja.prototype.bindFramebuffer=function(){n.bindFramebuffer(n.FRAMEBUFFER,this.$[this.P^1]);this.P^=1};
Ja.prototype.pa=function(){if(this.canvas.img.hasOwnProperty("getContext"))var a=this.canvas.img.getContext("2d");else this.canvas.img=document.createElement("canvas"),this.canvas.img.style.display="none",this.canvas.img.width=this.I,this.canvas.img.height=this.D,a=this.canvas.img.getContext("2d");a.clearRect(0,0,this.I,this.D);this.drawTo(a,0,0);this.canvas.img.generation++};
function Ma(a){if(!(a.canvas.live&&(a.canvas.img.webkitDecodedFrameCount||a.canvas.img.i)&&a.ja>=(a.canvas.img.webkitDecodedFrameCount||a.canvas.img.i)||!a.canvas.live&&(!a.canvas.ready||a.generation>=a.canvas.generation))){if(a.I!=a.canvas.width||a.D!=a.canvas.height){a.I=a.canvas.width;a.D=a.canvas.height;Ka(a);for(var b=Da(a.W*a.K*4),c=0;2>c;c++)n.bindTexture(n.TEXTURE_2D,a.l[c]),n.texImage2D(n.TEXTURE_2D,0,n.RGBA,a.W,a.K,0,n.RGBA,Ea(),b)}a.bindTexture();n.pixelStorei(n.UNPACK_FLIP_Y_WEBGL,1);
a.i.repeat?(m.width=a.W,m.height=a.K,b=m.getContext("2d"),b.drawImage(a.canvas.img,0,a.K-a.D),b.drawImage(a.canvas.img,a.I,a.K-a.D),b.drawImage(a.canvas.img,0,a.K-2*a.D),b.drawImage(a.canvas.img,a.I,a.K-2*a.D),n.texSubImage2D(n.TEXTURE_2D,0,0,0,n.RGBA,Ea(),m)):n.texSubImage2D(n.TEXTURE_2D,0,0,0,n.RGBA,Ea(),a.canvas.img);a.i.J&&n.generateMipmap(n.TEXTURE_2D);n.pixelStorei(n.UNPACK_FLIP_Y_WEBGL,0);a.generation=a.canvas.generation;a.ja=Math.min(a.ja+1,a.canvas.img.webkitDecodedFrameCount||a.canvas.img.i)}}
Ja.prototype.drawTo=function(a,b,c){va(this.I,this.D);n.viewport(0,0,this.W,this.K);n.useProgram(this.Z.i);n.activeTexture(n.TEXTURE0);n.bindTexture(n.TEXTURE_2D,this.l[this.P]);this.Z.l.sampler([0]);n.bindFramebuffer(n.FRAMEBUFFER,null);n.drawArrays(n.TRIANGLE_STRIP,0,4);n.flush();a.drawImage(h,0,h.height-this.D,this.I,this.D,b,c,this.I,this.D)};
Ja.prototype.na=function(a,b,c,d){n.bindFramebuffer(n.FRAMEBUFFER,this.$[this.P]);n.framebufferTexture2D(n.FRAMEBUFFER,n.COLOR_ATTACHMENT0,n.TEXTURE_2D,this.l[this.P],0);var f=Da(c*d*4);n.readPixels(a,this.D-b-d,c,d,n.RGBA,Ea(),f);a=[];for(--d;0<=d;d--)a=a.concat(Fa(f.slice(d*c*4,(d+1)*c*4)));return a};function Na(a,b){this.B=a;this.P=b;Oa(this)}
function Oa(a){var b=Pa(new Qa(a.B),a.P);a.l=b.C;a.N=b.N;a.fa=b.fa;a.Z=ja.standardFragmentHeader+b.code;a.$=ja.vshader;a.i=new La(a.$,a.Z);b=n.createBuffer();n.bindBuffer(n.ARRAY_BUFFER,b);b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,1,0]);var c=n.getAttribLocation(a.i.i,"aPos");n.enableVertexAttribArray(c);a=n.getAttribLocation(a.i.i,"aTexCoord");n.enableVertexAttribArray(a);var d=new Float32Array([0,0,1,0,0,1,1,1]),f=b.byteLength;n.bufferData(n.ARRAY_BUFFER,f+d.byteLength,n.STATIC_DRAW);n.bufferSubData(n.ARRAY_BUFFER,
0,b);n.bufferSubData(n.ARRAY_BUFFER,f,d);n.vertexAttribPointer(c,3,n.FLOAT,!1,0,0);n.vertexAttribPointer(a,2,n.FLOAT,!1,0,f)}
function Ra(a){function b(a,c,d){if(a)if("function"===typeof a)switch(c){case z.h:a([d.value.real,d.value.imag]);break;case z.A:d.value?a([1]):a([0]);break;case z.u:case z.f:a([d.value.real]);break;default:if("list"===c.type&&c.parameters===z.f)a(d.value.map(function(a){return a.value.real}));else if("list"===c.type&&"list"===c.parameters.type&&c.parameters.parameters===z.f){for(var f=[],g=0;g<c.length;g++)for(var k=0;k<c.parameters.length;k++)f.push(d.value[g].value[k].value.real);a(f)}else console.error("Don't know how to set uniform of type "+
C(c)+", to "+d)}else if("list"===c.type)if(g=Sa(c),1===D(c)&&g===z.f){c=Ta(c.length);var l=0;for(f in c)b(a["a"+f],z.aa(c[f]),{ctype:"list",value:E(c[f]).map(function(a){return d.value[l+a]})}),l+=c[f]}else for(f=0;f<c.length;f++)b(a["a"+f],c.parameters,{ctype:"list",value:d.value[f].value});else console.error("Don't know how to set uniform of type "+C(c)+", to"),console.log(d)}for(var c in a.l){var d=a.B.evaluateAndVal(a.l[c].V),f=a.l[c].type;if(!F(Ua(d),f)){console.log("Type of "+c+" changed ("+
C(Ua(d))+" is no subtype of  "+C(f)+"); forcing rebuild.");Oa(a);n.useProgram(a.i.i);Ra(a);return}a.i.l[c]&&b(a.i.l[c],f,d)}[["rnd_",function(){return[Math.random()]}],["_lowerleft",function(){var b=xa(a.B);return[b.x,b.y]}],["_lowerright",function(){var b=ya(a.B);return[b.x,b.y]}]].map(function(b){return a.i.l[b[0]]&&a.i.l[b[0]](b[1]())})}
function Va(a){var b=0,c;for(c in a.N){n.activeTexture(n.TEXTURE0+b);var d=a.N[c],f=d.name;d=Wa(d);Ma(d);d.bindTexture();[["_sampler"+f,[b]],["_ratio"+f,[d.I/d.D]],["_cropfact"+f,[d.I/d.W,d.D/d.K]]].map(function(b){return a.i.l[b[0]]&&a.i.l[b[0]](b[1])});b++}};CindyJS.registerPlugin(1,"CindyGL",function(a){function b(b,d,f,g,k,l){if(!b.la||b.ka<pa)b.la=!0,b.ka=pa,b.oa=new Na(a,b);b=b.oa;a:{for(c in b.fa)if(b.B.getMyfunction(c).generation>b.fa[c]){console.log(c+" is outdated; forcing rebuild.");var c=!1;break a}c=!0}c||Oa(b);var t=k/g;c=d.x+-(f.y-d.y)*t;t=d.y+(f.x-d.x)*t;va(g,k);l?n.viewport(0,0,g,k):n.viewport(0,h.height-k,g,k);n.useProgram(b.i.i);Ra(b);d=[f.x-d.x,c-d.x,d.x,f.y-d.y,t-d.y,d.y,0,0,1];b.i.l.hasOwnProperty("transformMatrix")&&b.i.l.transformMatrix([d[0],
d[3],d[6],d[1],d[4],d[7],d[2],d[5],d[8]]);Va(b);l?(l.bindFramebuffer(),l.generation=++l.canvas.generation):n.bindFramebuffer(n.FRAMEBUFFER,null);n.drawArrays(n.TRIANGLE_STRIP,0,4);n.flush();l&&(l.generation=Math.max(l.generation,l.canvas.generation+1))}r=a.nada;a.defineFunction("compile",1,function(b){b=Pa(new Qa(a),b[0]);console.log(b);return{ctype:"string",value:b}});a.defineFunction("use8bittextures",0,function(){oa=!0;w=v=!1;console.log("Switching to 8-bit textures mode.");return a.nada});a.defineFunction("forcerecompile",
0,function(){pa++;return r});a.defineFunction("colorplot",1,function(c){qa();var d=a.instance.canvas.clientWidth,f=a.instance.canvas.clientHeight,g=a.instance.canvas.width,k=a.instance.canvas.height;b(c[0],xa(a),ya(a),g,k,null);a.instance.canvas.getContext("2d").drawImage(h,0,0,g,k,0,0,d,f);return r});a.defineFunction("colorplot",3,function(c){qa();var d=c[0],f=a.extractPoint(a.evaluateAndVal(c[1])),g=a.extractPoint(a.evaluateAndVal(c[2])),k={x:Math.min(f.x,g.x),y:Math.min(f.y,g.y)},l={x:Math.max(f.x,
g.x),y:Math.min(f.y,g.y)};c=a.instance.canvas.clientWidth;var p=a.instance.canvas.clientHeight,t=a.instance.canvas.width,q=a.instance.canvas.height,u=wa(a,0,0),G=xa(a),T=ya(a);T=Math.abs((f.x-g.x)/(G.x-T.x));u=Math.abs((f.y-g.y)/(u.y-G.y));b(d,k,l,t*T,q*u,null);d=a.instance.canvas.getContext("2d");k=Math.min(f.x,g.x);f=Math.max(f.y,g.y);g=a.getInitialMatrix();d.drawImage(h,0,0,t*T,q*u,k*g.a-f*g.b+g.tx,k*g.c-f*g.d-g.ty,T*c,u*p);return r});a.defineFunction("colorplot",4,function(c){qa();var d=a.extractPoint(a.evaluateAndVal(c[0])),
f=a.extractPoint(a.evaluateAndVal(c[1])),g=a.evaluateAndVal(c[2]);c=c[3];if(!d.ok||!f.ok||"string"!==g.ctype)return r;g=a.getImage(g.value,!0);var k=Ha(g,!1);b(c,d,f,g.width,g.height,k);return r});a.defineFunction("colorplot",2,function(c){qa();var d=xa(a),f=ya(a),g=a.evaluateAndVal(c[0]);c=c[1];if("string"!==g.ctype)return r;g=a.getImage(g.value,!0);var k=Ha(g,!1);b(c,d,f,g.width,g.height,k);return r});a.defineFunction("setpixel",4,function(b){var c=a.evaluateAndVal(b[0]);var f=void 0===f?null:f;
if("string"===c.ctype)var g=c.value;else console.log("argument is not a string"),g=f;c=Xa(a.evaluateAndVal(b[1]));f=Xa(a.evaluateAndVal(b[2]));b=Ya(a.evaluateAndVal(b[3]));if(!g)return r;var k=a.getImage(g,!0);k=Ha(k,!1);isFinite(c)&&isFinite(f)&&g&&k&&b&&(k.bindTexture(),g=[b[0],b[1],b[2],1],n.texSubImage2D(n.TEXTURE_2D,0,c,f,1,1,n.RGBA,Ea(),Ca(g)),b=k.canvas.img.getContext("2d"),k=b.createImageData(1,1),k.data.d=g,b.putImageData(k,c,f));return r})});function H(a,b){return{type:"list",length:a,parameters:b}}function Ua(a){return{type:"constant",value:a}}function Za(a){return Ua({ctype:"number",value:{real:a,imag:0}})}var z={A:1,u:2,f:3,h:4,U:5,color:6,M:7,line:8,H:9,image:10,L:H(2,3),O:H(3,3),ba:H(4,3),aa:function(a){return H(a,3)},ea:function(a){return H(a,4)},ra:H(2,H(2,3)),sa:H(3,H(3,3)),ta:H(4,H(4,3))};Object.freeze(z);
function C(a){return 1<=a&&10>=a?"bool int float complex voidt color point line coordinate2d image".split(" ")[a-1]:"list"===a.type?C(a.parameters)+"["+a.length+"]":"constant"===a.type?"const["+JSON.stringify(a.value.value)+"]":JSON.stringify(a)}function I(a){return"list"===a.type&&I(a.parameters)||F(a,z.f)}function J(a){return"list"===a.type&&J(a.parameters)||F(a,z.h)}function $a(a){return"constant"===a.type&&F(a,z.u)}function K(a){return"constant"===a.type?y(a.value):a}
function D(a){return"list"===a.type?D(a.parameters)+1:0}function Sa(a){return void 0!==a.parameters?Sa(a.parameters):a}function ab(a,b){return D(a)===D(b)&&(0===D(a)||a.length===b.length&&ab(a.parameters,b.parameters))}function L(a){return F(a,z.f)?z.f:F(a,z.h)?z.h:{type:"list",length:a.length,parameters:L(a.parameters)}}function bb(a){return F(a,z.h)?z.h:{type:"list",length:a.length,parameters:bb(a.parameters)}}
function M(a){return a===z.A||a===z.u||a===z.f||a===z.h||"list"===a.type&&a.parameters===z.f&&1<=a.length&&4>=a.length||"list"===a.type&&"list"===a.parameters.type&&a.parameters.parameters===z.f&&a.length===a.parameters.length&&2<=a.length&&4>=a.length}function cb(a){return-1!==[z.A,z.u,z.f,z.h].indexOf(a)}function db(a,b){return a===b||"constant"===a.type&&"constant"===b.type&&ta(a.value,b.value)||"list"===a.type&&"list"===b.type&&a.length===b.length&&db(a.parameters,b.parameters)}
function F(a,b){return db(a,b)?!0:a?cb(a)&&cb(b)?a<=b:"constant"===b.type?!1:"constant"===a.type?F(y(a.value),b):b===z.H?F(a,z.h)||F(a,z.L)||F(a,z.M):b===z.M||b===z.line?F(a,z.O):b===z.color?F(a,z.f)||"list"===a.type&&(3===a.length||4===a.length)&&F(a.parameters,z.f):"list"===a.type&&"list"===b.type&&a.length===b.length?F(a.parameters,b.parameters):!1:!1}
function A(a,b){if(!a)return b;if(!b||db(a,b))return a;"constant"===a.type&&(a=y(a.value));"constant"===b.type&&(b=y(b.value));return cb(a)&&cb(b)?Math.max(a,b):"list"===a.type&&"list"===b.type&&a.length===b.length&&(b=A(a.parameters,b.parameters))?{type:"list",length:a.length,parameters:b}:!1}
function N(a){return function(b){var c={},d;for(d in a){var f=a[d];c.da=f[0];if(b.length==c.da.length&&b.every(function(a){return function(b,c){return F(b,a.da[c])}}(c)))return{s:c.da,v:f[1],o:f[2]};c={da:c.da}}return!1}}
function eb(a){switch(a){case z.u:return N([[[z.A],z.u,O("int")]]);case z.f:return N([[[z.A],z.f,O("float")],[[z.u],z.f,O("float")]]);case z.h:return N([[[z.f],z.h,function(a){return"vec2("+a+", 0.)"}]]);case z.color:return N([[[z.f],z.color,P("float2color")],[[z.O],z.color,function(a){return"vec4("+a+",1.0)"}],[[z.ba],z.color,Q]]);case z.M:return N([[[z.L],z.M,function(a){return"vec3("+a+",1.0)"}],[[z.O],z.M,Q]]);case z.line:return N([[[z.L],z.line,function(a){return"vec3("+a+",1.0)"}],[[z.O],z.line,
Q]]);case z.H:return N([[[z.h],z.H,Q],[[z.L],z.H,Q],[[z.M],z.H,P("dehomogenize")]]);default:if("list"===a.type)return function(b){var c=b[0],d=eb(a.parameters)([c.parameters]).o;return{s:b,v:a,o:function(b,g,k){return fb(a)(E(a.length).map(function(a){return d([R(c,a)([b],g,k)],g,k)}),g,k)}}}}console.log("no inclusionfunction ->"+C(a)+" implemented yet; using identity...");return function(b){return{s:b,v:a,o:Q}}}
function S(a){switch(a){case z.A:return"bool";case z.u:return"int";case z.f:return"float";case z.h:case z.H:return"vec2";case z.U:return"void";case z.color:return"vec4";case z.M:case z.line:return"vec3"}if("list"===a.type&&a.parameters===z.f)return 1==a.length?"float":"vec"+a.length;if("list"===a.type&&a.parameters===z.h)return"cvec"+a.length;if("list"===a.type&&"list"===a.parameters.type&&a.length===a.parameters.length&&a.parameters.parameters===z.f)switch(a.length){case 2:return"mat2";case 3:return"mat3";
case 4:return"mat4"}if("list"===a.type)return"l"+a.length+"_"+S(a.parameters);console.error("No WebGL implementation for type "+C(a)+" found")}function gb(a,b){switch(b){case z.A:return S(b)+"("+a.value+")";case z.u:return""+(a.value.real|0);case z.f:return S(b)+"("+a.value.real+")";case z.h:return S(b)+"("+a.value.real+", "+a.value.imag+")";case z.color:return a=a.value.real,"vec4("+a+","+a+","+a+",1.)";default:console.error("Dont know how to paste values of Type "+C(b)+" yet.")}};var U={};function hb(a,b,c){if(!c.mark("includedfunctions",a)){for(var d in U[a])hb(U[a][d],b,c);c.add("includedfunctions",a,function(){return ja[a]})}}function P(a){return function(b,c,d){hb(a,c,d);return O(a)(b)}};function E(a){return Array.from(Array(a).keys())}function Ta(a){return 4>=a?[a]:5==a?[2,3]:Ta(a-4).concat([4])}function ib(a){var b=Sa(a),c=D(a);return 1==c&&b===z.f?Ta(a.length).map(function(a,b){return{type:z.aa(a),name:"a"+b}}):1<=c?E(a.length).map(function(b){return{type:a.parameters,name:"a"+b}}):[]}function jb(a,b){if(!M(a)){var c=S(a);b.add("structs",c,function(){return"struct "+c+" { "+ib(a).map(function(a){return jb(a.type,b)||S(a.type)+" "+a.name+";"}).join("")+"};"})}}
function kb(a,b,c){if(!M(a)){var d=a.length,f=a.parameters.length;c.add("functions","mult"+d+"_"+f,function(){return S(z.aa(d))+" mult"+d+"_"+f+"("+S(a)+" a, "+S(z.aa(f))+" b){return "+lb(d)(E(d).map(function(a){return mb(f)(["a.a"+a,"b"],b,c)}),b,c)+";}"})}}
function nb(a,b,c){if(!M(a)){var d=a.length,f="sum"+S(a);c.add("functions",f,function(){return S(a.parameters)+" "+f+"("+S(a)+" a){"+(S(a.parameters)+" res = "+ob(a.parameters,0)([],b,c)+";\n      "+E(d).map(function(d){return"res = "+pb(a.parameters)(["res",R(a,d)(["a",d],b,c)],b,c)+";"}).join("\n")+"\n        return res;\n    }")})}}
function qb(a,b,c){var d=a.length,f=a.parameters.length;c.add("functions","multc"+d+"_"+f,function(){return S(z.ea(d))+" multc"+d+"_"+f+"("+S(a)+" a, "+S(z.ea(f))+" b){\n        return cvec"+d+"("+E(d).map(function(a){return rb(f)(["a.a"+a,"b"],b,c)})+");\n    }\n    "})}function sb(a,b){2<=a&&4>=a||b.add("functions","dot"+a,function(){return"float dot"+a+"(vec"+a+" a, vec"+a+" b) {\n    return "+Ta(a).map(function(a,b){return"dot(a.a"+b+",b.a"+b+")"}).join("+")+"; }\n    "})}
function tb(a,b){b.add("functions","cdot"+a,function(){return"vec2 cdot"+a+"(cvec"+a+" a, cvec"+a+" b) {\n      return "+E(a).map(function(a){return"vec2(dot(a.a"+a+",vec2(b.a"+a+".x,-b.a"+a+".y)), dot(a.a"+a+",b.a"+a+".yx))"}).join("+\n")+";\n    }\n    "})}
function ub(a,b,c){var d="add"+S(a);c.add("functions",d,function(){return S(a)+" "+d+"("+S(a)+" a, "+S(a)+" b) {\n    return "+S(a)+"("+ib(a).map(function(a){return S(a.type)+"("+pb(a.type)(["a."+a.name,"b."+a.name],b,c)+")"}).join(",")+");\n      }"})}
function vb(a,b,c){var d="sub"+S(a);c.add("functions",d,function(){return S(a)+" "+d+"("+S(a)+" a, "+S(a)+" b) {\n    return "+S(a)+"("+ib(a).map(function(a){return S(a.type)+"("+wb(a.type)(["a."+a.name,"b."+a.name],b,c)+")"}).join(",")+");\n    }"})}function xb(a,b,c){var d="scalarmult"+S(a);c.add("functions",d,function(){return S(a)+" "+d+"(float a, "+S(a)+" b) {\n    return "+S(a)+"("+ib(a).map(function(a){return S(a.type)+"("+yb(a.type)(["a","b."+a.name],b,c)+")"}).join(",")+");\n    }"})}
function zb(a,b,c){hb("multc",b,c);var d="cscalarmult"+S(a);c.add("functions",d,function(){return S(a)+" "+d+"(vec2 a, "+S(a)+" b) {\n    return "+S(a)+"("+ib(a).map(function(a){return""+Ab(a.type)(["a","b."+a.name],b,c)}).join(",")+");\n    }"})}
function Bb(a){if(a===z.h)return P("multc");if(M(a))return function(a){return V("*")([a[1],a[0]])};var b=Sa(a);if(F(b,z.f))return function(b,d,f){return kb(a,d,f)||"mult"+a.length+"_"+a.parameters.length+"("+b.join(",")+")"};if(b===z.h)return function(b,d,f){return qb(a,d,f)||"multc"+a.length+"_"+a.parameters.length+"("+b.join(",")+")"}}function mb(a){return function(b,c,d){return sb(a,d)||"dot"+(2<=a&&4>=a?"":a)+"("+b.join(",")+")"}}
function rb(a){return function(b,c,d){return tb(a,d)||"cdot"+a+"("+b.join(",")+")"}}function pb(a){return M(a)?V("+"):function(b,c,d){return ub(a,c,d)||"add"+S(a)+"("+b.join(",")+")"}}function wb(a){return M(a)?V("-"):function(b,c,d){return vb(a,c,d)||"sub"+S(a)+"("+b.join(",")+")"}}function Cb(a){return I(a)&&1==D(a)?function(b,c,d){return mb(a.length)([b[0],lb(a.length)(Array(a.length).fill("1."),c,d)],c,d)}:function(b,c,d){return nb(a,c,d)||"sum"+S(a)+"("+b.join(",")+")"}}
function lb(a){if(2<=a&&4>=a)return function(b){return"vec"+a+"("+b.join(",")+")"};if(1==a)return function(a){return"float("+a.join(",")+")"};var b=0;return function(c,d,f){return jb(z.aa(a),f)||"vec"+a+"("+Ta(a).map(function(a){return"vec"+a+"("+E(a).map(function(){return++b&&c[b-1]}).join(",")+")"}).join(",")+")"}}function fb(a){return M(a)?function(b){return S(a)+"("+b.join(",")+")"}:1==D(a)&&a.parameters===z.f?lb(a.length):function(b,c,d){return jb(a,d)||S(a)+"("+b.join(",")+")"}}
function R(a,b){var c=Sa(a);return 1==D(a)&&c===z.f?Db(a.length,b):M(a)?function(a){return"("+a[0]+")["+b+"]"}:function(a){return"("+a[0]+").a"+b}}function ob(a,b){return M(a)?function(){return S(a)+"(float("+b+"))"}:function(c,d,f){return fb(a)+"("+ib(a).map(function(a){return ob(a.type,b)(c,d,f)}).join(",")+")"}}
function Db(a,b){return function(c){if(1==a)return c[0];if(2<=a&&4>=a)return"("+c[0]+")["+b+"]";a:{var d=b;var f=Ta(a),g;for(g in f)if(f[g]<=d)d-=f[g];else{d={first:g,second:d};break a}console.error("Accessing index out of range");d=void 0}return"("+c[0]+").a"+d.first+"["+d.second+"]"}}function yb(a){return M(a)?V("*"):function(b,c,d){return xb(a,c,d)||"scalarmult"+S(a)+"("+b.join(",")+")"}}
function Ab(a){return a===z.h?P("multc"):function(b,c,d){return zb(a,c,d)||"cscalarmult"+S(a)+"("+b.join(",")+")"}}function Eb(a,b,c){var d="reverse"+S(a);c.add("functions",d,function(){return S(a)+" "+d+"("+S(a)+" a){"+(S(a.parameters)+" m;\n")+E(Math.floor(a.length/2)).map(function(d){var f=R(a,d)(["a",d],b,c);d=R(a,a.length-1-d)(["a",a.length-1-d],b,c);return"m = "+f+"; "+f+" = "+d+"; "+d+" = m;"}).join("\n")+"return a;\n      }"})}
function Fb(a){return function(b,c,d){return Eb(a,c,d)||"reverse"+S(a)+"("+b.join(",")+")"}}function Gb(a,b,c){var d="max"+S(a);c.add("functions",d,function(){return S(a.parameters)+" "+d+"("+S(a)+" a){"+(S(a.parameters)+" m = "+R(a,a.length-1)(["a",a.length-1],b,c)+";\n")+E(a.length-1).map(function(d){return"m = max(m,"+R(a,d)(["a",d],b,c)+");"}).join("\n")+"return m;\n      }"})}function Hb(a){return function(b,c,d){return Gb(a,c,d)||"max"+S(a)+"("+b.join(",")+")"}}
function Ib(a,b,c){var d="min"+S(a);c.add("functions",d,function(){return S(a.parameters)+" "+d+"("+S(a)+" a){"+(S(a.parameters)+" m = "+R(a,a.length-1)(["a",a.length-1],b,c)+";\n")+E(a.length-1).map(function(d){return"m = min(m,"+R(a,d)(["a",d],b,c)+");"}).join("\n")+"return m;\n      }"})}function Jb(a){return function(b,c,d){return Ib(a,c,d)||"min"+S(a)+"("+b.join(",")+")"}};function Kb(a){function b(a,d,k){if(1<d){var f=d/2|0;b(a,f,!k);b(a+f,d-f,k);c(a,d,k)}}function c(a,b,k){if(1<b){var f;for(f=1;f<b;)f<<=1;f>>=1;for(var g=a;g<a+b-f;g++){var t=g,q=g+f;k?d.push([t,q]):d.push([q,t])}c(a,f,k);c(a+f,b-f,k)}}var d=[];b(0,a,!0);return d}
function Lb(a,b,c){var d="sort"+S(a);c.add("functions",d,function(){return S(a)+" "+d+"("+S(a)+" a){"+(S(a.parameters)+" m;\n")+Kb(a.length).map(function(d){var f=R(a,d[0])(["a",d[0]],b,c);d=R(a,d[1])(["a",d[1]],b,c);return"m = min("+f+","+d+"); "+d+" = max("+f+","+d+"); "+f+" = m;"}).join("\n")+"return a;\n      }"})}function Mb(a){return function(b,c,d){return Lb(a,c,d)||"sort"+S(a)+"("+b.join(",")+")"}};function O(a){return function(b){return x(a)+"("+b+")"}}function V(a){return function(b){return"("+b.join(a)+")"}}function Q(a){return a}var W={};W.join=N([[[z.M,z.M],z.line,O("cross")]]);W.meet=N([[[z.line,z.line],z.M,O("cross")]]);W.gauss=N([[[z.h],z.L,Q]]);W.complex=N([[[z.L],z.h,Q]]);
W["if"]=function(a){if(!a.every(function(a){return a}))return!1;if(2===a.length)return{s:a,v:a[1],o:function(a){return"if("+a[0]+") {"+a[1]+";}"}};if(3===a.length){var b=A(a[1],a[2]);return b?{s:[z.A,b,b],v:b,o:function(a){return"("+a[0]+" ? "+a[1]+" : "+a[2]+")"}}:{s:a,v:z.U,o:function(a){return"if("+a[0]+") {"+a[1]+";} else {"+a[2]+";}"}}}return!1};W["="]=function(a){a=A(a[0],a[1]);return{s:a,v:a,o:function(a){return a[0]+" = "+a[1]+";"}}};
W[";"]=function(a){return{s:a,v:a[1]!==z.U?a[1]:a[0],o:function(a){return a[0]+" ; "+a[1]+";"}}};W.repeat=function(a){return 2!=a.length&&3!=a.length||!$a(a[0])?!1:{s:a,v:a[a.length-1],o:function(){return""}}};W.forall=function(a){return 2!=a.length&&3!=a.length||"list"!==K(a[0]).type?!1:{s:a,v:a[a.length-1],o:function(){return""}}};W.apply=function(a){return 2!=a.length&&3!=a.length||"list"!==K(a[0]).type?!1:{s:a,v:H(K(a[0]).length,a[a.length-1]),o:function(){return""}}};
W.sum=function(a){return 1==a.length&&(I(a[0])||J(a[0]))?{s:a,v:a[0].parameters,o:Cb(a[0])}:!1};W.regional=function(a){return{s:a,v:z.U,o:function(){return""}}};W.sqrt=N([[[z.f],z.h,P("sqrtf")],[[z.h],z.h,P("sqrtc")]]);W.abs=N([[[z.f],z.f,O("abs")],[[z.h],z.f,O("length")],[[z.L],z.f,O("length")],[[z.O],z.f,O("length")],[[z.ba],z.f,O("length")]]);W.abs_infix=W.abs;
W.dist=N([[[z.f,z.f],z.f,function(a){return O("abs")(V("-")(a))}],[[z.h,z.h],z.f,function(a){return O("length")(V("-")(a))}],[[z.L,z.L],z.f,function(a){return O("length")(V("-")(a))}],[[z.O,z.O],z.f,function(a){return O("length")(V("-")(a))}],[[z.ba,z.ba],z.f,function(a){return O("length")(V("-")(a))}]]);W.dist_infix=W.dist;W.sin=N([[[z.f],z.f,O("sin")],[[z.h],z.h,P("sinc")]]);W.cos=N([[[z.f],z.f,O("cos")],[[z.h],z.h,P("cosc")]]);W.tan=N([[[z.f],z.f,O("tan")],[[z.h],z.h,P("tanc")]]);
W.exp=N([[[z.f],z.f,O("exp")],[[z.h],z.h,P("expc")]]);W.arctan=N([[[z.f],z.f,O("atan")],[[z.h],z.h,P("arctanc")]]);W.arcsin=N([[[z.f],z.h,P("arcsinf")],[[z.h],z.h,P("arcsinc")]]);W.arccos=N([[[z.f],z.h,P("arccosf")],[[z.h],z.h,P("arccosc")]]);W.log=N([[[z.f],z.h,P("logr")],[[z.h],z.h,P("logc")]]);var Nb=[2,3,4].map(function(a){return H(a,z.f)}).concat([2,3,4].map(function(a){return H(a,H(a,z.f))})),Ob=[z.u,z.f,z.h].concat(Nb);
W.add=function(a){var b=N(Ob.map(function(a){return[[a,a],a,V("+")]}))(a);if(b)return b;b=a[0];a=a[1];if([b,a].every(function(a){return I(a)||J(a)})&&ab(b,a))return a=A(L(b),L(a)),{s:[a,a],v:a,o:pb(a)}};W.sub=function(a){var b=N(Ob.map(function(a){return[[a,a],a,V("-")]}).concat(Ob.map(function(a){return[[z.U,a],a,V("-")]})))(a);if(b)return b;b=a[0];a=a[1];if([b,a].every(function(a){return I(a)||J(a)})&&ab(b,a))return a=A(L(b),L(a)),{s:[a,a],v:a,o:wb(a)}};W["+"]=W.add;W["-"]=W.sub;
W._=function(a){var b=K(a[0]);if("list"===b.type&&$a(a[1])){var c=Number(a[1].value.value.real);return 1<=Math.abs(c)&&Math.abs(c)<=b.length?(0<c&&--c,0>c&&(c=b.length+c),{s:a,v:b.parameters,o:R(b,c)}):{s:a,v:b.parameters,o:function(){return console.error("try to access "+c+"-th Element of "+b.length+"-list "+JSON.stringify(a[0]))}}}return!1};
W.mult=function(a){var b=N([[[z.u,z.u],z.u,V("*")],[[z.f,z.f],z.f,V("*")],[[z.h,z.f],z.h,V("*")],[[z.f,z.h],z.h,V("*")],[[z.h,z.h],z.h,P("multc")]])(a);if(b)return b;if(2!==a.length)return!1;b=a[0];var c=a[1];if([b,c].every(function(a){return"list"===a.type&&F(a.parameters,z.f)})&&b.length===c.length)return a=L(b),M(a)?{s:[a,a],v:z.f,o:O("dot")}:{s:[a,a],v:z.f,o:mb(b.length)};if([b,c].every(function(a){return"list"===a.type&&F(a.parameters,z.h)})&&b.length===c.length)return a=bb(b),{s:[a,a],v:z.h,
o:rb(b.length)};if(I(b)&&2===D(b)&&I(c)&&1===D(c)&&b.parameters.length===c.length)return{s:[L(b),L(c)],v:z.aa(b.length),o:Bb(L(b))};if(J(b)&&2===D(b)&&J(c)&&1===D(c)&&b.parameters.length===c.length)return{s:[bb(b),bb(c)],v:z.ea(b.length),o:Bb(bb(b))};for(b={F:0};2>b.F;b={X:b.X,F:b.F,ca:b.ca},b.F++){if(F(a[0^b.F],z.f)&&(I(a[1^b.F])||J(a[1^b.F])))return b.X=L(a[1^b.F]),{s:b.F?[b.X,z.f]:[z.f,b.X],v:b.X,o:function(a){return function(b,c,d){return yb(a.X)([b[0^a.F],b[1^a.F]],c,d)}}(b)};if(F(a[0^b.F],z.h)&&
J(a[1^b.F]))return b.ca=bb(a[1^b.F]),{s:b.F?[b.ca,z.h]:[z.h,b.ca],v:b.ca,o:function(a){return function(b,c,d){return Ab(a.ca)([b[0^a.F],b[1^a.F]],c,d)}}(b)}}};W["*"]=W.mult;W.div=function(a){var b=N([[[z.f,z.f],z.f,V("/")],[[z.f,z.h],z.h,P("divfc")],[[z.h,z.f],z.h,V("/")],[[z.h,z.h],z.h,P("divc")]])(a);return b?b:F(a[1],z.f)&&J(a[0])&&(a=L(a[0]),M(a))?{s:[a,z.f],v:a,o:V("/")}:!1};W["/"]=W.div;W.re=N([[[z.h],z.f,P("realc")]]);W.im=N([[[z.h],z.f,P("imagc")]]);
W.floor=N([[[z.f],z.u,function(a){return"int(floor("+a+"))"}],[[z.h],z.h,O("floor")]]);W.round=N([[[z.f],z.u,function(a){return"int(floor("+a+"+.5))"}],[[z.h],z.h,function(a){return"floor("+a+"+vec2(.5))"}]]);W.ceil=N([[[z.f],z.u,function(a){return"int(ceil("+a+"))"}],[[z.h],z.h,O("ceil")]]);W.mod=N([[[z.u,z.u],z.u,function(a,b){return"int("+O("mod")("float("+a[0]+"), float("+a[1]+")",b)+")"}],[[z.f,z.f],z.f,O("mod")],[[z.h,z.h],z.h,P("mod")]]);
W.random=N([[[],z.f,P("random")],[[z.f],z.f,function(a,b,c){return P("random")([],b,c)+"*"+a[0]}],[[z.h],z.h,function(a,b,c){return"vec2("+P("random")([],b,c)+","+P("random")([],b,c)+")*"+a[0]}]]);W.randomint=N([[[z.u],z.u,function(a,b,c){return"int(floor("+P("random")([],b,c)+"*float("+a[0]+")))"}],[[z.f],z.u,function(a,b,c){return"int(floor("+P("random")([],b,c)+"*floor("+a[0]+")))"}]]);W.randominteger=W.randomint;W.randombool=N([[[],z.A,function(a,b,c){return"("+P("random")([],b,c)+">.5)"}]]);
W.randomnormal=N([[[],z.f,P("randomnormal")]]);W.arctan2=N([[[z.f,z.f],z.f,function(a){return"atan("+a[1]+", "+a[0]+")"}],[[z.h,z.h],z.h,P("arctan2c")],[[z.h],z.f,P("arctan2vec2")],[[z.L],z.f,P("arctan2vec2")],[[z.ea(2)],z.h,P("arctan2cvec2")]]);["red","green","blue","gray","hue"].forEach(function(a){W[a]=N([[[z.f],z.O,P(a)]])});W.grey=W.gray;W.min=function(a){var b=N([[[z.f,z.f],z.f,O("min")]])(a);if(b)return b;if(1===a.length&&1===D(a[0])&&I(a[0]))return{s:a,v:a[0].parameters,o:Jb(a[0])}};
W.max=function(a){var b=N([[[z.u,z.u],z.u,O("max")],[[z.f,z.f],z.f,O("max")]])(a);if(b)return b;if(1===a.length&&1===D(a[0])&&I(a[0]))return{s:a,v:a[0].parameters,o:Hb(a[0])}};function Pb(a,b){if(!(1>=a))if(2==a)b.add("functions","raise2",function(){return"float raise2(float a) { return a*a; }"});else{Pb(2,b);var c=function(a,b){return 1==b?a:b&1?c(a,b-1)+"*a":"raise2("+c(a,b/2)+")"},d="raise"+a;b.add("functions",d,function(){return"float "+d+"(float a) { return "+c("a",a)+";}"})}}
function Qb(a){return function(b,c,d){return 0==a?"1.":1==a?b[0]:Pb(a,d)||"raise"+a+"("+b[0]+")"}}W.pow=function(a){if($a(a[1])&&F(a[0],z.f)){var b=Number(a[1].value.value.real);if(0<=b)return{s:[z.f,a[1]],v:z.f,o:Qb(b)}}return N([[[z.f,z.u],z.f,P("powi")],[[z.h,z.h],z.h,P("powc")]])(a)};W["^"]=W.pow;W.re=N([[[z.h],z.f,function(a){return"("+a+").x"}]]);W.conjugate=N([[[z.h],z.h,P("conjugate")]]);W.im=N([[[z.h],z.f,function(a){return"("+a+").y"}]]);
W.genList=function(a){var b=a.length;if(0<b){var c=!1,d;for(d in a)c=A(c,a[d]);if(c)return a=H(b,c),{s:Array(b).fill(c),v:a,o:fb(a)}}return!1};W["&"]=N([[[z.A,z.A],z.A,V("&&")]]);W["%"]=N([[[z.A,z.A],z.A,V("||")]]);"> < >= <= == !=".split(" ").forEach(function(a){W[a]=N([[[z.u,z.u],z.A,V(a)],[[z.f,z.f],z.A,V(a)]])});W["!"]=N([[[z.A],z.A,O("!")],[[z.U,z.A],z.A,function(a){return O("!")([a[1]])}]]);W.not=W["!"];W.imagergb=N([[[z.image,z.H],z.O,Rb],[[z.H,z.H,z.image,z.H],z.O,Sb]]);
W.imagergba=N([[[z.image,z.H],z.ba,Tb],[[z.H,z.H,z.image,z.H],z.ba,Ub]]);W.reverse=function(a){return 1===a.length&&"list"===a[0].type?{s:a,v:a[0],o:Fb(a[0])}:!1};W.sort=function(a){return 1===a.length&&1===D(a[0])&&I(a[0])?{s:a,v:a[0],o:Mb(a[0])}:!1};Object.freeze(W);U.powc=["expc","multc","logc"];U.sqrtc=["expc","multc","logc"];U.arccosc=["multc","negc","sqrtc","addc","logc"];U.arcsinc=["multc","negc","sqrtc","addc","logc"];U.tanc=["sinc","cosc","divc"];U.arctanc=["logc","addc","multc","subc"];
U.arctan2c=["logc","divc","sqrtc","multc"];U.arctan2vec2c=["arctan2c"];U.hue=["hsv2rgb"];U.randomnormal=["random"];Object.freeze(U);function Qa(a){this.j={};this.C={};this.i={};this.S=0;this.l={};this.B=a;this.N={}}Qa.prototype.add=function(a,b,c){this.mark(a,b);this.i[a].ha[b]||(this.i[a].ha[b]=c(),this.i[a].ga[b]=!0,this.i[a].order.push(b))};Qa.prototype.mark=function(a,b){this.i[a]||(this.i[a]={order:[],ga:{},ha:{}});var c=this.i[a].ga[b]||!1;this.i[a].ga[b]=!0;return c};function Vb(a,b){return a.i[b]?a.i[b].order.map(function(c){return a.i[b].ha[c]}).join("\n"):"\n"}
function Wb(a,b,c,d){if(db(c,d))return b;if(F(c,d)){if("constant"===c.type)return gb(c.value,d);var f=eb(d)([c]);if(!f)return console.error("cannot find an implementation for "+C(c)+" -> "+C(d)+", using identity"),b;d=f.o;return d(Wb(a,b,c,f.s[0]),{},a)}console.error(C(c)+" is no subtype of "+C(d)+" (trying to cast the term "+b+")");return b}function X(a,b,c){a.j[b]||(a.j[b]={});a.j[b].T||(a.j[b].T=[]);a.j[b].w||(a.j[b].w=!1);a.hasOwnProperty("global")||(a.j[b].global=c)}
function Xb(a,b){var c=b.G;if(b.isuniform)return a.C[b.uvariable].type;if("variable"===b.ctype)return b=b.name,b=c[b]||b,a.j[b].w;if("function"===b.ctype&&a.l.hasOwnProperty(b.oper))return a.j[c[b.oper]].w;if("number"===b.ctype)return Ua(b);if("void"===b.ctype)return z.U;if("field"===b.ctype){a=K(Y(a,b.obj));if("list"===a.type)return a.parameters;if(!a)return!1}else{if("string"===b.ctype)return z.image;if("function"===b.ctype||"infix"===b.ctype){c=Array(b.args.length);for(var d=!0,f=0;f<b.args.length;f++)c[f]=
Y(a,b.args[f]),d&="constant"===c[f].type;if(d&&b.impl)return b={ctype:b.ctype,oper:b.oper,impl:b.impl,args:c.map(function(a){return a.value})},b=a.B.evaluateAndVal(b),Ua(b);a=x(b.oper);d=W[a]?W[a](c):!1;if(!d&&c.every(function(a){return Sa(a)}))throw console.error("Could not find an implementation for "+a+" with args ("+c.map(C).join(", ")+")"),console.log(b),"error";return d?d.v:!1}}console.error("Don't know how to compute type of");console.log(b);return!1}
function Y(a,b){if(!b.ia||!b.S||a.S>b.S)b.ia=Xb(a,b),b.S=a.S;return b.ia}
function Yb(a,b,c){function d(a,b,c){var d={},f;for(f in a)d[f]=a[f];a=B();X(l,a,!1);g[a].w=c;g[a].ma=!0;d[b]=a;return d}function f(a,b,c,u){a.G=b;for(var q in a.args){var p=u||"repeat$2"===a.oper&&0==q||"repeat$3"===a.oper&&0==q||"_"===a.oper&&1==q,t=b;-1!=["repeat","forall","apply"].indexOf(x(a.oper))&&(1==q?t="repeat$2"===a.oper?d(b,"#",z.u):"repeat$3"===a.oper?d(b,a.args[1].name,z.u):"forall$2"===a.oper||"apply$2"===a.oper?d(b,"#",!1):"forall$3"===a.oper||"apply$3"===a.oper?d(b,a.args[1].name,
!1):b:2==q&&(t=a.args[1].G));f(a.args[q],t,c,p)}"field"===a.ctype&&f(a.obj,b,c,u);"variable"===a.ctype&&(q=a.name,q=b[q]||q,u&&l.j[q]&&(l.j[q].Y=!0));if("="===a.oper)u=a.args[0].name,u=b[u]||u,X(l,u,!0),g[u].T.push(a.args[1]);else if(a.oper&&"regional"===x(a.oper)&&"global"!=c)for(var la in a.args){u=a.args[la].name;var ma=B();b[u]=ma;k[c].j||(k[c].j=[]);k[c].j.push(ma);X(l,ma,!1)}else if("forall$2"===a.oper||"apply$2"===a.oper||"forall$3"===a.oper||"apply$3"===a.oper)g[2===a.args.length?a.args[1].G["#"]:
a.args[2].G[a.args[1].name]].T.push({ctype:"infix",oper:"_",args:[a.args[0],{ctype:"number",value:{real:1,imag:0}}],G:a.args[0].G});else if("function"===a.ctype&&k.hasOwnProperty(a.oper)){c=a.oper;la=c.replace("$","_");X(l,la,!1);b[c]=la;b={};for(ma in k[c].arglist)q=k[c].arglist[ma].name,p=la+"_"+q,b[q]=p,X(l,p,!1),g[p].T.push(a.args[ma]);k[c].qa||(k[c].qa=!0,f(k[c].body,b,c,u),g[la].T.push(k[c].body))}}var g=a.j,k=a.l,l=a;f(b,c,"global",!1)}
function Zb(a,b){function c(a){if(a.hasOwnProperty("dependsOnPixel"))return a.dependsOnPixel;if("variable"===a.ctype){var b=a.name;b=a.G[b]||b;return k[b]?a.dependsOnPixel=!0:a.dependsOnPixel=!1}b="random randomint randominteger randombool randomnormal verbatimglsl".split(" ");if("function"===a.ctype&&-1!=b.indexOf(x(a.oper)))return a.dependsOnPixel=!0;if("repeat$2"===a.oper||"forall$2"===a.oper||"apply$2"===a.oper)return c(a.args[1])?(k[a.args[1].G["#"]]=!0,a.dependsOnPixel=!0):a.dependsOnPixel=
!1;if("repeat$3"===a.oper||"forall$3"===a.oper||"apply$3"===a.oper)return c(a.args[2])?(k[a.args[2].G[a.args[1].name]]=!0,a.args[1].dependsOnPixel=!0,a.dependsOnPixel=!0):a.dependsOnPixel=!1;for(var d in a.args)if(c(a.args[d]))return a.dependsOnPixel=!0;return"function"===a.ctype&&g.hasOwnProperty(a.oper)&&c(g[a.oper].body)?a.dependsOnPixel=!0:"field"===a.ctype?a.dependsOnPixel=c(a.obj):a.dependsOnPixel=!1}function d(a,b){if(c(a)){for(var f in a.args)d(a.args[f],b||"repeat$2"===a.oper&&0==f||"repeat$3"===
a.oper&&0==f||"_"===a.oper&&1==f);"field"===a.ctype&&d(a.obj,b);"function"===a.ctype&&g.hasOwnProperty(a.oper)&&(a=a.oper,p.hasOwnProperty(a)||(p[a]=!0,d(g[a].body,b)))}else if("boolean"!==a.ctype&&"number"!==a.ctype&&"void"!==a.ctype){".."===a.oper&&(b=!0);f=!1;var k;for(k in t)if(!f&&ta(a,t[k].V)){f=!0;var l=k}f||(l=B(),t[l]={V:a,type:!1,Y:b});t[l].Y=t[l].Y||b;a.isuniform=!0;a.uvariable=l}}var f=a.j,g=a.l,k={cgl_pixel:!0,"cgl_pixel.x":!0,"cgl_pixel.y":!0},l;for(l in f)if(1<=f[l].T.length||f[l].ma)k[l]=
!0;c(b);var p={"":!0},t=a.C;d(b,!1)}function $b(a,b){if("function"===b.ctype&&!a.l.hasOwnProperty(b.oper)&&null!==a.B.getMyfunction(b.oper)){var c=b.oper;a.l[c]=sa(a.B.getMyfunction(c));$b(a,a.l[c].body)}for(var d in b.args)$b(a,b.args[d])}
function ac(a,b){function c(a){var b={},c;for(c in a)b[c]=a[c];return b}function d(a,b){"repeat$2"===a.oper||"forall$2"===a.oper||"apply$2"===a.oper?(b=c(b),b["#"]=!0):"repeat$3"===a.oper||"forall$3"===a.oper||"apply$3"===a.oper?(b=c(b),b[a.args[1].name]=!0):"="===a.oper&&(b[a.args[0].name]=!0);for(var f in a.args)d(a.args[f],b);"field"===a.ctype&&d(a.obj,b);"variable"===a.ctype&&(a=a.name,b[a]||(g[a]=!0))}var f={},g={};d(b,{});X(a,"cgl_pixel",!1);a.j.cgl_pixel.w=z.L;if(1==Object.keys(g).length)f[Object.keys(g)[0]]=
"cgl_pixel";else if(g["#"])f["#"]="cgl_pixel";else if(g.x&&g.y)X(a,"cgl_pixel.x",!1),a.j["cgl_pixel.x"].w=z.f,f.x="cgl_pixel.x",X(a,"cgl_pixel.y",!1),a.j["cgl_pixel.y"].w=z.f,f.y="cgl_pixel.y";else{b=[];for(var k in g)a.B.nada==a.B.evaluateAndVal({ctype:"variable",name:k})&&b.push(k);1==b.length?f[b[0]]="cgl_pixel":g.p?f.p="cgl_pixel":g.z&&(f.z="cgl_pixel")}"cgl_pixel"===f.z&&(a.j.cgl_pixel.w=z.h);return f}
function Z(a,b,c){var d=Y(a,b);if(b.isuniform)return b=b.uvariable,c?{code:"",m:"constant"===d.type?gb(d.value,K(d)):b}:{code:""};if(";"===b.oper){d={m:""};for(var f="",g=b.args.length-1,k=g;0<=k;k--)"void"===b.args[k].ctype&&(g=k-1);for(k=0;k<=g;k++)d=Z(a,b.args[k],c&&k===g),f+=d.code;return c?{code:f,m:d.m}:{code:f}}if("constant"===d.type)return c?{m:gb(d.value,K(d)),code:""}:{code:""};if("="===b.oper)return d=Z(a,b.args[1],!0),b=Z(a,b.args[0],!0).m+" = "+Wb(a,d.m,Y(a,b.args[1]),Y(a,b.args[0])),
c?{code:d.code,m:b}:{code:d.code+b+";\n"};if("repeat$2"===b.oper||"repeat$3"===b.oper){f=Z(a,b.args[0],!0);if("constant"!==Y(a,b.args[0]).type)return console.error("repeat possible only for fixed constant number in GLSL"),!1;d="repeat$2"===b.oper?b.args[1].G["#"]:b.args[2].G[b.args[1].name];f=Number(f.m);g="";if("constant"===a.j[d].w.type)for(k=1;k<=f;k++){a.j[d].w=Za(k);a.S++;var l=Z(a,b.args["repeat$2"===b.oper?1:2],k===f&&c);g+=l.code;if(k===f&&c)return{code:g,m:l.m}}else if(k="",l=Z(a,b.args["repeat$2"===
b.oper?1:2],c),b=Y(a,b.args["repeat$2"===b.oper?1:2]),c&&(k=B(),a.j[k]||(X(a,k,!0),a.j[k].w=b)),g=g+("for(int "+d+"=1; "+d+" <= "+f+"; "+d+"++) {\n")+l.code,c&&(g+=k+" = "+l.m+";\n"),g+="}\n",c)return{code:g,m:k};return{code:g}}if("forall$2"===b.oper||"forall$3"===b.oper||"apply$2"===b.oper||"apply$3"===b.oper){var p=Y(a,b.args[0]);if("list"!==p.type&&("constant"!==p.type||"list"!==p.value.ctype))return console.error(b.oper+" only possible for lists"),!1;f=p.length||p.value.value.length;k=2===b.args.length?
b.args[1].G["#"]:b.args[2].G[b.args[1].name];var t=a.j[k].w,q=l="";c&&(q=B(),l+=S(d)+" "+q+";\n");"list"===d.type&&jb(d,a);if("constant"===a.j[k].w.type||"constant"===p.type)for(p=a.B.evaluateAndVal(b.args[0]),t=0;t<f;t++)a.j[k].w=Ua(p.value[t]),a.S++,g=Z(a,b.args[2===b.args.length?1:2],c),l+=g.code,"forall$2"===b.oper||"forall$3"===b.oper?t+1===f&&c&&(l+=q+" = "+g.m+";\n"):c&&(l+=R(d,t)([q],[],a)+" = "+g.m+";\n");else{g=Z(a,b.args[2===b.args.length?1:2],c);var u=Z(a,b.args[0],!0);l+=u.code;var G=
u.m;!a.j[G]&&!a.C[G]&&2<=p.length&&(G=B(),l+=S(p)+" "+G+" = "+u.m+";\n");a.j[k].global=!0;for(u=0;u<f;u++)l+=k+" = "+R(p,u)([G],[],a)+";\n",l+=g.code,c&&("forall$2"===b.oper||"forall$3"===b.oper?u===f-1&&(l+=q+" = "+g.m+";\n"):l+=R(d,u)([q],[],a)+" = "+g.m+";\n");"list"===t.type&&jb(t,a)}return c?{code:l,m:q}:{code:l}}if("if$2"===b.oper||"if$3"===b.oper){l=Z(a,b.args[0],!0);f=Y(a,b.args[0]);k=g="";q=Z(a,b.args[1],c);c&&(k=B(),a.j[k]||(X(a,k,!0),a.j[k].w=d));"constant"!=f.type&&(g+=l.code,g+="if("+
l.m+") {\n");if("constant"!=f.type||"constant"==f.type&&f.value.value)g+=q.code,c&&(g+=k+" = "+Wb(a,q.m,Y(a,b.args[1]),d)+";\n");"if$3"===b.oper&&(l=Z(a,b.args[2],c),"constant"!=f.type&&(g+="} else {\n"),"constant"!=f.type||"constant"==f.type&&!f.value.value)&&(g+=l.code,c&&(g+=k+" = "+Wb(a,l.m,Y(a,b.args[2]),d)+";\n"));"constant"!=f.type&&(g+="}\n");return c?{code:g,m:k}:{code:g}}if("function"===b.ctype||"infix"===b.ctype){l=b.oper;if("verbatimglsl"===x(l))return b=a.B.evaluateAndVal(b.args[0]).value,
c?{m:b,code:""}:{code:b};d=b.args.map(function(b){return Z(a,b,!0)});f=b.args.map(function(b){return Y(a,b)});if(a.l.hasOwnProperty(l))for(k=bc(a,l),g=Array(d.length),q=0;q<d.length;q++)g[q]=a.j[a.l[l].body.G[a.l[l].arglist[q].name]].w;else{l=x(l);if("regional"===l)return c?{m:"",code:""}:{code:""};k=W[l](f);if(!k)return console.error("Could not find an implementation for "+l+"("+f.map(C).join(", ")+").\nReturning empty code"),c?{m:"",code:""}:{code:""};g=k.s;k=k.o}l="";q=Array(d.length);for(p=0;p<
d.length;p++)l+=d[p].code,q[p]=Wb(a,d[p].m,f[p],g[p]);b=k(q,b.modifs,a);return c?{m:b,code:l}:{code:l+b+";\n"}}if("variable"===b.ctype)return d=b.name,d=b.G[d]||d,c?{m:d,code:""}:{code:d+";\n"};if("void"===b.ctype)return c?{m:"",code:""}:{code:""};if("field"===b.ctype&&(d={x:0,y:1,z:2,r:0,g:1,b:2,a:3}[b.key],void 0!=d))return b=R(Y(a,b.obj),d)([Z(a,b.obj,!0).m],null,a),c?{m:b,code:""}:{code:b+";\n"};console.error("dont know how to this.compile "+JSON.stringify(b))}
function bc(a,b){cc(a,b,a.l[b].arglist.length);return O(b.replace("$","_"))}
function cc(a,b,c){if(!a.mark("compiledfunctions",b)){for(var d=a.l[b],f=b.replace("$","_"),g=d.body.G,k=Array(c),l=0;l<c;l++)k[l]=d.arglist[l].name;c=a.j[f].w===z.U;var p=S(a.j[f].w)+" "+f+"("+k.map(function(b){return S(a.j[g[b]].w)+" "+g[b]}).join(", ")+"){\n";for(t in d.j)k=d.j[t],p+=S(a.j[k].w)+" "+k+";\n";var t=Z(a,d.body,!c);d=Y(a,d.body);p+=t.code;c||(p+="return "+Wb(a,t.m,d,a.j[f].w)+";\n");p+="}\n";a.add("compiledfunctions",b,function(){return p})}}
function Pa(a,b){ua=0;var c=b=sa(b);$b(a,c);Yb(a,c,ac(a,c));Zb(a,c);for(var d in a.C){c=a.B.evaluateAndVal(a.C[d].V);if(!c.ctype||"undefined"===c.ctype){console.error("can not evaluate:");console.log(a.C[d].V);break}a.C[d].type=a.C[d].Y?Ua(c):y(c)}d=!0;for(var f in a.j)a.j[f].w=a.j[f].w||!1,a.j[f].Y&&(a.j[f].w=Za(1),a.S++);for(;d;){d=!1;for(var g in a.j)if(!a.j[g].Y)for(var k in a.j[g].T){f=K(Y(a,a.j[g].T[k]));var l=c=a.j[g].w||!1;f&&(c?F(f,c)?l=c:l=A(c,f):l=f,l&&l!==c&&(a.j[g].w=l,a.S++,d=!0))}}for(var p in a.C)"list"===
a.C[p].type.type&&jb(a.C[p].type,a);for(var t in a.j)"list"===a.j[t].w.type&&jb(a.j[t].w,a);g=Z(a,b,!0);k=Y(a,b);b=Wb(a,g.m,k,z.color);F(k,z.color)||console.error("expression does not generate a color");k=Vb(a,"structs");k+=Vb(a,"uniforms");p=[];for(var q in a.C)"constant"!=a.C[q].type.type&&a.C[q].type!=z.image&&p.push("uniform "+S(a.C[q].type)+" "+q+";");k+=p.join("\n");q="";for(var u in a.N)q+=a.N[u].code+"\n";k=k+q+Vb(a,"includedfunctions");k+=Vb(a,"functions");for(var G in a.j)a.j[G].w&&a.j[G].global&&
(k+=S(a.j[G].w)+" "+G+";\n");k+=Vb(a,"compiledfunctions");k+="void main(void) {\n"+g.code+"gl_FragColor = "+b+";\n}\n";console.log(k);u={};if(a.i.compiledfunctions)for(var T in a.i.compiledfunctions.ga)u[T]=a.B.getMyfunction(T).generation;return{code:k,C:a.C,N:a.N,fa:u}};function dc(a,b,c,d){this.V=b;this.B=d;this.l=c;ec(this);b=this.i;this.name=a;this.code="uniform sampler2D _sampler"+a+";\nuniform float _ratio"+a+";\nuniform vec2 _cropfact"+a+";\nvec4 _imagergba"+a+"(vec2 A, vec2 B, vec2 p) {\n  p -= A; B -= A;\n  float b = dot(B,B);\n  p = vec2(dot(p,B),_ratio"+a+"*dot(p,vec2(-B.y,B.x)))/b;\n  "+(b.repeat?"p = mod(p, vec2(1.));":"")+"\n  "+(b.repeat&&b.J?"vec4 color = vec4(0.);\n    float totalWeight = 0.;\n    for(int dx=0; dx<2; dx++) for(int dy=0; dy<2; dy++) {\n      vec2 delta = .5*vec2(dx, dy);\n      vec2 center = delta+vec2(.5);\n      vec2 tc = fract(p-delta)+delta;\n      float dst = dot(abs(tc-center),vec2(1.));\n      float w = max(.5-dst,0.);\n      w=w*w;\n      color += w * texture2D(_sampler"+
a+", tc*_cropfact"+a+");\n      totalWeight += w;\n    }\n    return color/totalWeight;":b.repeat?"return texture2D(_sampler"+a+", p*_cropfact"+a+");":"if(0. <= p.x && p.x <= 1. && 0. <= p.y && p.y <= 1.)\n          return texture2D(_sampler"+a+", p*_cropfact"+a+");\n       else\n          return vec4(0.);")+"\n  }"}
function ec(a){var b=a.l,c=a.B;b={R:b.hasOwnProperty("interpolate")?c.evaluateAndVal(b.interpolate).value:!0,J:b.hasOwnProperty("mipmap")?c.evaluateAndVal(b.mipmap).value:!1,repeat:b.hasOwnProperty("repeat")?c.evaluateAndVal(b.repeat).value:!1};!a.i||a.i.J==b.J&&a.i.repeat==b.repeat||(console.log("enfore recompilation because texture modifiers changed."),pa++);a.i=b}
function Wa(a){var b=a.B.evaluateAndVal(a.V).value,c="string"===typeof b?a.B.getImage(b,!0):b;if(null==c)return console.error("Could not find image "+b+"."),r;ec(a);return Ha(c,a.i)}function fc(a,b,c){c.N.hasOwnProperty(a)||(c.N[a]=new dc(a,c.C[a].V,b,c.B));return a}function Ub(a,b,c){return["_imagergba",fc(a[2],b,c),"(",a[0],",",a[1],",",a[3],")"].join("")}function Sb(a,b,c){return["(_imagergba",fc(a[2],b,c),"(",a[0],",",a[1],",",a[3],").rgb)"].join("")}
function Tb(a,b,c){c.add("uniforms","corners",function(){return"uniform vec2 _lowerleft, _lowerright;"});return["_imagergba",fc(a[0],b,c),"(_lowerleft, _lowerright, ",a[1],")"].join("")}function Rb(a,b,c){c.add("uniforms","corners",function(){return"uniform vec2 _lowerleft, _lowerright;"});return["(_imagergba",fc(a[0],b,c),"(_lowerleft, _lowerright, ",a[1],").rgb)"].join("")};function gc(a){var b=void 0===b?null:b;return"list"!==a.ctype?(console.log("argument is not a list"),b):a.value}function Ya(a){var b=void 0===b?[.5,.5,.5]:b;if("number"===a.ctype){var c=hc(a);if(!isNaN(c))return[c,c,c]}a=gc(a);return null===a?b:3!=a.length?(console.log("Not an RGB color vector"),b):a.map(function(a){return hc(a)})}
function Xa(a){var b=void 0===b?Number.NaN:b;if("number"!==a.ctype)return console.log("argument is not a number"),b;b=a.value;a=b.real;b=b.imag;0!==b&&console.log("complex number is not real");b=Math.round(a);b!==a&&console.log("number is not an integer");return b}
function hc(a){var b=void 0===b?Number.NaN:b;b=void 0===b?Number.NaN:b;"number"!==a.ctype?(console.log("argument is not a number"),a=b):(a=a.value,b=a.real,0!==a.imag&&console.log("complex number is not real"),a=b);return 0>a?0:1<a?1:a};function ra(a){this.message=a}ra.prototype.toString=function(){return this.message};
function La(a,b){var c=n;this.i=c.createProgram();c.i&&(a="#version 300 es\n"+a.replace(/attribute/g,"in").replace(/varying/g,"out"),b="#version 300 es\n"+b.replace(/varying/g,"in").replace(/gl_FragColor/g,"FragColor").replace(/texture2D/g,"texture").replace(/precision highp float;/g,"precision highp float;\n#define webgl2 true\nout vec4 FragColor;"));this.X=ic(this,c,c.VERTEX_SHADER,a);ic(this,c,c.FRAGMENT_SHADER,b);a=this.i;c.linkProgram(a);if(!c.getProgramParameter(a,c.LINK_STATUS))throw new ra("Error linking shader:\n"+
c.getProgramInfoLog(a));c.validateProgram(a);if(!c.getProgramParameter(a,c.VALIDATE_STATUS))throw new ra("Error validating shader:\n"+c.getProgramInfoLog(a));var d=this.i,f,g,k={},l;b=c.getProgramParameter(d,c.ACTIVE_UNIFORMS);for(a=0;a<b;++a){var p=c.getActiveUniform(d,a);if(null!==p&&(f=p.name.replace(/\]/g,""))){for(l=k;null!==(g=/[.\[]/.exec(f));){var t=f.substr(0,g.index);l.hasOwnProperty(t)?l=l[t]:"."===g[0]?l=l[t]={}:l=l[t]=[];f=f.substr(g.index+1)}if(1<p.size){g=p.size;var q=Array(g);for(t=
0;t<g;++t){var u=p.name+"["+t+"]";u=jc(this,c,u,p);q[t]=u}l[f]=q}else u=jc(this,c,p.name,p),l[f]=u}}this.l=k}function ic(a,b,c,d){c=b.createShader(c);b.shaderSource(c,d);b.compileShader(c);if(!b.getShaderParameter(c,b.COMPILE_STATUS))throw console.warn(d.split("\n")),new ra("Error compiling shader:\n"+b.getShaderInfoLog(c));b.attachShader(a.i,c);return c}
function jc(a,b,c,d){a=b.getUniformLocation(a.i,c);switch(d.type){case b.FLOAT:return b.uniform1fv.bind(b,a);case b.FLOAT_VEC2:return b.uniform2fv.bind(b,a);case b.FLOAT_VEC3:return b.uniform3fv.bind(b,a);case b.FLOAT_VEC4:return b.uniform4fv.bind(b,a);case b.BOOL:case b.INT:case b.SAMPLER_2D:case b.SAMPLER_CUBE:return b.uniform1iv.bind(b,a);case b.BOOL_VEC2:case b.INT_VEC2:return b.uniform2iv.bind(b,a);case b.BOOL_VEC3:case b.INT_VEC3:return b.uniform3iv.bind(b,a);case b.BOOL_VEC4:case b.INT_VEC4:return b.uniform4iv.bind(b,
a);case b.FLOAT_MAT2:return b.uniformMatrix2fv.bind(b,a,!1);case b.FLOAT_MAT3:return b.uniformMatrix3fv.bind(b,a,!1);case b.FLOAT_MAT4:return b.uniformMatrix4fv.bind(b,a,!1);default:throw new ra("Unknown data type for uniform "+c);}};
}).call(this);//# sourceMappingURL=CindyGL.js.map


