(function(){
'use strict';var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},e="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;
function ba(a,b){if(b){var c=e;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}
ba("String.prototype.repeat",function(a){return a?a:function(a){var c;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");c=this+"";if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=c),a>>>=1)c+=c;return d}});function ca(){ca=function(){};e.Symbol||(e.Symbol=da)}var ea=0;function da(a){return"jscomp_symbol_"+(a||"")+ea++}
function fa(){ca();var a=e.Symbol.iterator;a||(a=e.Symbol.iterator=e.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ga(this)}});fa=function(){}}function ga(a){var b=0;return ha(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ha(a){fa();a={next:a};a[e.Symbol.iterator]=function(){return this};return a}
ba("Array.from",function(a){return a?a:function(a,c,d){fa();c=c?c:function(a){return a};var f=[],g=a[Symbol.iterator];if("function"==typeof g)for(a=g.call(a);!(g=a.next()).done;)f.push(c.call(d,g.value));else for(var g=a.length,h=0;h<g;h++)f.push(c.call(d,a[h]));return f}});
function ia(a,b){fa();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}ba("Array.prototype.keys",function(a){return a?a:function(){return ia(this,function(a){return a})}});
ba("Array.prototype.fill",function(a){return a?a:function(a,c,d){var f=this.length||0;0>c&&(c=Math.max(0,f+c));if(null==d||d>f)d=f;d=Number(d);0>d&&(d=Math.max(0,f+d));for(c=Number(c||0);c<d;c++)this[c]=a;return this}});
var ja={addc:"vec2 addc(vec2 a,vec2 b){\nreturn a+b;\n}\n",arccosc:"vec2 arccosc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=addc(multc(logc(tmp1),vec2(0.0,1.0)),vec2(pi*0.5,0.0));\nreturn erg;\n}\n",arcsinc:"vec2 arcsinc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=multc(logc(tmp1),vec2(0.0,-1.0));\nreturn erg;\n}\n",arctan2c:"\n\n\n\nvec2 arctan2c(vec2 x,vec2 y){\nvec2 r=logc(divc(x+vec2(-y.y,y.x),sqrtc(multc(x,x)+multc(y,y))));\nreturn vec2(r.y, -r.x);\n}\n",
arctan2cvec2:"vec2 arctan2cvec2(cvec2 v){\nreturn arctan2c(v.real,v.imag);\n}\n",arctan2vec2:"float arctan2vec2(vec2 v){\nreturn atan(v.y,v.x);\n}\n",arctanc:"vec2 arctanc(vec2 a){\nvec2 t1=logc(addc(multc(a,vec2(0.0,-1.0)),vec2(1.0,0.0)));\nvec2 t2=logc(addc(multc(a,vec2(0.0,1.0)),vec2(1.0,0.0)));\nvec2 erg=multc(subc(t1,t2),vec2(0.0,0.5));\nreturn erg;\n}\n",blue:"vec3 blue(float f)\n{\nreturn vec3(0.,0.,clamp(f,0.,1.));\n}\n",cimag:"float imagc(vec2 a){\nreturn a.y;\n}\n",conjugate:"vec2 conjugate(vec2 a){\nreturn vec2(a.x, -a.y);\n}\n",
copytexture_f:"#ifdef GL_ES\nprecision highp float;\n#endif\n\nuniform sampler2D sampler;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_FragColor=texture2D(sampler,cgl_pixel);\n}\n",copytexture_v:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_Position=vec4(aPos,1.);\ncgl_pixel=aTexCoord;\n}\n",cosc:"vec2 cosc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat i= (imag1+imag2) /2.0;\nfloat r= (real1+real2) /2.0;\n\nreturn vec2(r,i);\n}\n",
creal:"float realc(vec2 a){\nreturn a.x;\n}\n",dehomogenize:"vec2 dehomogenize(vec3 z){\nreturn vec2(z.x,z.y)/z.z;\n}\n",divc:"vec2 divc(vec2 a,vec2 b){\nreturn vec2(dot(a,b),dot(a,vec2(-b.y,b.x)))/dot(b,b);\n}\n",divfc:"vec2 divfc(float a,vec2 b){\nreturn a*vec2(b.x,-b.y)/dot(b,b);\n}\n",expc:"vec2 expc(vec2 a){\nfloat n=exp(a.x);\nfloat r=n*cos(a.y);\nfloat i=n*sin(a.y);\nreturn vec2(r,i);\n}\n",float2color:"vec4 float2color(float f)\n{\nreturn vec4(f,f,f,1.);\n}\n",gray:"vec3 gray(float f)\n{\nf=clamp(f,0.,1.);\nreturn vec3(f,f,f);\n}\n",
green:"vec3 green(float f)\n{\nreturn vec3(0.,clamp(f,0.,1.),0.);\n}\n",hsv2rgb:"vec3 hsv2rgb(vec3 c)\n{\nvec4 K=vec4(1.0,2.0/3.0,1.0/3.0,3.0);\nvec3 p=abs(fract(c.xxx+K.xyz) *6.0-K.www);\nreturn c.z*mix(K.xxx,clamp(p-K.xxx,0.0,1.0),c.y);\n}\n",hue:"vec3 hue(float a){\nreturn hsv2rgb(vec3(a,1.,1.));\n}\n",imagc:"float imagc(vec2 a){\nreturn a.y;\n}\n",invc:"vec2 invc(vec2 a){\nfloat n=a.x*a.x+a.y*a.y;\nreturn vec2(a.x/n,-a.y/n);\n}\n",logc:"vec2 logc(vec2 a){\nfloat re=a.x;\nfloat im=a.y;\nfloat s=sqrt(re*re+im*im);\nfloat i=im;\nfloat imag=atan(im,re);\nif(i<0.0){\nimag+= (2.0*pi);\n}\nif(i==0.0&&re<0.0){\nimag=pi;\n}\nif(imag>pi){\nimag-= (2.0*pi);\n};\nfloat real=log(s);\n\nreturn vec2(real,imag);\n}\n",
logr:"vec2 logr(float a){\nif(a>=0.)return vec2(log(a),0);\nelse return vec2(log(-a),pi);\n}\n",mat2complex:"mat4 mat2complex(mat2 a)\n{\nreturn mat4(\nvec4(a[0][0],0,a[0][1],0),\nvec4(0,a[0][0],0,a[0][1]),\nvec4(a[1][0],0,a[1][1],0),\nvec4(0,a[1][0],0,a[1][1])\n);\n}\n",multc:"vec2 multc(vec2 a,vec2 b){\nreturn vec2(dot(a,vec2(b.x,-b.y)),dot(a,b.yx));\n}\n",negc:"vec2 negc(vec2 a){\nreturn vec2(-a.x,-a.y);\n}\n",powc:"vec2 powc(vec2 a,vec2 b){\nreturn expc(multc(logc(a),b));\n}\n",powi:"float powi(float a,int b){\nif(mod(float(b),2.) < .5)\nreturn pow(abs(a),float(b));\nelse\nreturn sign(a)*pow(abs(a),float(b));\n}\n",
random:"uniform float rnd_;\n\nfloat last_rnd= .1231;\nfloat random(){\nfloat a=mod(rnd_*plain_pixel.x*32.23,1.21);\nfloat b=mod(last_rnd*plain_pixel.y*54.21,1.32);\nlast_rnd=mod(a+b+12232.2213*(1.+rnd_)*dot(plain_pixel,plain_pixel)+a+sin(b)+b*sin(dot(plain_pixel,vec2(232.121+rnd_,2232.11))+last_rnd*121.11)*129.12+rnd_,1.);\nreturn last_rnd;\n\n\n}\n",realc:"float realc(vec2 a){\nreturn a.x;\n}\n",red:"vec3 red(float f)\n{\nreturn vec3(clamp(f,0.,1.),0.,0.);\n}\n",rgb2hsv:"vec3 rgb2hsv(vec3 c)\n{\nvec4 K=vec4(0.0, -1.0/3.0,2.0/3.0, -1.0);\nvec4 p=mix(vec4(c.bg,K.wz),vec4(c.gb,K.xy),step(c.b,c.g));\nvec4 q=mix(vec4(p.xyw,c.r),vec4(c.r,p.yzx),step(p.x,c.r));\n\nfloat d=q.x-min(q.w,q.y);\nfloat e=1.0e-10;\nreturn vec3(abs(q.z+ (q.w-q.y) / (6.0*d+e)),d/ (q.x+e),q.x);\n}\n",
sinc:"\n\nvec2 sinc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat r= -(imag1-imag2) /2.0;\nfloat i= (real1-real2) /2.0;\n\nreturn vec2(r,i);\n}\n",sqrtc:"vec2 sqrtc(vec2 a){\nreturn expc(multc(logc(a),vec2(0.5,0.0)));\n}\n",sqrtf:"vec2 sqrtf(float a){\nif(a>=0.)return vec2(sqrt(a),0.);\nelse return vec2(0.,sqrt(-a));\n}\n",standardFragmentHeader:"#ifdef GL_ES\nprecision highp float;\nprecision highp int;\n#endif\n\n#define pi 3.141592653589793\n\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\n",
subc:"vec2 subc(vec2 a,vec2 b){\nreturn a-b;\n}\n",tanc:"vec2 tanc(vec2 a){\nvec2 s=sinc(a);\nvec2 c=cosc(a);\nreturn divc(s,c);\n}\n",vec2complex:"vec4 vec2complex(vec2 a)\n{\nreturn vec4(a.x,0.,a.y,0);\n}\n",vshader:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\nuniform mat3 transformMatrix;\nvoid main(void){\ngl_Position=vec4(aPos,1.);\nplain_pixel=aTexCoord;\nvec3 r=transformMatrix*vec3(plain_pixel,1);\ncgl_pixel=r.xy/r.z;\n}\n"};var ka=!1,k,m,n,u,v=!1,ma,w=!1,na=1;
function oa(){function a(c){k.removeEventListener("webglcontextcreationerror",a,!1);c.statusMessage&&(b=c.statusMessage)}if(!ka){k=document.createElement("canvas");k.id="glcanvas";k.style.display="none";k.width=k.height=0;document.body.appendChild(k);m=document.createElement("canvas");m.id="tmpcanvas";m.style.display="none";m.width=m.height=0;document.body.appendChild(m);var b="Unknown";k.addEventListener("webglcontextcreationerror",a,!1);(n=k.getContext("webgl"))||(n=k.getContext("experimental-webgl"));
if(!n)throw new pa("Could not obtain a WebGL context.\nReason: "+b);k.removeEventListener("webglcontextcreationerror",a,!1);w=n.getExtension("OES_texture_float")&&n.getExtension("OES_texture_float_linear");w||(console.error("Your browser does not suppert OES_texture_float, trying OES_texture_half_float..."),(v=(ma=n.getExtension("OES_texture_half_float"))&&n.getExtension("OES_texture_half_float_linear"))||console.error("Your browser does not suppert OES_texture_half_float, will use 8-bit textures."));
navigator.userAgent.match(/(iPad|iPhone)/i)&&(console.log("You are  using an iPhone/iPad."),w=v=!1,n.getExtension("OES_texture_half_float")&&n.getExtension("OES_texture_half_float_linear")&&n.getExtension("EXT_color_buffer_half_float")?v=!0:console.error("Your browser does not suppert writing to half_float textures, we will use 8-bit textures."));ka=!0}};function qa(a){var b;if(null==a||"object"!=typeof a)return a;if(a instanceof Array){b=[];for(var c=0,d=a.length;c<d;c++)b[c]=qa(a[c]);return b}if(a instanceof Object){b={};for(c in a)a.hasOwnProperty(c)&&(0<="oper impl args ctype stack name arglist value real imag key obj body".split(" ").indexOf(c)&&(b[c]=qa(a[c])),a.modifs&&(b.modifs=a.modifs));return b}}
function ra(a,b){if(null==a||"object"!=typeof a)return a===b;if(a instanceof Array&&b instanceof Array){if(a.length!=b.length)return!1;for(var c=0,d=a.length;c<d;c++)if(!ra(a[c],b[c]))return!1;return!0}if(a instanceof Object&&b instanceof Object){c="oper impl args ctype stack name modifs arglist value real imag key obj body".split(" ");for(d=0;d<c.length;d++){var f=c[d];if(!ra(a[f],b[f]))return!1}return!0}return!1}function x(a){return-1===a.indexOf("$")?a:a.substr(0,a.indexOf("$"))}
function y(a){if("boolean"===a.ctype)return z.F;if("number"===a.ctype)return a=a.value,1E-5>Math.abs(a.imag)?(a.real|0)===a.real?z.v:z.f:z.h;if("list"===a.ctype){var b=a.value;if(0<b.length){for(var c=y(b[0]),d=1;d<b.length;d++)c=B(c,y(b[d]));if(c)return{type:"list",length:b.length,i:c}}}else if("string"===a.ctype||"image"===a.ctype)return z.image;console.error("Cannot guess type of the following type:");console.log(a);return!1}var sa=0;function C(){sa++;return"_h"+sa}
function ta(a,b){if(a>k.width||b>k.height)k.width=Math.ceil(a),k.height=Math.ceil(b)}function ua(a,b,c){a=a.getInitialMatrix();b-=a.tx;c+=a.ty;return{x:(b*a.d-c*a.b)/a.det,y:-(-b*a.c+c*a.a)/a.det}}function va(a){return ua(a,0,a.instance.canvas.clientHeight)}function wa(a){return ua(a,a.instance.canvas.clientWidth,a.instance.canvas.clientHeight)}var xa=new Float32Array(1),ya=new Int32Array(xa.buffer);
function za(a){xa[0]=a;a=ya[0];var b=a>>16&32768,c=(a&2147483647)+4096;if(1199570944<=c)return 1199570944<=(a&2147483647)?2139095040>c?b|31744:b|31744|(a&8388607)>>13:b|31743;if(947912704<=c)return b|c-939524096>>13;if(855638016>c)return b;c=(a&2147483647)>>23;return b|(a&8388607|8388608)+(8388608>>>c-102)>>126-c}
function Aa(a){if(w)return new Float32Array(a);if(v){for(var b=new Uint16Array(a.length),c=0;c<a.length;c++)b[c]=za(a[c]);return b}b=new Uint8Array(a.length);for(c=0;c<a.length;c++)b[c]=255*a[c];return b}function Ba(a){return w?new Float32Array(a):v?new Uint16Array(a):new Uint8Array(a)}function Ca(){return w?n.FLOAT:v?ma.HALF_FLOAT_OES:n.UNSIGNED_BYTE}
function Da(a){for(var b=[],c=0;c<a.length;c++)if(w)b.push(a[c]);else if(v){var d=a[c],f=(d&31744)>>10,g=d&1023;b.push((d>>15?-1:1)*(f?31===f?g?NaN:Infinity:Math.pow(2,f-15)*(1+g/1024):g/1024*6.103515625E-5))}else b.push(a[c]/255);return b}function Ea(a){for(var b=1;b<a;)b<<=1;return b};function Fa(a,b){a.hasOwnProperty("readcanvaswrappers")||(a.readcanvaswrappers=Array(4));var c=2*b.U+b.$;a.readcanvaswrappers.hasOwnProperty(c)||(a.writecanvaswrapper&&a.writecanvaswrapper.generation>a.generation&&a.writecanvaswrapper.na(),a.readcanvaswrappers[c]=new Ga(a,b),a.ready||(console.error("Image not ready. Creating onload event."),a.whenReady(function(){a.generation=Math.max(a.generation,a.readcanvaswrappers[c].generation+1)})));a.writecanvaswrapper&&(a.writecanvaswrapper=a.readcanvaswrappers[c]);
return a.readcanvaswrappers[c]}function Ha(a){if(!a.hasOwnProperty("writecanvaswrapper")){var b=-1;if(a.readcanvaswrappers)for(var c=3;0<=c;c--)a.readcanvaswrappers.hasOwnProperty(b)&&(b=c);else a.readcanvaswrappers=Array(4);-1==b&&(c={$:!0,U:!1,repeat:!1},b=2*c.U+c.$,a.readcanvaswrappers[b]=new Ga(a,c));a.writecanvaswrapper=a.readcanvaswrappers[b]}a.readPixels=a.writecanvaswrapper.readPixels.bind(a.writecanvaswrapper);return a.writecanvaswrapper}
function Ga(a,b){this.canvas=a;this.S=b;this.K=a.width;this.G=a.height;Ia(this);this.l=0;this.s=[];this.ba=[];this.generation=-1;this.bindTexture();a.drawTo=this.drawTo.bind(this);a.readPixels=this.readPixels.bind(this);a.cdyUpdate=this.na.bind(this);a=Ba(this.W*this.L*4);for(var c=0;2>c;c++)this.s[c]=n.createTexture(),n.bindTexture(n.TEXTURE_2D,this.s[c]),n.pixelStorei(n.UNPACK_ALIGNMENT,1),n.texImage2D(n.TEXTURE_2D,0,n.RGBA,this.W,this.L,0,n.RGBA,Ca(),a),b.U?n.texParameteri(n.TEXTURE_2D,n.TEXTURE_MIN_FILTER,
b.$?n.LINEAR_MIPMAP_LINEAR:n.NEAREST_MIPMAP_LINEAR):n.texParameteri(n.TEXTURE_2D,n.TEXTURE_MIN_FILTER,b.$?n.LINEAR:n.NEAREST),n.texParameteri(n.TEXTURE_2D,n.TEXTURE_MAG_FILTER,b.$?n.LINEAR:n.NEAREST),this.ba[c]=n.createFramebuffer(),n.bindFramebuffer(n.FRAMEBUFFER,this.ba[c]),n.framebufferTexture2D(n.FRAMEBUFFER,n.COLOR_ATTACHMENT0,n.TEXTURE_2D,this.s[c],0);this.aa=new Ja(ja.copytexture_v,ja.copytexture_f);b=n.createBuffer();n.bindBuffer(n.ARRAY_BUFFER,b);b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,
1,1,0]);a=n.getAttribLocation(this.aa.l,"aPos");n.enableVertexAttribArray(a);c=n.getAttribLocation(this.aa.l,"aTexCoord");n.enableVertexAttribArray(c);var d=new Float32Array([0,0,1,0,0,1,1,1]),f=b.byteLength;n.bufferData(n.ARRAY_BUFFER,f+d.byteLength,n.STATIC_DRAW);n.bufferSubData(n.ARRAY_BUFFER,0,b);n.bufferSubData(n.ARRAY_BUFFER,f,d);n.vertexAttribPointer(a,3,n.FLOAT,!1,0,0);n.vertexAttribPointer(c,2,n.FLOAT,!1,0,f)}
function Ia(a){a.W=Ea(a.K+a.K/2*(a.S.U&&a.S.repeat));a.L=Ea(a.G+a.G/2*(a.S.U&&a.S.repeat))}Ga.prototype.bindTexture=function(){n.bindTexture(n.TEXTURE_2D,this.s[this.l])};Ga.prototype.bindFramebuffer=function(){n.bindFramebuffer(n.FRAMEBUFFER,this.ba[this.l^1]);this.l^=1};
Ga.prototype.na=function(){var a;this.canvas.img.hasOwnProperty("getContext")?a=this.canvas.img.getContext("2d"):(this.canvas.img=document.createElement("canvas"),this.canvas.img.style.display="none",this.canvas.img.width=this.K,this.canvas.img.height=this.G,a=this.canvas.img.getContext("2d"));a.clearRect(0,0,this.K,this.G);this.drawTo(a,0,0);this.canvas.img.generation++};
function Ka(a){if(a.canvas.live||a.canvas.ready&&!(a.generation>=a.canvas.generation)){if(a.K!=a.canvas.width||a.G!=a.canvas.height){a.K=a.canvas.width;a.G=a.canvas.height;Ia(a);for(var b=Ba(a.W*a.L*4),c=0;2>c;c++)n.bindTexture(n.TEXTURE_2D,a.s[c]),n.texImage2D(n.TEXTURE_2D,0,n.RGBA,a.W,a.L,0,n.RGBA,Ca(),b)}a.bindTexture();n.pixelStorei(n.UNPACK_FLIP_Y_WEBGL,1);a.S.repeat?(m.width=a.W,m.height=a.L,b=m.getContext("2d"),b.drawImage(a.canvas.img,0,a.L-a.G),b.drawImage(a.canvas.img,a.K,a.L-a.G),b.drawImage(a.canvas.img,
0,a.L-2*a.G),b.drawImage(a.canvas.img,a.K,a.L-2*a.G),n.texSubImage2D(n.TEXTURE_2D,0,0,0,n.RGBA,Ca(),m)):n.texSubImage2D(n.TEXTURE_2D,0,0,0,n.RGBA,Ca(),a.canvas.img);a.S.U&&n.generateMipmap(n.TEXTURE_2D);n.pixelStorei(n.UNPACK_FLIP_Y_WEBGL,0);a.generation=a.canvas.generation;console.log("Image has been loaded to GPU")}}
Ga.prototype.drawTo=function(a,b,c){ta(this.K,this.G);n.viewport(0,0,this.W,this.L);n.useProgram(this.aa.l);n.activeTexture(n.TEXTURE0);n.bindTexture(n.TEXTURE_2D,this.s[this.l]);this.aa.s.sampler([0]);n.bindFramebuffer(n.FRAMEBUFFER,null);n.drawArrays(n.TRIANGLE_STRIP,0,4);n.flush();a.drawImage(k,0,k.height-this.G,this.K,this.G,b,c,this.K,this.G)};
Ga.prototype.readPixels=function(a,b,c,d){n.bindFramebuffer(n.FRAMEBUFFER,this.ba[this.l]);n.framebufferTexture2D(n.FRAMEBUFFER,n.COLOR_ATTACHMENT0,n.TEXTURE_2D,this.s[this.l],0);var f=Ba(c*d*4);n.readPixels(a,this.G-b-d,c,d,n.RGBA,Ca(),f);a=[];for(--d;0<=d;d--)a=a.concat(Da(f.slice(d*c*4,(d+1)*c*4)));return a};function La(a,b){this.B=a;this.S=b;Ma(this)}
function Ma(a){var b=Na(new Oa(a.B),a.S);a.s=b.D;a.C=b.C;a.ia=b.ia;a.aa=ja.standardFragmentHeader+b.code;a.ba=ja.vshader;a.l=new Ja(a.ba,a.aa);b=n.createBuffer();n.bindBuffer(n.ARRAY_BUFFER,b);var b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,1,0]),c=n.getAttribLocation(a.l.l,"aPos");n.enableVertexAttribArray(c);a=n.getAttribLocation(a.l.l,"aTexCoord");n.enableVertexAttribArray(a);var d=new Float32Array([0,0,1,0,0,1,1,1]),f=b.byteLength;n.bufferData(n.ARRAY_BUFFER,f+d.byteLength,n.STATIC_DRAW);n.bufferSubData(n.ARRAY_BUFFER,
0,b);n.bufferSubData(n.ARRAY_BUFFER,f,d);n.vertexAttribPointer(c,3,n.FLOAT,!1,0,0);n.vertexAttribPointer(a,2,n.FLOAT,!1,0,f)}
function Pa(a){function b(a,c,d){if(a)if("function"===typeof a)switch(c){case z.h:a([d.value.real,d.value.imag]);break;case z.F:d.value?a([1]):a([0]);break;case z.v:case z.f:a([d.value.real]);break;default:if("list"===c.type&&c.i===z.f)a(d.value.map(function(a){return a.value.real}));else if("list"===c.type&&"list"===c.i.type&&c.i.i===z.f){for(var f=[],p=0;p<c.length;p++)for(var r=0;r<c.i.length;r++)f.push(d.value[p].value[r].value.real);a(f)}else console.error("Don't know how to set uniform of type "+
D(c)+", to "+d)}else if("list"===c.type)if(p=Qa(c),1===E(c)&&p===z.f){c=Ra(c.length);var t=0;for(f in c)b(a["a"+f],z.ca(c[f]),{ctype:"list",value:F(c[f]).map(function(a){return d.value[t+a]})}),t+=c[f]}else for(f=0;f<c.length;f++)b(a["a"+f],c.i,{ctype:"list",value:d.value[f].value});else console.error("Don't know how to set uniform of type "+D(c)+", to"),console.log(d)}for(var c in a.s){var d=a.B.evaluateAndVal(a.s[c].Z),f=a.s[c].type;if(!G(Sa(d),f)){console.log("Type of "+c+" changed ("+D(Sa(d))+
" is no subtype of  "+D(f)+"); forcing rebuild.");Ma(a);n.useProgram(a.l.l);Pa(a);return}a.l.s[c]&&b(a.l.s[c],f,d)}[["rnd_",function(){return[Math.random()]}],["_lowerleft",function(){var b=va(a.B);return[b.x,b.y]}],["_lowerright",function(){var b=wa(a.B);return[b.x,b.y]}]].map(function(b){return a.l.s[b[0]]&&a.l.s[b[0]](b[1]())})}
function Ta(a){var b=0,c;for(c in a.C)for(var d in a.C[c]){n.activeTexture(n.TEXTURE0+b);var f=a.C[c][d],g=f.name,h={$:f.V.hasOwnProperty("interpolate")?f.B.evaluateAndVal(f.V.interpolate).value:!0,U:f.V.hasOwnProperty("mipmap")?f.B.evaluateAndVal(f.V.mipmap).value:!1,repeat:f.V.hasOwnProperty("repeat")?f.B.evaluateAndVal(f.V.repeat).value:!1},f=Ua(f,h);Ka(f);f.bindTexture();[["_sampler"+g,[b]],["_ratio"+g,[f.K/f.G]],["_cropfact"+g,[f.K/f.W,f.G/f.L]],["_repeat"+g,[h.repeat]],["_mipmap"+g,[h.U]]].map(function(b){return a.l.s[b[0]]&&
a.l.s[b[0]](b[1])});b++}};CindyJS.registerPlugin(1,"CindyGL",function(a){function b(b,d,f,g,h,l){if(!b.pa||b.oa<na)b.pa=!0,b.oa=na,b.ra=new La(a,b);b=b.ra;var q;a:{for(q in b.ia)if(b.B.getMyfunction(q).generation>b.ia[q]){console.log(q+" is outdated; forcing rebuild.");q=!1;break a}q=!0}q||Ma(b);var p=h/g;q=d.x+-(f.y-d.y)*p;p=d.y+(f.x-d.x)*p;ta(g,h);l?n.viewport(0,0,g,h):n.viewport(0,k.height-h,g,h);n.useProgram(b.l.l);Pa(b);d=[f.x-d.x,q-d.x,d.x,f.y-d.y,p-d.y,d.y,0,0,1];b.l.s.hasOwnProperty("transformMatrix")&&b.l.s.transformMatrix([d[0],
d[3],d[6],d[1],d[4],d[7],d[2],d[5],d[8]]);Ta(b);l?(l.bindFramebuffer(),l.generation=++l.canvas.generation):n.bindFramebuffer(n.FRAMEBUFFER,null);n.drawArrays(n.TRIANGLE_STRIP,0,4);n.flush();l&&(l.generation=Math.max(l.generation,l.canvas.generation+1))}u=a.nada;a.defineFunction("compile",1,function(b){b=Na(new Oa(a),b[0]);console.log(b);return{ctype:"string",value:b}});a.defineFunction("forcerecompile",0,function(){na++;return u});a.defineFunction("colorplot",1,function(c){oa();var d=a.instance.canvas.clientWidth,
f=a.instance.canvas.clientHeight,g=a.instance.canvas.width,h=a.instance.canvas.height;b(c[0],va(a),wa(a),g,h,null);a.instance.canvas.getContext("2d").drawImage(k,0,0,g,h,0,0,d,f);return u});a.defineFunction("colorplot",3,function(c){oa();var d=c[0],f=a.extractPoint(a.evaluateAndVal(c[1])),g=a.extractPoint(a.evaluateAndVal(c[2])),h={x:Math.min(f.x,g.x),y:Math.min(f.y,g.y)},l={x:Math.max(f.x,g.x),y:Math.min(f.y,g.y)};c=a.instance.canvas.clientWidth;var q=a.instance.canvas.clientHeight,p=a.instance.canvas.width,
r=a.instance.canvas.height,t=ua(a,0,0),A=va(a),H=wa(a),H=Math.abs((f.x-g.x)/(A.x-H.x)),t=Math.abs((f.y-g.y)/(t.y-A.y));b(d,h,l,p*H,r*t,null);d=a.instance.canvas.getContext("2d");h=Math.min(f.x,g.x);f=Math.max(f.y,g.y);g=a.getInitialMatrix();d.drawImage(k,0,0,p*H,r*t,h*g.a-f*g.b+g.tx,h*g.c-f*g.d-g.ty,H*c,t*q);return u});a.defineFunction("colorplot",4,function(c){oa();var d=a.extractPoint(a.evaluateAndVal(c[0])),f=a.extractPoint(a.evaluateAndVal(c[1])),g=a.evaluateAndVal(c[2]);c=c[3];if(!d.ok||!f.ok||
"string"!==g.ctype)return u;var g=a.getImage(g.value,!0),h=Ha(g);b(c,d,f,g.width,g.height,h);return u});a.defineFunction("colorplot",2,function(c){oa();var d=va(a),f=wa(a),g=a.evaluateAndVal(c[0]);c=c[1];if("string"!==g.ctype)return u;var g=a.getImage(g.value,!0),h=Ha(g);b(c,d,f,g.width,g.height,h);return u});a.defineFunction("setpixel",4,function(b){var d;var f=a.evaluateAndVal(b[0]),g;g=void 0===g?null:g;"string"===f.ctype?d=f.value:(console.log("argument is not a string"),d=g);f=Va(a.evaluateAndVal(b[1]));
g=Va(a.evaluateAndVal(b[2]));b=Wa(a.evaluateAndVal(b[3]));if(!d)return u;var h=a.getImage(d,!0),h=Ha(h);isFinite(f)&&isFinite(g)&&d&&h&&b&&(h.bindTexture(),d=[b[0],b[1],b[2],1],n.texSubImage2D(n.TEXTURE_2D,0,f,g,1,1,n.RGBA,Ca(),Aa(d)),b=h.canvas.img.getContext("2d"),h=b.createImageData(1,1),h.data.d=d,b.putImageData(h,f,g));return u})});function I(a,b){return{type:"list",length:a,i:b}}function Sa(a){return{type:"constant",value:a}}function Xa(a){return Sa({ctype:"number",value:{real:a,imag:0}})}var z={F:1,v:2,f:3,h:4,X:5,color:6,M:7,T:8,J:9,image:10,N:I(2,3),O:I(3,3),da:I(4,3),ca:function(a){return I(a,3)},ga:function(a){return I(a,4)},ta:I(2,I(2,3)),ua:I(3,I(3,3)),va:I(4,I(4,3)),la:18};Object.freeze(z);
function D(a){return 1<=a&&10>=a?"bool int float complex voidt color point line coordinate2d image".split(" ")[a-1]:"list"===a.type?D(a.i)+"["+a.length+"]":"constant"===a.type?"const["+JSON.stringify(a.value.value)+"]":JSON.stringify(a)}function J(a){return"list"===a.type&&J(a.i)||G(a,z.f)}function K(a){return"list"===a.type&&K(a.i)||G(a,z.h)}function Ya(a){return"constant"===a.type&&G(a,z.v)}function L(a){return"constant"===a.type?y(a.value):a}function E(a){return"list"===a.type?E(a.i)+1:0}
function Qa(a){return void 0!==a.i?Qa(a.i):a}function Za(a,b){return E(a)===E(b)&&(0===E(a)||a.length===b.length&&Za(a.i,b.i))}function M(a){return G(a,z.f)?z.f:G(a,z.h)?z.h:{type:"list",length:a.length,i:M(a.i)}}function $a(a){return G(a,z.h)?z.h:{type:"list",length:a.length,i:$a(a.i)}}function N(a){return a===z.F||a===z.v||a===z.f||a===z.h||"list"===a.type&&a.i===z.f&&1<=a.length&&4>=a.length||"list"===a.type&&"list"===a.i.type&&a.i.i===z.f&&a.length===a.i.length&&2<=a.length&&4>=a.length}
function ab(a){return-1!==[z.F,z.v,z.f,z.h].indexOf(a)}function bb(a,b){return a===b||"constant"===a.type&&"constant"===b.type&&ra(a.value,b.value)||"list"===a.type&&"list"===b.type&&a.length===b.length&&bb(a.i,b.i)}
function G(a,b){return bb(a,b)||a===z.la?!0:a?ab(a)&&ab(b)?a<=b:"constant"===b.type?!1:"constant"===a.type?G(y(a.value),b):b===z.J?G(a,z.h)||G(a,z.N)||G(a,z.M):b===z.M||b===z.T?G(a,z.O):b===z.color?G(a,z.f)||"list"===a.type&&(3===a.length||4===a.length)&&G(a.i,z.f):"list"===a.type&&"list"===b.type&&a.length===b.length?G(a.i,b.i):!1:!1}
function B(a,b){if(!a)return b;if(!b||bb(a,b))return a;"constant"===a.type&&(a=y(a.value));"constant"===b.type&&(b=y(b.value));return ab(a)&&ab(b)?Math.max(a,b):"list"===a.type&&"list"===b.type&&a.length===b.length&&(b=B(a.i,b.i))?{type:"list",length:a.length,i:b}:!1}function O(a){return function(b){var c={},d;for(d in a){var f=a[d];c.fa=f[0];if(b.length==c.fa.length&&b.every(function(a){return function(b,c){return G(b,a.fa[c])}}(c)))return{u:c.fa,w:f[1],o:f[2]};c={fa:c.fa}}return!1}}
function cb(a){switch(a){case z.v:return O([[[z.F],z.v,P("int")]]);case z.f:return O([[[z.F],z.f,P("float")],[[z.v],z.f,P("float")]]);case z.h:return O([[[z.f],z.h,function(a){return"vec2("+a+", 0.)"}]]);case z.color:return O([[[z.f],z.color,R("float2color")],[[z.O],z.color,function(a){return"vec4("+a+",1.0)"}],[[z.da],z.color,db]]);case z.M:return O([[[z.N],z.M,function(a){return"vec3("+a+",1.0)"}],[[z.O],z.M,db]]);case z.T:return O([[[z.N],z.T,function(a){return"vec3("+a+",1.0)"}],[[z.O],z.T,db]]);
case z.J:return O([[[z.h],z.J,db],[[z.N],z.J,db],[[z.M],z.J,R("dehomogenize")]]);default:if("list"===a.type)return function(b){var c=b[0],d=cb(a.i)([c.i]).o;return{u:b,w:a,o:function(b,g,h){return eb(a)(F(a.length).map(function(a){return d([S(c,a)([b],g,h)],g,h)}),g,h)}}}}console.log("no inclusionfunction ->"+D(a)+" implemented yet; using identity...");return function(b){return{u:b,w:a,o:db}}}
function T(a){switch(a){case z.F:return"bool";case z.v:return"int";case z.f:return"float";case z.h:case z.J:return"vec2";case z.X:return"void";case z.color:return"vec4";case z.M:case z.T:return"vec3"}if("list"===a.type&&a.i===z.f)return 1==a.length?"float":"vec"+a.length;if("list"===a.type&&a.i===z.h)return"cvec"+a.length;if("list"===a.type&&"list"===a.i.type&&a.length===a.i.length&&a.i.i===z.f)switch(a.length){case 2:return"mat2";case 3:return"mat3";case 4:return"mat4"}if("list"===a.type)return"l"+
a.length+"_"+T(a.i);console.error("No WebGL implementation for type "+D(a)+" found")}function fb(a,b){switch(b){case z.F:return T(b)+"("+a.value+")";case z.v:return""+(a.value.real|0);case z.f:return T(b)+"("+a.value.real+")";case z.h:return T(b)+"("+a.value.real+", "+a.value.imag+")";case z.color:return a=a.value.real,"vec4("+a+","+a+","+a+",1.)";default:console.error("Dont know how to paste values of Type "+D(b)+" yet.")}};var U={};function gb(a,b,c){if(!c.mark("includedfunctions",a)){for(var d in U[a])gb(U[a][d],b,c);c.add("includedfunctions",a,function(){return ja[a]})}}function R(a){return function(b,c,d){gb(a,c,d);return P(a)(b)}};function F(a){return Array.from(Array(a).keys())}function Ra(a){return 4>=a?[a]:5==a?[2,3]:Ra(a-4).concat([4])}function hb(a){var b=Qa(a),c=E(a);return 1==c&&b===z.f?Ra(a.length).map(function(a,b){return{type:z.ca(a),name:"a"+b}}):1<=c?F(a.length).map(function(b){return{type:a.i,name:"a"+b}}):[]}function ib(a,b){if(!N(a)){var c=T(a);b.add("structs",c,function(){return"struct "+c+" { "+hb(a).map(function(a){return ib(a.type,b)||T(a.type)+" "+a.name+";"}).join("")+"};"})}}
function jb(a,b,c){if(!N(a)){var d=a.length,f=a.i.length;c.add("functions","mult"+d+"_"+f,function(){return T(z.ca(d))+" mult"+d+"_"+f+"("+T(a)+" a, "+T(z.ca(f))+" b){return "+kb(d)(F(d).map(function(a){return lb(f)(["a.a"+a,"b"],b,c)}),b,c)+";}"})}}
function mb(a,b,c){if(!N(a)){var d=a.length,f="sum"+T(a);c.add("functions",f,function(){return T(a.i)+" "+f+"("+T(a)+" a){"+(T(a.i)+" res = "+nb(a.i,0)([],b,c)+";\n      "+F(d).map(function(d){return"res = "+ob(a.i)(["res",S(a,d)(["a",d],b,c)],b,c)+";"}).join("\n")+"\n        return res;\n    }")})}}
function pb(a,b,c){var d=a.length,f=a.i.length;c.add("functions","multc"+d+"_"+f,function(){return T(z.ga(d))+" multc"+d+"_"+f+"("+T(a)+" a, "+T(z.ga(f))+" b){\n        return cvec"+d+"("+F(d).map(function(a){return qb(f)(["a.a"+a,"b"],b,c)})+");\n    }\n    "})}function rb(a,b){2<=a&&4>=a||b.add("functions","dot"+a,function(){return"float dot"+a+"(vec"+a+" a, vec"+a+" b) {\n    return "+Ra(a).map(function(a,b){return"dot(a.a"+b+",b.a"+b+")"}).join("+")+"; }\n    "})}
function sb(a,b){b.add("functions","cdot"+a,function(){return"vec2 cdot"+a+"(cvec"+a+" a, cvec"+a+" b) {\n      return "+F(a).map(function(a){return"vec2(dot(a.a"+a+",vec2(b.a"+a+".x,-b.a"+a+".y)), dot(a.a"+a+",b.a"+a+".yx))"}).join("+\n")+";\n    }\n    "})}
function tb(a,b,c){var d="add"+T(a);c.add("functions",d,function(){return T(a)+" "+d+"("+T(a)+" a, "+T(a)+" b) {\n    return "+T(a)+"("+hb(a).map(function(a){return T(a.type)+"("+ob(a.type)(["a."+a.name,"b."+a.name],b,c)+")"}).join(",")+");\n      }"})}
function ub(a,b,c){var d="sub"+T(a);c.add("functions",d,function(){return T(a)+" "+d+"("+T(a)+" a, "+T(a)+" b) {\n    return "+T(a)+"("+hb(a).map(function(a){return T(a.type)+"("+vb(a.type)(["a."+a.name,"b."+a.name],b,c)+")"}).join(",")+");\n    }"})}function wb(a,b,c){var d="scalarmult"+T(a);c.add("functions",d,function(){return T(a)+" "+d+"(float a, "+T(a)+" b) {\n    return "+T(a)+"("+hb(a).map(function(a){return T(a.type)+"("+xb(a.type)(["a","b."+a.name],b,c)+")"}).join(",")+");\n    }"})}
function yb(a,b,c){gb("multc",b,c);var d="cscalarmult"+T(a);c.add("functions",d,function(){return T(a)+" "+d+"(vec2 a, "+T(a)+" b) {\n    return "+T(a)+"("+hb(a).map(function(a){return""+zb(a.type)(["a","b."+a.name],b,c)}).join(",")+");\n    }"})}
function Ab(a){if(a===z.h)return R("multc");if(N(a))return function(a){return V("*")([a[1],a[0]])};var b=Qa(a);if(G(b,z.f))return function(b,d,f){return jb(a,d,f)||"mult"+a.length+"_"+a.i.length+"("+b.join(",")+")"};if(b===z.h)return function(b,d,f){return pb(a,d,f)||"multc"+a.length+"_"+a.i.length+"("+b.join(",")+")"}}function lb(a){return function(b,c,d){return rb(a,d)||"dot"+(2<=a&&4>=a?"":a)+"("+b.join(",")+")"}}
function qb(a){return function(b,c,d){return sb(a,d)||"cdot"+a+"("+b.join(",")+")"}}function ob(a){return N(a)?V("+"):function(b,c,d){return tb(a,c,d)||"add"+T(a)+"("+b.join(",")+")"}}function vb(a){return N(a)?V("-"):function(b,c,d){return ub(a,c,d)||"sub"+T(a)+"("+b.join(",")+")"}}function Bb(a){return J(a)&&1==E(a)?function(b,c,d){return lb(a.length)([b[0],kb(a.length)(Array(a.length).fill("1."),c,d)],c,d)}:function(b,c,d){return mb(a,c,d)||"sum"+T(a)+"("+b.join(",")+")"}}
function kb(a){if(2<=a&&4>=a)return function(b){return"vec"+a+"("+b.join(",")+")"};if(1==a)return function(a){return"float("+a.join(",")+")"};var b=0;return function(c,d,f){return ib(z.ca(a),f)||"vec"+a+"("+Ra(a).map(function(a){return"vec"+a+"("+F(a).map(function(){return++b&&c[b-1]}).join(",")+")"}).join(",")+")"}}function eb(a){return N(a)?function(b){return T(a)+"("+b.join(",")+")"}:1==E(a)&&a.i===z.f?kb(a.length):function(b,c,d){return ib(a,d)||T(a)+"("+b.join(",")+")"}}
function S(a,b){var c=Qa(a);return 1==E(a)&&c===z.f?Cb(a.length,b):N(a)?function(a){return"("+a[0]+")["+b+"]"}:function(a){return"("+a[0]+").a"+b}}function nb(a,b){return N(a)?function(){return T(a)+"(float("+b+"))"}:function(c,d,f){return eb(a)+"("+hb(a).map(function(a){return nb(a.type,b)(c,d,f)}).join(",")+")"}}
function Cb(a,b){return function(c){if(1==a)return c[0];if(2<=a&&4>=a)return"("+c[0]+")["+b+"]";var d;a:{d=b;var f=Ra(a),g;for(g in f)if(f[g]<=d)d-=f[g];else{d={first:g,second:d};break a}console.error("Accessing index out of range");d=void 0}return"("+c[0]+").a"+d.first+"["+d.second+"]"}}function xb(a){return N(a)?V("*"):function(b,c,d){return wb(a,c,d)||"scalarmult"+T(a)+"("+b.join(",")+")"}}
function zb(a){return a===z.h?R("multc"):function(b,c,d){return yb(a,c,d)||"cscalarmult"+T(a)+"("+b.join(",")+")"}}function Db(a,b,c){var d="reverse"+T(a);c.add("functions",d,function(){return T(a)+" "+d+"("+T(a)+" a){"+(T(a.i)+" m;\n")+F(Math.floor(a.length/2)).map(function(d){var g=S(a,d)(["a",d],b,c);d=S(a,a.length-1-d)(["a",a.length-1-d],b,c);return"m = "+g+"; "+g+" = "+d+"; "+d+" = m;"}).join("\n")+"return a;\n      }"})}
function Eb(a){return function(b,c,d){return Db(a,c,d)||"reverse"+T(a)+"("+b.join(",")+")"}}function Fb(a,b,c){var d="max"+T(a);c.add("functions",d,function(){return T(a.i)+" "+d+"("+T(a)+" a){"+(T(a.i)+" m = "+S(a,a.length-1)(["a",a.length-1],b,c)+";\n")+F(a.length-1).map(function(d){return"m = max(m,"+S(a,d)(["a",d],b,c)+");"}).join("\n")+"return m;\n      }"})}function Gb(a){return function(b,c,d){return Fb(a,c,d)||"max"+T(a)+"("+b.join(",")+")"}}
function Hb(a,b,c){var d="min"+T(a);c.add("functions",d,function(){return T(a.i)+" "+d+"("+T(a)+" a){"+(T(a.i)+" m = "+S(a,a.length-1)(["a",a.length-1],b,c)+";\n")+F(a.length-1).map(function(d){return"m = min(m,"+S(a,d)(["a",d],b,c)+");"}).join("\n")+"return m;\n      }"})}function Ib(a){return function(b,c,d){return Hb(a,c,d)||"min"+T(a)+"("+b.join(",")+")"}};function Jb(a){function b(a,d,h){if(1<d){var l=d/2|0;b(a,l,!h);b(a+l,d-l,h);c(a,d,h)}}function c(a,b,h){if(1<b){var l;for(l=1;l<b;)l<<=1;l>>=1;for(var q=a;q<a+b-l;q++){var p=q,r=q+l;h?d.push([p,r]):d.push([r,p])}c(a,l,h);c(a+l,b-l,h)}}var d=[];b(0,a,!0);return d}
function Kb(a,b,c){var d="sort"+T(a);c.add("functions",d,function(){return T(a)+" "+d+"("+T(a)+" a){"+(T(a.i)+" m;\n")+Jb(a.length).map(function(d){var g=S(a,d[0])(["a",d[0]],b,c);d=S(a,d[1])(["a",d[1]],b,c);return"m = min("+g+","+d+"); "+d+" = max("+g+","+d+"); "+g+" = m;"}).join("\n")+"return a;\n      }"})}function Lb(a){return function(b,c,d){return Kb(a,c,d)||"sort"+T(a)+"("+b.join(",")+")"}};function P(a){return function(b){return x(a)+"("+b+")"}}function V(a){return function(b){return"("+b.join(a)+")"}}function db(a){return a}var W={};W.join=O([[z.M,z.M],z.T,P("cross")]);W.meet=O([[z.T,z.T],z.M,P("cross")]);
W["if"]=function(a){if(!a.every(function(a){return a}))return!1;if(2===a.length)return{u:a,w:a[1],o:function(a){return"if("+a[0]+") {"+a[1]+";}"}};if(3===a.length){var b=B(a[1],a[2]);return b?{u:[z.F,b,b],w:b,o:function(a){return"("+a[0]+" ? "+a[1]+" : "+a[2]+")"}}:{u:a,w:z.X,o:function(a){return"if("+a[0]+") {"+a[1]+";} else {"+a[2]+";}"}}}return!1};W["="]=function(a){a=B(a[0],a[1]);return{u:a,w:a,o:function(a){return a[0]+" = "+a[1]+";"}}};
W[";"]=function(a){return{u:a,w:a[1]!==z.X?a[1]:a[0],o:function(a){return a[0]+" ; "+a[1]+";"}}};W.repeat=function(a){return 2!=a.length&&3!=a.length||!Ya(a[0])?!1:{u:a,w:a[a.length-1],o:function(){return""}}};W.forall=function(a){return 2!=a.length&&3!=a.length||"list"!==L(a[0]).type?!1:{u:a,w:a[a.length-1],o:function(){return""}}};W.apply=function(a){return 2!=a.length&&3!=a.length||"list"!==L(a[0]).type?!1:{u:a,w:I(L(a[0]).length,a[a.length-1]),o:function(){return""}}};
W.sum=function(a){return 1==a.length&&(J(a[0])||K(a[0]))?{u:a,w:a[0].i,o:Bb(a[0])}:!1};W.regional=function(a){return{u:a,w:z.X,o:function(){return""}}};W.sqrt=O([[[z.f],z.h,R("sqrtf")],[[z.h],z.h,R("sqrtc")]]);W.abs=O([[[z.f],z.f,P("abs")],[[z.h],z.f,P("length")],[[z.N],z.f,P("length")],[[z.O],z.f,P("length")],[[z.da],z.f,P("length")]]);W.abs_infix=W.abs;
W.dist=O([[[z.f,z.f],z.f,function(a){return P("abs")(V("-")(a))}],[[z.h,z.h],z.f,function(a){return P("length")(V("-")(a))}],[[z.N,z.N],z.f,function(a){return P("length")(V("-")(a))}],[[z.O,z.O],z.f,function(a){return P("length")(V("-")(a))}],[[z.da,z.da],z.f,function(a){return P("length")(V("-")(a))}]]);W.dist_infix=W.dist;W.sin=O([[[z.f],z.f,P("sin")],[[z.h],z.h,R("sinc")]]);W.cos=O([[[z.f],z.f,P("cos")],[[z.h],z.h,R("cosc")]]);W.tan=O([[[z.f],z.f,P("tan")],[[z.h],z.h,R("tanc")]]);
W.exp=O([[[z.f],z.f,P("exp")],[[z.h],z.h,R("expc")]]);W.arctan=O([[[z.f],z.f,P("atan")],[[z.h],z.h,R("arctanc")]]);W.log=O([[[z.f],z.h,R("logr")],[[z.h],z.h,R("logc")]]);var Mb=[2,3,4].map(function(a){return I(a,z.f)}).concat([2,3,4].map(function(a){return I(a,I(a,z.f))})),Nb=[z.v,z.f,z.h].concat(Mb);W.add=function(a){var b=O(Nb.map(function(a){return[[a,a],a,V("+")]}))(a);if(b)return b;b=a[0];a=a[1];if([b,a].every(function(a){return J(a)||K(a)})&&Za(b,a))return a=B(M(b),M(a)),{u:[a,a],w:a,o:ob(a)}};
W.sub=function(a){var b=O(Nb.map(function(a){return[[a,a],a,V("-")]}).concat(Nb.map(function(a){return[[z.X,a],a,V("-")]})))(a);if(b)return b;b=a[0];a=a[1];if([b,a].every(function(a){return J(a)||K(a)})&&Za(b,a))return a=B(M(b),M(a)),{u:[a,a],w:a,o:vb(a)}};W["+"]=W.add;W["-"]=W.sub;
W._=function(a){var b=L(a[0]);if("list"===b.type&&Ya(a[1])){var c=Number(a[1].value.value.real);return 1<=Math.abs(c)&&Math.abs(c)<=b.length?(0<c&&--c,0>c&&(c=b.length-c),{u:a,w:b.i,o:S(b,c)}):{u:a,w:b.i,o:function(){return console.error("try to access "+c+"-th Element of "+b.length+"-list "+JSON.stringify(a[0]))}}}return!1};
W.mult=function(a){var b=O([[[z.v,z.v],z.v,V("*")],[[z.f,z.f],z.f,V("*")],[[z.h,z.f],z.h,V("*")],[[z.f,z.h],z.h,V("*")],[[z.h,z.h],z.h,R("multc")]])(a);if(b)return b;if(2!==a.length)return!1;var b=a[0],c=a[1];if([b,c].every(function(a){return"list"===a.type&&G(a.i,z.f)})&&b.length===c.length)return a=M(b),N(a)?{u:[a,a],w:z.f,o:P("dot")}:{u:[a,a],w:z.f,o:lb(b.length)};if([b,c].every(function(a){return"list"===a.type&&G(a.i,z.h)})&&b.length===c.length)return a=$a(b),{u:[a,a],w:z.h,o:qb(b.length)};if(J(b)&&
2===E(b)&&J(c)&&1===E(c)&&b.i.length===c.length)return{u:[M(b),M(c)],w:z.ca(b.length),o:Ab(M(b))};if(K(b)&&2===E(b)&&K(c)&&1===E(c)&&b.i.length===c.length)return{u:[$a(b),$a(c)],w:z.ga(b.length),o:Ab($a(b))};for(b={H:0};2>b.H;b={Y:b.Y,H:b.H,ea:b.ea},b.H++){if(G(a[0^b.H],z.f)&&(J(a[1^b.H])||K(a[1^b.H])))return b.Y=M(a[1^b.H]),{u:b.H?[b.Y,z.f]:[z.f,b.Y],w:b.Y,o:function(a){return function(b,c,h){return xb(a.Y)([b[0^a.H],b[1^a.H]],c,h)}}(b)};if(G(a[0^b.H],z.h)&&K(a[1^b.H]))return b.ea=$a(a[1^b.H]),{u:b.H?
[b.ea,z.h]:[z.h,b.ea],w:b.ea,o:function(a){return function(b,c,h){return zb(a.ea)([b[0^a.H],b[1^a.H]],c,h)}}(b)}}};W["*"]=W.mult;W.div=function(a){var b=O([[[z.f,z.f],z.f,V("/")],[[z.f,z.h],z.h,R("divfc")],[[z.h,z.f],z.h,V("/")],[[z.h,z.h],z.h,R("divc")]])(a);return b?b:G(a[1],z.f)&&K(a[0])&&(a=M(a[0]),N(a))?{u:[a,z.f],w:a,o:V("/")}:!1};W["/"]=W.div;W.re=O([[[z.h],z.f,R("realc")]]);W.im=O([[[z.h],z.f,R("imagc")]]);W.floor=O([[[z.f],z.v,function(a){return"int(floor("+a+"))"}],[[z.h],z.h,P("floor")]]);
W.round=O([[[z.f],z.v,function(a){return"int(floor("+a+"+.5))"}],[[z.h],z.h,function(a){return"floor("+a+"+vec2(.5))"}]]);W.ceil=O([[[z.f],z.v,function(a){return"int(ceil("+a+"))"}],[[z.h],z.h,P("ceil")]]);W.mod=O([[[z.v,z.v],z.v,function(a,b){return"int("+P("mod")("float("+a[0]+"), float("+a[1]+")",b)+")"}],[[z.f,z.f],z.f,P("mod")],[[z.h,z.h],z.h,R("mod")]]);
W.random=O([[[],z.f,R("random")],[[z.f],z.f,function(a,b){return R("random")([],b)+"*"+a[0]}],[[z.h],z.h,function(a,b){return"vec2("+R("random")([],b)+","+R("random")([],b)+")*"+a[0]}]]);W.arctan2=O([[[z.f,z.f],z.f,function(a){return"atan("+a[1]+", "+a[0]+")"}],[[z.h,z.h],z.h,R("arctan2c")],[[z.h],z.f,R("arctan2vec2")],[[z.N],z.f,R("arctan2vec2")],[[z.ga(2)],z.h,R("arctan2cvec2")]]);["red","green","blue","gray","hue"].forEach(function(a){W[a]=O([[[z.f],z.O,R(a)]])});W.grey=W.gray;
W.min=function(a){var b=O([[[z.v,z.v],z.v,P("min")],[[z.f,z.f],z.f,P("min")]])(a);if(b)return b;if(1===a.length&&1===E(a[0])&&J(a[0]))return{u:a,w:a[0].i,o:Ib(a[0])}};W.max=function(a){var b=O([[[z.v,z.v],z.v,P("max")],[[z.f,z.f],z.f,P("max")]])(a);if(b)return b;if(1===a.length&&1===E(a[0])&&J(a[0]))return{u:a,w:a[0].i,o:Gb(a[0])}};W.complex=O([[[z.N],z.h,db]]);
function Ob(a,b){if(!(1>=a))if(2==a)b.add("functions","raise2",function(){return"float raise2(float a) { return a*a; }"});else{Ob(2,b);var c=function(a,b){return 1==b?a:b&1?c(a,b-1)+"*a":"raise2("+c(a,b/2)+")"},d="raise"+a;b.add("functions",d,function(){return"float "+d+"(float a) { return "+c("a",a)+";}"})}}function Pb(a){return function(b,c,d){return 0==a?"1.":1==a?b[0]:Ob(a,d)||"raise"+a+"("+b[0]+")"}}
W.pow=function(a){if(Ya(a[1])&&G(a[0],z.f)){var b=Number(a[1].value.value.real);if(0<=b)return{u:[z.f,a[1]],w:z.f,o:Pb(b)}}return O([[[z.f,z.v],z.f,R("powi")],[[z.h,z.h],z.h,R("powc")]])(a)};W["^"]=W.pow;W.re=O([[[z.h],z.f,function(a){return"("+a+").x"}]]);W.conjugate=O([[[z.h],z.h,R("conjugate")]]);W.im=O([[[z.h],z.f,function(a){return"("+a+").y"}]]);W.genList=function(a){var b=a.length;if(0<b){var c=!1,d;for(d in a)c=B(c,a[d]);if(c)return a=I(b,c),{u:Array(b).fill(c),w:a,o:eb(a)}}return!1};
W["&"]=O([[[z.F,z.F],z.F,V("&&")]]);W["%"]=O([[[z.F,z.F],z.F,V("||")]]);"> < >= <= == !=".split(" ").forEach(function(a){W[a]=O([[[z.v,z.v],z.F,V(a)],[[z.f,z.f],z.F,V(a)]])});W.imagergb=O([[[z.image,z.J],z.O,Qb],[[z.J,z.J,z.image,z.J],z.O,Rb]]);W.imagergba=O([[[z.image,z.J],z.da,Sb],[[z.J,z.J,z.image,z.J],z.da,Tb]]);W.reverse=function(a){return 1===a.length&&"list"===a[0].type?{u:a,w:a[0],o:Eb(a[0])}:!1};W.sort=function(a){return 1===a.length&&1===E(a[0])&&J(a[0])?{u:a,w:a[0],o:Lb(a[0])}:!1};Object.freeze(W);
U.powc=["expc","multc","logc"];U.sqrtc=["expc","multc","logc"];U.arccosc=["multc","negc","sqrtc","addc","logc"];U.arcsinc=["multc","negc","sqrtc","addc","logc"];U.tanc=["sinc","cosc","divc"];U.arctanc=["logc","addc","multc","subc"];U.arctan2c=["logc","divc","sqrtc","multc"];U.arctan2vec2c=["arctan2c"];U.hue=["hsv2rgb"];Object.freeze(U);function Oa(a){this.j={};this.D={};this.l={};this.P=0;this.s={};this.B=a;this.C={}}Oa.prototype.add=function(a,b,c){this.mark(a,b);this.l[a].ka[b]||(this.l[a].ka[b]=c(),this.l[a].ja[b]=!0,this.l[a].order.push(b))};Oa.prototype.mark=function(a,b){this.l[a]||(this.l[a]={order:[],ja:{},ka:{}});var c=this.l[a].ja[b]||!1;this.l[a].ja[b]=!0;return c};function Ub(a,b){return a.l[b]?a.l[b].order.map(function(c){return a.l[b].ka[c]}).join("\n"):"\n"}
function Vb(a,b,c,d){if(bb(c,d)||c===z.la)return b;if(G(c,d)){if("constant"===c.type)return fb(c.value,d);var f=cb(d)([c]);if(!f)return console.error("cannot find an implementation for "+D(c)+" -> "+D(d)+", using identity"),b;d=f.o;return d(Vb(a,b,c,f.u[0]),{},a)}console.error(D(c)+" is no subtype of "+D(d)+" (trying to cast the term "+b+")");return b}function X(a,b,c){a.j[b]||(a.j[b]={});a.j[b].R||(a.j[b].R=[]);a.j[b].A||(a.j[b].A=!1);a.hasOwnProperty("global")||(a.j[b].global=c)}
function Wb(a,b){var c=b.I;if(b.isuniform)return a.D[b.uvariable].type;if("variable"===b.ctype)return b=b.name,b=c[b]||b,a.j[b].A;if("function"===b.ctype&&a.s.hasOwnProperty(b.oper))return a.j[c[b.oper]].A;if("number"===b.ctype)return Sa(b);if("void"===b.ctype)return z.X;if("field"===b.ctype){a=L(Y(a,b.obj));if("list"===a.type)return a.i;if(!a)return!1}else{if("string"===b.ctype)return z.image;if("function"===b.ctype||"infix"===b.ctype){for(var c=Array(b.args.length),d=!0,f=0;f<b.args.length;f++)c[f]=
Y(a,b.args[f]),d&="constant"===c[f].type;if(d&&b.impl)return b={ctype:b.ctype,oper:b.oper,impl:b.impl,args:c.map(function(a){return a.value})},b=a.B.evaluateAndVal(b),Sa(b);a=x(b.oper);d=W[a]?W[a](c):!1;if(!d&&c.every(function(a){return Qa(a)}))throw console.error("Could not find an implementation for "+a+" with args ("+c.map(D).join(", ")+")"),console.log(b),"error";return d?d.w:!1}}console.error("Don't know how to compute type of");console.log(b);return!1}
function Y(a,b){if(!b.ma||!b.P||a.P>b.P)b.ma=Wb(a,b),b.P=a.P;return b.ma}
function Xb(a,b){function c(a,b,c){var d={},g;for(g in a)d[g]=a[g];a=C();X(h,a,!1);f[a].A=c;f[a].qa=!0;d[b]=a;return d}function d(a,b,p,r){a.I=b;for(var t in a.args){var A=r||"repeat$2"===a.oper&&0==t||"repeat$3"===a.oper&&0==t||"_"===a.oper&&1==t,H=b;-1!=["repeat","forall","apply"].indexOf(x(a.oper))&&(1==t?H="repeat$2"===a.oper?c(b,"#",z.v):"repeat$3"===a.oper?c(b,a.args[1].name,z.v):"forall$2"===a.oper||"apply$2"===a.oper?c(b,"#",!1):"forall$3"===a.oper||"apply$3"===a.oper?c(b,a.args[1].name,!1):
b:2==t&&(H=a.args[1].I));d(a.args[t],H,p,A)}"field"===a.ctype&&d(a.obj,b,p,r);"variable"===a.ctype&&(t=a.name,t=b[t]||t,r&&h.j[t]&&(h.j[t].ha=!0));if("="===a.oper)r=a.args[0].name,r=b[r]||r,X(h,r,!0),f[r].R.push(a.args[1]);else if(a.oper&&"regional"===x(a.oper)&&"global"!=p)for(var Q in a.args){r=a.args[Q].name;var la=C();b[r]=la;g[p].j||(g[p].j=[]);g[p].j.push(la);X(h,la,!1)}else if("forall$2"===a.oper||"apply$2"===a.oper||"forall$3"===a.oper||"apply$3"===a.oper)f[2===a.args.length?a.args[1].I["#"]:
a.args[2].I[a.args[1].name]].R.push({ctype:"infix",oper:"_",args:[a.args[0],{ctype:"number",value:{real:1,imag:0}}],I:a.args[0].I});else if("function"===a.ctype&&g.hasOwnProperty(a.oper)){p=a.oper;Q=p.replace("$","_");X(h,Q,!1);b[p]=Q;b={};for(la in g[p].arglist)t=g[p].arglist[la].name,A=Q+"_"+t,b[t]=A,X(h,A,!1),f[A].R.push(a.args[la]);g[p].sa||(g[p].sa=!0,d(g[p].body,b,p,r),f[Q].R.push(g[p].body))}}var f=a.j,g=a.s,h=a;d(b,{"#":"cgl_pixel"},"global",!1)}
function Yb(a,b){function c(a){if(a.hasOwnProperty("dependsOnPixel"))return a.dependsOnPixel;if("variable"===a.ctype){var b=a.name,b=a.I[b]||b;return h[b]?a.dependsOnPixel=!0:a.dependsOnPixel=!1}b=["random","verbatimglsl"];if("function"===a.ctype&&-1!=b.indexOf(x(a.oper)))return a.dependsOnPixel=!0;if("repeat$2"===a.oper||"forall$2"===a.oper||"apply$2"===a.oper)return c(a.args[1])?(h[a.args[1].I["#"]]=!0,a.dependsOnPixel=!0):a.dependsOnPixel=!1;if("repeat$3"===a.oper||"forall$3"===a.oper||"apply$3"===
a.oper)return c(a.args[2])?(h[a.args[2].I[a.args[1].name]]=!0,a.args[1].dependsOnPixel=!0,a.dependsOnPixel=!0):a.dependsOnPixel=!1;for(var d in a.args)if(c(a.args[d]))return a.dependsOnPixel=!0;return"function"===a.ctype&&g.hasOwnProperty(a.oper)&&c(g[a.oper].body)?a.dependsOnPixel=!0:"field"===a.ctype?a.dependsOnPixel=c(a.obj):a.dependsOnPixel=!1}function d(a,b){if(c(a)){for(var f in a.args)d(a.args[f],b||"repeat$2"===a.oper&&0==f||"repeat$3"===a.oper&&0==f||"_"===a.oper&&1==f);"field"===a.ctype&&
d(a.obj,b);"function"===a.ctype&&g.hasOwnProperty(a.oper)&&(a=a.oper,q.hasOwnProperty(a)||(q[a]=!0,d(g[a].body,b)))}else if("number"!==a.ctype&&"void"!==a.ctype){".."===a.oper&&(b=!0);f=!1;var h,l;for(l in p)!f&&ra(a,p[l].Z)&&(f=!0,h=l);f||(h=C(),p[h]={Z:a,type:!1,ha:b});a.isuniform=!0;a.uvariable=h}}var f=a.j,g=a.s,h={cgl_pixel:!0},l;for(l in f)if(1<=f[l].R.length||f[l].qa)h[l]=!0;c(b);var q={"":!0},p=a.D;d(b,!1)}
function Zb(a,b){if("function"===b.ctype&&!a.s.hasOwnProperty(b.oper)&&null!==a.B.getMyfunction(b.oper)){var c=b.oper;a.s[c]=qa(a.B.getMyfunction(c));Zb(a,a.s[c].body)}for(var d in b.args)Zb(a,b.args[d])}
function Z(a,b,c){var d=Y(a,b);if(b.isuniform)return b=b.uvariable,c?{code:"",m:"constant"===d.type?fb(d.value,L(d)):b}:{code:""};if(";"===b.oper){for(var d={m:""},f="",g=b.args.length-1,h=g;0<=h;h--)"void"===b.args[h].ctype&&(g=h-1);for(h=0;h<=g;h++)d=Z(a,b.args[h],c&&h===g),f+=d.code;return c?{code:f,m:d.m}:{code:f}}if("constant"===d.type)return c?{m:fb(d.value,L(d)),code:""}:{code:""};if("="===b.oper)return d=Z(a,b.args[1],!0),b=Z(a,b.args[0],!0).m+" = "+Vb(a,d.m,Y(a,b.args[1]),Y(a,b.args[0])),
c?{code:d.code,m:b}:{code:d.code+b+";\n"};if("repeat$2"===b.oper||"repeat$3"===b.oper){f=Z(a,b.args[0],!0);if("constant"!==Y(a,b.args[0]).type)return console.error("repeat possible only for fixed constant number in GLSL"),!1;d="repeat$2"===b.oper?b.args[1].I["#"]:b.args[2].I[b.args[1].name];f=Number(f.m);g="";if("constant"===a.j[d].A.type)for(h=1;h<=f;h++){a.j[d].A=Xa(h);a.P++;var l=Z(a,b.args["repeat$2"===b.oper?1:2],h===f&&c),g=g+l.code;if(h===f&&c)return{code:g,m:l.m}}else if(h="",l=Z(a,b.args["repeat$2"===
b.oper?1:2],c),b=Y(a,b.args["repeat$2"===b.oper?1:2]),c&&(h=C(),a.j[h]||(X(a,h,!0),a.j[h].A=b)),g=g+("for(int "+d+"=1; "+d+" <= "+f+"; "+d+"++) {\n")+l.code,c&&(g+=h+" = "+l.m+";\n"),g+="}\n",c)return{code:g,m:h};return{code:g}}if("forall$2"===b.oper||"forall$3"===b.oper||"apply$2"===b.oper||"apply$3"===b.oper){var q=Y(a,b.args[0]);if("list"!==q.type&&("constant"!==q.type||"list"!==q.value.ctype))return console.error(b.oper+" only possible for lists"),!1;var f=q.length||q.value.value.length,h=2===
b.args.length?b.args[1].I["#"]:b.args[2].I[b.args[1].name],p=a.j[h].A,r=l="";c&&(r=C(),l+=T(d)+" "+r+";\n");"list"===d.type&&ib(d,a);if("constant"===a.j[h].A.type||"constant"===q.type)for(q=a.B.evaluateAndVal(b.args[0]),p=0;p<f;p++)a.j[h].A=Sa(q.value[p]),a.P++,g=Z(a,b.args[2===b.args.length?1:2],c),l+=g.code,"forall$2"===b.oper||"forall$3"===b.oper?p+1===f&&c&&(l+=r+" = "+g.m+";\n"):c&&(l+=S(d,p)([r],[],a)+" = "+g.m+";\n");else{var g=Z(a,b.args[2===b.args.length?1:2],c),t=Z(a,b.args[0],!0),l=l+t.code,
A=t.m;!a.j[A]&&!a.D[A]&&2<=q.length&&(A=C(),l+=T(q)+" "+A+" = "+t.m+";\n");a.j[h].global=!0;for(t=0;t<f;t++)l+=h+" = "+S(q,t)([A],[],a)+";\n",l+=g.code,c&&("forall$2"===b.oper||"forall$3"===b.oper?t===f-1&&(l+=r+" = "+g.m+";\n"):l+=S(d,t)([r],[],a)+" = "+g.m+";\n");"list"===p.type&&ib(p,a)}return c?{code:l,m:r}:{code:l}}if("if$2"===b.oper||"if$3"===b.oper){l=Z(a,b.args[0],!0);f=Y(a,b.args[0]);h=g="";r=Z(a,b.args[1],c);c&&(h=C(),a.j[h]||(X(a,h,!0),a.j[h].A=d));"constant"!=f.type&&(g+=l.code,g+="if("+
l.m+") {\n");if("constant"!=f.type||"constant"==f.type&&f.value.value)g+=r.code,c&&(g+=h+" = "+Vb(a,r.m,Y(a,b.args[1]),d)+";\n");"if$3"===b.oper&&(l=Z(a,b.args[2],c),"constant"!=f.type&&(g+="} else {\n"),"constant"!=f.type||"constant"==f.type&&!f.value.value)&&(g+=l.code,c&&(g+=h+" = "+Vb(a,l.m,Y(a,b.args[2]),d)+";\n"));"constant"!=f.type&&(g+="}\n");return c?{code:g,m:h}:{code:g}}if("function"===b.ctype||"infix"===b.ctype){l=b.oper;if("verbatimglsl"===x(l))return b=a.B.evaluateAndVal(b.args[0]).value,
c?{m:b,code:""}:{code:b};d=b.args.map(function(b){return Z(a,b,!0)});f=b.args.map(function(b){return Y(a,b)});if(a.s.hasOwnProperty(l))for(h=$b(a,l),g=Array(d.length),r=0;r<d.length;r++)g[r]=a.j[a.s[l].body.I[a.s[l].arglist[r].name]].A;else{l=x(l);if("regional"===l)return c?{m:"",code:""}:{code:""};h=W[l](f);if(!h)return console.error("Could not find an implementation for "+l+"("+f.map(D).join(", ")+").\nReturning empty code"),c?{m:"",code:""}:{code:""};g=h.u;h=h.o}l="";r=Array(d.length);for(q=0;q<
d.length;q++)l+=d[q].code,r[q]=Vb(a,d[q].m,f[q],g[q]);b=h(r,b.modifs,a);return c?{m:b,code:l}:{code:l+b+";\n"}}if("variable"===b.ctype)return d=b.name,d=b.I[d]||d,c?{m:d,code:""}:{code:d+";\n"};if("void"===b.ctype)return c?{m:"",code:""}:{code:""};if("field"===b.ctype&&(d={x:0,y:1,z:2,r:0,g:1,b:2,a:3}[b.key],void 0!=d))return b=S(Y(a,b.obj),d)([Z(a,b.obj,!0).m],null,a),c?{m:b,code:""}:{code:b+";\n"};console.error("dont know how to this.compile "+JSON.stringify(b))}
function $b(a,b){ac(a,b,a.s[b].arglist.length);return P(b.replace("$","_"))}
function ac(a,b,c){if(!a.mark("compiledfunctions",b)){for(var d=a.s[b],f=b.replace("$","_"),g=d.body.I,h=Array(c),l=0;l<c;l++)h[l]=d.arglist[l].name;c=a.j[f].A===z.X;var q=T(a.j[f].A)+" "+f+"("+h.map(function(b){return T(a.j[g[b]].A)+" "+g[b]}).join(", ")+"){\n",p;for(p in d.j)h=d.j[p],q+=T(a.j[h].A)+" "+h+";\n";p=Z(a,d.body,!c);d=Y(a,d.body);q+=p.code;c||(q+="return "+Vb(a,p.m,d,a.j[f].A)+";\n");q+="}\n";a.add("compiledfunctions",b,function(){return q})}}
function Na(a,b){sa=0;b=qa(b);X(a,"cgl_pixel",!1);a.j.cgl_pixel.A=z.N;var c=b;Zb(a,c);Xb(a,c);Yb(a,c);for(var d in a.D)c=a.B.evaluateAndVal(a.D[d].Z),a.D[d].type=a.D[d].ha?Sa(c):y(c);d=!0;for(var f in a.j)a.j[f].A=a.j[f].A||!1,a.j[f].ha&&(a.j[f].A=Xa(1),a.P++);for(;d;){d=!1;for(var g in a.j)if(!a.j[g].ha)for(var h in a.j[g].R){f=L(Y(a,a.j[g].R[h]));var l=c=a.j[g].A||!1;f&&(c?G(f,c)?l=c:l=B(c,f):l=f,l&&l!==c&&(a.j[g].A=l,a.P++,d=!0))}}for(var q in a.D)"list"===a.D[q].type.type&&ib(a.D[q].type,a);for(var p in a.j)"list"===
a.j[p].A.type&&ib(a.j[p].A,a);g=Z(a,b,!0);h=Y(a,b);b=Vb(a,g.m,h,z.color);G(h,z.color)||console.error("expression does not generate a color");h=Ub(a,"structs");h+=Ub(a,"uniforms");q=[];for(var r in a.D)"constant"!=a.D[r].type.type&&a.D[r].type!=z.image&&q.push("uniform "+T(a.D[r].type)+" "+r+";");h+=q.join("\n");r="";for(var t in a.C)for(var A in a.C[t])r+=a.C[t][A].code+"\n";h=h+r+Ub(a,"includedfunctions");h+=Ub(a,"functions");for(var H in a.j)a.j[H].A&&a.j[H].global&&(h+=T(a.j[H].A)+" "+H+";\n");
h+=Ub(a,"compiledfunctions");h+="void main(void) {\n"+g.code+"gl_FragColor = "+b+";\n}\n";console.log(h);t={};if(a.l.compiledfunctions)for(var Q in a.l.compiledfunctions.ja)t[Q]=a.B.getMyfunction(Q).generation;return{code:h,D:a.D,C:a.C,ia:t}};function bc(a,b,c,d){this.Z=b;this.B=d;this.V=c;this.name=a;this.code="uniform sampler2D _sampler"+a+";\nuniform float _ratio"+a+";\nuniform vec2 _cropfact"+a+";\nuniform bool _repeat"+a+";\nuniform bool _mipmap"+a+";\nvec4 _imagergba"+a+" (vec2 A, vec2 B, vec2 p) {\n  p -= A; B -= A;\n  float b = dot(B,B);\n  p = vec2(dot(p,B),_ratio"+a+"*dot(p,vec2(-B.y,B.x)))/b;\n  if(_repeat"+a+") p = mod(p, vec2(1.));\n  if(_repeat"+a+" && _mipmap"+a+") {\n    vec4 color = vec4(0.);\n    float totalWeight = 0.;\n    for(int dx=0; dx<2; dx++) for(int dy=0; dy<2; dy++) {\n      vec2 delta = .5*vec2(dx, dy);\n      vec2 center = delta+vec2(.5);\n      vec2 tc = fract(p-delta)+delta;\n      float dst = dot(abs(tc-center),vec2(1.));\n      float w = max(.5-dst,0.);\n      w=w*w;\n      color += w * texture2D(_sampler"+
a+", tc*_cropfact"+a+");\n      totalWeight += w;\n    }\n    return color/totalWeight;\n  }\n  if(0. <= p.x && p.x <= 1. && 0. <= p.y && p.y <= 1.)\n    return texture2D(_sampler"+a+", p*_cropfact"+a+");\n  else\n    return vec4(0.);\n  }"}function Ua(a,b){var c=a.B.evaluateAndVal(a.Z).value;a="string"===typeof c?a.B.getImage(c,!0):c;return null==a?(console.error("Could not find image "+c+"."),u):Fa(a,b)}
function cc(a,b,c){c.C.hasOwnProperty(a)||(c.C[a]=[]);var d=c.C[a].length,f;for(f in c.C[a])if(d==c.C[a].length){var g=c.C[a][f].V,h=!0,l;for(l in["interpolation","mipmap","repeat"])h&&(ra(g,b)||(h=!1));h&&(d=f)}f=a+"_"+d;d==c.C[a].length&&c.C[a].push(new bc(f,c.D[a].Z,b,c.B));return f}function Tb(a,b,c){return["_imagergba",cc(a[2],b,c),"(",a[0],",",a[1],",",a[3],")"].join("")}function Rb(a,b,c){return["(_imagergba",cc(a[2],b,c),"(",a[0],",",a[1],",",a[3],").rgb)"].join("")}
function Sb(a,b,c){c.add("uniforms","corners",function(){return"uniform vec2 _lowerleft, _lowerright;"});return["_imagergba",cc(a[0],b,c),"(_lowerleft, _lowerright, ",a[1],")"].join("")}function Qb(a,b,c){c.add("uniforms","corners",function(){return"uniform vec2 _lowerleft, _lowerright;"});return["(_imagergba",cc(a[0],b,c),"(_lowerleft, _lowerright, ",a[1],").rgb)"].join("")};function dc(a){var b;b=b?b:null;return"list"!==a.ctype?(console.log("argument is not a list"),b):a.value}function Wa(a){var b;b=b?b:[.5,.5,.5];if("number"===a.ctype){var c=ec(a);if(!isNaN(c))return[c,c,c]}a=dc(a);return a?3!=a.length?(console.log("Not an RGB color vector"),b):a.map(function(a){return ec(a)}):b}
function Va(a){var b;b=void 0===b?Number.NaN:b;if("number"!==a.ctype)return console.log("argument is not a number"),b;b=a.value;a=b.real;b=b.imag;0!==b&&console.log("complex number is not real");b=Math.round(a);b!==a&&console.log("number is not an integer");return b}
function ec(a){var b;b=void 0===b?Number.NaN:b;b=void 0===b?Number.NaN:b;"number"!==a.ctype?(console.log("argument is not a number"),a=b):(a=a.value,b=a.real,0!==a.imag&&console.log("complex number is not real"),a=b);return 0>a?0:1<a?1:a};function pa(a){this.l=a}pa.prototype.toString=function(){return this.l};
function Ja(a,b){var c=n;this.l=c.createProgram();this.Y=fc(this,c,c.VERTEX_SHADER,a);fc(this,c,c.FRAGMENT_SHADER,b);a=this.l;c.linkProgram(a);if(!c.getProgramParameter(a,c.LINK_STATUS))throw new pa("Error linking shader:\n"+c.getProgramInfoLog(a));c.validateProgram(a);if(!c.getProgramParameter(a,c.VALIDATE_STATUS))throw new pa("Error validating shader:\n"+c.getProgramInfoLog(a));var d=this.l,f,g,h,l={},q,p,r,t;b=c.getProgramParameter(d,c.ACTIVE_UNIFORMS);for(a=0;a<b;++a)if(f=c.getActiveUniform(d,
a))if(g=f.name.replace(/\]/g,"")){for(q=l;h=/[.\[]/.exec(g);)p=g.substr(0,h.index),q.hasOwnProperty(p)?q=q[p]:"."===h[0]?q=q[p]={}:q=q[p]=[],g=g.substr(h.index+1);if(1<f.size){h=f.size;t=Array(h);for(p=0;p<h;++p)r=f.name+"["+p+"]",r=gc(this,c,r,f),t[p]=r;q[g]=t}else r=gc(this,c,f.name,f),q[g]=r}this.s=l}
function fc(a,b,c,d){c=b.createShader(c);b.shaderSource(c,d);b.compileShader(c);if(!b.getShaderParameter(c,b.COMPILE_STATUS))throw console.warn(d.split("\n")),new pa("Error compiling shader:\n"+b.getShaderInfoLog(c));b.attachShader(a.l,c);return c}
function gc(a,b,c,d){a=b.getUniformLocation(a.l,c);switch(d.type){case b.FLOAT:return b.uniform1fv.bind(b,a);case b.FLOAT_VEC2:return b.uniform2fv.bind(b,a);case b.FLOAT_VEC3:return b.uniform3fv.bind(b,a);case b.FLOAT_VEC4:return b.uniform4fv.bind(b,a);case b.BOOL:case b.INT:case b.SAMPLER_2D:case b.SAMPLER_CUBE:return b.uniform1iv.bind(b,a);case b.BOOL_VEC2:case b.INT_VEC2:return b.uniform2iv.bind(b,a);case b.BOOL_VEC3:case b.INT_VEC3:return b.uniform3iv.bind(b,a);case b.BOOL_VEC4:case b.INT_VEC4:return b.uniform4iv.bind(b,
a);case b.FLOAT_MAT2:return b.uniformMatrix2fv.bind(b,a,!1);case b.FLOAT_MAT3:return b.uniformMatrix3fv.bind(b,a,!1);case b.FLOAT_MAT4:return b.uniformMatrix4fv.bind(b,a,!1);default:throw new pa("Unknown data type for uniform "+c);}};
}).call(this);//# sourceMappingURL=CindyGL.js.map


