(function(){
'use strict';var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},d="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;
function ba(a,b){if(b){var c=d;a=a.split(".");for(var e=0;e<a.length-1;e++){var f=a[e];f in c||(c[f]={});c=c[f]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}
ba("String.prototype.repeat",function(a){return a?a:function(a){var c;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");c=this+"";if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var e="";a;)if(a&1&&(e+=c),a>>>=1)c+=c;return e}});function ca(){ca=function(){};d.Symbol||(d.Symbol=da)}var ea=0;function da(a){return"jscomp_symbol_"+(a||"")+ea++}
function fa(){ca();var a=d.Symbol.iterator;a||(a=d.Symbol.iterator=d.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ga(this)}});fa=function(){}}function ga(a){var b=0;return ha(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ha(a){fa();a={next:a};a[d.Symbol.iterator]=function(){return this};return a}
ba("Array.from",function(a){return a?a:function(a,c,e){fa();c=c?c:function(a){return a};var f=[],g=a[Symbol.iterator];if("function"==typeof g)for(a=g.call(a);!(g=a.next()).done;)f.push(c.call(e,g.value));else for(var g=a.length,k=0;k<g;k++)f.push(c.call(e,a[k]));return f}});
function ia(a,b){fa();a instanceof String&&(a+="");var c=0,e={next:function(){if(c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e}ba("Array.prototype.keys",function(a){return a?a:function(){return ia(this,function(a){return a})}});
ba("Array.prototype.fill",function(a){return a?a:function(a,c,e){var f=this.length||0;0>c&&(c=Math.max(0,f+c));if(null==e||e>f)e=f;e=Number(e);0>e&&(e=Math.max(0,f+e));for(c=Number(c||0);c<e;c++)this[c]=a;return this}});
var ja={addc:"vec2 addc(vec2 a,vec2 b){\nreturn a+b;\n}\n",arccosc:"vec2 arccosc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=addc(multc(logc(tmp1),vec2(0.0,1.0)),vec2(pi*0.5,0.0));\nreturn erg;\n}\n",arcsinc:"vec2 arcsinc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=multc(logc(tmp1),vec2(0.0,-1.0));\nreturn erg;\n}\n",arctan2c:"\n\n\n\nvec2 arctan2c(vec2 x,vec2 y){\nvec2 r=logc(divc(x+vec2(-y.y,y.x),sqrtc(multc(x,x)+multc(y,y))));\nreturn vec2(r.y, -r.x);\n}\n",
arctan2cvec2:"vec2 arctan2cvec2(cvec2 v){\nreturn arctan2c(v.real,v.imag);\n}\n",arctan2vec2:"float arctan2vec2(vec2 v){\nreturn atan(v.y,v.x);\n}\n",arctanc:"vec2 arctanc(vec2 a){\nvec2 t1=logc(addc(multc(a,vec2(0.0,-1.0)),vec2(1.0,0.0)));\nvec2 t2=logc(addc(multc(a,vec2(0.0,1.0)),vec2(1.0,0.0)));\nvec2 erg=multc(subc(t1,t2),vec2(0.0,0.5));\nreturn erg;\n}\n",blue:"vec3 blue(float f)\n{\nreturn vec3(0.,0.,clamp(f,0.,1.));\n}\n",cimag:"float imagc(vec2 a){\nreturn a.y;\n}\n",conjugate:"vec2 conjugate(vec2 a){\nreturn vec2(a.x, -a.y);\n}\n",
copytexture_f:"#ifdef GL_ES\nprecision highp float;\n#endif\n\nuniform sampler2D sampler;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_FragColor=texture2D(sampler,cgl_pixel);\n}\n",copytexture_v:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_Position=vec4(aPos,1.);\ncgl_pixel=aTexCoord;\n}\n",cosc:"vec2 cosc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat i= (imag1+imag2) /2.0;\nfloat r= (real1+real2) /2.0;\n\nreturn vec2(r,i);\n}\n",
creal:"float realc(vec2 a){\nreturn a.x;\n}\n",dehomogenize:"vec2 dehomogenize(vec3 z){\nreturn vec2(z.x,z.y)/z.z;\n}\n",divc:"vec2 divc(vec2 a,vec2 b){\nreturn vec2(dot(a,b),dot(a,vec2(-b.y,b.x)))/dot(b,b);\n}\n",expc:"vec2 expc(vec2 a){\nfloat n=exp(a.x);\nfloat r=n*cos(a.y);\nfloat i=n*sin(a.y);\nreturn vec2(r,i);\n}\n",float2color:"vec4 float2color(float f)\n{\nreturn vec4(f,f,f,1.);\n}\n",gray:"vec3 gray(float f)\n{\nf=clamp(f,0.,1.);\nreturn vec3(f,f,f);\n}\n",green:"vec3 green(float f)\n{\nreturn vec3(0.,clamp(f,0.,1.),0.);\n}\n",
hsv2rgb:"vec3 hsv2rgb(vec3 c)\n{\nvec4 K=vec4(1.0,2.0/3.0,1.0/3.0,3.0);\nvec3 p=abs(fract(c.xxx+K.xyz) *6.0-K.www);\nreturn c.z*mix(K.xxx,clamp(p-K.xxx,0.0,1.0),c.y);\n}\n",hue:"vec3 hue(float a){\nreturn hsv2rgb(vec3(a,1.,1.));\n}\n",imagc:"float imagc(vec2 a){\nreturn a.y;\n}\n",invc:"vec2 invc(vec2 a){\nfloat n=a.x*a.x+a.y*a.y;\nreturn vec2(a.x/n,-a.y/n);\n}\n",logc:"vec2 logc(vec2 a){\nfloat re=a.x;\nfloat im=a.y;\nfloat s=sqrt(re*re+im*im);\nfloat i=im;\nfloat imag=atan(im,re);\nif(i<0.0){\nimag+= (2.0*pi);\n}\nif(i==0.0&&re<0.0){\nimag=pi;\n}\nif(imag>pi){\nimag-= (2.0*pi);\n};\nfloat real=log(s);\n\nreturn vec2(real,imag);\n}\n",
logr:"vec2 logr(float a){\nif(a>=0.)return vec2(log(a),0);\nelse return vec2(log(-a),pi);\n}\n",mat2complex:"mat4 mat2complex(mat2 a)\n{\nreturn mat4(\nvec4(a[0][0],0,a[0][1],0),\nvec4(0,a[0][0],0,a[0][1]),\nvec4(a[1][0],0,a[1][1],0),\nvec4(0,a[1][0],0,a[1][1])\n);\n}\n",multc:"vec2 multc(vec2 a,vec2 b){\nreturn vec2(dot(a,vec2(b.x,-b.y)),dot(a,b.yx));\n}\n",negc:"vec2 negc(vec2 a){\nreturn vec2(-a.x,-a.y);\n}\n",powc:"vec2 powc(vec2 a,vec2 b){\nreturn expc(multc(logc(a),b));\n}\n",powi:"float powi(float a,int b){\nif(mod(float(b),2.) < .5)\nreturn pow(abs(a),float(b));\nelse\nreturn sign(a)*pow(abs(a),float(b));\n}\n",
random:"uniform float rnd_;\n\nfloat last_rnd= .1231;\nfloat random(){\nfloat a=mod(rnd_*plain_pixel.x*32.23,1.21);\nfloat b=mod(last_rnd*plain_pixel.y*54.21,1.32);\nlast_rnd=mod(a+b+12232.2213*(1.+rnd_)*dot(plain_pixel,plain_pixel)+a+sin(b)+b*sin(dot(plain_pixel,vec2(232.121+rnd_,2232.11))+last_rnd*121.11)*129.12+rnd_,1.);\nreturn last_rnd;\n\n\n}\n",realc:"float realc(vec2 a){\nreturn a.x;\n}\n",red:"vec3 red(float f)\n{\nreturn vec3(clamp(f,0.,1.),0.,0.);\n}\n",rgb2hsv:"vec3 rgb2hsv(vec3 c)\n{\nvec4 K=vec4(0.0, -1.0/3.0,2.0/3.0, -1.0);\nvec4 p=mix(vec4(c.bg,K.wz),vec4(c.gb,K.xy),step(c.b,c.g));\nvec4 q=mix(vec4(p.xyw,c.r),vec4(c.r,p.yzx),step(p.x,c.r));\n\nfloat d=q.x-min(q.w,q.y);\nfloat e=1.0e-10;\nreturn vec3(abs(q.z+ (q.w-q.y) / (6.0*d+e)),d/ (q.x+e),q.x);\n}\n",
sinc:"\n\nvec2 sinc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat r= -(imag1-imag2) /2.0;\nfloat i= (real1-real2) /2.0;\n\nreturn vec2(r,i);\n}\n",sqrtc:"vec2 sqrtc(vec2 a){\nreturn expc(multc(logc(a),vec2(0.5,0.0)));\n}\n",sqrtf:"vec2 sqrtf(float a){\nif(a>=0.)return vec2(sqrt(a),0.);\nelse return vec2(0.,sqrt(-a));\n}\n",standardFragmentHeader:"#ifdef GL_ES\nprecision highp float;\n#endif\n\n#define pi 3.141592653589793\n\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\n",
subc:"vec2 subc(vec2 a,vec2 b){\nreturn a-b;\n}\n",tanc:"vec2 tanc(vec2 a){\nvec2 s=sinc(a);\nvec2 c=cosc(a);\nreturn divc(s,c);\n}\n",vec2complex:"vec4 vec2complex(vec2 a)\n{\nreturn vec4(a.x,0.,a.y,0);\n}\n",vshader:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\nuniform mat3 transformMatrix;\nvoid main(void){\ngl_Position=vec4(aPos,1.);\nplain_pixel=aTexCoord;\nvec3 r=transformMatrix*vec3(plain_pixel,1);\ncgl_pixel=r.xy/r.z;\n}\n"};var ka=!1,h,m,q,u,v=!1,ma,w=!1,na=1;
function oa(){function a(c){h.removeEventListener("webglcontextcreationerror",a,!1);c.statusMessage&&(b=c.statusMessage)}if(!ka){h=document.createElement("canvas");h.id="glcanvas";h.style.display="none";h.width=h.height=0;document.body.appendChild(h);m=document.createElement("canvas");m.id="tmpcanvas";m.style.display="none";m.width=m.height=0;document.body.appendChild(m);var b="Unknown";h.addEventListener("webglcontextcreationerror",a,!1);(q=h.getContext("webgl"))||(q=h.getContext("experimental-webgl"));
if(!q)throw new pa("Could not obtain a WebGL context.\nReason: "+b);h.removeEventListener("webglcontextcreationerror",a,!1);w=q.getExtension("OES_texture_float")&&q.getExtension("OES_texture_float_linear");w||(console.error("Your browser does not suppert OES_texture_float, trying OES_texture_half_float..."),(v=(ma=q.getExtension("OES_texture_half_float"))&&q.getExtension("OES_texture_half_float_linear"))||console.error("Your browser does not suppert OES_texture_half_float, will use 8-bit textures."));
navigator.userAgent.match(/(iPad|iPhone)/i)&&(console.log("You are  using an iPhone/iPad."),w=v=!1,q.getExtension("OES_texture_half_float")&&q.getExtension("OES_texture_half_float_linear")&&q.getExtension("EXT_color_buffer_half_float")?v=!0:console.error("Your browser does not suppert writing to half_float textures, we will use 8-bit textures."));ka=!0}};function qa(a){var b;if(null==a||"object"!=typeof a)return a;if(a instanceof Array){b=[];for(var c=0,e=a.length;c<e;c++)b[c]=qa(a[c]);return b}if(a instanceof Object){b={};for(c in a)a.hasOwnProperty(c)&&(0<="oper impl args ctype stack name arglist value real imag key obj body".split(" ").indexOf(c)&&(b[c]=qa(a[c])),a.modifs&&(b.modifs=a.modifs));return b}}
function ra(a,b){if(null==a||"object"!=typeof a)return a===b;if(a instanceof Array&&b instanceof Array){if(a.length!=b.length)return!1;for(var c=0,e=a.length;c<e;c++)if(!ra(a[c],b[c]))return!1;return!0}if(a instanceof Object&&b instanceof Object){c="oper impl args ctype stack name modifs arglist value real imag key obj body".split(" ");for(e=0;e<c.length;e++){var f=c[e];if(!ra(a[f],b[f]))return!1}return!0}return!1}function sa(a){return-1===a.indexOf("$")?a:a.substr(0,a.indexOf("$"))}
function x(a){if("boolean"===a.ctype)return y.F;if("number"===a.ctype)return a=a.value,1E-10>Math.abs(a.imag)?(a.real|0)===a.real?y.s:y.f:y.h;if("list"===a.ctype){var b=a.value;if(0<b.length){for(var c=x(b[0]),e=1;e<b.length;e++)c=z(c,x(b[e]));if(c)return{type:"list",length:b.length,i:c}}}else if("string"===a.ctype||"image"===a.ctype)return y.image;console.error("Cannot guess type of the following type:");console.log(a);return!1}var ta=0;function B(){ta++;return"_h"+ta}
function ua(a,b){if(a>h.width||b>h.height)h.width=Math.ceil(a),h.height=Math.ceil(b)}function va(a,b,c){a=a.getInitialMatrix();b-=a.tx;c+=a.ty;return{x:(b*a.d-c*a.b)/a.det,y:-(-b*a.c+c*a.a)/a.det}}function wa(a){return va(a,0,a.instance.canvas.clientHeight)}function xa(a){return va(a,a.instance.canvas.clientWidth,a.instance.canvas.clientHeight)}var ya=new Float32Array(1),za=new Int32Array(ya.buffer);
function Aa(a){ya[0]=a;a=za[0];var b=a>>16&32768,c=(a&2147483647)+4096;if(1199570944<=c)return 1199570944<=(a&2147483647)?2139095040>c?b|31744:b|31744|(a&8388607)>>13:b|31743;if(947912704<=c)return b|c-939524096>>13;if(855638016>c)return b;c=(a&2147483647)>>23;return b|(a&8388607|8388608)+(8388608>>>c-102)>>126-c}
function Ba(a){if(w)return new Float32Array(a);if(v){for(var b=new Uint16Array(a.length),c=0;c<a.length;c++)b[c]=Aa(a[c]);return b}b=new Uint8Array(a.length);for(c=0;c<a.length;c++)b[c]=255*a[c];return b}function Ca(a){return w?new Float32Array(a):v?new Uint16Array(a):new Uint8Array(a)}function Da(){return w?q.FLOAT:v?ma.HALF_FLOAT_OES:q.UNSIGNED_BYTE}
function Ea(a){for(var b=[],c=0;c<a.length;c++)if(w)b.push(a[c]);else if(v){var e=a[c],f=(e&31744)>>10,g=e&1023;b.push((e>>15?-1:1)*(f?31===f?g?NaN:Infinity:Math.pow(2,f-15)*(1+g/1024):g/1024*6.103515625E-5))}else b.push(a[c]/255);return b}function Fa(a){for(var b=1;b<a;)b<<=1;return b};function Ga(a,b){a.hasOwnProperty("readcanvaswrappers")||(a.readcanvaswrappers=Array(4));var c=2*b.U+b.$;a.readcanvaswrappers.hasOwnProperty(c)||(a.writecanvaswrapper&&a.writecanvaswrapper.generation>a.generation&&a.writecanvaswrapper.na(),a.readcanvaswrappers[c]=new C(a,b),a.ready||(console.error("Image not ready. Creating onload event."),a.whenReady(function(){a.generation=Math.max(a.generation,a.readcanvaswrappers[c].generation+1)})));a.writecanvaswrapper&&(a.writecanvaswrapper=a.readcanvaswrappers[c]);
return a.readcanvaswrappers[c]}function Ha(a){if(!a.hasOwnProperty("writecanvaswrapper")){var b=-1;if(a.readcanvaswrappers)for(var c=3;0<=c;c--)a.readcanvaswrappers.hasOwnProperty(b)&&(b=c);else a.readcanvaswrappers=Array(4);-1==b&&(c={$:!0,U:!1,repeat:!1},b=2*c.U+c.$,a.readcanvaswrappers[b]=new C(a,c));a.writecanvaswrapper=a.readcanvaswrappers[b]}a.readPixels=a.writecanvaswrapper.readPixels.bind(a.writecanvaswrapper);return a.writecanvaswrapper}
function C(a,b){this.canvas=a;this.S=b;this.K=a.width;this.G=a.height;Ia(this);this.j=0;this.o=[];this.ba=[];this.generation=-1;this.bindTexture();a.drawTo=this.drawTo.bind(this);a.readPixels=this.readPixels.bind(this);a.cdyUpdate=this.na.bind(this);a=Ca(this.W*this.L*4);for(var c=0;2>c;c++)this.o[c]=q.createTexture(),q.bindTexture(q.TEXTURE_2D,this.o[c]),q.pixelStorei(q.UNPACK_ALIGNMENT,1),q.texImage2D(q.TEXTURE_2D,0,q.RGBA,this.W,this.L,0,q.RGBA,Da(),a),b.U?q.texParameteri(q.TEXTURE_2D,q.TEXTURE_MIN_FILTER,
b.$?q.LINEAR_MIPMAP_LINEAR:q.NEAREST_MIPMAP_LINEAR):q.texParameteri(q.TEXTURE_2D,q.TEXTURE_MIN_FILTER,b.$?q.LINEAR:q.NEAREST),q.texParameteri(q.TEXTURE_2D,q.TEXTURE_MAG_FILTER,b.$?q.LINEAR:q.NEAREST),this.ba[c]=q.createFramebuffer(),q.bindFramebuffer(q.FRAMEBUFFER,this.ba[c]),q.framebufferTexture2D(q.FRAMEBUFFER,q.COLOR_ATTACHMENT0,q.TEXTURE_2D,this.o[c],0);this.aa=new Ja(ja.copytexture_v,ja.copytexture_f);b=q.createBuffer();q.bindBuffer(q.ARRAY_BUFFER,b);b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,
1,1,0]);a=q.getAttribLocation(this.aa.j,"aPos");q.enableVertexAttribArray(a);c=q.getAttribLocation(this.aa.j,"aTexCoord");q.enableVertexAttribArray(c);var e=new Float32Array([0,0,1,0,0,1,1,1]),f=b.byteLength;q.bufferData(q.ARRAY_BUFFER,f+e.byteLength,q.STATIC_DRAW);q.bufferSubData(q.ARRAY_BUFFER,0,b);q.bufferSubData(q.ARRAY_BUFFER,f,e);q.vertexAttribPointer(a,3,q.FLOAT,!1,0,0);q.vertexAttribPointer(c,2,q.FLOAT,!1,0,f)}
function Ia(a){a.W=Fa(a.K+a.K/2*(a.S.U&&a.S.repeat));a.L=Fa(a.G+a.G/2*(a.S.U&&a.S.repeat))}C.prototype.bindTexture=function(){q.bindTexture(q.TEXTURE_2D,this.o[this.j])};C.prototype.bindFramebuffer=function(){q.bindFramebuffer(q.FRAMEBUFFER,this.ba[this.j^1]);this.j^=1};
C.prototype.na=function(){var a;this.canvas.img.hasOwnProperty("getContext")?a=this.canvas.img.getContext("2d"):(this.canvas.img=document.createElement("canvas"),this.canvas.img.style.display="none",this.canvas.img.width=this.K,this.canvas.img.height=this.G,a=this.canvas.img.getContext("2d"));a.clearRect(0,0,this.K,this.G);this.drawTo(a,0,0);this.canvas.img.generation++};
function Ka(a){if(a.canvas.live||a.canvas.ready&&!(a.generation>=a.canvas.generation)){if(a.K!=a.canvas.width||a.G!=a.canvas.height){a.K=a.canvas.width;a.G=a.canvas.height;Ia(a);for(var b=Ca(a.W*a.L*4),c=0;2>c;c++)q.bindTexture(q.TEXTURE_2D,a.o[c]),q.texImage2D(q.TEXTURE_2D,0,q.RGBA,a.W,a.L,0,q.RGBA,Da(),b)}a.bindTexture();q.pixelStorei(q.UNPACK_FLIP_Y_WEBGL,1);a.S.repeat?(m.width=a.W,m.height=a.L,b=m.getContext("2d"),b.drawImage(a.canvas.img,0,a.L-a.G),b.drawImage(a.canvas.img,a.K,a.L-a.G),b.drawImage(a.canvas.img,
0,a.L-2*a.G),b.drawImage(a.canvas.img,a.K,a.L-2*a.G),q.texSubImage2D(q.TEXTURE_2D,0,0,0,q.RGBA,Da(),m)):q.texSubImage2D(q.TEXTURE_2D,0,0,0,q.RGBA,Da(),a.canvas.img);a.S.U&&q.generateMipmap(q.TEXTURE_2D);q.pixelStorei(q.UNPACK_FLIP_Y_WEBGL,0);a.generation=a.canvas.generation;console.log("Image has been loaded to GPU")}}
C.prototype.drawTo=function(a,b,c){ua(this.K,this.G);q.viewport(0,0,this.W,this.L);q.useProgram(this.aa.j);q.activeTexture(q.TEXTURE0);q.bindTexture(q.TEXTURE_2D,this.o[this.j]);this.aa.o.sampler([0]);q.bindFramebuffer(q.FRAMEBUFFER,null);q.drawArrays(q.TRIANGLE_STRIP,0,4);q.flush();a.drawImage(h,0,h.height-this.G,this.K,this.G,b,c,this.K,this.G)};
C.prototype.readPixels=function(a,b,c,e){q.bindFramebuffer(q.FRAMEBUFFER,this.ba[this.j]);q.framebufferTexture2D(q.FRAMEBUFFER,q.COLOR_ATTACHMENT0,q.TEXTURE_2D,this.o[this.j],0);var f=Ca(c*e*4);q.readPixels(a,this.G-b-e,c,e,q.RGBA,Da(),f);a=[];for(--e;0<=e;e--)a=a.concat(Ea(f.slice(e*c*4,(e+1)*c*4)));return a};function La(a,b){this.B=a;this.S=b;Ma(this)}
function Ma(a){var b=Na(new Oa(a.B),a.S);a.o=b.D;a.C=b.C;a.ia=b.ia;a.aa=ja.standardFragmentHeader+b.code;a.ba=ja.vshader;a.j=new Ja(a.ba,a.aa);b=q.createBuffer();q.bindBuffer(q.ARRAY_BUFFER,b);var b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,1,0]),c=q.getAttribLocation(a.j.j,"aPos");q.enableVertexAttribArray(c);a=q.getAttribLocation(a.j.j,"aTexCoord");q.enableVertexAttribArray(a);var e=new Float32Array([0,0,1,0,0,1,1,1]),f=b.byteLength;q.bufferData(q.ARRAY_BUFFER,f+e.byteLength,q.STATIC_DRAW);q.bufferSubData(q.ARRAY_BUFFER,
0,b);q.bufferSubData(q.ARRAY_BUFFER,f,e);q.vertexAttribPointer(c,3,q.FLOAT,!1,0,0);q.vertexAttribPointer(a,2,q.FLOAT,!1,0,f)}
function Pa(a){function b(a,c,e){if(a)if("function"===typeof a)switch(c){case y.h:a([e.value.real,e.value.imag]);break;case y.F:e.value?a([1]):a([0]);break;case y.s:case y.f:a([e.value.real]);break;default:if("list"===c.type&&c.i===y.f)a(e.value.map(function(a){return a.value.real}));else if("list"===c.type&&"list"===c.i.type&&c.i.i===y.f){for(var f=[],n=0;n<c.length;n++)for(var r=0;r<c.i.length;r++)f.push(e.value[n].value[r].value.real);a(f)}else console.error("Don't know how to set uniform of type "+
D(c)+", to "+e)}else if("list"===c.type)if(n=Qa(c),1===E(c)&&n===y.f){c=Ra(c.length);var t=0;for(f in c)b(a["a"+f],y.ca(c[f]),{ctype:"list",value:F(c[f]).map(function(a){return e.value[t+a]})}),t+=c[f]}else for(f=0;f<c.length;f++)b(a["a"+f],c.i,{ctype:"list",value:e.value[f].value});else console.error("Don't know how to set uniform of type "+D(c)+", to"),console.log(e)}for(var c in a.o){var e=a.B.evaluateAndVal(a.o[c].Z),f=a.o[c].type;if(!G(H(e),f)){console.log("Type of "+c+" changed ("+D(H(e))+" is no subtype of  "+
D(f)+"); forcing rebuild.");Ma(a);q.useProgram(a.j.j);Pa(a);return}a.j.o[c]&&b(a.j.o[c],f,e)}[["rnd_",function(){return[Math.random()]}],["_lowerleft",function(){var b=wa(a.B);return[b.x,b.y]}],["_lowerright",function(){var b=xa(a.B);return[b.x,b.y]}]].map(function(b){return a.j.o[b[0]]&&a.j.o[b[0]](b[1]())})}
function Sa(a){var b=0,c;for(c in a.C)for(var e in a.C[c]){q.activeTexture(q.TEXTURE0+b);var f=a.C[c][e],g=f.name,k={$:f.V.hasOwnProperty("interpolate")?f.B.evaluateAndVal(f.V.interpolate).value:!0,U:f.V.hasOwnProperty("mipmap")?f.B.evaluateAndVal(f.V.mipmap).value:!1,repeat:f.V.hasOwnProperty("repeat")?f.B.evaluateAndVal(f.V.repeat).value:!1},f=Ta(f,k);Ka(f);f.bindTexture();[["_sampler"+g,[b]],["_ratio"+g,[f.K/f.G]],["_cropfact"+g,[f.K/f.W,f.G/f.L]],["_repeat"+g,[k.repeat]],["_mipmap"+g,[k.U]]].map(function(b){return a.j.o[b[0]]&&
a.j.o[b[0]](b[1])});b++}};CindyJS.registerPlugin(1,"CindyGL",function(a){function b(b,e,f,g,k,l){if(!b.pa||b.oa<na)b.pa=!0,b.oa=na,b.ra=new La(a,b);b=b.ra;var p;a:{for(p in b.ia)if(b.B.getMyfunction(p).generation>b.ia[p]){console.log(p+" is outdated; forcing rebuild.");p=!1;break a}p=!0}p||Ma(b);var n=k/g;p=e.x+-(f.y-e.y)*n;n=e.y+(f.x-e.x)*n;ua(g,k);l?q.viewport(0,0,g,k):q.viewport(0,h.height-k,g,k);q.useProgram(b.j.j);Pa(b);e=[f.x-e.x,p-e.x,e.x,f.y-e.y,n-e.y,e.y,0,0,1];b.j.o.hasOwnProperty("transformMatrix")&&b.j.o.transformMatrix([e[0],
e[3],e[6],e[1],e[4],e[7],e[2],e[5],e[8]]);Sa(b);l?(l.bindFramebuffer(),l.generation=++l.canvas.generation):q.bindFramebuffer(q.FRAMEBUFFER,null);q.drawArrays(q.TRIANGLE_STRIP,0,4);q.flush();l&&(l.generation=Math.max(l.generation,l.canvas.generation+1))}u=a.nada;a.defineFunction("compile",1,function(b){b=Na(new Oa(a),b[0]);console.log(b);return{ctype:"string",value:b}});a.defineFunction("forcerecompile",0,function(){na++;return u});a.defineFunction("colorplot",1,function(c){oa();var e=a.instance.canvas.clientWidth,
f=a.instance.canvas.clientHeight,g=a.instance.canvas.width,k=a.instance.canvas.height;b(c[0],wa(a),xa(a),g,k,null);a.instance.canvas.getContext("2d").drawImage(h,0,0,g,k,0,0,e,f);return u});a.defineFunction("colorplot",3,function(c){oa();var e=c[0],f=a.extractPoint(a.evaluateAndVal(c[1])),g=a.extractPoint(a.evaluateAndVal(c[2])),k={x:Math.min(f.x,g.x),y:Math.min(f.y,g.y)},l={x:Math.max(f.x,g.x),y:Math.min(f.y,g.y)};c=a.instance.canvas.clientWidth;var p=a.instance.canvas.clientHeight,n=a.instance.canvas.width,
r=a.instance.canvas.height,t=va(a,0,0),A=wa(a),J=xa(a),J=Math.abs((f.x-g.x)/(A.x-J.x)),t=Math.abs((f.y-g.y)/(t.y-A.y));b(e,k,l,n*J,r*t,null);e=a.instance.canvas.getContext("2d");k=Math.min(f.x,g.x);f=Math.max(f.y,g.y);g=a.getInitialMatrix();e.drawImage(h,0,0,n*J,r*t,k*g.a-f*g.b+g.tx,k*g.c-f*g.d-g.ty,J*c,t*p);return u});a.defineFunction("colorplot",4,function(c){oa();var e=a.extractPoint(a.evaluateAndVal(c[0])),f=a.extractPoint(a.evaluateAndVal(c[1])),g=a.evaluateAndVal(c[2]);c=c[3];if(!e.ok||!f.ok||
"string"!==g.ctype)return u;var g=a.getImage(g.value,!0),k=Ha(g);b(c,e,f,g.width,g.height,k);return u});a.defineFunction("colorplot",2,function(c){oa();var e=wa(a),f=xa(a),g=a.evaluateAndVal(c[0]);c=c[1];if("string"!==g.ctype)return u;var g=a.getImage(g.value,!0),k=Ha(g);b(c,e,f,g.width,g.height,k);return u});a.defineFunction("setpixel",4,function(b){var e;var f=a.evaluateAndVal(b[0]),g;g=void 0===g?null:g;"string"===f.ctype?e=f.value:(console.log("argument is not a string"),e=g);f=Ua(a.evaluateAndVal(b[1]));
g=Ua(a.evaluateAndVal(b[2]));b=Va(a.evaluateAndVal(b[3]));if(!e)return u;var k=a.getImage(e,!0),k=Ha(k);isFinite(f)&&isFinite(g)&&e&&k&&b&&(k.bindTexture(),e=[b[0],b[1],b[2],1],q.texSubImage2D(q.TEXTURE_2D,0,f,g,1,1,q.RGBA,Da(),Ba(e)),b=k.canvas.img.getContext("2d"),k=b.createImageData(1,1),k.data.d=e,b.putImageData(k,f,g));return u})});function I(a,b){return{type:"list",length:a,i:b}}function H(a){return{type:"constant",value:a}}function Wa(a){return H({ctype:"number",value:{real:a,imag:0}})}var y={F:1,s:2,f:3,h:4,X:5,color:6,M:7,T:8,J:9,image:10,N:I(2,3),O:I(3,3),da:I(4,3),ca:function(a){return I(a,3)},ga:function(a){return I(a,4)},ta:I(2,I(2,3)),ua:I(3,I(3,3)),va:I(4,I(4,3)),la:18};Object.freeze(y);
function D(a){return 1<=a&&10>=a?"bool int float complex voidt color point line coordinate2d image".split(" ")[a-1]:"list"===a.type?D(a.i)+"["+a.length+"]":"constant"===a.type?"const["+JSON.stringify(a.value.value)+"]":JSON.stringify(a)}function K(a){return"list"===a.type&&K(a.i)||G(a,y.f)}function L(a){return"list"===a.type&&L(a.i)||G(a,y.h)}function Xa(a){return"constant"===a.type&&G(a,y.s)}function M(a){return"constant"===a.type?x(a.value):a}function E(a){return"list"===a.type?E(a.i)+1:0}
function Qa(a){return void 0!==a.i?Qa(a.i):a}function Ya(a,b){return E(a)===E(b)&&(0===E(a)||a.length===b.length&&Ya(a.i,b.i))}function N(a){return G(a,y.f)?y.f:G(a,y.h)?y.h:{type:"list",length:a.length,i:N(a.i)}}function Za(a){return G(a,y.h)?y.h:{type:"list",length:a.length,i:Za(a.i)}}function P(a){return a===y.F||a===y.s||a===y.f||a===y.h||"list"===a.type&&a.i===y.f&&1<=a.length&&4>=a.length||"list"===a.type&&"list"===a.i.type&&a.i.i===y.f&&a.length===a.i.length&&2<=a.length&&4>=a.length}
function $a(a){return-1!==[y.F,y.s,y.f,y.h].indexOf(a)}function ab(a,b){return a===b||"constant"===a.type&&"constant"===b.type&&ra(a.value,b.value)||"list"===a.type&&"list"===b.type&&a.length===b.length&&ab(a.i,b.i)}
function G(a,b){return ab(a,b)||a===y.la?!0:a?$a(a)&&$a(b)?a<=b:"constant"===b.type?!1:"constant"===a.type?G(x(a.value),b):b===y.J?G(a,y.h)||G(a,y.N)||G(a,y.M):b===y.M||b===y.T?G(a,y.O):b===y.color?G(a,y.f)||"list"===a.type&&(3===a.length||4===a.length)&&G(a.i,y.f):"list"===a.type&&"list"===b.type&&a.length===b.length?G(a.i,b.i):!1:!1}
function z(a,b){if(!a)return b;if(!b||ab(a,b))return a;"constant"===a.type&&(a=x(a.value));"constant"===b.type&&(b=x(b.value));return $a(a)&&$a(b)?Math.max(a,b):"list"===a.type&&"list"===b.type&&a.length===b.length&&(b=z(a.i,b.i))?{type:"list",length:a.length,i:b}:!1}function Q(a){return function(b){var c={},e;for(e in a){var f=a[e];c.fa=f[0];if(b.length==c.fa.length&&b.every(function(a){return function(b,c){return G(b,a.fa[c])}}(c)))return{v:c.fa,w:f[1],u:f[2]};c={fa:c.fa}}return!1}}
function bb(a){switch(a){case y.s:return Q([[[y.F],y.s,R("int")]]);case y.f:return Q([[[y.F],y.f,R("float")],[[y.s],y.f,R("float")]]);case y.h:return Q([[[y.f],y.h,function(a){return"vec2("+a+", 0.)"}]]);case y.color:return Q([[[y.f],y.color,S("float2color")],[[y.O],y.color,function(a){return"vec4("+a+",1.0)"}],[[y.da],y.color,T]]);case y.M:return Q([[[y.N],y.M,function(a){return"vec3("+a+",1.0)"}],[[y.O],y.M,T]]);case y.T:return Q([[[y.N],y.T,function(a){return"vec3("+a+",1.0)"}],[[y.O],y.T,T]]);
case y.J:return Q([[[y.h],y.J,T],[[y.N],y.J,T],[[y.M],y.J,S("dehomogenize")]]);default:if("list"===a.type)return function(b){var c=b[0],e=bb(a.i)([c.i]).u;return{v:b,w:a,u:function(b,g,k){return cb(a)(F(a.length).map(function(a){return e([db(c,a)([b],g,k)],g,k)}),g,k)}}}}console.log("no inclusionfunction ->"+D(a)+" implemented yet; using identity...");return function(b){return{v:b,w:a,u:T}}}
function U(a){switch(a){case y.F:return"bool";case y.s:return"int";case y.f:return"float";case y.h:case y.J:return"vec2";case y.X:return"void";case y.color:return"vec4";case y.M:case y.T:return"vec3"}if("list"===a.type&&a.i===y.f)return 1==a.length?"float":"vec"+a.length;if("list"===a.type&&a.i===y.h)return"cvec"+a.length;if("list"===a.type&&"list"===a.i.type&&a.length===a.i.length&&a.i.i===y.f)switch(a.length){case 2:return"mat2";case 3:return"mat3";case 4:return"mat4"}if("list"===a.type)return"l"+
a.length+"_"+U(a.i);console.error("No WebGL implementation for type "+D(a)+" found")}function eb(a,b){switch(b){case y.F:return U(b)+"("+a.value+")";case y.s:return""+(a.value.real|0);case y.f:return U(b)+"("+a.value.real+")";case y.h:return U(b)+"("+a.value.real+", "+a.value.imag+")";case y.color:return a=a.value.real,"vec4("+a+","+a+","+a+",1.)";default:console.error("Dont know how to paste values of Type "+D(b)+" yet.")}};var V={};function fb(a,b,c){if(!c.mark("includedfunctions",a)){for(var e in V[a])fb(V[a][e],b,c);c.add("includedfunctions",a,function(){return ja[a]})}}function S(a){return function(b,c,e){fb(a,c,e);return R(a)(b)}};function F(a){return Array.from(Array(a).keys())}function Ra(a){return 4>=a?[a]:5==a?[2,3]:Ra(a-4).concat([4])}function gb(a){var b=Qa(a),c=E(a);return 1==c&&b===y.f?Ra(a.length).map(function(a,b){return{type:y.ca(a),name:"a"+b}}):1<=c?F(a.length).map(function(b){return{type:a.i,name:"a"+b}}):[]}function hb(a,b){if(!P(a)){var c=U(a);b.add("structs",c,function(){return"struct "+c+" { "+gb(a).map(function(a){return hb(a.type,b)||U(a.type)+" "+a.name+";"}).join("")+"};"})}}
function ib(a,b,c){if(!P(a)){var e=a.length,f=a.i.length;c.add("functions","mult"+e+"_"+f,function(){return U(y.ca(e))+" mult"+e+"_"+f+"("+U(a)+" a, "+U(y.ca(f))+" b){return "+jb(e)(F(e).map(function(a){return kb(f)(["a.a"+a,"b"],b,c)}),b,c)+";}"})}}
function lb(a,b,c){if(!P(a)){var e=a.length,f="sum"+U(a);c.add("functions",f,function(){return U(a.i)+" "+f+"("+U(a)+" a){"+(U(a.i)+" res = "+mb(a.i,0)([],b,c)+";\n      "+F(e).map(function(e){return"res = "+nb(a.i)(["res",db(a,e)(["a",e],b,c)],b,c)+";"}).join("\n")+"\n        return res;\n    }")})}}
function ob(a,b,c){var e=a.length,f=a.i.length;c.add("functions","multc"+e+"_"+f,function(){return U(y.ga(e))+" multc"+e+"_"+f+"("+U(a)+" a, "+U(y.ga(f))+" b){\n        return cvec"+e+"("+F(e).map(function(a){return pb(f)(["a.a"+a,"b"],b,c)})+");\n    }\n    "})}function qb(a,b){2<=a&&4>=a||b.add("functions","dot"+a,function(){return"float dot"+a+"(vec"+a+" a, vec"+a+" b) {\n    return "+Ra(a).map(function(a,b){return"dot(a.a"+b+",b.a"+b+")"}).join("+")+"; }\n    "})}
function rb(a,b){b.add("functions","cdot"+a,function(){return"vec2 cdot"+a+"(cvec"+a+" a, cvec"+a+" b) {\n      return "+F(a).map(function(a){return"vec2(dot(a.a"+a+",vec2(b.a"+a+".x,-b.a"+a+".y)), dot(a.a"+a+",b.a"+a+".yx))"}).join("+\n")+";\n    }\n    "})}
function sb(a,b,c){var e="add"+U(a);c.add("functions",e,function(){return U(a)+" "+e+"("+U(a)+" a, "+U(a)+" b) {\n    return "+U(a)+"("+gb(a).map(function(a){return U(a.type)+"("+nb(a.type)(["a."+a.name,"b."+a.name],b,c)+")"}).join(",")+");\n      }"})}
function tb(a,b,c){var e="sub"+U(a);c.add("functions",e,function(){return U(a)+" "+e+"("+U(a)+" a, "+U(a)+" b) {\n    return "+U(a)+"("+gb(a).map(function(a){return U(a.type)+"("+ub(a.type)(["a."+a.name,"b."+a.name],b,c)+")"}).join(",")+");\n    }"})}function vb(a,b,c){var e="scalarmult"+U(a);c.add("functions",e,function(){return U(a)+" "+e+"(float a, "+U(a)+" b) {\n    return "+U(a)+"("+gb(a).map(function(a){return U(a.type)+"("+wb(a.type)(["a","b."+a.name],b,c)+")"}).join(",")+");\n    }"})}
function xb(a,b,c){fb("multc",b,c);var e="cscalarmult"+U(a);c.add("functions",e,function(){return U(a)+" "+e+"(vec2 a, "+U(a)+" b) {\n    return "+U(a)+"("+gb(a).map(function(a){return""+yb(a.type)(["a","b."+a.name],b,c)}).join(",")+");\n    }"})}
function zb(a){if(a===y.h)return S("multc");if(P(a))return function(a){return W("*")([a[1],a[0]])};var b=Qa(a);if(G(b,y.f))return function(b,e,f){return ib(a,e,f)||"mult"+a.length+"_"+a.i.length+"("+b.join(",")+")"};if(b===y.h)return function(b,e,f){return ob(a,e,f)||"multc"+a.length+"_"+a.i.length+"("+b.join(",")+")"}}function kb(a){return function(b,c,e){return qb(a,e)||"dot"+(2<=a&&4>=a?"":a)+"("+b.join(",")+")"}}
function pb(a){return function(b,c,e){return rb(a,e)||"cdot"+a+"("+b.join(",")+")"}}function nb(a){return P(a)?W("+"):function(b,c,e){return sb(a,c,e)||"add"+U(a)+"("+b.join(",")+")"}}function ub(a){return P(a)?W("-"):function(b,c,e){return tb(a,c,e)||"sub"+U(a)+"("+b.join(",")+")"}}function Ab(a){return K(a)&&1==E(a)?function(b,c,e){return kb(a.length)([b[0],jb(a.length)(Array(a.length).fill("1."),c,e)],c,e)}:function(b,c,e){return lb(a,c,e)||"sum"+U(a)+"("+b.join(",")+")"}}
function jb(a){if(2<=a&&4>=a)return function(b){return"vec"+a+"("+b.join(",")+")"};if(1==a)return function(a){return"float("+a.join(",")+")"};var b=0;return function(c,e,f){return hb(y.ca(a),f)||"vec"+a+"("+Ra(a).map(function(a){return"vec"+a+"("+F(a).map(function(){return++b&&c[b-1]}).join(",")+")"}).join(",")+")"}}function cb(a){return P(a)?function(b){return U(a)+"("+b.join(",")+")"}:1==E(a)&&K(a)?jb(a.length):function(b,c,e){return hb(a,e)||U(a)+"("+b.join(",")+")"}}
function db(a,b){var c=Qa(a);return 1==E(a)&&c===y.f?Bb(a.length,b):P(a)?function(a){return"("+a[0]+")["+b+"]"}:function(a){return"("+a[0]+").a"+b}}function mb(a,b){return P(a)?function(){return U(a)+"(float("+b+"))"}:function(c,e,f){return cb(a)+"("+gb(a).map(function(a){return mb(a.type,b)(c,e,f)}).join(",")+")"}}
function Bb(a,b){return function(c){if(1==a)return c[0];if(2<=a&&4>=a)return"("+c[0]+")["+b+"]";var e;a:{e=b;var f=Ra(a),g;for(g in f)if(f[g]<=e)e-=f[g];else{e={first:g,second:e};break a}console.error("Accessing index out of range");e=void 0}return"("+c[0]+").a"+e.first+"["+e.second+"]"}}function wb(a){return P(a)?W("*"):function(b,c,e){return vb(a,c,e)||"scalarmult"+U(a)+"("+b.join(",")+")"}}
function yb(a){return a===y.h?S("multc"):function(b,c,e){return xb(a,c,e)||"cscalarmult"+U(a)+"("+b.join(",")+")"}};function R(a){return function(b){return sa(a)+"("+b+")"}}function W(a){return function(b){return"("+b.join(a)+")"}}function T(a){return a}var X={};X.join=Q([[y.M,y.M],y.T,R("cross")]);X.meet=Q([[y.T,y.T],y.M,R("cross")]);
X["if"]=function(a){if(!a.every(function(a){return a}))return!1;if(2===a.length)return{v:a,w:a[1],u:function(a){return"if("+a[0]+") {"+a[1]+";}"}};if(3===a.length){var b=z(a[1],a[2]);return b?{v:[y.F,b,b],w:b,u:function(a){return"("+a[0]+" ? "+a[1]+" : "+a[2]+")"}}:{v:a,w:y.X,u:function(a){return"if("+a[0]+") {"+a[1]+";} else {"+a[2]+";}"}}}return!1};X["="]=function(a){a=z(a[0],a[1]);return{v:a,w:a,u:function(a){return a[0]+" = "+a[1]+";"}}};
X[";"]=function(a){return{v:a,w:a[1]!==y.X?a[1]:a[0],u:function(a){return a[0]+" ; "+a[1]+";"}}};X.repeat=function(a){return 2!=a.length&&3!=a.length||!Xa(a[0])?!1:{v:a,w:a[a.length-1],u:function(){return""}}};X.forall=function(a){return 2!=a.length&&3!=a.length||"list"!==M(a[0]).type?!1:{v:a,w:a[a.length-1],u:function(){return""}}};X.apply=function(a){return 2!=a.length&&3!=a.length||"list"!==M(a[0]).type?!1:{v:a,w:I(M(a[0]).length,a[a.length-1]),u:function(){return""}}};
X.sum=function(a){return 1==a.length&&(K(a[0])||L(a[0]))?{v:a,w:a[0].i,u:Ab(a[0])}:!1};X.regional=function(a){return{v:a,w:y.X,u:function(){return""}}};X.sqrt=Q([[[y.f],y.h,S("sqrtf")],[[y.h],y.h,S("sqrtc")]]);X.abs=Q([[[y.f],y.f,R("abs")],[[y.h],y.f,R("length")],[[y.N],y.f,R("length")],[[y.O],y.f,R("length")],[[y.da],y.f,R("length")]]);X.abs_infix=X.abs;
X.dist=Q([[[y.f,y.f],y.f,function(a){return R("abs")(W("-")(a))}],[[y.h,y.h],y.f,function(a){return R("length")(W("-")(a))}],[[y.N,y.N],y.f,function(a){return R("length")(W("-")(a))}],[[y.O,y.O],y.f,function(a){return R("length")(W("-")(a))}],[[y.da,y.da],y.f,function(a){return R("length")(W("-")(a))}]]);X.dist_infix=X.dist;X.sin=Q([[[y.f],y.f,R("sin")],[[y.h],y.h,S("sinc")]]);X.cos=Q([[[y.f],y.f,R("cos")],[[y.h],y.h,S("cosc")]]);X.tan=Q([[[y.f],y.f,R("tan")],[[y.h],y.h,S("tanc")]]);
X.exp=Q([[[y.f],y.f,R("exp")],[[y.h],y.h,S("expc")]]);X.arctan=Q([[[y.f],y.f,R("atan")],[[y.h],y.h,S("arctanc")]]);X.log=Q([[[y.f],y.h,S("logr")],[[y.h],y.h,S("logc")]]);var Cb=[2,3,4].map(function(a){return I(a,y.f)}).concat([2,3,4].map(function(a){return I(a,I(a,y.f))})),Db=[y.s,y.f,y.h].concat(Cb);X.add=function(a){var b=Q(Db.map(function(a){return[[a,a],a,W("+")]}))(a);if(b)return b;b=a[0];a=a[1];if([b,a].every(function(a){return K(a)||L(a)})&&Ya(b,a))return a=z(N(b),N(a)),{v:[a,a],w:a,u:nb(a)}};
X.sub=function(a){var b=Q(Db.map(function(a){return[[a,a],a,W("-")]}).concat(Db.map(function(a){return[[y.X,a],a,W("-")]})))(a);if(b)return b;b=a[0];a=a[1];if([b,a].every(function(a){return K(a)||L(a)})&&Ya(b,a))return a=z(N(b),N(a)),{v:[a,a],w:a,u:ub(a)}};X["+"]=X.add;X["-"]=X.sub;
X._=function(a){var b=M(a[0]);if("list"===b.type&&Xa(a[1])){var c=Number(a[1].value.value.real);return 1<=Math.abs(c)&&Math.abs(c)<=b.length?(0<c&&--c,0>c&&(c=b.length-c),{v:a,w:b.i,u:db(b,c)}):{v:a,w:b.i,u:function(){return console.error("try to access "+c+"-th Element of "+b.length+"-list "+JSON.stringify(a[0]))}}}return!1};
X.mult=function(a){var b=Q([[[y.s,y.s],y.s,W("*")],[[y.f,y.f],y.f,W("*")],[[y.h,y.h],y.h,S("multc")]])(a);if(b)return b;if(2!==a.length)return!1;var b=a[0],c=a[1];if([b,c].every(function(a){return"list"===a.type&&G(a.i,y.f)})&&b.length===c.length)return a=N(b),P(a)?{v:[a,a],w:y.f,u:R("dot")}:{v:[a,a],w:y.f,u:kb(b.length)};if([b,c].every(function(a){return"list"===a.type&&G(a.i,y.h)})&&b.length===c.length)return a=Za(b),{v:[a,a],w:y.h,u:pb(b.length)};if(K(b)&&2===E(b)&&K(c)&&1===E(c)&&b.i.length===
c.length)return{v:[N(b),N(c)],w:y.ca(b.length),u:zb(N(b))};if(L(b)&&2===E(b)&&L(c)&&1===E(c)&&b.i.length===c.length)return{v:[Za(b),Za(c)],w:y.ga(b.length),u:zb(Za(b))};for(b={H:0};2>b.H;b={Y:b.Y,H:b.H,ea:b.ea},b.H++){if(G(a[0^b.H],y.f)&&(K(a[1^b.H])||L(a[1^b.H])))return b.Y=N(a[1^b.H]),{v:b.H?[b.Y,y.f]:[y.f,b.Y],w:b.Y,u:function(a){return function(b,c,k){return wb(a.Y)([b[0^a.H],b[1^a.H]],c,k)}}(b)};if(G(a[0^b.H],y.h)&&L(a[1^b.H]))return b.ea=Za(a[1^b.H]),{v:b.H?[b.ea,y.h]:[y.h,b.ea],w:b.ea,u:function(a){return function(b,
c,k){return yb(a.ea)([b[0^a.H],b[1^a.H]],c,k)}}(b)}}};X["*"]=X.mult;X.div=function(a){var b=Q([[[y.f,y.f],y.f,W("/")],[[y.h,y.h],y.h,S("divc")]])(a);return b?b:G(a[1],y.f)&&L(a[0])&&(a=N(a[0]),P(a))?{v:[a,y.f],w:a,u:W("/")}:!1};X["/"]=X.div;X.re=Q([[[y.h],y.f,S("realc")]]);X.im=Q([[[y.h],y.f,S("imagc")]]);X.floor=Q([[[y.f],y.s,function(a){return"int(floor("+a+"))"}],[[y.h],y.h,R("floor")]]);X.round=Q([[[y.f],y.s,function(a){return"int(floor("+a+"+.5))"}],[[y.h],y.h,function(a){return"floor("+a+"+vec2(.5))"}]]);
X.ceil=Q([[[y.f],y.s,function(a){return"int(ceil("+a+"))"}],[[y.h],y.h,R("ceil")]]);X.mod=Q([[[y.s,y.s],y.s,function(a,b){return"int("+R("mod")("float("+a[0]+"), float("+a[1]+")",b)+")"}],[[y.f,y.f],y.f,R("mod")],[[y.h,y.h],y.h,S("mod")]]);X.random=Q([[[],y.f,S("random")],[[y.f],y.f,function(a,b){return S("random")([],b)+"*"+a[0]}],[[y.h],y.h,function(a,b){return"vec2("+S("random")([],b)+","+S("random")([],b)+")*"+a[0]}]]);
X.arctan2=Q([[[y.f,y.f],y.f,function(a){return"atan("+a[1]+", "+a[0]+")"}],[[y.h,y.h],y.h,S("arctan2c")],[[y.h],y.f,S("arctan2vec2")],[[y.N],y.f,S("arctan2vec2")],[[y.ga(2)],y.h,S("arctan2cvec2")]]);["red","green","blue","gray","hue"].forEach(function(a){X[a]=Q([[[y.f],y.O,S(a)]])});X.grey=X.gray;X.min=Q([[[y.s,y.s],y.s,R("min")],[[y.f,y.f],y.f,R("min")]]);X.max=Q([[[y.s,y.s],y.s,R("max")],[[y.f,y.f],y.f,R("max")]]);X.complex=Q([[[y.N],y.h,T]]);X.pow=Q([[[y.f,y.s],y.f,S("powi")],[[y.h,y.h],y.h,S("powc")]]);
X["^"]=X.pow;X.re=Q([[[y.h],y.f,function(a){return"("+a+").x"}]]);X.conjugate=Q([[[y.h],y.h,S("conjugate")]]);X.im=Q([[[y.h],y.f,function(a){return"("+a+").y"}]]);X.genList=function(a){var b=a.length;if(0<b){var c=!1,e;for(e in a)c=z(c,a[e]);if(c)return a=I(b,c),{v:Array(b).fill(c),w:a,u:cb(a)}}return!1};X["&"]=Q([[[y.F,y.F],y.F,W("&&")]]);X["%"]=Q([[[y.F,y.F],y.F,W("||")]]);"> < >= <= == !=".split(" ").forEach(function(a){X[a]=Q([[[y.s,y.s],y.F,W(a)],[[y.f,y.f],y.F,W(a)]])});
X.imagergb=Q([[[y.image,y.J],y.O,Eb],[[y.J,y.J,y.image,y.J],y.O,Fb]]);X.imagergba=Q([[[y.image,y.J],y.da,Gb],[[y.J,y.J,y.image,y.J],y.da,Hb]]);Object.freeze(X);V.powc=["expc","multc","logc"];V.sqrtc=["expc","multc","logc"];V.arccosc=["multc","negc","sqrtc","addc","logc"];V.arcsinc=["multc","negc","sqrtc","addc","logc"];V.tanc=["sinc","cosc","divc"];V.arctanc=["logc","addc","multc","subc"];V.arctan2c=["logc","divc","sqrtc","multc"];V.arctan2vec2c=["arctan2c"];V.hue=["hsv2rgb"];Object.freeze(V);function Oa(a){this.l={};this.D={};this.j={};this.P=0;this.o={};this.B=a;this.C={}}Oa.prototype.add=function(a,b,c){this.mark(a,b);this.j[a].ka[b]||(this.j[a].ka[b]=c(),this.j[a].ja[b]=!0,this.j[a].order.push(b))};Oa.prototype.mark=function(a,b){this.j[a]||(this.j[a]={order:[],ja:{},ka:{}});var c=this.j[a].ja[b]||!1;this.j[a].ja[b]=!0;return c};function Ib(a,b){return a.j[b]?a.j[b].order.map(function(c){return a.j[b].ka[c]}).join("\n"):"\n"}
function Jb(a,b,c,e){if(ab(c,e)||c===y.la)return b;if(G(c,e)){if("constant"===c.type)return eb(c.value,e);var f=bb(e)([c]);if(!f)return console.error("cannot find an implementation for "+D(c)+" -> "+D(e)+", using identity"),b;e=f.u;return e(Jb(a,b,c,f.v[0]),{},a)}console.error(D(c)+" is no subtype of "+D(e)+" (trying to cast the term "+b+")");return b}function Kb(a,b,c){a.l[b]||(a.l[b]={});a.l[b].R||(a.l[b].R=[]);a.l[b].A||(a.l[b].A=!1);a.hasOwnProperty("global")||(a.l[b].global=c)}
function Lb(a,b){var c=b.I;if(b.isuniform)return a.D[b.uvariable].type;if("variable"===b.ctype)return b=b.name,b=c[b]||b,a.l[b].A;if("function"===b.ctype&&a.o.hasOwnProperty(b.oper))return a.l[c[b.oper]].A;if("number"===b.ctype)return H(b);if("void"===b.ctype)return y.X;if("field"===b.ctype){a=M(Y(a,b.obj));if("list"===a.type)return a.i;if(!a)return!1}else{if("string"===b.ctype)return y.image;if("function"===b.ctype||"infix"===b.ctype){for(var c=Array(b.args.length),e=!0,f=0;f<b.args.length;f++)c[f]=
Y(a,b.args[f]),e&="constant"===c[f].type;if(e&&b.impl)return b={ctype:b.ctype,oper:b.oper,impl:b.impl,args:c.map(function(a){return a.value})},a=a.B.evaluateAndVal(b),H(a);a=sa(b.oper);b=X[a]?X[a](c):!1;if(!b&&c.every(function(a){return Qa(a)}))throw console.error("Could not find an implementation for "+a+" with args ("+c.map(D).join(", ")+")"),"error";return b?b.w:!1}}console.error("Don't know how to compute type of");console.log(b);return!1}
function Y(a,b){if(!b.ma||!b.P||a.P>b.P)b.ma=Lb(a,b),b.P=a.P;return b.ma}
function Mb(a,b){function c(a,b,c){var e={},g;for(g in a)e[g]=a[g];a=B();Kb(k,a,!1);f[a].A=c;f[a].qa=!0;e[b]=a;return e}function e(a,b,n,r){a.I=b;for(var t in a.args){var A=r||"repeat$2"===a.oper&&0==t||"repeat$3"===a.oper&&0==t||"_"===a.oper&&1==t,J=1<=t&&"repeat$2"===a.oper?c(b,"#",y.s):1<=t&&"repeat$3"===a.oper?c(b,a.args[1].name,y.s):1<=t&&("forall$2"===a.oper||"apply$2"===a.oper)?c(b,"#",!1):1<=t&&("forall$3"===a.oper||"apply$3"===a.oper)?c(b,a.args[1].name,!1):b;e(a.args[t],J,n,A)}"field"===
a.ctype&&e(a.obj,b,n,r);"variable"===a.ctype&&(t=a.name,t=b[t]||t,r&&k.l[t]&&(k.l[t].ha=!0));if("="===a.oper)r=a.args[0].name,r=b[r]||r,Kb(k,r,!0),f[r].R.push(a.args[1]);else if(a.oper&&"regional"===sa(a.oper)&&"global"!=n)for(var O in a.args){r=a.args[O].name;var la=B();b[r]=la;g[n].l||(g[n].l=[]);g[n].l.push(la);Kb(k,la,!1)}else if("forall$2"===a.oper||"apply$2"===a.oper||"forall$3"===a.oper||"apply$3"===a.oper)f[2===a.args.length?a.args[1].I["#"]:a.args[2].I[a.args[1].name]].R.push({ctype:"infix",
oper:"_",args:[a.args[0],{ctype:"number",value:{real:1,imag:0}}],I:a.args[0].I});else if("function"===a.ctype&&g.hasOwnProperty(a.oper)){n=a.oper;O=n.replace("$","_");Kb(k,O,!1);b[n]=O;b={};for(la in g[n].arglist)t=g[n].arglist[la].name,A=O+"_"+t,b[t]=A,Kb(k,A,!1),f[A].R.push(a.args[la]);g[n].sa||(g[n].sa=!0,e(g[n].body,b,n,r),f[O].R.push(g[n].body))}}var f=a.l,g=a.o,k=a;e(b,{"#":"cgl_pixel"},"global",!1)}
function Nb(a,b){function c(a){if(a.hasOwnProperty("dependsOnPixel"))return a.dependsOnPixel;if("variable"===a.ctype){var b=a.name,b=a.I[b]||b;return k[b]?a.dependsOnPixel=!0:a.dependsOnPixel=!1}b=["random","verbatimglsl"];if("function"===a.ctype&&-1!=b.indexOf(sa(a.oper)))return a.dependsOnPixel=!0;if("repeat$2"===a.oper||"forall$2"===a.oper||"apply$2"===a.oper)return c(a.args[1])?(k[a.args[1].I["#"]]=!0,a.dependsOnPixel=!0):a.dependsOnPixel=!1;if("repeat$3"===a.oper||"forall$3"===a.oper||"apply$3"===
a.oper)return c(a.args[2])?(k[a.args[2].I[a.args[1].name]]=!0,a.args[1].dependsOnPixel=!0,a.dependsOnPixel=!0):a.dependsOnPixel=!1;for(var e in a.args)if(c(a.args[e]))return a.dependsOnPixel=!0;return"function"===a.ctype&&g.hasOwnProperty(a.oper)&&c(g[a.oper].body)?a.dependsOnPixel=!0:"field"===a.ctype?a.dependsOnPixel=c(a.obj):a.dependsOnPixel=!1}function e(a,b){if(c(a)){for(var f in a.args)e(a.args[f],b||"repeat$2"===a.oper&&0==f||"repeat$3"===a.oper&&0==f||"_"===a.oper&&1==f);"field"===a.ctype&&
e(a.obj,b);"function"===a.ctype&&g.hasOwnProperty(a.oper)&&(a=a.oper,p.hasOwnProperty(a)||(p[a]=!0,e(g[a].body,b)))}else if("number"!==a.ctype&&"void"!==a.ctype){".."===a.oper&&(b=!0);f=!1;var k,l;for(l in n)!f&&ra(a,n[l].Z)&&(f=!0,k=l);f||(k=B(),n[k]={Z:a,type:!1,ha:b});a.isuniform=!0;a.uvariable=k}}var f=a.l,g=a.o,k={cgl_pixel:!0},l;for(l in f)if(1<=f[l].R.length||f[l].qa)k[l]=!0;c(b);var p={"":!0},n=a.D;e(b,!1)}
function Ob(a,b){if("function"===b.ctype&&!a.o.hasOwnProperty(b.oper)&&null!==a.B.getMyfunction(b.oper)){var c=b.oper;a.o[c]=qa(a.B.getMyfunction(c));Ob(a,a.o[c].body)}for(var e in b.args)Ob(a,b.args[e])}
function Z(a,b,c){var e=Y(a,b);if(b.isuniform)return b=b.uvariable,c?{code:"",m:"constant"===e.type?eb(e.value,M(e)):b}:{code:""};if(";"===b.oper){for(var e={m:""},f="",g=b.args.length-1,k=g;0<=k;k--)"void"===b.args[k].ctype&&(g=k-1);for(k=0;k<=g;k++)e=Z(a,b.args[k],c&&k===g),f+=e.code;return c?{code:f,m:e.m}:{code:f}}if("constant"===e.type)return c?{m:eb(e.value,M(e)),code:""}:{code:""};if("="===b.oper)return e=Z(a,b.args[1],!0),b=Z(a,b.args[0],!0).m+" = "+Jb(a,e.m,Y(a,b.args[1]),Y(a,b.args[0])),
c?{code:e.code,m:b}:{code:e.code+b+";\n"};if("repeat$2"===b.oper||"repeat$3"===b.oper){f=Z(a,b.args[0],!0);if("constant"!==Y(a,b.args[0]).type)return console.error("repeat possible only for fixed constant number in GLSL"),!1;e="repeat$2"===b.oper?b.args[1].I["#"]:b.args[2].I[b.args[1].name];f=Number(f.m);g="";if("constant"===a.l[e].A.type)for(k=1;k<=f;k++){a.l[e].A=Wa(k);a.P++;var l=Z(a,b.args["repeat$2"===b.oper?1:2],k===f&&c),g=g+l.code;if(k===f&&c)return{code:g,m:l.m}}else if(k="",l=Z(a,b.args["repeat$2"===
b.oper?1:2],c),b=Y(a,b.args["repeat$2"===b.oper?1:2]),c&&(k=B(),g+=U(b)+" "+k+";"),g=g+("for(int "+e+"=1; "+e+" <= "+f+"; "+e+"++) {\n")+l.code,c&&(g+=k+" = "+l.m+";\n"),g+="}\n",c)return{code:g,m:k};return{code:g}}if("forall$2"===b.oper||"forall$3"===b.oper||"apply$2"===b.oper||"apply$3"===b.oper){var p=Y(a,b.args[0]);if("list"!==p.type&&("constant"!==p.type||"list"!==p.value.ctype))return console.error(b.oper+" only possible for lists"),!1;var f=p.length||p.value.value.length,k=2===b.args.length?
b.args[1].I["#"]:b.args[2].I[b.args[1].name],n=a.l[k].A,r=l="";c&&(r=B(),l+=U(e)+" "+r+";\n");"list"===e.type&&hb(e,a);if("constant"===a.l[k].A.type||"constant"===p.type)for(p=a.B.evaluateAndVal(b.args[0]),n=0;n<f;n++)a.l[k].A=H(p.value[n]),a.P++,g=Z(a,b.args[2===b.args.length?1:2],c),l+=g.code,"forall$2"===b.oper||"forall$3"===b.oper?n+1===f&&c&&(l+=r+" = "+g.m+";\n"):c&&(l+=db(e,n)([r],[],a)+" = "+g.m+";\n");else{var g=Z(a,b.args[2===b.args.length?1:2],c),t=Z(a,b.args[0],!0),l=l+t.code,A=t.m;!a.l[A]&&
!a.D[A]&&2<=p.length&&(A=B(),l+=U(p)+" "+A+" = "+t.m+";\n");l+=U(n)+" "+k+";\n";for(t=0;t<f;t++)l+=k+" = "+db(p,t)([A],[],a)+";\n",l+=g.code,c&&("forall$2"===b.oper||"forall$3"===b.oper?t===f-1&&(l+=r+" = "+g.m+";\n"):l+=db(e,t)([r],[],a)+" = "+g.m+";\n");"list"===n.type&&hb(n,a)}return c?{code:l,m:r}:{code:l}}if("if$2"===b.oper||"if$3"===b.oper)return k=Z(a,b.args[0],!0),l=Z(a,b.args[1],c),g=f="",c&&(g=B(),f+=U(e)+" "+g+";"),f+=k.code,f+="if("+k.m+") {\n",f+=l.code,c&&(f+=g+" = "+Jb(a,l.m,Y(a,b.args[1]),
e)+";\n"),"if$3"===b.oper&&(k=Z(a,b.args[2],c),f=f+"} else {\n"+k.code,c&&(f+=g+" = "+Jb(a,k.m,Y(a,b.args[2]),e)+";\n")),f+="}\n",c?{code:f,m:g}:{code:f};if("function"===b.ctype||"infix"===b.ctype){l=b.oper;if("verbatimglsl"===sa(l))return b=a.B.evaluateAndVal(b.args[0]).value,c?{m:b,code:""}:{code:b};e=b.args.map(function(b){return Z(a,b,!0)});f=b.args.map(function(b){return Y(a,b)});if(a.o.hasOwnProperty(l))for(k=Pb(a,l),g=Array(e.length),r=0;r<e.length;r++)g[r]=a.l[a.o[l].body.I[a.o[l].arglist[r].name]].A;
else{l=sa(l);if("regional"===l)return c?{m:"",code:""}:{code:""};k=X[l](f);if(!k)return console.error("Could not find an implementation for "+l+"("+f.map(D).join(", ")+").\nReturning empty code"),c?{m:"",code:""}:{code:""};g=k.v;k=k.u}l="";r=Array(e.length);for(p=0;p<e.length;p++)l+=e[p].code,r[p]=Jb(a,e[p].m,f[p],g[p]);b=k(r,b.modifs,a);return c?{m:b,code:l}:{code:l+b+";\n"}}if("variable"===b.ctype)return e=b.name,e=b.I[e]||e,c?{m:e,code:""}:{code:e+";\n"};if("void"===b.ctype)return c?{m:"",code:""}:
{code:""};if("field"===b.ctype&&(e={x:0,y:1,z:2,r:0,g:1,b:2,a:3}[b.key],void 0!=e))return b=db(Y(a,b.obj),e)([Z(a,b.obj,!0).m],null,a),c?{m:b,code:""}:{code:b+";\n"};console.error("dont know how to this.compile "+JSON.stringify(b))}function Pb(a,b){Qb(a,b,a.o[b].arglist.length);return R(b.replace("$","_"))}
function Qb(a,b,c){if(!a.mark("compiledfunctions",b)){for(var e=a.o[b],f=b.replace("$","_"),g=e.body.I,k=Array(c),l=0;l<c;l++)k[l]=e.arglist[l].name;c=a.l[f].A===y.X;var p=U(a.l[f].A)+" "+f+"("+k.map(function(b){return U(a.l[g[b]].A)+" "+g[b]}).join(", ")+"){\n",n;for(n in e.l)k=e.l[n],p+=U(a.l[k].A)+" "+k+";\n";n=Z(a,e.body,!c);e=Y(a,e.body);p+=n.code;c||(p+="return "+Jb(a,n.m,e,a.l[f].A)+";\n");p+="}\n";a.add("compiledfunctions",b,function(){return p})}}
function Na(a,b){ta=0;b=qa(b);Kb(a,"cgl_pixel",!1);a.l.cgl_pixel.A=y.N;var c=b;Ob(a,c);Mb(a,c);Nb(a,c);for(var e in a.D)c=a.B.evaluateAndVal(a.D[e].Z),a.D[e].type=a.D[e].ha?H(c):x(c);e=!0;for(var f in a.l)a.l[f].A=a.l[f].A||!1,a.l[f].ha&&(a.l[f].A=Wa(1),a.P++);for(;e;){e=!1;for(var g in a.l)if(!a.l[g].ha)for(var k in a.l[g].R){f=M(Y(a,a.l[g].R[k]));var l=c=a.l[g].A||!1;f&&(c?G(f,c)?l=c:l=z(c,f):l=f,l&&l!==c&&(a.l[g].A=l,a.P++,e=!0))}}for(var p in a.D)"list"===a.D[p].type.type&&hb(a.D[p].type,a);for(var n in a.l)"list"===
a.l[n].A.type&&hb(a.l[n].A,a);g=Z(a,b,!0);k=Y(a,b);b=Jb(a,g.m,k,y.color);G(k,y.color)||console.error("expression does not generate a color");k=Ib(a,"structs");k+=Ib(a,"uniforms");p=[];for(var r in a.D)"constant"!=a.D[r].type.type&&a.D[r].type!=y.image&&p.push("uniform "+U(a.D[r].type)+" "+r+";");k+=p.join("\n");r="";for(var t in a.C)for(var A in a.C[t])r+=a.C[t][A].code+"\n";k=k+r+Ib(a,"includedfunctions");k+=Ib(a,"functions");for(var J in a.l)a.l[J].global&&(k+=U(a.l[J].A)+" "+J+";\n");k+=Ib(a,"compiledfunctions");
k+="void main(void) {\n"+g.code+"gl_FragColor = "+b+";\n}\n";console.log(k);t={};if(a.j.compiledfunctions)for(var O in a.j.compiledfunctions.ja)t[O]=a.B.getMyfunction(O).generation;return{code:k,D:a.D,C:a.C,ia:t}};function Rb(a,b,c,e){this.Z=b;this.B=e;this.V=c;this.name=a;this.code="uniform sampler2D _sampler"+a+";\nuniform float _ratio"+a+";\nuniform vec2 _cropfact"+a+";\nuniform bool _repeat"+a+";\nuniform bool _mipmap"+a+";\nvec4 _imagergba"+a+" (vec2 A, vec2 B, vec2 p) {\n  p -= A; B -= A;\n  float b = dot(B,B);\n  p = vec2(dot(p,B),_ratio"+a+"*dot(p,vec2(-B.y,B.x)))/b;\n  if(_repeat"+a+") p = mod(p, vec2(1.));\n  if(_repeat"+a+" && _mipmap"+a+") {\n    vec4 color = vec4(0.);\n    float totalWeight = 0.;\n    for(int dx=0; dx<2; dx++) for(int dy=0; dy<2; dy++) {\n      vec2 delta = .5*vec2(dx, dy);\n      vec2 center = delta+vec2(.5);\n      vec2 tc = fract(p-delta)+delta;\n      float dst = dot(abs(tc-center),vec2(1.));\n      float w = max(.5-dst,0.);\n      w=w*w;\n      color += w * texture2D(_sampler"+
a+", tc*_cropfact"+a+");\n      totalWeight += w;\n    }\n    return color/totalWeight;\n  }\n  if(0. <= p.x && p.x <= 1. && 0. <= p.y && p.y <= 1.)\n    return texture2D(_sampler"+a+", p*_cropfact"+a+");\n  else\n    return vec4(0.);\n  }"}function Ta(a,b){var c=a.B.evaluateAndVal(a.Z).value;a="string"===typeof c?a.B.getImage(c,!0):c;return null==a?(console.error("Could not find image "+c+"."),u):Ga(a,b)}
function Sb(a,b,c){c.C.hasOwnProperty(a)||(c.C[a]=[]);var e=c.C[a].length,f;for(f in c.C[a])if(e==c.C[a].length){var g=c.C[a][f].V,k=!0,l;for(l in["interpolation","mipmap","repeat"])k&&(ra(g,b)||(k=!1));k&&(e=f)}f=a+"_"+e;e==c.C[a].length&&c.C[a].push(new Rb(f,c.D[a].Z,b,c.B));return f}function Hb(a,b,c){return["_imagergba",Sb(a[2],b,c),"(",a[0],",",a[1],",",a[3],")"].join("")}function Fb(a,b,c){return["(_imagergba",Sb(a[2],b,c),"(",a[0],",",a[1],",",a[3],").rgb)"].join("")}
function Gb(a,b,c){c.add("uniforms","corners",function(){return"uniform vec2 _lowerleft, _lowerright;"});return["_imagergba",Sb(a[0],b,c),"(_lowerleft, _lowerright, ",a[1],")"].join("")}function Eb(a,b,c){c.add("uniforms","corners",function(){return"uniform vec2 _lowerleft, _lowerright;"});return["(_imagergba",Sb(a[0],b,c),"(_lowerleft, _lowerright, ",a[1],").rgb)"].join("")};function Tb(a){var b;b=b?b:null;return"list"!==a.ctype?(console.log("argument is not a list"),b):a.value}function Va(a){var b;b=b?b:[.5,.5,.5];if("number"===a.ctype){var c=Ub(a);if(!isNaN(c))return[c,c,c]}a=Tb(a);return a?3!=a.length?(console.log("Not an RGB color vector"),b):a.map(function(a){return Ub(a)}):b}
function Ua(a){var b;b=void 0===b?Number.NaN:b;if("number"!==a.ctype)return console.log("argument is not a number"),b;b=a.value;a=b.real;b=b.imag;0!==b&&console.log("complex number is not real");b=Math.round(a);b!==a&&console.log("number is not an integer");return b}
function Ub(a){var b;b=void 0===b?Number.NaN:b;b=void 0===b?Number.NaN:b;"number"!==a.ctype?(console.log("argument is not a number"),a=b):(a=a.value,b=a.real,0!==a.imag&&console.log("complex number is not real"),a=b);return 0>a?0:1<a?1:a};function pa(a){this.j=a}pa.prototype.toString=function(){return this.j};
function Ja(a,b){var c=q;this.j=c.createProgram();this.Y=Vb(this,c,c.VERTEX_SHADER,a);Vb(this,c,c.FRAGMENT_SHADER,b);a=this.j;c.linkProgram(a);if(!c.getProgramParameter(a,c.LINK_STATUS))throw new pa("Error linking shader:\n"+c.getProgramInfoLog(a));c.validateProgram(a);if(!c.getProgramParameter(a,c.VALIDATE_STATUS))throw new pa("Error validating shader:\n"+c.getProgramInfoLog(a));var e=this.j,f,g,k,l={},p,n,r,t;b=c.getProgramParameter(e,c.ACTIVE_UNIFORMS);for(a=0;a<b;++a)if(f=c.getActiveUniform(e,
a))if(g=f.name.replace(/\]/g,"")){for(p=l;k=/[.\[]/.exec(g);)n=g.substr(0,k.index),p.hasOwnProperty(n)?p=p[n]:"."===k[0]?p=p[n]={}:p=p[n]=[],g=g.substr(k.index+1);if(1<f.size){k=f.size;t=Array(k);for(n=0;n<k;++n)r=f.name+"["+n+"]",r=Wb(this,c,r,f),t[n]=r;p[g]=t}else r=Wb(this,c,f.name,f),p[g]=r}this.o=l}
function Vb(a,b,c,e){c=b.createShader(c);b.shaderSource(c,e);b.compileShader(c);if(!b.getShaderParameter(c,b.COMPILE_STATUS))throw console.warn(e.split("\n")),new pa("Error compiling shader:\n"+b.getShaderInfoLog(c));b.attachShader(a.j,c);return c}
function Wb(a,b,c,e){a=b.getUniformLocation(a.j,c);switch(e.type){case b.FLOAT:return b.uniform1fv.bind(b,a);case b.FLOAT_VEC2:return b.uniform2fv.bind(b,a);case b.FLOAT_VEC3:return b.uniform3fv.bind(b,a);case b.FLOAT_VEC4:return b.uniform4fv.bind(b,a);case b.BOOL:case b.INT:case b.SAMPLER_2D:case b.SAMPLER_CUBE:return b.uniform1iv.bind(b,a);case b.BOOL_VEC2:case b.INT_VEC2:return b.uniform2iv.bind(b,a);case b.BOOL_VEC3:case b.INT_VEC3:return b.uniform3iv.bind(b,a);case b.BOOL_VEC4:case b.INT_VEC4:return b.uniform4iv.bind(b,
a);case b.FLOAT_MAT2:return b.uniformMatrix2fv.bind(b,a,!1);case b.FLOAT_MAT3:return b.uniformMatrix3fv.bind(b,a,!1);case b.FLOAT_MAT4:return b.uniformMatrix4fv.bind(b,a,!1);default:throw new pa("Unknown data type for uniform "+c);}};
}).call(this);//# sourceMappingURL=CindyGL.js.map


