(function(){
'use strict';var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},d="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;
function ba(a,b){if(b){var c=d;a=a.split(".");for(var e=0;e<a.length-1;e++){var f=a[e];f in c||(c[f]={});c=c[f]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}
ba("String.prototype.repeat",function(a){return a?a:function(a){var c;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");c=this+"";if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var e="";a;)if(a&1&&(e+=c),a>>>=1)c+=c;return e}});function ca(){ca=function(){};d.Symbol||(d.Symbol=da)}var ea=0;function da(a){return"jscomp_symbol_"+(a||"")+ea++}
function fa(){ca();var a=d.Symbol.iterator;a||(a=d.Symbol.iterator=d.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ga(this)}});fa=function(){}}function ga(a){var b=0;return ha(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ha(a){fa();a={next:a};a[d.Symbol.iterator]=function(){return this};return a}
ba("Array.from",function(a){return a?a:function(a,c,e){fa();c=c?c:function(a){return a};var f=[],g=a[Symbol.iterator];if("function"==typeof g)for(a=g.call(a);!(g=a.next()).done;)f.push(c.call(e,g.value));else for(var g=a.length,k=0;k<g;k++)f.push(c.call(e,a[k]));return f}});
function ia(a,b){fa();a instanceof String&&(a+="");var c=0,e={next:function(){if(c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e}ba("Array.prototype.keys",function(a){return a?a:function(){return ia(this,function(a){return a})}});
ba("Array.prototype.fill",function(a){return a?a:function(a,c,e){var f=this.length||0;0>c&&(c=Math.max(0,f+c));if(null==e||e>f)e=f;e=Number(e);0>e&&(e=Math.max(0,f+e));for(c=Number(c||0);c<e;c++)this[c]=a;return this}});
var ja={addc:"vec2 addc(vec2 a,vec2 b){\nreturn a+b;\n}\n",arccosc:"vec2 arccosc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=addc(multc(logc(tmp1),vec2(0.0,1.0)),vec2(pi*0.5,0.0));\nreturn erg;\n}\n",arcsinc:"vec2 arcsinc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=multc(logc(tmp1),vec2(0.0,-1.0));\nreturn erg;\n}\n",arctan2c:"\n\n\n\nvec2 arctan2c(vec2 x,vec2 y){\nvec2 r=logc(divc(x+vec2(-y.y,y.x),sqrtc(multc(x,x)+multc(y,y))));\nreturn vec2(r.y, -r.x);\n}\n",
arctan2cvec2:"vec2 arctan2cvec2(cvec2 v){\nreturn arctan2c(v.real,v.imag);\n}\n",arctan2vec2:"float arctan2vec2(vec2 v){\nreturn atan(v.y,v.x);\n}\n",arctanc:"vec2 arctanc(vec2 a){\nvec2 t1=logc(addc(multc(a,vec2(0.0,-1.0)),vec2(1.0,0.0)));\nvec2 t2=logc(addc(multc(a,vec2(0.0,1.0)),vec2(1.0,0.0)));\nvec2 erg=multc(subc(t1,t2),vec2(0.0,0.5));\nreturn erg;\n}\n",blue:"vec3 blue(float f)\n{\nreturn vec3(0.,0.,clamp(f,0.,1.));\n}\n",cimag:"float imagc(vec2 a){\nreturn a.y;\n}\n",conjugate:"vec2 conjugate(vec2 a){\nreturn vec2(a.x, -a.y);\n}\n",
copytexture_f:"#ifdef GL_ES\nprecision highp float;\n#endif\n\nuniform sampler2D sampler;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_FragColor=texture2D(sampler,cgl_pixel);\n}\n",copytexture_v:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_Position=vec4(aPos,1.);\ncgl_pixel=aTexCoord;\n}\n",cosc:"vec2 cosc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat i= (imag1+imag2) /2.0;\nfloat r= (real1+real2) /2.0;\n\nreturn vec2(r,i);\n}\n",
creal:"float realc(vec2 a){\nreturn a.x;\n}\n",dehomogenize:"vec2 dehomogenize(vec3 z){\nreturn vec2(z.x,z.y)/z.z;\n}\n",divc:"vec2 divc(vec2 a,vec2 b){\nreturn 1./(b.x*b.x+b.y*b.y)*multc(a,vec2(b.x,-b.y));\n}\n",expc:"vec2 expc(vec2 a){\nfloat n=exp(a.x);\nfloat r=n*cos(a.y);\nfloat i=n*sin(a.y);\nreturn vec2(r,i);\n}\n",float2color:"vec4 float2color(float f)\n{\nreturn vec4(f,f,f,1.);\n}\n",gray:"vec3 gray(float f)\n{\nf=clamp(f,0.,1.);\nreturn vec3(f,f,f);\n}\n",green:"vec3 green(float f)\n{\nreturn vec3(0.,clamp(f,0.,1.),0.);\n}\n",
hsv2rgb:"vec3 hsv2rgb(vec3 c)\n{\nvec4 K=vec4(1.0,2.0/3.0,1.0/3.0,3.0);\nvec3 p=abs(fract(c.xxx+K.xyz) *6.0-K.www);\nreturn c.z*mix(K.xxx,clamp(p-K.xxx,0.0,1.0),c.y);\n}\n",hue:"vec3 hue(float a){\nreturn hsv2rgb(vec3(a,1.,1.));\n}\n",imagc:"float imagc(vec2 a){\nreturn a.y;\n}\n",invc:"vec2 invc(vec2 a){\nfloat n=a.x*a.x+a.y*a.y;\nreturn vec2(a.x/n,-a.y/n);\n}\n",logc:"vec2 logc(vec2 a){\nfloat re=a.x;\nfloat im=a.y;\nfloat s=sqrt(re*re+im*im);\nfloat i=im;\nfloat imag=atan(im,re);\nif(i<0.0){\nimag+= (2.0*pi);\n}\nif(i==0.0&&re<0.0){\nimag=pi;\n}\nif(imag>pi){\nimag-= (2.0*pi);\n};\nfloat real=log(s);\n\nreturn vec2(real,imag);\n}\n",
logr:"vec2 logr(float a){\nif(a>=0.)return vec2(log(a),0);\nelse return vec2(log(-a),pi);\n}\n",mat2complex:"mat4 mat2complex(mat2 a)\n{\nreturn mat4(\nvec4(a[0][0],0,a[0][1],0),\nvec4(0,a[0][0],0,a[0][1]),\nvec4(a[1][0],0,a[1][1],0),\nvec4(0,a[1][0],0,a[1][1])\n);\n}\n",multc:"vec2 multc(vec2 a,vec2 b){\nreturn vec2(a.x*b.x-a.y*b.y+0.0000000000000001,a.y*b.x+a.x*b.y);\n}\n",negc:"vec2 negc(vec2 a){\nreturn vec2(-a.x,-a.y);\n}\n",powc:"vec2 powc(vec2 a,vec2 b){\nreturn expc(multc(logc(a),b));\n}\n",
powi:"float powi(float a,int b){\nif(mod(float(b),2.) < .5)\nreturn pow(abs(a),float(b));\nelse\nreturn sign(a)*pow(abs(a),float(b));\n}\n",random:"uniform float rnd_;\n\nfloat last_rnd= .1231;\nfloat random(){\nfloat a=mod(rnd_*plain_pixel.x*32.23,1.21);\nfloat b=mod(last_rnd*plain_pixel.y*54.21,1.32);\nlast_rnd=mod(a+b+12232.2213*(1.+rnd_)*dot(plain_pixel,plain_pixel)+a+sin(b)+b*sin(dot(plain_pixel,vec2(232.121+rnd_,2232.11))+last_rnd*121.11)*129.12+rnd_,1.);\nreturn last_rnd;\n\n\n}\n",realc:"float realc(vec2 a){\nreturn a.x;\n}\n",
red:"vec3 red(float f)\n{\nreturn vec3(clamp(f,0.,1.),0.,0.);\n}\n",rgb2hsv:"vec3 rgb2hsv(vec3 c)\n{\nvec4 K=vec4(0.0, -1.0/3.0,2.0/3.0, -1.0);\nvec4 p=mix(vec4(c.bg,K.wz),vec4(c.gb,K.xy),step(c.b,c.g));\nvec4 q=mix(vec4(p.xyw,c.r),vec4(c.r,p.yzx),step(p.x,c.r));\n\nfloat d=q.x-min(q.w,q.y);\nfloat e=1.0e-10;\nreturn vec3(abs(q.z+ (q.w-q.y) / (6.0*d+e)),d/ (q.x+e),q.x);\n}\n",sinc:"\n\nvec2 sinc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat r= -(imag1-imag2) /2.0;\nfloat i= (real1-real2) /2.0;\n\nreturn vec2(r,i);\n}\n",
sqrtc:"vec2 sqrtc(vec2 a){\nreturn expc(multc(logc(a),vec2(0.5,0.0)));\n}\n",sqrtf:"vec2 sqrtf(float a){\nif(a>=0.)return vec2(sqrt(a),0.);\nelse return vec2(0.,sqrt(-a));\n}\n",standardFragmentHeader:"#ifdef GL_ES\nprecision highp float;\n#endif\n\n#define pi 3.141592653589793\n\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\n",subc:"vec2 subc(vec2 a,vec2 b){\nreturn a-b;\n}\n",tanc:"vec2 tanc(vec2 a){\nvec2 s=sinc(a);\nvec2 c=cosc(a);\nreturn divc(s,c);\n}\n",vec2complex:"vec4 vec2complex(vec2 a)\n{\nreturn vec4(a.x,0.,a.y,0);\n}\n",
vshader:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\nuniform mat3 transformMatrix;\nvoid main(void){\ngl_Position=vec4(aPos,1.);\nplain_pixel=aTexCoord;\nvec3 r=transformMatrix*vec3(plain_pixel,1);\ncgl_pixel=r.xy/r.z;\n}\n"};var ka=!1,h,n,p,t,u=!1,la,w=!1,ma=1;
function na(){function a(c){h.removeEventListener("webglcontextcreationerror",a,!1);c.statusMessage&&(b=c.statusMessage)}if(!ka){h=document.createElement("canvas");h.id="glcanvas";h.style.display="none";h.width=h.height=0;document.body.appendChild(h);n=document.createElement("canvas");n.id="tmpcanvas";n.style.display="none";n.width=n.height=0;document.body.appendChild(n);var b="Unknown";h.addEventListener("webglcontextcreationerror",a,!1);(p=h.getContext("webgl"))||(p=h.getContext("experimental-webgl"));
if(!p)throw new oa("Could not obtain a WebGL context.\nReason: "+b);h.removeEventListener("webglcontextcreationerror",a,!1);w=p.getExtension("OES_texture_float")&&p.getExtension("OES_texture_float_linear");w||(console.error("Your browser does not suppert OES_texture_float, trying OES_texture_half_float..."),(u=(la=p.getExtension("OES_texture_half_float"))&&p.getExtension("OES_texture_half_float_linear"))||console.error("Your browser does not suppert OES_texture_half_float, will use 8-bit textures."));
navigator.userAgent.match(/(iPad|iPhone)/i)&&(console.log("You are  using an iPhone/iPad."),w=u=!1,p.getExtension("OES_texture_half_float")&&p.getExtension("OES_texture_half_float_linear")&&p.getExtension("EXT_color_buffer_half_float")?u=!0:console.error("Your browser does not suppert writing to half_float textures, we will use 8-bit textures."));ka=!0}};function pa(a){var b;if(null==a||"object"!=typeof a)return a;if(a instanceof Array){b=[];for(var c=0,e=a.length;c<e;c++)b[c]=pa(a[c]);return b}if(a instanceof Object){b={};for(c in a)a.hasOwnProperty(c)&&(0<="oper impl args ctype stack name arglist value real imag key obj body".split(" ").indexOf(c)&&(b[c]=pa(a[c])),a.modifs&&(b.modifs=a.modifs));return b}}
function qa(a,b){if(null==a||"object"!=typeof a)return a===b;if(a instanceof Array&&b instanceof Array){if(a.length!=b.length)return!1;for(var c=0,e=a.length;c<e;c++)if(!qa(a[c],b[c]))return!1;return!0}if(a instanceof Object&&b instanceof Object){c="oper impl args ctype stack name modifs arglist value real imag key obj body".split(" ");for(e=0;e<c.length;e++){var f=c[e];if(!qa(a[f],b[f]))return!1}return!0}return!1}function ra(a){return-1===a.indexOf("$")?a:a.substr(0,a.indexOf("$"))}
function x(a){if("boolean"===a.ctype)return y.F;if("number"===a.ctype)return a=a.value,1E-10>Math.abs(a.imag)?(a.real|0)===a.real?y.m:y.f:y.g;if("list"===a.ctype){var b=a.value;if(0<b.length){for(var c=x(b[0]),e=1;e<b.length;e++)c=z(c,x(b[e]));sa(c)&&(c=z(c,y.f));if(c)return{type:"list",length:b.length,h:c}}}else if("string"===a.ctype||"image"===a.ctype)return y.image;console.error("Cannot guess type of the following type:");console.log(a);return!1}var ta=0;function A(){ta++;return"_h"+ta}
function ua(a,b){if(a>h.width||b>h.height)h.width=Math.ceil(a),h.height=Math.ceil(b)}function va(a,b,c){a=a.getInitialMatrix();b-=a.tx;c+=a.ty;return{x:(b*a.d-c*a.b)/a.det,y:-(-b*a.c+c*a.a)/a.det}}function wa(a){return va(a,0,a.instance.canvas.clientHeight)}function xa(a){return va(a,a.instance.canvas.clientWidth,a.instance.canvas.clientHeight)}var ya=new Float32Array(1),za=new Int32Array(ya.buffer);
function Aa(a){ya[0]=a;a=za[0];var b=a>>16&32768,c=(a&2147483647)+4096;if(1199570944<=c)return 1199570944<=(a&2147483647)?2139095040>c?b|31744:b|31744|(a&8388607)>>13:b|31743;if(947912704<=c)return b|c-939524096>>13;if(855638016>c)return b;c=(a&2147483647)>>23;return b|(a&8388607|8388608)+(8388608>>>c-102)>>126-c}
function Ba(a){if(w)return new Float32Array(a);if(u){for(var b=new Uint16Array(a.length),c=0;c<a.length;c++)b[c]=Aa(a[c]);return b}b=new Uint8Array(a.length);for(c=0;c<a.length;c++)b[c]=255*a[c];return b}function Ca(a){return w?new Float32Array(a):u?new Uint16Array(a):new Uint8Array(a)}function Da(){return w?p.FLOAT:u?la.HALF_FLOAT_OES:p.UNSIGNED_BYTE}function Ea(a){for(var b=1;b<a;)b<<=1;return b};function Fa(a,b){a.hasOwnProperty("readcanvaswrappers")||(a.readcanvaswrappers=Array(4));var c=2*b.T+b.Z;a.readcanvaswrappers.hasOwnProperty(c)||(a.writecanvaswrapper&&a.writecanvaswrapper.generation>a.generation&&a.writecanvaswrapper.ja(),a.readcanvaswrappers[c]=new Ga(a,b),a.ready||(console.error("Image not ready. Creating onload event."),a.whenReady(function(){a.generation=Math.max(a.generation,a.readcanvaswrappers[c].generation+1)})));a.writecanvaswrapper&&(a.writecanvaswrapper=a.readcanvaswrappers[c]);
return a.readcanvaswrappers[c]}function Ha(a){if(!a.hasOwnProperty("writecanvaswrapper")){var b=-1;if(a.readcanvaswrappers)for(var c=3;0<=c;c--)a.readcanvaswrappers.hasOwnProperty(b)&&(b=c);else a.readcanvaswrappers=Array(4);-1==b&&(c={Z:!0,T:!1,repeat:!1},b=2*c.T+c.Z,a.readcanvaswrappers[b]=new Ga(a,c));a.writecanvaswrapper=a.readcanvaswrappers[b]}return a.writecanvaswrapper}
function Ga(a,b){this.canvas=a;this.i=b;this.J=a.width;this.H=a.height;Ia(this);this.K=0;this.l=[];this.ba=[];this.generation=-1;this.bindTexture();a.drawTo=this.drawTo.bind(this);a.cdyUpdate=this.ja.bind(this);a=Ca(this.V*this.L*4);for(var c=0;2>c;c++)this.l[c]=p.createTexture(),p.bindTexture(p.TEXTURE_2D,this.l[c]),p.pixelStorei(p.UNPACK_ALIGNMENT,1),p.texImage2D(p.TEXTURE_2D,0,p.RGBA,this.V,this.L,0,p.RGBA,Da(),a),b.T?p.texParameteri(p.TEXTURE_2D,p.TEXTURE_MIN_FILTER,b.Z?p.LINEAR_MIPMAP_LINEAR:
p.NEAREST_MIPMAP_LINEAR):p.texParameteri(p.TEXTURE_2D,p.TEXTURE_MIN_FILTER,b.Z?p.LINEAR:p.NEAREST),p.texParameteri(p.TEXTURE_2D,p.TEXTURE_MAG_FILTER,b.Z?p.LINEAR:p.NEAREST),this.ba[c]=p.createFramebuffer(),p.bindFramebuffer(p.FRAMEBUFFER,this.ba[c]),p.framebufferTexture2D(p.FRAMEBUFFER,p.COLOR_ATTACHMENT0,p.TEXTURE_2D,this.l[c],0);this.Y=new Ja(ja.copytexture_v,ja.copytexture_f);b=p.createBuffer();p.bindBuffer(p.ARRAY_BUFFER,b);b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,1,0]);a=p.getAttribLocation(this.Y.i,
"aPos");p.enableVertexAttribArray(a);c=p.getAttribLocation(this.Y.i,"aTexCoord");p.enableVertexAttribArray(c);var e=new Float32Array([0,0,1,0,0,1,1,1]),f=b.byteLength;p.bufferData(p.ARRAY_BUFFER,f+e.byteLength,p.STATIC_DRAW);p.bufferSubData(p.ARRAY_BUFFER,0,b);p.bufferSubData(p.ARRAY_BUFFER,f,e);p.vertexAttribPointer(a,3,p.FLOAT,!1,0,0);p.vertexAttribPointer(c,2,p.FLOAT,!1,0,f)}function Ia(a){a.V=Ea(a.J+a.J/2*(a.i.T&&a.i.repeat));a.L=Ea(a.H+a.H/2*(a.i.T&&a.i.repeat))}
Ga.prototype.bindTexture=function(){p.bindTexture(p.TEXTURE_2D,this.l[this.K])};Ga.prototype.bindFramebuffer=function(){p.bindFramebuffer(p.FRAMEBUFFER,this.ba[this.K^1]);this.K^=1};
Ga.prototype.ja=function(){var a;this.canvas.img.hasOwnProperty("getContext")?a=this.canvas.img.getContext("2d"):(this.canvas.img=document.createElement("canvas"),this.canvas.img.style.display="none",this.canvas.img.width=this.J,this.canvas.img.height=this.H,a=this.canvas.img.getContext("2d"));a.clearRect(0,0,this.J,this.H);this.drawTo(a,0,0);this.canvas.img.generation++};
function Ka(a){if(a.canvas.live||a.canvas.ready&&!(a.generation>=a.canvas.generation)){if(a.J!=a.canvas.width||a.H!=a.canvas.height){a.J=a.canvas.width;a.H=a.canvas.height;Ia(a);for(var b=Ca(a.V*a.L*4),c=0;2>c;c++)p.bindTexture(p.TEXTURE_2D,a.l[c]),p.texImage2D(p.TEXTURE_2D,0,p.RGBA,a.V,a.L,0,p.RGBA,Da(),b)}a.bindTexture();p.pixelStorei(p.UNPACK_FLIP_Y_WEBGL,1);a.i.repeat?(n.width=a.V,n.height=a.L,b=n.getContext("2d"),b.drawImage(a.canvas.img,0,a.L-a.H),b.drawImage(a.canvas.img,a.J,a.L-a.H),b.drawImage(a.canvas.img,
0,a.L-2*a.H),b.drawImage(a.canvas.img,a.J,a.L-2*a.H),p.texSubImage2D(p.TEXTURE_2D,0,0,0,p.RGBA,Da(),n)):p.texSubImage2D(p.TEXTURE_2D,0,0,0,p.RGBA,Da(),a.canvas.img);a.i.T&&p.generateMipmap(p.TEXTURE_2D);p.pixelStorei(p.UNPACK_FLIP_Y_WEBGL,0);a.generation=a.canvas.generation;console.log("Image has been loaded to GPU")}}
Ga.prototype.drawTo=function(a,b,c){ua(this.J,this.H);p.viewport(0,0,this.V,this.L);p.useProgram(this.Y.i);p.activeTexture(p.TEXTURE0);p.bindTexture(p.TEXTURE_2D,this.l[this.K]);this.Y.l.sampler([0]);p.bindFramebuffer(p.FRAMEBUFFER,null);p.drawArrays(p.TRIANGLE_STRIP,0,4);p.flush();a.drawImage(h,0,h.height-this.H,this.J,this.H,b,c,this.J,this.H)};function La(a,b){this.B=a;this.K=b;Ma(this)}
function Ma(a){var b=Na(new Oa(a.B),a.K);a.l=b.A;a.C=b.C;a.da=b.da;a.Y=ja.standardFragmentHeader+b.code;a.ba=ja.vshader;a.i=new Ja(a.ba,a.Y);b=p.createBuffer();p.bindBuffer(p.ARRAY_BUFFER,b);var b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,1,0]),c=p.getAttribLocation(a.i.i,"aPos");p.enableVertexAttribArray(c);a=p.getAttribLocation(a.i.i,"aTexCoord");p.enableVertexAttribArray(a);var e=new Float32Array([0,0,1,0,0,1,1,1]),f=b.byteLength;p.bufferData(p.ARRAY_BUFFER,f+e.byteLength,p.STATIC_DRAW);p.bufferSubData(p.ARRAY_BUFFER,
0,b);p.bufferSubData(p.ARRAY_BUFFER,f,e);p.vertexAttribPointer(c,3,p.FLOAT,!1,0,0);p.vertexAttribPointer(a,2,p.FLOAT,!1,0,f)}
function Pa(a){function b(a,c,e,f){f=void 0===f?"real":f;if(a)if("function"===typeof a)switch(c){case y.g:a([e.value.real,e.value.imag]);break;case y.F:e.value?a([1]):a([0]);break;case y.m:case y.f:a([e.value[f]]);break;default:if("list"===c.type&&D(c.h,y.f))a(e.value.map(function(a){return a.value[f]}));else if("list"===c.type&&"list"===c.h.type&&D(c.h.h,y.f)){for(var m=[],r=0;r<c.h.length;r++)for(var v=0;v<c.length;v++)m.push(e.value[v].value[r].value[f]);a(m)}else console.error("Don't know how to set uniform of type "+
E(c)+", to "+e)}else{if(F(c)){r=G(c);if(1===r){c=Qa(c.length);var C=0;for(m in c)b(a["a"+m],y.fa(c[m]),{ctype:"list",value:H(c[m]).map(function(a){return e.value[C+a]})}),C+=c[m];return}if(2<=r){for(m=0;m<c.length;m++)b(a["a"+m],c.h,{ctype:"list",value:e.value[m].value});return}}else if(I(c)){var B=function(a){return D(a,y.g)?y.f:J(a.length,B(a.h))};c=B(c);b(a.real,c,e,f="real");b(a.imag,c,e,f="imag");return}console.error("Don't know how to set uniform of type "+E(c)+", to");console.log(e)}}for(var c in a.l){var e=
a.B.evaluateAndVal(a.l[c].X),f=a.l[c].type;if(!D(Ra(e),f)){console.log("Type of "+c+" changed ("+E(Ra(e))+" is no subtype of  "+E(f)+"); forcing rebuild.");Ma(a);p.useProgram(a.i.i);Pa(a);return}a.i.l[c]&&b(a.i.l[c],f,e)}[["rnd_",function(){return[Math.random()]}],["_lowerleft",function(){var b=wa(a.B);return[b.x,b.y]}],["_lowerright",function(){var b=xa(a.B);return[b.x,b.y]}]].map(function(b){return a.i.l[b[0]]&&a.i.l[b[0]](b[1]())})}
function Sa(a){var b=0,c;for(c in a.C)for(var e in a.C[c]){p.activeTexture(p.TEXTURE0+b);var f=a.C[c][e],g=f.name,k={Z:f.U.hasOwnProperty("interpolate")?f.B.evaluateAndVal(f.U.interpolate).value:!0,T:f.U.hasOwnProperty("mipmap")?f.B.evaluateAndVal(f.U.mipmap).value:!1,repeat:f.U.hasOwnProperty("repeat")?f.B.evaluateAndVal(f.U.repeat).value:!1},f=Ta(f,k);Ka(f);f.bindTexture();[["_sampler"+g,[b]],["_ratio"+g,[f.J/f.H]],["_cropfact"+g,[f.J/f.V,f.H/f.L]],["_repeat"+g,[k.repeat]],["_mipmap"+g,[k.T]]].map(function(b){return a.i.l[b[0]]&&
a.i.l[b[0]](b[1])});b++}};CindyJS.registerPlugin(1,"CindyGL",function(a){function b(b,e,f,g,k,l){if(!b.ma||b.ka<ma)b.ma=!0,b.ka=ma,b.oa=new La(a,b);b=b.oa;var q;a:{for(q in b.da)if(b.B.getMyfunction(q).generation>b.da[q]){console.log(q+" is outdated; forcing rebuild.");q=!1;break a}q=!0}q||Ma(b);var m=k/g;q=e.x+-(f.y-e.y)*m;m=e.y+(f.x-e.x)*m;ua(g,k);l?p.viewport(0,0,g,k):p.viewport(0,h.height-k,g,k);p.useProgram(b.i.i);Pa(b);e=[f.x-e.x,q-e.x,e.x,f.y-e.y,m-e.y,e.y,0,0,1];b.i.l.hasOwnProperty("transformMatrix")&&b.i.l.transformMatrix([e[0],
e[3],e[6],e[1],e[4],e[7],e[2],e[5],e[8]]);Sa(b);l?(l.bindFramebuffer(),l.generation=++l.canvas.generation):p.bindFramebuffer(p.FRAMEBUFFER,null);p.drawArrays(p.TRIANGLE_STRIP,0,4);p.flush();l&&(l.generation=Math.max(l.generation,l.canvas.generation+1))}t=a.nada;a.defineFunction("compile",1,function(b){b=Na(new Oa(a),b[0]);console.log(b);return{ctype:"string",value:b}});a.defineFunction("forcerecompile",0,function(){ma++;return t});a.defineFunction("colorplot",1,function(c){na();var e=a.instance.canvas.clientWidth,
f=a.instance.canvas.clientHeight,g=a.instance.canvas.width,k=a.instance.canvas.height;b(c[0],wa(a),xa(a),g,k,null);a.instance.canvas.getContext("2d").drawImage(h,0,0,g,k,0,0,e,f);return t});a.defineFunction("colorplot",3,function(c){na();var e=c[0],f=a.extractPoint(a.evaluateAndVal(c[1])),g=a.extractPoint(a.evaluateAndVal(c[2])),k={x:Math.min(f.x,g.x),y:Math.min(f.y,g.y)},l={x:Math.max(f.x,g.x),y:Math.min(f.y,g.y)};c=a.instance.canvas.clientWidth;var q=a.instance.canvas.clientHeight,m=a.instance.canvas.width,
r=a.instance.canvas.height,v=va(a,0,0),C=wa(a),B=xa(a),B=Math.abs((f.x-g.x)/(C.x-B.x)),v=Math.abs((f.y-g.y)/(v.y-C.y));b(e,k,l,m*B,r*v,null);e=a.instance.canvas.getContext("2d");k=Math.min(f.x,g.x);f=Math.max(f.y,g.y);g=a.getInitialMatrix();e.drawImage(h,0,0,m*B,r*v,k*g.a-f*g.b+g.tx,k*g.c-f*g.d-g.ty,B*c,v*q);return t});a.defineFunction("colorplot",4,function(c){na();var e=a.extractPoint(a.evaluateAndVal(c[0])),f=a.extractPoint(a.evaluateAndVal(c[1])),g=a.evaluateAndVal(c[2]);c=c[3];if(!e.ok||!f.ok||
"string"!==g.ctype)return t;var g=a.getImage(g.value,!0),k=Ha(g);b(c,e,f,g.width,g.height,k);return t});a.defineFunction("colorplot",2,function(c){na();var e=wa(a),f=xa(a),g=a.evaluateAndVal(c[0]);c=c[1];if("string"!==g.ctype)return t;var g=a.getImage(g.value,!0),k=Ha(g);b(c,e,f,g.width,g.height,k);return t});a.defineFunction("setpixel",4,function(b){var e;var f=a.evaluateAndVal(b[0]),g;g=void 0===g?null:g;"string"===f.ctype?e=f.value:(console.log("argument is not a string"),e=g);f=Ua(a.evaluateAndVal(b[1]));
g=Ua(a.evaluateAndVal(b[2]));b=Va(a.evaluateAndVal(b[3]));if(!e)return t;var k=a.getImage(e,!0),k=Ha(k);isFinite(f)&&isFinite(g)&&e&&k&&b&&(k.bindTexture(),e=[b[0],b[1],b[2],1],p.texSubImage2D(p.TEXTURE_2D,0,f,g,1,1,p.RGBA,Da(),Ba(e)),b=k.canvas.img.getContext("2d"),k=b.createImageData(1,1),k.data.d=e,b.putImageData(k,f,g));return t})});function F(a){return"list"===a.type&&F(a.h)||D(a,y.f)}function I(a){return"list"===a.type&&I(a.h)||D(a,y.g)}function Wa(a){return"constant"===a.type&&D(a,y.m)}function Xa(a){return"constant"===a.type?x(a.value):a}function G(a){return"list"===a.type?G(a.h)+1:0}function Ya(a){return a.h?Ya(a.h):a}function Za(a,b){return G(a)===G(b)&&(0===G(a)||a.length===b.length&&Za(a.h,b.h))}function K(a){return D(a,y.f)?y.f:D(a,y.g)?y.g:{type:"list",length:a.length,h:K(a.h)}}
function ab(a){return D(a,y.g)?y.g:{type:"list",length:a.length,h:K(a.h)}}function L(a){return a===y.g?y.f:{type:"list",length:a.length,h:L(a.h)}}function M(a){return a===y.F||a===y.m||a===y.f||a===y.g||"list"===a.type&&a.h===y.f&&1<=a.length&&4>=a.length||"list"===a.type&&"list"===a.h.type&&a.h.h===y.f&&a.length===a.h.length&&2<=a.length&&4>=a.length}function sa(a){return-1!==[y.F,y.m,y.f,y.g].indexOf(a)}
function bb(a,b){return a===b||"constant"===a.type&&"constant"===b.type&&a.value.ctype===b.value.ctype&&("number"===a.value.ctype&&a.value.value.real===b.value.value.real&&a.value.value.imag===b.value.value.imag||"boolean"===a.value.ctype&&a.value.value===b.value.value)||"list"===a.type&&"list"===b.type&&a.length===b.length&&bb(a.h,b.h)}
function D(a,b){return bb(a,b)||a===y.ga?!0:a?sa(a)&&sa(b)?a<=b:"constant"===b.type?!1:"constant"===a.type?D(x(a.value),b):b===y.I?D(a,y.g)||D(a,y.O)||D(a,y.N):b===y.N||b===y.S?D(a,y.P):b===y.color?D(a,y.f)||"list"===a.type&&(3===a.length||4===a.length)&&D(a.h,y.f):"list"===a.type&&"list"===b.type&&a.length===b.length?D(a.h,b.h):!1:!1}
function z(a,b){if(!a)return b;if(!b||bb(a,b))return a;"constant"===a.type&&(a=x(a.value));"constant"===b.type&&(b=x(b.value));return sa(a)&&sa(b)?Math.max(a,b):"list"===a.type&&"list"===b.type&&a.length===b.length&&(b=z(a.h,b.h))?{type:"list",length:a.length,h:b}:!1}function N(a){return function(b){var c={},e;for(e in a){var f=a[e];c.ca=f[0];if(b.length==c.ca.length&&b.every(function(a){return function(b,c){return D(b,a.ca[c])}}(c)))return{s:c.ca,v:f[1],u:f[2]};c={ca:c.ca}}return!1}}
function cb(a){switch(a){case y.m:return N([[[y.F],y.m,O("int")]]);case y.f:return N([[[y.F],y.f,O("float")],[[y.m],y.f,O("float")]]);case y.g:return N([[[y.f],y.g,function(a){return"vec2("+a+", 0.)"}]]);case y.color:return N([[[y.f],y.color,P("float2color")],[[y.P],y.color,function(a){return"vec4("+a+",1.0)"}],[[y.$],y.color,Q]]);case y.N:return N([[[y.O],y.N,function(a){return"vec3("+a+",1.0)"}],[[y.P],y.N,Q]]);case y.S:return N([[[y.O],y.S,function(a){return"vec3("+a+",1.0)"}],[[y.P],y.S,Q]]);
case y.I:return N([[[y.g],y.I,Q],[[y.O],y.I,Q],[[y.N],y.I,P("dehomogenize")]]);default:if("list"===a.type){var b=Ya(a);if(D(b,y.f))return function(b){if(D(b[0],a))return{s:b,v:a,u:Q}};if(D(b,y.g))return function(b){var e=L(a);if(D(b[0],e))return{s:b,v:a,u:function(b,c,k){return R(a)+"("+b+", "+db(e,0)([],c,k)+" )"}}}}}console.log("no inclusionfunction ->"+E(a)+" implemented yet; using identity...");return function(b){return{s:b,v:a,u:Q}}}
function R(a){switch(a){case y.F:return"bool";case y.m:return"int";case y.f:return"float";case y.g:case y.I:return"vec2";case y.M:return"void";case y.color:return"vec4";case y.N:case y.S:return"vec3"}if("list"===a.type&&D(a.h,y.f))return 1==a.length?"float":"vec"+a.length;if("list"===a.type&&D(a.h,y.g))return"cvec"+a.length;if("list"===a.type&&"list"===a.h.type&&a.length===a.h.length&&D(a.h.h,y.f))switch(a.length){case 2:return"mat2";case 3:return"mat3";case 4:return"mat4"}if("list"===a.type&&"list"===
a.h.type&&D(a.h.h,y.f))return"mat"+a.length+"_"+a.h.length;if("list"===a.type&&"list"===a.h.type&&D(a.h.h,y.g))return"cmat"+a.length+"_"+a.h.length;if("list"===a.type)return"l"+a.length+"_"+R(a.h);console.error("No WebGL implementation for type "+E(a)+" found")}
function eb(a,b){switch(b){case y.F:return R(b)+"("+a.value+")";case y.m:return R(b)+"("+(a.value.real|0)+")";case y.f:return R(b)+"("+a.value.real+")";case y.g:return R(b)+"("+a.value.real+", "+a.value.imag+")";case y.color:return a=a.value.real,"vec4("+a+","+a+","+a+",1.)";default:console.error("Dont know how to paste values of Type "+E(b)+" yet.")}};var S={};function fb(a,b,c){if(!c.mark("includedfunctions",a)){for(var e in S[a])fb(S[a][e],b,c);c.add("includedfunctions",a,function(){return ja[a]})}}function P(a){return function(b,c,e){fb(a,c,e);return O(a)(b)}};function H(a){return Array.from(Array(a).keys())}function Qa(a){return 4>=a?[a]:5==a?[2,3]:Qa(a-4).concat([4])}function gb(a){var b=Ya(a),c=G(a);if(b===y.g){var e=L(a);return(0===c?["x","y"]:["real","imag"]).map(function(a){return{type:e,name:a}})}return D(b,y.f)?1==c?Qa(a.length).map(function(a,b){return{type:y.fa(a),name:"a"+b}}):H(a.length).map(function(b){return{type:a.h,name:"a"+b}}):[]}
function T(a,b){if(!M(a)){var c=R(a);b.add("structs",c,function(){return"struct "+c+" { "+gb(a).map(function(a){return T(a.type,b)||R(a.type)+" "+a.name+";"}).join("")+"};"})}}function hb(a,b,c){if(!M(a)){var e=a.length,f=a.h.length;c.add("functions","mult"+e+"_"+f,function(){return"vec"+e+" mult"+e+"_"+f+"(mat"+e+"_"+f+" a, vec"+f+" b){return "+ib(e)(H(e).map(function(a){return U(f)(["a.a"+a,"b"],b,c)}),b,c)+";}"})}}
function jb(a,b,c){if(!M(a)){var e=a.length,f="sum"+R(a);c.add("functions",f,function(){return R(a.h)+" "+f+"("+R(a)+" a){"+(R(a.h)+" res = "+db(a.h,0)([],b,c)+";\n      "+H(e).map(function(e){return kb(a.h)(["res",lb(a,e)(["a",e],b,c)],b,c)}).join("\n")+"\n        return res;\n    }")})}}
function mb(a,b,c){var e=a.length,f=a.h.length,g=L(a);c.add("functions","cmult"+e+"_"+f,function(){return"cvec"+e+" cmult"+e+"_"+f+"(cmat"+e+"_"+f+" a, cvec"+f+" b){\n      return cvec"+e+"("+nb(g.h)([ob(g)(["a.real","b.real"],b,c),ob(g)(["a.imag","b.imag"],b,c)],b,c)+","+kb(g.h)([ob(g)(["a.real","b.imag"],b,c),ob(g)(["a.imag","b.real"],b,c)],b,c)+");\n    }"})}
function pb(a,b){2<=a&&4>=a||b.add("functions","dot"+a,function(){return"float dot"+a+"(vec"+a+" a, vec"+a+" b) {\n    return "+Qa(a).map(function(a,b){return"dot(a.a"+b+",b.a"+b+")"}).join("+")+"; }"})}function qb(a,b,c){c.add("functions","cdot"+a,function(){return"vec2 cdot"+a+"(cvec"+a+" a, cvec"+a+" b) {\n  return vec2("+U(a)(["a.real","b.real"],b,c)+" + "+U(a)(["a.imag","b.imag"],b,c)+", "+U(a)(["a.real","b.imag"],b,c)+" + "+U(a)(["a.imag","b.real"],b,c)+"\n  ); }"})}
function rb(a,b,c){var e="add"+R(a);c.add("functions",e,function(){return R(a)+" "+e+"("+R(a)+" a, "+R(a)+" b) {\n    return "+R(a)+"("+gb(a).map(function(a){return R(a.type)+"("+kb(a.type)(["a."+a.name,"b."+a.name],b,c)+")"}).join(",")+");\n    }"})}
function sb(a,b,c){var e="sub"+R(a);c.add("functions",e,function(){return R(a)+" "+e+"("+R(a)+" a, "+R(a)+" b) {\n    return "+R(a)+"("+gb(a).map(function(a){return R(a.type)+"("+nb(a.type)(["a."+a.name,"b."+a.name],b,c)+")"}).join(",")+");\n    }"})}function tb(a,b,c){var e="scalarmult"+R(a);c.add("functions",e,function(){return R(a)+" "+e+"(float a, "+R(a)+" b) {\n    return "+R(a)+"("+gb(a).map(function(a){return R(a.type)+"("+ub(a.type)(["a","b."+a.name],b,c)+")"}).join(",")+");\n    }"})}
function vb(a,b,c){var e="cscalarmult"+R(a),f=L(a);c.add("functions",e,function(){return R(a)+" "+e+"(vec2 a, "+R(a)+" b) {\n    return "+R(a)+"("+nb(f)([ub(f)(["a.x","b.real"],b,c),ub(f)(["a.y","b.imag"],b,c)],b,c)+","+kb(f)([ub(f)(["a.x","b.imag"],b,c),ub(f)(["a.y","b.real"],b,c)],b,c)+");}"})}
function ob(a){if(M(a))return V("*");var b=Ya(a);if(D(b,y.f))return function(b,e,f){return hb(a,e,f)||"mult"+a.length+"_"+a.h.length+"("+b.join(",")+")"};if(b===y.g)return function(b,e,f){return mb(a,e,f)||"cmult"+a.length+"_"+a.h.length+"("+b.join(",")+")"}}function U(a){return function(b,c,e){return pb(a,e)||"dot"+(2<=a&&4>=a?"":a)+"("+b.join(",")+")"}}function wb(a){return function(b,c,e){return qb(a,c,e)||"cdot"+a+"("+b.join(",")+")"}}
function kb(a){return M(a)?V("+"):function(b,c,e){return rb(a,c,e)||"add"+R(a)+"("+b.join(",")+")"}}function nb(a){return M(a)?V("-"):function(b,c,e){return sb(a,c,e)||"sub"+R(a)+"("+b.join(",")+")"}}function xb(a){return F(a)&&1==G(a)?function(b,c,e){return U(a.length)([b[0],ib(a.length)(Array(a.length).fill("1."),c,e)],c,e)}:function(b,c,e){return jb(a,c,e)||"sum"+R(a)+"("+b.join(",")+")"}}
function ib(a){if(2<=a&&4>=a)return function(b){return"vec"+a+"("+b.join(",")+")"};if(1==a)return function(a){return"float("+a.join(",")+")"};var b=0;return function(c,e,f){return T(y.fa(a),f)||"vec"+a+"("+Qa(a).map(function(a){return"vec"+a+"("+H(a).map(function(){return++b&&c[b-1]}).join(",")+")"}).join(",")+")"}}function yb(a){return function(b,c,e){return T(y.ia(a),e)||"cvec"+a+"("+ib(a)(b.map(function(a){return"("+a+").x"}),c,e)+","+ib(a)(b.map(function(a){return"("+a+").y"}),c,e)+")"}}
function zb(a){var b=G(a);if(M(a)){if(2==b){var c=a.length;if(c==a.h.length&&2<=c&&4>=c)return function(a){return"mat"+c+"("+H(c).map(function(b){return"vec"+c+"("+H(c).map(function(c){return a[c]+"["+b+"]"}).join(",")+")"}).join(",")}}return function(b){return R(a)+"("+b.join(",")+")"}}if(1==b){if(F(a))return ib(a.length);if(I(a))return yb(a.length)}if(Ya(a)===y.g){var e=L(a);return function(b,c,k){return T(a,k)||R(a)+"("+zb(e)(b.map(function(a){return"("+a+").real"}),c,k)+","+zb(e)(b.map(function(a){return"("+
a+").imag"}),c,k)+")"}}return function(b,c,e){return T(a,e)||R(a)+"("+b.join(",")+")"}}function lb(a,b){if(Ya(a)===y.g){var c=L(a);return function(e,f,g){return R(a.h)+"("+lb(c,b)([e[0]+".real"],f,g)+","+lb(c,b)([e[0]+".imag"],f,g)+")"}}return 1==G(a)&&F(a)?Ab(a.length,b):function(a){return"("+a[0]+").a"+b}}function db(a,b){return M(a)?function(){return R(a)+"(float("+b+"))"}:function(c,e,f){return zb(a)+"(dadadadada"+gb(a).map(function(a){return db(a.type,b)(c,e,f)}).join(",")+")"}}
function Ab(a,b){return function(c){if(1==a)return"("+c[0]+")";if(2<=a&&4>=a)return"("+c[0]+")["+b+"]";var e;a:{e=b;var f=Qa(a),g;for(g in f)if(f[g]<=e)e-=f[g];else{e={first:g,second:e};break a}console.error("Accessing index out of range");e=void 0}return"("+c[0]+").a"+e.first+"["+e.second+"]"}}function ub(a){return M(a)?V("*"):function(b,c,e){return tb(a,c,e)||"scalarmult"+R(a)+"("+b.join(",")+")"}}function Bb(a){return function(b,c,e){return vb(a,c,e)||"cscalarmult"+R(a)+"("+b.join(",")+")"}};function J(a,b){return{type:"list",length:a,h:b}}function Ra(a){return{type:"constant",value:a}}var y={F:1,m:2,f:3,g:4,M:5,color:6,N:7,S:8,I:9,image:10,O:J(2,3),P:J(3,3),$:J(4,3),fa:function(a){return J(a,3)},ia:function(a){return J(a,4)},qa:J(2,J(2,3)),ra:J(3,J(3,3)),sa:J(4,J(4,3)),ga:18};Object.freeze(y);
function E(a){return 1<=a&&10>=a?"bool int float complex voidt color point line coordinate2d image".split(" ")[a-1]:"list"===a.type?E(a.h)+"["+a.length+"]":"constant"===a.type?"const["+JSON.stringify(a.value.value)+"]":JSON.stringify(a)}function O(a){return function(b){return ra(a)+"("+b+")"}}function V(a){return function(b){return"("+b.join(a)+")"}}function Q(a){return a}var W={};W.join=N([[y.N,y.N],y.S,O("cross")]);W.meet=N([[y.S,y.S],y.N,O("cross")]);
W["if"]=function(a){if(!a.every(function(a){return a}))return!1;if(2===a.length)return{s:a,v:a[1],u:function(a){return"if("+a[0]+") {"+a[1]+";}"}};if(3===a.length){var b=z(a[1],a[2]);return b?{s:[y.F,b,b],v:b,u:function(a){return"("+a[0]+" ? "+a[1]+" : "+a[2]+")"}}:{s:a,v:y.M,u:function(a){return"if("+a[0]+") {"+a[1]+";} else {"+a[2]+";}"}}}return!1};W["="]=function(a){a=z(a[0],a[1]);return{s:a,v:a,u:function(a){return a[0]+" = "+a[1]+";"}}};
W[";"]=function(a){return{s:a,v:a[1]!==y.M?a[1]:a[0],u:function(a){return a[0]+" ; "+a[1]+";"}}};W.repeat=function(a){return 2!=a.length&&3!=a.length||!Wa(a[0])?!1:{s:a,v:a[a.length-1],u:function(){return""}}};W.forall=function(a){return 2!=a.length&&3!=a.length||"list"!==a[0].type?!1:{s:a,v:a[a.length-1],u:function(){return""}}};W.apply=function(a){return 2!=a.length&&3!=a.length||"list"!==a[0].type?!1:{s:a,v:J(a[0].length,a[a.length-1]),u:function(){return""}}};
W.sum=function(a){return 1==a.length&&(F(a[0])||I(a[0]))?{s:a,v:a[0].h,u:xb(a[0])}:!1};W.regional=function(a){return{s:a,v:y.M,u:xb(a[0])}};W.sqrt=N([[[y.f],y.g,P("sqrtf")],[[y.g],y.g,P("sqrtc")]]);W.abs=N([[[y.f],y.f,O("abs")],[[y.g],y.f,O("length")],[[y.O],y.f,O("length")],[[y.P],y.f,O("length")],[[y.$],y.f,O("length")]]);W.abs_infix=W.abs;
W.dist=N([[[y.f,y.f],y.f,function(a){return O("abs")(V("-")(a))}],[[y.g,y.g],y.f,function(a){return O("length")(V("-")(a))}],[[y.O,y.O],y.f,function(a){return O("length")(V("-")(a))}],[[y.P,y.P],y.f,function(a){return O("length")(V("-")(a))}],[[y.$,y.$],y.f,function(a){return O("length")(V("-")(a))}]]);W.dist_infix=W.dist;W.sin=N([[[y.f],y.f,O("sin")],[[y.g],y.g,P("sinc")]]);W.cos=N([[[y.f],y.f,O("cos")],[[y.g],y.g,P("cosc")]]);W.tan=N([[[y.f],y.f,O("tan")],[[y.g],y.g,P("tanc")]]);
W.exp=N([[[y.f],y.f,O("exp")],[[y.g],y.g,P("expc")]]);W.arctan=N([[[y.f],y.f,O("atan")],[[y.g],y.g,P("arctanc")]]);W.log=N([[[y.f],y.g,P("logr")],[[y.g],y.g,P("logc")]]);var Cb=[2,3,4].map(function(a){return J(a,y.f)}).concat([2,3,4].map(function(a){return J(a,J(a,y.f))})),Db=[y.m,y.f,y.g].concat(Cb);W.add=function(a){var b=N(Db.map(function(a){return[[a,a],a,V("+")]}))(a);if(b)return b;b=a[0];a=a[1];if([b,a].every(function(a){return F(a)||I(a)})&&Za(b,a))return a=z(K(b),K(a)),{s:[a,a],v:a,u:kb(a)}};
W.sub=function(a){var b=N(Db.map(function(a){return[[a,a],a,V("-")]}).concat(Db.map(function(a){return[[y.M,a],a,V("-")]})))(a);if(b)return b;b=a[0];a=a[1];if([b,a].every(function(a){return F(a)||I(a)})&&Za(b,a))return a=z(K(b),K(a)),{s:[a,a],v:a,u:nb(a)}};W["+"]=W.add;W["-"]=W.sub;W._=function(a){var b=a[0];if("list"===b.type&&Wa(a[1])){var c=Number(a[1].value.value.real);if(1<=Math.abs(c)&&Math.abs(c)<=b.length)return 0<c&&--c,0>c&&(c=b.length-c),{s:a,v:b.h,u:lb(b,c)}}return!1};
W.mult=function(a){var b=N([[[y.m,y.m],y.m,V("*")],[[y.f,y.f],y.f,V("*")],[[y.g,y.g],y.g,P("multc")]])(a);if(b)return b;if(2!==a.length)return!1;var b=a[0],c=a[1];if([b,c].every(function(a){return"list"===a.type&&D(a.h,y.f)})&&b.length===c.length)return a=K(b),M(a)?{s:[a,a],v:y.f,u:O("dot")}:{s:[a,a],v:y.f,u:U(b.length)};if([b,c].every(function(a){return"list"===a.type&&D(a.h,y.g)})&&b.length===c.length)return a=ab(b),{s:[a,a],v:y.f,u:wb(b.length)};if(F(b)&&2===G(b)&&F(c)&&1===G(c)&&b.h.length===
c.length)return{s:[K(b),K(c)],v:y.fa(b.length),u:ob(K(b))};if(I(b)&&2===G(b)&&I(c)&&1===G(c)&&b.h.length===c.length)return{s:[ab(b),ab(c)],v:y.ia(b.length),u:ob(ab(b))};for(b={G:0};2>b.G;b={W:b.W,G:b.G,aa:b.aa},b.G++){if(D(a[0^b.G],y.f)&&(F(a[1^b.G])||I(a[1^b.G])))return b.W=K(a[1^b.G]),{s:b.G?[b.W,y.f]:[y.f,b.W],v:b.W,u:function(a){return function(b,c,k){return ub(a.W)([b[0^a.G],b[1^a.G]],c,k)}}(b)};if(D(a[0^b.G],y.g)&&I(a[1^b.G]))return b.aa=ab(a[1^b.G]),{s:b.G?[b.aa,y.g]:[y.g,b.aa],v:b.aa,u:function(a){return function(b,
c,k){return Bb(a.aa)([b[0^a.G],b[1^a.G]],c,k)}}(b)}}};W["*"]=W.mult;W.div=function(a){var b=N([[[y.f,y.f],y.f,V("/")],[[y.g,y.g],y.g,P("divc")]])(a);return b?b:D(a[1],y.f)&&I(a[0])&&(a=K(a[0]),M(a))?{s:[a,y.f],v:a,u:V("/")}:!1};W["/"]=W.div;W.re=N([[[y.g],y.f,P("realc")]]);W.im=N([[[y.g],y.f,P("imagc")]]);W.floor=N([[[y.f],y.m,function(a){return"int(floor("+a+"))"}],[[y.g],y.g,O("floor")]]);W.round=N([[[y.f],y.m,function(a){return"int(floor("+a+"+.5))"}],[[y.g],y.g,function(a){return"floor("+a+"+vec2(.5))"}]]);
W.ceil=N([[[y.f],y.m,function(a){return"int(ceil("+a+"))"}],[[y.g],y.g,O("ceil")]]);W.mod=N([[[y.m,y.m],y.m,function(a,b){return"int("+O("mod")("float("+a[0]+"), float("+a[1]+")",b)+")"}],[[y.f,y.f],y.f,O("mod")],[[y.g,y.g],y.g,P("mod")]]);W.random=N([[[],y.f,P("random")],[[y.f],y.f,function(a,b){return P("random")([],b)+"*"+a[0]}],[[y.g],y.g,function(a,b){return"vec2("+P("random")([],b)+","+P("random")([],b)+")*"+a[0]}]]);
W.arctan2=N([[[y.f,y.f],y.f,function(a){return"atan("+a[1]+", "+a[0]+")"}],[[y.g,y.g],y.g,P("arctan2c")],[[y.g],y.f,P("arctan2vec2")],[[y.O],y.f,P("arctan2vec2")],[[y.ia(2)],y.g,P("arctan2cvec2")]]);["red","green","blue","gray","hue"].forEach(function(a){W[a]=N([[[y.f],y.P,P(a)]])});W.grey=W.gray;W.min=N([[[y.m,y.m],y.m,O("min")],[[y.f,y.f],y.f,O("min")]]);W.max=N([[[y.m,y.m],y.m,O("max")],[[y.f,y.f],y.f,O("max")]]);W.complex=N([[[y.O],y.g,Q]]);W.pow=N([[[y.f,y.m],y.f,P("powi")],[[y.g,y.g],y.g,P("powc")]]);
W["^"]=W.pow;W.re=N([[[y.g],y.f,function(a){return"("+a+").x"}]]);W.conjugate=N([[[y.g],y.g,P("conjugate")]]);W.im=N([[[y.g],y.f,function(a){return"("+a+").y"}]]);W.genList=function(a){var b=a.length;if(0<b){var c=!1,e;for(e in a)c=z(c,a[e]);if(c)return a=J(b,c),{s:Array(b).fill(c),v:a,u:zb(a)}}return!1};W["&"]=N([[[y.F,y.F],y.F,V("&&")]]);W["%"]=N([[[y.F,y.F],y.F,V("||")]]);[">","<",">=","<=","=="].forEach(function(a){W[a]=N([[[y.m,y.m],y.F,V(a)],[[y.f,y.f],y.F,V(a)]])});
W.imagergb=N([[[y.image,y.I],y.P,Eb],[[y.I,y.I,y.image,y.I],y.P,Fb]]);W.imagergba=N([[[y.image,y.I],y.$,Gb],[[y.I,y.I,y.image,y.I],y.$,Hb]]);Object.freeze(W);S.divc=["multc"];S.powc=["expc","multc","logc"];S.sqrtc=["expc","multc","logc"];S.arccosc=["multc","negc","sqrtc","addc","logc"];S.arcsinc=["multc","negc","sqrtc","addc","logc"];S.tanc=["sinc","cosc","divc"];S.arctanc=["logc","addc","multc","subc"];S.arctan2c=["logc","divc","sqrtc","multc"];S.arctan2vec2c=["arctan2c"];S.hue=["hsv2rgb"];Object.freeze(S);function Oa(a){this.j={};this.A={};this.i={};this.K=!1;this.l={};this.B=a;this.C={}}Oa.prototype.add=function(a,b,c){this.mark(a,b);this.i[a].ha[b]||(this.i[a].ha[b]=c(),this.i[a].ea[b]=!0,this.i[a].order.push(b))};Oa.prototype.mark=function(a,b){this.i[a]||(this.i[a]={order:[],ea:{},ha:{}});var c=this.i[a].ea[b]||!1;this.i[a].ea[b]=!0;return c};function Ib(a,b){return a.i[b]?a.i[b].order.map(function(c){return a.i[b].ha[c]}).join("\n"):"\n"}
function X(a,b,c,e){if(bb(c,e)||c===y.ga)return b;if(D(c,e)){if("constant"===c.type)return eb(c.value,e);var f=cb(e)([c]);if(!f)return console.error("cannot find an implementation for "+E(c)+" -> "+E(e)+", using identity"),b;e=f.u;return e(X(a,b,c,f.s[0]),{},a)}console.error(E(c)+" is no subtype of "+E(e)+" (trying to cast the term "+b+")");return b}function Jb(a,b,c){a.j[b]||(a.j[b]={});a.j[b].R||(a.j[b].R=[]);a.j[b].w||(a.j[b].w=!1);a.hasOwnProperty("global")||(a.j[b].global=c)}
function Kb(a,b){var c=b.D;if(b.isuniform)return a.A[b.uvariable].type;if("variable"===b.ctype)return b=b.name,b=c[b]||b,a.j[b].w;if("function"===b.ctype&&a.l.hasOwnProperty(b.oper))return a.j[c[b.oper]].w;if("number"===b.ctype)return Ra(b);if("void"===b.ctype)return y.M;if("field"===b.ctype)return y.f;if("string"===b.ctype)return y.image;if("function"===b.ctype||"infix"===b.ctype){for(var c=Array(b.args.length),e=0;e<b.args.length;e++)c[e]=Y(a,b.args[e]);a=ra(b.oper);return(a=W[a]?W[a](c):!1)?a.v:
!1}console.error("Don't know how to compute type of");console.log(b);return!1}function Y(a,b){a.K&&b.hasOwnProperty("computedType")||(b.computedType=Kb(a,b));return b.computedType}
function Lb(a,b){function c(a,b,c){var e={},g;for(g in a)e[g]=a[g];a=A();Jb(k,a,!1);f[a].w=c;f[a].na=!0;e[b]=a;return e}function e(a,b,m){a.D=b;for(var r in a.args)e(a.args[r],1<=r&&"repeat$2"===a.oper?c(b,"#",y.m):1<=r&&"repeat$3"===a.oper?c(b,a.args[1].name,y.m):1<=r&&("forall$2"===a.oper||"apply$2"===a.oper)?c(b,"#",!1):1<=r&&("forall$3"===a.oper||"apply$3"===a.oper)?c(b,a.args[1].name,!1):b,m);"field"===a.ctype&&e(a.obj,b,m);if("="===a.oper){var v=a.args[0].name,v=b[v]||v;Jb(k,v,!0);f[v].R.push(a.args[1])}else if(a.oper&&
"regional"===ra(a.oper)&&"global"!=m)for(var C in a.args)v=a.args[C].name,r=A(),b[v]=r,g[m].j||(g[m].j=[]),g[m].j.push(r),Jb(k,r,!1);else if("forall$2"===a.oper||"apply$2"===a.oper||"forall$3"===a.oper||"apply$3"===a.oper)f[2===a.args.length?a.args[1].D["#"]:a.args[2].D[a.args[1].name]].R.push({ctype:"infix",oper:"_",args:[a.args[0],{ctype:"number",value:{real:1,imag:0}}],D:a.args[0].D});else if("function"===a.ctype&&g.hasOwnProperty(a.oper)){m=a.oper;C=m.replace("$","_");Jb(k,C,!1);b[m]=C;b={};for(v in g[m].arglist){r=
g[m].arglist[v].name;var B=C+"_"+r;b[r]=B;Jb(k,B,!1);f[B].R.push(a.args[v])}g[m].pa||(g[m].pa=!0,e(g[m].body,b,m),f[C].R.push(g[m].body))}}var f=a.j,g=a.l,k=a;e(b,{"#":"cgl_pixel"},"global")}
function Mb(a,b){function c(a){if(a.hasOwnProperty("dependsOnPixel"))return a.dependsOnPixel;if("variable"===a.ctype){var b=a.name,b=a.D[b]||b;return k[b]?a.dependsOnPixel=!0:a.dependsOnPixel=!1}b=["random","verbatimglsl"];if("function"===a.ctype&&-1!=b.indexOf(ra(a.oper)))return a.dependsOnPixel=!0;if("repeat$2"===a.oper||"forall$2"===a.oper||"apply$2"===a.oper)return c(a.args[1])?(k[a.args[1].D["#"]]=!0,a.dependsOnPixel=!0):a.dependsOnPixel=!1;if("repeat$3"===a.oper||"forall$3"===a.oper||"apply$3"===
a.oper)return c(a.args[2])?(k[a.args[2].D[a.args[1].name]]=!0,a.args[1].dependsOnPixel=!0,a.dependsOnPixel=!0):a.dependsOnPixel=!1;for(var e in a.args)if(c(a.args[e]))return a.dependsOnPixel=!0;return"function"===a.ctype&&g.hasOwnProperty(a.oper)&&c(g[a.oper].body)?a.dependsOnPixel=!0:"field"===a.ctype?a.dependsOnPixel=c(a.obj):a.dependsOnPixel=!1}function e(a,b){if(c(a)){for(var f in a.args)e(a.args[f],b||"repeat$2"===a.oper&&0==f||"repeat$3"===a.oper&&0==f||"_"===a.oper&&1==f);"field"===a.ctype&&
e(a.obj,b);"function"===a.ctype&&g.hasOwnProperty(a.oper)&&(a=a.oper,q.hasOwnProperty(a)||(q[a]=!0,e(g[a].body,b)))}else if("number"!==a.ctype&&"void"!==a.ctype){f=!1;var k,l;for(l in m)!f&&qa(a,m[l].X)&&(f=!0,k=l);f||(k=A(),m[k]={X:a,type:!1,la:b});a.isuniform=!0;a.uvariable=k}}var f=a.j,g=a.l,k={cgl_pixel:!0},l;for(l in f)if(1<=f[l].R.length||f[l].na)k[l]=!0;c(b);var q={"":!0},m=a.A;e(b,!1)}
function Nb(a,b){if("function"===b.ctype&&!a.l.hasOwnProperty(b.oper)&&null!==a.B.getMyfunction(b.oper)){var c=b.oper;a.l[c]=pa(a.B.getMyfunction(c));Nb(a,a.l[c].body)}for(var e in b.args)Nb(a,b.args[e])}
function Z(a,b,c){if(b.isuniform){b=b.uvariable;var e=a.A[b].type;return c?{code:"",o:"constant"===e.type?eb(e.value,Xa(e)):b,type:e}:{code:""}}if(";"===b.oper){for(var e={type:y.M,o:""},f="",g=b.args.length-1,k=g;0<=k;k--)"void"===b.args[k].ctype&&g--;for(k=0;k<=g;k++)e=Z(a,b.args[k],c&&k===g),f+=e.code;return c?{code:f,o:e.o,type:e.type}:{code:f}}if("="===b.oper)return e=Z(a,b.args[1],!0),f=b.args[0].name,f=b.D[f]||f,b=f+" = "+X(a,e.o,e.type,Y(a,b.args[0])),c?{code:e.code,o:b,type:a.j[f].w}:{code:e.code+
b+";\n"};if("repeat$2"===b.oper||"repeat$3"===b.oper){f=Z(a,b.args[0],!0);if("constant"!==f.type.type)return console.error("repeat possible only for fixed constant number in GLSL"),!1;e="repeat$2"===b.oper?b.args[1].D["#"]:b.args[2].D[b.args[1].name];f=f.o;b=Z(a,b.args["repeat$2"===b.oper?1:2],c);k=g="";c&&(k=A(),g+=R(b.type)+" "+k+";");g=g+("for(int "+e+"=1; "+e+" <= "+f+"; "+e+"++) {\n")+b.code;c&&(g+=k+" = "+b.o+";\n");g+="}\n";return c?{code:g,o:k,type:b.type}:{code:g}}if("forall$2"===b.oper||
"forall$3"===b.oper||"apply$2"===b.oper||"apply$3"===b.oper){e=Z(a,b.args[0],!0);if("list"!==e.type.type)return console.error(b.oper+" only possible for lists"),!1;var f=2===b.args.length?b.args[1].D["#"]:b.args[2].D[b.args[1].name],g=a.j[f].w,k=Z(a,b.args[2===b.args.length?1:2],c),l="",q="",m=!1;c&&(m="forall$2"===b.oper||"forall$3"===b.oper?k.type:J(e.type.length,k.type),q=A(),l+=R(m)+" "+q+";");var l=l+e.code,r=e.o;!a.j[r]&&!a.A[r]&&2<=e.type.length&&(r=A(),l+=R(e.type)+" "+r+" = "+e.o+";\n");
for(var l=l+(R(g)+" "+f+";\n"),v=0;v<e.type.length;v++)l+=f+" = "+lb(e.type,v)([r],[],a)+";\n",l+=k.code,c&&("forall$2"===b.oper||"forall$3"===b.oper?v===e.type.length-1&&(l+=q+" = "+k.o+";\n"):l+=lb(m,v)([q],[],a)+" = "+k.o+";\n");"list"===g.type&&T(g,a);"list"===m.type&&T(m,a);return c?{code:l,o:q,type:m}:{code:l}}if("if$2"===b.oper||"if$3"===b.oper)return k=Z(a,b.args[0],!0),l=Z(a,b.args[1],c),f=e="",g=Y(a,b),c&&(f=A(),e+=R(g)+" "+f+";"),e+=k.code,e+="if("+k.o+") {\n",e+=l.code,c&&(e+=f+" = "+
X(a,l.o,l.type,g)+";\n"),"if$3"===b.oper&&(b=Z(a,b.args[2],c),e=e+"} else {\n"+b.code,c&&(e+=f+" = "+X(a,b.o,b.type,g)+";\n")),e+="}\n",c?{code:e,o:f,type:g}:{code:e};if("function"===b.ctype||"infix"===b.ctype){l=b.oper;if("verbatimglsl"===ra(l))return b=a.B.evaluateAndVal(b.args[0]).value,c?{o:b,type:y.ga,code:""}:{code:b};e=b.args.map(function(b){return Z(a,b,!0)});f=e.map(function(a){return a.type});if(a.l.hasOwnProperty(l)){k=Ob(a,l);g=Array(e.length);for(q=0;q<e.length;q++)g[q]=a.j[a.l[l].body.D[a.l[l].arglist[q].name]].w;
l=a.j[b.D[l]].w}else{l=ra(l);if("regional"===l)return c?{o:"",type:y.M,code:""}:{code:""};k=W[l](f);if(!k)return console.error("Could not find an implementation for "+l+"("+f.map(E).join(", ")+").\nReturning empty code"),c?{o:"",type:y.M,code:""}:{code:""};g=k.s;l=k.v;k=k.u}q="";m=Array(e.length);for(r=0;r<e.length;r++)q+=e[r].code,m[r]=X(a,e[r].o,f[r],g[r]);b=k(m,b.modifs,a);return c?{o:b,type:l,code:q}:{code:q+b+";\n"}}if("number"===b.ctype)return e=Y(a,b),b=eb(b,x(b)),c?{o:b,type:e,code:""}:{code:e+
";\n"};if("string"===b.ctype)return console.error("Cannot compile strings to WebGL."),!1;if("variable"===b.ctype)return e=Y(a,b),f=b.name,f=b.D[f]||f,c?{o:f,type:e,code:""}:{code:f+";\n"};if("void"===b.ctype)return c?{o:"",type:y.M,code:""}:{code:""};if("field"===b.ctype)return e=Y(a,b),f=Z(a,b.obj,!0).o,f+="."+b.key,c?{o:f,type:e,code:""}:{code:f+";\n"};console.error("dont know how to this.compile "+JSON.stringify(b))}function Ob(a,b){Pb(a,b,a.l[b].arglist.length);return O(b.replace("$","_"))}
function Pb(a,b,c){if(!a.mark("compiledfunctions",b)){for(var e=a.l[b],f=b.replace("$","_"),g=e.body.D,k=Array(c),l=0;l<c;l++)k[l]=e.arglist[l].name;c=a.j[f].w===y.M;var q=R(a.j[f].w)+" "+f+"("+k.map(function(b){return R(a.j[g[b]].w)+" "+g[b]}).join(", ")+"){\n",m;for(m in e.j)k=e.j[m],q+=R(a.j[k].w)+" "+k+";\n";e=Z(a,e.body,!c);q+=e.code;c||(q+="return "+X(a,e.o,e.type,a.j[f].w)+";\n");q+="}\n";a.add("compiledfunctions",b,function(){return q})}}
function Na(a,b){ta=0;b=pa(b);Jb(a,"cgl_pixel",!1);a.j.cgl_pixel.w=y.O;var c=b;a.K=!1;Nb(a,c);Lb(a,c);Mb(a,c);for(var e in a.A)c=a.B.evaluateAndVal(a.A[e].X),a.A[e].type=a.A[e].la?Ra(c):x(c);e=!0;for(var f in a.j)a.j[f].w=a.j[f].w||!1;for(;e;){e=!1;for(var g in a.j)for(var k in a.j[g].R){f=Xa(Y(a,a.j[g].R[k]));var l=c=a.j[g].w||!1;f&&(c?D(f,c)?l=c:l=z(c,f):l=f,l&&l!==c&&(a.j[g].w=l,e=!0))}}for(var q in a.A)"list"===a.A[q].type.type&&T(a.A[q].type,a);for(var m in a.j)"list"===a.j[m].w.type&&T(a.j[m].w,
a);a.K=!0;b=Z(a,b,!0);g=X(a,b.o,b.type,y.color);D(b.type,y.color)||console.error("expression does not generate a color");k=Ib(a,"structs");k+=Ib(a,"uniforms");q=[];for(var r in a.A)"constant"!=a.A[r].type.type&&a.A[r].type!=y.image&&q.push("uniform "+R(a.A[r].type)+" "+r+";");k+=q.join("\n");r="";for(var v in a.C)for(var C in a.C[v])r+=a.C[v][C].code+"\n";k=k+r+Ib(a,"functions");k+=Ib(a,"includedfunctions");for(var B in a.j)a.j[B].global&&(k+=R(a.j[B].w)+" "+B+";\n");k+=Ib(a,"compiledfunctions");
k+="void main(void) {\n"+b.code+"gl_FragColor = "+g+";\n}\n";console.log(k);v={};if(a.i.compiledfunctions)for(var $a in a.i.compiledfunctions.ea)v[$a]=a.B.getMyfunction($a).generation;return{code:k,A:a.A,C:a.C,da:v}};function Qb(a,b,c,e){this.X=b;this.B=e;this.U=c;this.name=a;this.code="uniform sampler2D _sampler"+a+";\nuniform float _ratio"+a+";\nuniform vec2 _cropfact"+a+";\nuniform bool _repeat"+a+";\nuniform bool _mipmap"+a+";\nvec4 _imagergba"+a+" (vec2 A, vec2 B, vec2 p) {\n  p -= A; B -= A;\n  float b = dot(B,B);\n  p = vec2(dot(p,B),_ratio"+a+"*dot(p,vec2(-B.y,B.x)))/b;\n  if(_repeat"+a+") p = mod(p, vec2(1.));\n  if(_repeat"+a+" && _mipmap"+a+") {\n    vec4 color = vec4(0.);\n    float totalWeight = 0.;\n    for(int dx=0; dx<2; dx++) for(int dy=0; dy<2; dy++) {\n      vec2 delta = .5*vec2(dx, dy);\n      vec2 center = delta+vec2(.5);\n      vec2 tc = fract(p-delta)+delta;\n      float dst = dot(abs(tc-center),vec2(1.));\n      float w = max(.5-dst,0.);\n      w=w*w;\n      color += w * texture2D(_sampler"+
a+", tc*_cropfact"+a+");\n      totalWeight += w;\n    }\n    return color/totalWeight;\n  }\n  if(0. <= p.x && p.x <= 1. && 0. <= p.y && p.y <= 1.)\n    return texture2D(_sampler"+a+", p*_cropfact"+a+");\n  else\n    return vec4(0.);\n  }"}function Ta(a,b){var c=a.B.evaluateAndVal(a.X).value;a="string"===typeof c?a.B.getImage(c,!0):c;return null==a?(console.error("Could not find image "+c+"."),t):Fa(a,b)}
function Rb(a,b,c){c.C.hasOwnProperty(a)||(c.C[a]=[]);var e=c.C[a].length,f;for(f in c.C[a])if(e==c.C[a].length){var g=c.C[a][f].U,k=!0,l;for(l in["interpolation","mipmap","repeat"])k&&(qa(g,b)||(k=!1));k&&(e=f)}f=a+"_"+e;e==c.C[a].length&&c.C[a].push(new Qb(f,c.A[a].X,b,c.B));return f}function Hb(a,b,c){return["_imagergba",Rb(a[2],b,c),"(",a[0],",",a[1],",",a[3],")"].join("")}function Fb(a,b,c){return["(_imagergba",Rb(a[2],b,c),"(",a[0],",",a[1],",",a[3],").rgb)"].join("")}
function Gb(a,b,c){c.add("uniforms","corners",function(){return"uniform vec2 _lowerleft, _lowerright;"});return["_imagergba",Rb(a[0],b,c),"(_lowerleft, _lowerright, ",a[1],")"].join("")}function Eb(a,b,c){c.add("uniforms","corners",function(){return"uniform vec2 _lowerleft, _lowerright;"});return["(_imagergba",Rb(a[0],b,c),"(_lowerleft, _lowerright, ",a[1],").rgb)"].join("")};function Sb(a){var b;b=b?b:null;return"list"!==a.ctype?(console.log("argument is not a list"),b):a.value}function Va(a){var b;b=b?b:[.5,.5,.5];if("number"===a.ctype){var c=Tb(a);if(!isNaN(c))return[c,c,c]}a=Sb(a);return a?3!=a.length?(console.log("Not an RGB color vector"),b):a.map(function(a){return Tb(a)}):b}
function Ua(a){var b;b=void 0===b?Number.NaN:b;if("number"!==a.ctype)return console.log("argument is not a number"),b;b=a.value;a=b.real;b=b.imag;0!==b&&console.log("complex number is not real");b=Math.round(a);b!==a&&console.log("number is not an integer");return b}
function Tb(a){var b;b=void 0===b?Number.NaN:b;b=void 0===b?Number.NaN:b;"number"!==a.ctype?(console.log("argument is not a number"),a=b):(a=a.value,b=a.real,0!==a.imag&&console.log("complex number is not real"),a=b);return 0>a?0:1<a?1:a};function oa(a){this.i=a}oa.prototype.toString=function(){return this.i};
function Ja(a,b){var c=p;this.i=c.createProgram();this.W=Ub(this,c,c.VERTEX_SHADER,a);Ub(this,c,c.FRAGMENT_SHADER,b);a=this.i;c.linkProgram(a);if(!c.getProgramParameter(a,c.LINK_STATUS))throw new oa("Error linking shader:\n"+c.getProgramInfoLog(a));c.validateProgram(a);if(!c.getProgramParameter(a,c.VALIDATE_STATUS))throw new oa("Error validating shader:\n"+c.getProgramInfoLog(a));var e=this.i,f,g,k,l={},q,m,r,v;b=c.getProgramParameter(e,c.ACTIVE_UNIFORMS);for(a=0;a<b;++a)if(f=c.getActiveUniform(e,
a))if(g=f.name.replace(/\]/g,"")){for(q=l;k=/[.\[]/.exec(g);)m=g.substr(0,k.index),q.hasOwnProperty(m)?q=q[m]:"."===k[0]?q=q[m]={}:q=q[m]=[],g=g.substr(k.index+1);if(1<f.size){k=f.size;v=Array(k);for(m=0;m<k;++m)r=f.name+"["+m+"]",r=Vb(this,c,r,f),v[m]=r;q[g]=v}else r=Vb(this,c,f.name,f),q[g]=r}this.l=l}
function Ub(a,b,c,e){c=b.createShader(c);b.shaderSource(c,e);b.compileShader(c);if(!b.getShaderParameter(c,b.COMPILE_STATUS))throw console.warn(e.split("\n")),new oa("Error compiling shader:\n"+b.getShaderInfoLog(c));b.attachShader(a.i,c);return c}
function Vb(a,b,c,e){a=b.getUniformLocation(a.i,c);switch(e.type){case b.FLOAT:return b.uniform1fv.bind(b,a);case b.FLOAT_VEC2:return b.uniform2fv.bind(b,a);case b.FLOAT_VEC3:return b.uniform3fv.bind(b,a);case b.FLOAT_VEC4:return b.uniform4fv.bind(b,a);case b.BOOL:case b.INT:case b.SAMPLER_2D:case b.SAMPLER_CUBE:return b.uniform1iv.bind(b,a);case b.BOOL_VEC2:case b.INT_VEC2:return b.uniform2iv.bind(b,a);case b.BOOL_VEC3:case b.INT_VEC3:return b.uniform3iv.bind(b,a);case b.BOOL_VEC4:case b.INT_VEC4:return b.uniform4iv.bind(b,
a);case b.FLOAT_MAT2:return b.uniformMatrix2fv.bind(b,a,!1);case b.FLOAT_MAT3:return b.uniformMatrix3fv.bind(b,a,!1);case b.FLOAT_MAT4:return b.uniformMatrix4fv.bind(b,a,!1);default:throw new oa("Unknown data type for uniform "+c);}};
}).call(this);//# sourceMappingURL=CindyGL.js.map


