(function(){
'use strict';var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},d="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;
function ba(a,b){if(b){var c=d;a=a.split(".");for(var e=0;e<a.length-1;e++){var f=a[e];f in c||(c[f]={});c=c[f]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}
ba("String.prototype.repeat",function(a){return a?a:function(a){var c;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");c=this+"";if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var e="";a;)if(a&1&&(e+=c),a>>>=1)c+=c;return e}});
ba("Array.prototype.fill",function(a){return a?a:function(a,c,e){var f=this.length||0;0>c&&(c=Math.max(0,f+c));if(null==e||e>f)e=f;e=Number(e);0>e&&(e=Math.max(0,f+e));for(c=Number(c||0);c<e;c++)this[c]=a;return this}});function ca(){ca=function(){};d.Symbol||(d.Symbol=da)}var ea=0;function da(a){return"jscomp_symbol_"+(a||"")+ea++}
function fa(){ca();var a=d.Symbol.iterator;a||(a=d.Symbol.iterator=d.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ga(this)}});fa=function(){}}function ga(a){var b=0;return ha(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ha(a){fa();a={next:a};a[d.Symbol.iterator]=function(){return this};return a}
ba("Array.from",function(a){return a?a:function(a,c,e){fa();c=c?c:function(a){return a};var f=[],g=a[Symbol.iterator];if("function"==typeof g)for(a=g.call(a);!(g=a.next()).done;)f.push(c.call(e,g.value));else for(var g=a.length,k=0;k<g;k++)f.push(c.call(e,a[k]));return f}});
function ia(a,b){fa();a instanceof String&&(a+="");var c=0,e={next:function(){if(c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e}ba("Array.prototype.keys",function(a){return a?a:function(){return ia(this,function(a){return a})}});
var ja={addc:"vec2 addc(vec2 a,vec2 b){\nreturn a+b;\n}\n",arccosc:"vec2 arccosc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=addc(multc(logc(tmp1),vec2(0.0,1.0)),vec2(pi*0.5,0.0));\nreturn erg;\n}\n",arcsinc:"vec2 arcsinc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=multc(logc(tmp1),vec2(0.0,-1.0));\nreturn erg;\n}\n",arctan2c:"\n\n\n\nvec2 arctan2c(vec2 x,vec2 y){\nvec2 r=logc(divc(x+vec2(-y.y,y.x),sqrtc(multc(x,x)+multc(y,y))));\nreturn vec2(r.y, -r.x);\n}\n",
arctan2cvec2:"vec2 arctan2cvec2(cvec2 v){\nreturn arctan2c(v.real,v.imag);\n}\n",arctan2vec2:"float arctan2vec2(vec2 v){\nreturn atan(v.y,v.x);\n}\n",arctanc:"vec2 arctanc(vec2 a){\nvec2 t1=logc(addc(multc(a,vec2(0.0,-1.0)),vec2(1.0,0.0)));\nvec2 t2=logc(addc(multc(a,vec2(0.0,1.0)),vec2(1.0,0.0)));\nvec2 erg=multc(subc(t1,t2),vec2(0.0,0.5));\nreturn erg;\n}\n",blue:"vec3 blue(float f)\n{\nreturn vec3(0.,0.,clamp(f,0.,1.));\n}\n",cimag:"float imagc(vec2 a){\nreturn a.y;\n}\n",conjugate:"vec2 conjugate(vec2 a){\nreturn vec2(a.x, -a.y);\n}\n",
copytexture_f:"#ifdef GL_ES\nprecision highp float;\n#endif\n\nuniform sampler2D sampler;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_FragColor=texture2D(sampler,cgl_pixel);\n}\n",copytexture_v:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_Position=vec4(aPos,1.);\ncgl_pixel=aTexCoord;\n}\n",cosc:"vec2 cosc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat i= (imag1+imag2) /2.0;\nfloat r= (real1+real2) /2.0;\n\nreturn vec2(r,i);\n}\n",
creal:"float realc(vec2 a){\nreturn a.x;\n}\n",dehomogenize:"vec2 dehomogenize(vec3 z){\nreturn vec2(z.x,z.y)/z.z;\n}\n",divc:"vec2 divc(vec2 a,vec2 b){\nreturn 1./(b.x*b.x+b.y*b.y)*multc(a,vec2(b.x,-b.y));\n}\n",expc:"vec2 expc(vec2 a){\nfloat n=exp(a.x);\nfloat r=n*cos(a.y);\nfloat i=n*sin(a.y);\nreturn vec2(r,i);\n}\n",float2color:"vec4 float2color(float f)\n{\nreturn vec4(f,f,f,1.);\n}\n",gray:"vec3 gray(float f)\n{\nf=clamp(f,0.,1.);\nreturn vec3(f,f,f);\n}\n",green:"vec3 green(float f)\n{\nreturn vec3(0.,clamp(f,0.,1.),0.);\n}\n",
hsv2rgb:"vec3 hsv2rgb(vec3 c)\n{\nvec4 K=vec4(1.0,2.0/3.0,1.0/3.0,3.0);\nvec3 p=abs(fract(c.xxx+K.xyz) *6.0-K.www);\nreturn c.z*mix(K.xxx,clamp(p-K.xxx,0.0,1.0),c.y);\n}\n",hue:"vec3 hue(float a){\nreturn hsv2rgb(vec3(a,1.,1.));\n}\n",imagc:"float imagc(vec2 a){\nreturn a.y;\n}\n",invc:"vec2 invc(vec2 a){\nfloat n=a.x*a.x+a.y*a.y;\nreturn vec2(a.x/n,-a.y/n);\n}\n",logc:"vec2 logc(vec2 a){\nfloat re=a.x;\nfloat im=a.y;\nfloat s=sqrt(re*re+im*im);\nfloat i=im;\nfloat imag=atan(im,re);\nif(i<0.0){\nimag+= (2.0*pi);\n}\nif(i==0.0&&re<0.0){\nimag=pi;\n}\nif(imag>pi){\nimag-= (2.0*pi);\n};\nfloat real=log(s);\n\nreturn vec2(real,imag);\n}\n",
logr:"vec2 logr(float a){\nif(a>=0.)return vec2(log(a),0);\nelse return vec2(log(-a),pi);\n}\n",mat2complex:"mat4 mat2complex(mat2 a)\n{\nreturn mat4(\nvec4(a[0][0],0,a[0][1],0),\nvec4(0,a[0][0],0,a[0][1]),\nvec4(a[1][0],0,a[1][1],0),\nvec4(0,a[1][0],0,a[1][1])\n);\n}\n",multc:"vec2 multc(vec2 a,vec2 b){\nreturn vec2(a.x*b.x-a.y*b.y+0.0000000000000001,a.y*b.x+a.x*b.y);\n}\n",negc:"vec2 negc(vec2 a){\nreturn vec2(-a.x,-a.y);\n}\n",powc:"vec2 powc(vec2 a,vec2 b){\nreturn expc(multc(logc(a),b));\n}\n",
powi:"float powi(float a,int b){\nif(mod(float(b),2.) < .5)\nreturn pow(abs(a),float(b));\nelse\nreturn sign(a)*pow(abs(a),float(b));\n}\n",random:"uniform float rnd_;\n\nfloat last_rnd= .1231;\nfloat random(){\nfloat a=mod(rnd_*plain_pixel.x*32.23,1.21);\nfloat b=mod(last_rnd*plain_pixel.y*54.21,1.32);\nlast_rnd=mod(a+b+12232.2213*(1.+rnd_)*dot(plain_pixel,plain_pixel)+a+sin(b)+b*sin(dot(plain_pixel,vec2(232.121+rnd_,2232.11))+last_rnd*121.11)*129.12+rnd_,1.);\nreturn last_rnd;\n\n\n}\n",realc:"float realc(vec2 a){\nreturn a.x;\n}\n",
red:"vec3 red(float f)\n{\nreturn vec3(clamp(f,0.,1.),0.,0.);\n}\n",rgb2hsv:"vec3 rgb2hsv(vec3 c)\n{\nvec4 K=vec4(0.0, -1.0/3.0,2.0/3.0, -1.0);\nvec4 p=mix(vec4(c.bg,K.wz),vec4(c.gb,K.xy),step(c.b,c.g));\nvec4 q=mix(vec4(p.xyw,c.r),vec4(c.r,p.yzx),step(p.x,c.r));\n\nfloat d=q.x-min(q.w,q.y);\nfloat e=1.0e-10;\nreturn vec3(abs(q.z+ (q.w-q.y) / (6.0*d+e)),d/ (q.x+e),q.x);\n}\n",sinc:"\n\nvec2 sinc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat r= -(imag1-imag2) /2.0;\nfloat i= (real1-real2) /2.0;\n\nreturn vec2(r,i);\n}\n",
sqrtc:"vec2 sqrtc(vec2 a){\nreturn expc(multc(logc(a),vec2(0.5,0.0)));\n}\n",sqrtf:"vec2 sqrtf(float a){\nif(a>=0.)return vec2(sqrt(a),0.);\nelse return vec2(0.,sqrt(-a));\n}\n",standardFragmentHeader:"#ifdef GL_ES\nprecision highp float;\n#endif\n\n#define pi 3.141592653589793\n\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\n",subc:"vec2 subc(vec2 a,vec2 b){\nreturn a-b;\n}\n",tanc:"vec2 tanc(vec2 a){\nvec2 s=sinc(a);\nvec2 c=cosc(a);\nreturn divc(s,c);\n}\n",vec2complex:"vec4 vec2complex(vec2 a)\n{\nreturn vec4(a.x,0.,a.y,0);\n}\n",
vshader:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\nuniform mat3 transformMatrix;\nvoid main(void){\ngl_Position=vec4(aPos,1.);\nplain_pixel=aTexCoord;\nvec3 r=transformMatrix*vec3(plain_pixel,1);\ncgl_pixel=r.xy/r.z;\n}\n"};var ka=!1,h,p,q,r,u=!1,la,v=!1,ma=1;
function na(){function a(c){h.removeEventListener("webglcontextcreationerror",a,!1);c.statusMessage&&(b=c.statusMessage)}if(!ka){h=document.createElement("canvas");h.id="glcanvas";h.style.display="none";h.width=h.height=0;document.body.appendChild(h);p=document.createElement("canvas");p.id="tmpcanvas";p.style.display="none";p.width=p.height=0;document.body.appendChild(p);var b="Unknown";h.addEventListener("webglcontextcreationerror",a,!1);(q=h.getContext("webgl"))||(q=h.getContext("experimental-webgl"));
if(!q)throw new w("Could not obtain a WebGL context.\nReason: "+b);h.removeEventListener("webglcontextcreationerror",a,!1);v=q.getExtension("OES_texture_float")&&q.getExtension("OES_texture_float_linear");v||(console.error("Your browser does not suppert OES_texture_float, trying OES_texture_half_float..."),(u=(la=q.getExtension("OES_texture_half_float"))&&q.getExtension("OES_texture_half_float_linear"))||console.error("Your browser does not suppert OES_texture_half_float, will use 8-bit textures."));
navigator.userAgent.match(/(iPad|iPhone)/i)&&(console.log("You are  using an iPhone/iPad."),v=u=!1,q.getExtension("OES_texture_half_float")&&q.getExtension("OES_texture_half_float_linear")&&q.getExtension("EXT_color_buffer_half_float")?u=!0:console.error("Your browser does not suppert writing to half_float textures, we will use 8-bit textures."));ka=!0}};function oa(a){var b;if(null==a||"object"!=typeof a)return a;if(a instanceof Array){b=[];for(var c=0,e=a.length;c<e;c++)b[c]=oa(a[c]);return b}if(a instanceof Object){b={};for(c in a)a.hasOwnProperty(c)&&(0<="oper impl args ctype stack name arglist value real imag key obj body".split(" ").indexOf(c)&&(b[c]=oa(a[c])),a.modifs&&(b.modifs=a.modifs));return b}}
function pa(a,b){if(null==a||"object"!=typeof a)return a===b;if(a instanceof Array&&b instanceof Array){if(a.length!=b.length)return!1;for(var c=0,e=a.length;c<e;c++)if(!pa(a[c],b[c]))return!1;return!0}if(a instanceof Object&&b instanceof Object){c="oper impl args ctype stack name modifs arglist value real imag key obj body".split(" ");for(e=0;e<c.length;e++){var f=c[e];if(!pa(a[f],b[f]))return!1}return!0}return!1}function y(a){return-1===a.indexOf("$")?a:a.substr(0,a.indexOf("$"))}
function qa(a){if("boolean"===a.ctype)return z.F;if("number"===a.ctype)return a=a.value,1E-10>Math.abs(a.imag)?(a.real|0)===a.real?z.l:z.f:z.g;if("list"===a.ctype){var b=a.value;if(0<b.length){for(var c=qa(b[0]),e=1;e<b.length;e++)c=A(c,qa(b[e]));if(c)return{type:"list",length:b.length,h:c}}}else if("string"===a.ctype||"image"===a.ctype)return z.image;console.error("Cannot guess type of the following type:");console.log(a);return!1}var ra=0;function sa(){ra++;return"_helper"+ra}
function ta(a,b){if(a>h.width||b>h.height)h.width=Math.ceil(a),h.height=Math.ceil(b)}function ua(a,b,c){a=a.getInitialMatrix();b-=a.tx;c+=a.ty;return{x:(b*a.d-c*a.b)/a.det,y:-(-b*a.c+c*a.a)/a.det}}function va(a){return ua(a,0,a.instance.canvas.clientHeight)}function wa(a){return ua(a,a.instance.canvas.clientWidth,a.instance.canvas.clientHeight)}var xa=new Float32Array(1),ya=new Int32Array(xa.buffer);
function za(a){xa[0]=a;a=ya[0];var b=a>>16&32768,c=(a&2147483647)+4096;if(1199570944<=c)return 1199570944<=(a&2147483647)?2139095040>c?b|31744:b|31744|(a&8388607)>>13:b|31743;if(947912704<=c)return b|c-939524096>>13;if(855638016>c)return b;c=(a&2147483647)>>23;return b|(a&8388607|8388608)+(8388608>>>c-102)>>126-c}
function Aa(a){if(v)return new Float32Array(a);if(u){for(var b=new Uint16Array(a.length),c=0;c<a.length;c++)b[c]=za(a[c]);return b}b=new Uint8Array(a.length);for(c=0;c<a.length;c++)b[c]=255*a[c];return b}function Ba(a){return v?new Float32Array(a):u?new Uint16Array(a):new Uint8Array(a)}function Ca(){return v?q.FLOAT:u?la.HALF_FLOAT_OES:q.UNSIGNED_BYTE}function Da(a){for(var b=1;b<a;)b<<=1;return b};function Ea(a,b){a.hasOwnProperty("readcanvaswrappers")||(a.readcanvaswrappers=Array(4));var c=2*b.T+b.X;a.readcanvaswrappers.hasOwnProperty(c)||(a.writecanvaswrapper&&a.writecanvaswrapper.generation>a.generation&&a.writecanvaswrapper.ha(),a.readcanvaswrappers[c]=new B(a,b),a.ready||(console.error("Image not ready. Creating onload event."),a.whenReady(function(){a.generation=Math.max(a.generation,a.readcanvaswrappers[c].generation+1)})));a.writecanvaswrapper&&(a.writecanvaswrapper=a.readcanvaswrappers[c]);
return a.readcanvaswrappers[c]}function Fa(a){if(!a.hasOwnProperty("writecanvaswrapper")){var b=-1;if(a.readcanvaswrappers)for(var c=3;0<=c;c--)a.readcanvaswrappers.hasOwnProperty(b)&&(b=c);else a.readcanvaswrappers=Array(4);-1==b&&(c={X:!0,T:!1,repeat:!1},b=2*c.T+c.X,a.readcanvaswrappers[b]=new B(a,c));a.writecanvaswrapper=a.readcanvaswrappers[b]}return a.writecanvaswrapper}
function B(a,b){this.canvas=a;this.i=b;this.I=a.width;this.G=a.height;Ga(this);this.w=0;this.j=[];this.K=[];this.generation=-1;this.bindTexture();a.drawTo=this.drawTo.bind(this);a.cdyUpdate=this.ha.bind(this);a=Ba(this.V*this.M*4);for(var c=0;2>c;c++)this.j[c]=q.createTexture(),q.bindTexture(q.TEXTURE_2D,this.j[c]),q.pixelStorei(q.UNPACK_ALIGNMENT,1),q.texImage2D(q.TEXTURE_2D,0,q.RGBA,this.V,this.M,0,q.RGBA,Ca(),a),b.T?q.texParameteri(q.TEXTURE_2D,q.TEXTURE_MIN_FILTER,b.X?q.LINEAR_MIPMAP_LINEAR:q.NEAREST_MIPMAP_LINEAR):
q.texParameteri(q.TEXTURE_2D,q.TEXTURE_MIN_FILTER,b.X?q.LINEAR:q.NEAREST),q.texParameteri(q.TEXTURE_2D,q.TEXTURE_MAG_FILTER,b.X?q.LINEAR:q.NEAREST),this.K[c]=q.createFramebuffer(),q.bindFramebuffer(q.FRAMEBUFFER,this.K[c]),q.framebufferTexture2D(q.FRAMEBUFFER,q.COLOR_ATTACHMENT0,q.TEXTURE_2D,this.j[c],0);this.B=new Ha(ja.copytexture_v,ja.copytexture_f);b=q.createBuffer();q.bindBuffer(q.ARRAY_BUFFER,b);b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,1,0]);a=q.getAttribLocation(this.B.i,"aPos");q.enableVertexAttribArray(a);
c=q.getAttribLocation(this.B.i,"aTexCoord");q.enableVertexAttribArray(c);var e=new Float32Array([0,0,1,0,0,1,1,1]),f=b.byteLength;q.bufferData(q.ARRAY_BUFFER,f+e.byteLength,q.STATIC_DRAW);q.bufferSubData(q.ARRAY_BUFFER,0,b);q.bufferSubData(q.ARRAY_BUFFER,f,e);q.vertexAttribPointer(a,3,q.FLOAT,!1,0,0);q.vertexAttribPointer(c,2,q.FLOAT,!1,0,f)}function Ga(a){a.V=Da(a.I+a.I/2*(a.i.T&&a.i.repeat));a.M=Da(a.G+a.G/2*(a.i.T&&a.i.repeat))}B.prototype.bindTexture=function(){q.bindTexture(q.TEXTURE_2D,this.j[this.w])};
B.prototype.bindFramebuffer=function(){q.bindFramebuffer(q.FRAMEBUFFER,this.K[this.w^1]);this.w^=1};B.prototype.ha=function(){var a;this.canvas.img.hasOwnProperty("getContext")?a=this.canvas.img.getContext("2d"):(this.canvas.img=document.createElement("canvas"),this.canvas.img.style.display="none",this.canvas.img.width=this.I,this.canvas.img.height=this.G,a=this.canvas.img.getContext("2d"));a.clearRect(0,0,this.I,this.G);this.drawTo(a,0,0);this.canvas.img.generation++};
function Ia(a){if(a.canvas.live||a.canvas.ready&&!(a.generation>=a.canvas.generation)){if(a.I!=a.canvas.width||a.G!=a.canvas.height){a.I=a.canvas.width;a.G=a.canvas.height;Ga(a);for(var b=Ba(a.V*a.M*4),c=0;2>c;c++)q.bindTexture(q.TEXTURE_2D,a.j[c]),q.texImage2D(q.TEXTURE_2D,0,q.RGBA,a.V,a.M,0,q.RGBA,Ca(),b)}a.bindTexture();q.pixelStorei(q.UNPACK_FLIP_Y_WEBGL,1);a.i.repeat?(p.width=a.V,p.height=a.M,b=p.getContext("2d"),b.drawImage(a.canvas.img,0,a.M-a.G),b.drawImage(a.canvas.img,a.I,a.M-a.G),b.drawImage(a.canvas.img,
0,a.M-2*a.G),b.drawImage(a.canvas.img,a.I,a.M-2*a.G),q.texSubImage2D(q.TEXTURE_2D,0,0,0,q.RGBA,Ca(),p)):q.texSubImage2D(q.TEXTURE_2D,0,0,0,q.RGBA,Ca(),a.canvas.img);a.i.T&&q.generateMipmap(q.TEXTURE_2D);q.pixelStorei(q.UNPACK_FLIP_Y_WEBGL,0);a.generation=a.canvas.generation;console.log("Image has been loaded to GPU")}}
B.prototype.drawTo=function(a,b,c){ta(this.I,this.G);q.viewport(0,0,this.V,this.M);q.useProgram(this.B.i);q.activeTexture(q.TEXTURE0);q.bindTexture(q.TEXTURE_2D,this.j[this.w]);this.B.j.sampler([0]);q.bindFramebuffer(q.FRAMEBUFFER,null);q.drawArrays(q.TRIANGLE_STRIP,0,4);q.flush();a.drawImage(h,0,h.height-this.G,this.I,this.G,b,c,this.I,this.G)};function Ja(a,b){this.v=a;this.w=b;Ka(this)}
function Ka(a){var b=La(new Ma(a.v),a.w);a.j=b.D;a.A=b.A;a.ba=b.ba;a.B=ja.standardFragmentHeader+b.code;a.K=ja.vshader;a.i=new Ha(a.K,a.B);b=q.createBuffer();q.bindBuffer(q.ARRAY_BUFFER,b);var b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,1,0]),c=q.getAttribLocation(a.i.i,"aPos");q.enableVertexAttribArray(c);a=q.getAttribLocation(a.i.i,"aTexCoord");q.enableVertexAttribArray(a);var e=new Float32Array([0,0,1,0,0,1,1,1]),f=b.byteLength;q.bufferData(q.ARRAY_BUFFER,f+e.byteLength,q.STATIC_DRAW);q.bufferSubData(q.ARRAY_BUFFER,
0,b);q.bufferSubData(q.ARRAY_BUFFER,f,e);q.vertexAttribPointer(c,3,q.FLOAT,!1,0,0);q.vertexAttribPointer(a,2,q.FLOAT,!1,0,f)}
function Na(a){function b(a,c,e,f){f=void 0===f?"real":f;if(a)if("function"===typeof a)switch(c){case z.g:a([e.value.real,e.value.imag]);break;case z.F:e.value?a([1]):a([0]);break;case z.l:case z.f:a([e.value[f]]);break;default:if("list"===c.type&&C(c.h,z.f))a(e.value.map(function(a){return a.value[f]}));else if("list"===c.type&&"list"===c.h.type&&C(c.h.h,z.f)){for(var n=[],t=0;t<c.h.length;t++)for(var x=0;x<c.length;x++)n.push(e.value[x].value[t].value[f]);a(n)}else console.error("Don't know how to set uniform of type "+
D(c)+", to "+e)}else{if(E(c)){t=F(c);if(1===t){c=H(c.length);var J=0;for(n in c)b(a["a"+n],z.L(c[n]),{ctype:"list",value:I(c[n]).map(function(a){return e.value[J+a]})}),J+=c[n];return}if(2<=t){for(n=0;n<c.length;n++)b(a["a"+n],c.h,{ctype:"list",value:e.value[n].value});return}}else if(K(c)){var G=function(a){return C(a,z.g)?z.f:L(a.length,G(a.h))};c=G(c);b(a.real,c,e,f="real");b(a.imag,c,e,f="imag");return}console.error("Don't know how to set uniform of type "+D(c)+", to");console.log(e)}}for(var c in a.j)if(a.i.j[c]){var e=
a.v.evaluateAndVal(a.j[c].J),f=a.j[c].type;if(!C(qa(e),f)){console.log("Type of "+c+" changed; forcing rebuild.");Ka(a);q.useProgram(a.i.i);Na(a);return}b(a.i.j[c],f,e)}a.i.j.hasOwnProperty("rnd_")&&a.i.j.rnd_([Math.random()])}
function Oa(a){var b=0,c;for(c in a.A)for(var e in a.A[c]){q.activeTexture(q.TEXTURE0+b);var f=a.A[c][e],g=f.name,k={X:f.U.hasOwnProperty("interpolate")?f.v.evaluateAndVal(f.U.interpolate).value:!0,T:f.U.hasOwnProperty("mipmap")?f.v.evaluateAndVal(f.U.mipmap).value:!1,repeat:f.U.hasOwnProperty("repeat")?f.v.evaluateAndVal(f.U.repeat).value:!1},f=Pa(f,k);Ia(f);f.bindTexture();[["_sampler"+g,[b]],["_ratio"+g,[f.I/f.G]],["_cropfact"+g,[f.I/f.V,f.G/f.M]],["_repeat"+g,[k.repeat]],["_mipmap"+g,[k.T]]].map(function(b){return a.i.j[b[0]]&&
a.i.j[b[0]](b[1])});b++}};CindyJS.registerPlugin(1,"CindyGL",function(a){function b(b,e,f,g,k,m){if(!b.ja||b.ia<ma)b.ja=!0,b.ia=ma,b.ka=new Ja(a,b);b=b.ka;var l;a:{for(l in b.ba)if(b.v.getMyfunction(l).generation>b.ba[l]){console.log(l+" is outdated; forcing rebuild.");l=!1;break a}l=!0}l||Ka(b);var n=k/g;l=e.x+-(f.y-e.y)*n;n=e.y+(f.x-e.x)*n;ta(g,k);m?q.viewport(0,0,g,k):q.viewport(0,h.height-k,g,k);q.useProgram(b.i.i);Na(b);e=[f.x-e.x,l-e.x,e.x,f.y-e.y,n-e.y,e.y,0,0,1];b.i.j.hasOwnProperty("transformMatrix")&&b.i.j.transformMatrix([e[0],
e[3],e[6],e[1],e[4],e[7],e[2],e[5],e[8]]);Oa(b);m?(m.bindFramebuffer(),m.generation=++m.canvas.generation):q.bindFramebuffer(q.FRAMEBUFFER,null);q.drawArrays(q.TRIANGLE_STRIP,0,4);q.flush();m&&(m.generation=Math.max(m.generation,m.canvas.generation+1))}r=a.nada;a.defineFunction("compile",1,function(b){b=La(new Ma(a),b[0]);console.log(b);return{ctype:"string",value:b}});a.defineFunction("forcerecompile",0,function(){ma++;return r});a.defineFunction("colorplot",1,function(c){na();var e=a.instance.canvas.clientWidth,
f=a.instance.canvas.clientHeight,g=a.instance.canvas.width,k=a.instance.canvas.height;b(c[0],va(a),wa(a),g,k,null);a.instance.canvas.getContext("2d").drawImage(h,0,0,g,k,0,0,e,f);return r});a.defineFunction("colorplot",3,function(c){na();var e=c[0],f=a.extractPoint(a.evaluateAndVal(c[1])),g=a.extractPoint(a.evaluateAndVal(c[2])),k={x:Math.min(f.x,g.x),y:Math.min(f.y,g.y)},m={x:Math.max(f.x,g.x),y:Math.min(f.y,g.y)};c=a.instance.canvas.clientWidth;var l=a.instance.canvas.clientHeight,n=a.instance.canvas.width,
t=a.instance.canvas.height,x=ua(a,0,0),J=va(a),G=wa(a),G=Math.abs((f.x-g.x)/(J.x-G.x)),x=Math.abs((f.y-g.y)/(x.y-J.y));b(e,k,m,n*G,t*x,null);e=a.instance.canvas.getContext("2d");k=Math.min(f.x,g.x);f=Math.max(f.y,g.y);g=a.getInitialMatrix();e.drawImage(h,0,0,n*G,t*x,k*g.a-f*g.b+g.tx,k*g.c-f*g.d-g.ty,G*c,x*l);return r});a.defineFunction("colorplot",4,function(c){na();var e=a.extractPoint(a.evaluateAndVal(c[0])),f=a.extractPoint(a.evaluateAndVal(c[1])),g=a.evaluateAndVal(c[2]);c=c[3];if(!e.ok||!f.ok||
"string"!==g.ctype)return r;var g=a.getImage(g.value,!0),k=Fa(g);b(c,e,f,g.width,g.height,k);return r});a.defineFunction("colorplot",2,function(c){na();var e=va(a),f=wa(a),g=a.evaluateAndVal(c[0]);c=c[1];if("string"!==g.ctype)return r;var g=a.getImage(g.value,!0),k=Fa(g);b(c,e,f,g.width,g.height,k);return r});a.defineFunction("setpixel",4,function(b){var e;var f=a.evaluateAndVal(b[0]),g;g=void 0===g?null:g;"string"===f.ctype?e=f.value:(console.log("argument is not a string"),e=g);f=Qa(a.evaluateAndVal(b[1]));
g=Qa(a.evaluateAndVal(b[2]));b=Ra(a.evaluateAndVal(b[3]));if(!e)return r;var k=a.getImage(e,!0),k=Fa(k);isFinite(f)&&isFinite(g)&&e&&k&&b&&(k.bindTexture(),e=[b[0],b[1],b[2],1],q.texSubImage2D(q.TEXTURE_2D,0,f,g,1,1,q.RGBA,Ca(),Aa(e)),b=k.canvas.img.getContext("2d"),k=b.createImageData(1,1),k.data.d=e,b.putImageData(k,f,g));return r})});function E(a){return"list"===a.type&&E(a.h)||C(a,z.f)}function K(a){return"list"===a.type&&K(a.h)||C(a,z.g)}function F(a){return"list"===a.type?F(a.h)+1:0}function Sa(a){return a.h?Sa(a.h):a}function Ta(a,b){return F(a)===F(b)&&(0===F(a)||a.length===b.length&&Ta(a.h,b.h))}function M(a){return C(a,z.f)?z.f:C(a,z.g)?z.g:{type:"list",length:a.length,h:M(a.h)}}function Ua(a){return C(a,z.g)?z.g:{type:"list",length:a.length,h:M(a.h)}}
function Va(a){return a===z.g?z.f:{type:"list",length:a.length,h:Va(a.h)}}function N(a){return a===z.F||a===z.l||a===z.f||a===z.g||"list"===a.type&&a.h===z.f&&2<=a.length&&4>=a.length||"list"===a.type&&"list"===a.h.type&&a.h.h===z.f&&a.length===a.h.length&&2<=a.length&&4>=a.length}function Wa(a){return-1!==[z.F,z.l,z.f,z.g].indexOf(a)}function Xa(a,b){return a===b||"list"===a.type&&"list"===b.type&&a.length===b.length&&Xa(a.h,b.h)}
function C(a,b){return Xa(a,b)||a===z.da?!0:a?Wa(a)&&Wa(b)?a<=b:b===z.H?C(a,z.g)||C(a,z.P)||C(a,z.O):b===z.O||b===z.S?C(a,z.R):b===z.color?C(a,z.f)||"list"===a.type&&(3===a.length||4===a.length)&&C(a.h,z.f):"list"===a.type&&"list"===b.type&&a.length===b.length?C(a.h,b.h):!1:!1}function A(a,b){return a?b?Wa(a)&&Wa(b)?Math.max(a,b):"list"===a.type&&"list"===b.type&&a.length===b.length&&(b=A(a.h,b.h))?{type:"list",length:a.length,h:b}:!1:a:b}
function O(a){return function(b){var c={},e;for(e in a){var f=a[e];c.$=f[0];if(b.length==c.$.length&&b.every(function(a){return function(b,c){return C(b,a.$[c])}}(c)))return{m:c.$,s:f[1],o:f[2]};c={$:c.$}}return!1}}
function Ya(a){switch(a){case z.l:return O([[[z.F],z.l,P("int")]]);case z.f:return O([[[z.F],z.f,P("float")],[[z.l],z.f,P("float")]]);case z.g:return O([[[z.f],z.g,function(a){return"vec2("+a+", 0.)"}]]);case z.color:return O([[[z.f],z.color,Q("float2color")],[[z.R],z.color,function(a){return"vec4("+a+",1.0)"}],[[z.Y],z.color,R]]);case z.O:return O([[[z.P],z.O,function(a){return"vec3("+a+",1.0)"}],[[z.R],z.O,R]]);case z.S:return O([[[z.P],z.S,function(a){return"vec3("+a+",1.0)"}],[[z.R],z.S,R]]);
case z.H:return O([[[z.g],z.H,R],[[z.P],z.H,R],[[z.O],z.H,Q("dehomogenize")]]);default:if("list"===a.type&&C(a.h,z.f))return function(b){var c=b[0];if("list"===c.type&&C(c.h,z.f)&&c.length===a.length)return{m:b,s:a,o:R}};if("list"===a.type&&a.h===z.g)return function(b){b=b[0];if("list"===b.type&&C(b.h,z.f)&&b.length===a.length){var c=a.length;return{m:[L(c,z.f)],s:a,o:function(a){return"cvec"+c+"("+a+", "+Za(c)(Array(c).fill("0."))+")"}}}};if("list"===a.type&&"list"===a.h&&C(a.h.h,z.f))return function(b){var c=
b[0];if("list"===c.type&&"list"===c.h&&C(c.h.h,z.f)&&c.length===a.length&&c.h.length===a.h.length)return{m:b,s:a,o:R}};if("list"===a.type&&"list"===a.h&&a.h.h===z.g)return function(b){b=b[0];if("list"===b.type&&"list"===b.h&&C(b.h.h,z.f)&&b.length===a.length&&b.h.length===a.h.length){var c=a.length,e=a.h.length;return{m:[L(c,L(e,z.f))],s:a,o:function(a){return"cmat"+c+"_"+e+"("+a+", "+$a(c,e)(Array(c).fill(Za(e)(Array(e).fill("0."))))+")"}}}}}console.log("no inclusionfunction ->"+D(a)+" implemented yet; using identity...");
return function(b){return{m:b,s:a,o:R}}}
function S(a){switch(a){case z.F:return"bool";case z.l:return"int";case z.f:return"float";case z.g:case z.H:return"vec2";case z.N:return"void";case z.color:return"vec4";case z.O:case z.S:return"vec3"}if("list"===a.type&&C(a.h,z.f))return"vec"+a.length;if("list"===a.type&&C(a.h,z.g))return"cvec"+a.length;if("list"===a.type&&"list"===a.h.type&&a.length===a.h.length&&C(a.h.h,z.f))switch(a.length){case 2:return"mat2";case 3:return"mat3";case 4:return"mat4"}if("list"===a.type&&"list"===a.h.type&&C(a.h.h,
z.f))return"mat"+a.length+"_"+a.h.length;if("list"===a.type&&"list"===a.h.type&&C(a.h.h,z.g))return"cmat"+a.length+"_"+a.h.length;console.error("No WebGL implementation for type "+D(a)+" found")};var T={};function ab(a,b,c){if(!c.mark("includedfunctions",a)){for(var e in T[a])ab(T[a][e],b,c);c.add("includedfunctions",a,function(){return ja[a]})}}function Q(a){return function(b,c,e){ab(a,c,e);return P(a)(b)}};function I(a){return Array.from(Array(a).keys())}function H(a){return 4>=a?[a]:5==a?[2,3]:H(a-4).concat([4])}function bb(a){var b=Sa(a),c=F(a);if(b===z.g){var e=Va(a);return(0===c?["x","y"]:["real","imag"]).map(function(a){return{type:e,name:a}})}return C(b,z.f)?1==c?H(a.length).map(function(a,b){return{type:z.L(a),name:"a"+b}}):I(a.length).map(function(b){return{type:a.h,name:"a"+b}}):[]}
function U(a,b){if(!N(a)){var c=S(a);b.add("structs",c,function(){return"struct "+c+" { "+bb(a).map(function(a){return U(a.type,b)||S(a.type)+" "+a.name+";"}).join("")+"};"})}}function cb(a,b,c){if(!N(a)){var e=a.length,f=a.h.length;U(z.L(f),c);U(z.L(e),c);U(a,c);c.add("functions","mult"+e+"_"+f,function(){return"vec"+e+" mult"+e+"_"+f+"(mat"+e+"_"+f+" a, vec"+f+" b){return "+Za(e)(I(e).map(function(a){return db(f)(["a.a"+a,"b"],b,c)}),b,c)+";}"})}}
function eb(a,b,c){var e=a.length,f=a.h.length;U(z.L(f),c);U(z.L(e),c);U(a,c);var g=Va(a);c.add("functions","cmult"+e+"_"+f,function(){return"cvec"+e+" cmult"+e+"_"+f+"(cmat"+e+"_"+f+" a, cvec"+f+" b){\n      return cvec"+e+"("+fb(g.h)([gb(g)(["a.real","b.real"],b,c),gb(g)(["a.imag","b.imag"],b,c)],b,c)+","+hb(g.h)([gb(g)(["a.real","b.imag"],b,c),gb(g)(["a.imag","b.real"],b,c)],b,c)+");\n    }"})}
function ib(a,b){2<=a&&4>=a||(U(z.L(a),b),b.add("functions","dot"+a,function(){return"float dot"+a+"(vec"+a+" a, vec"+a+" b) {\n    return "+H(a).map(function(a,b){return"dot(a.a"+b+",b.a"+b+")"}).join("+")+"; }"}))}function jb(a,b,c){var e="add"+S(a);c.add("functions",e,function(){return S(a)+" "+e+"("+S(a)+" a, "+S(a)+" b) {\n    return "+S(a)+"("+bb(a).map(function(a){return S(a.type)+"("+hb(a.type)(["a."+a.name,"b."+a.name],b,c)+")"}).join(",")+");\n    }"})}
function kb(a,b,c){var e="sub"+S(a);c.add("functions",e,function(){return S(a)+" "+e+"("+S(a)+" a, "+S(a)+" b) {\n    return "+S(a)+"("+bb(a).map(function(a){return S(a.type)+"("+fb(a.type)(["a."+a.name,"b."+a.name],b,c)+")"}).join(",")+");\n    }"})}function lb(a,b,c){var e="scalarmult"+S(a);c.add("functions",e,function(){return S(a)+" "+e+"(float a, "+S(a)+" b) {\n    return "+S(a)+"("+bb(a).map(function(a){return S(a.type)+"("+mb(a.type)(["a","b."+a.name],b,c)+")"}).join(",")+");\n    }"})}
function nb(a,b,c){var e="cscalarmult"+S(a),f=Va(a);c.add("functions",e,function(){return S(a)+" "+e+"(vec2 a, "+S(a)+" b) {\n    return "+S(a)+"("+fb(f)([mb(f)(["a.x","b.real"],b,c),mb(f)(["a.y","b.imag"],b,c)],b,c)+","+hb(f)([mb(f)(["a.x","b.imag"],b,c),mb(f)(["a.y","b.real"],b,c)],b,c)+");}"})}
function gb(a){if(N(a))return V("*");var b=Sa(a);if(C(b,z.f))return function(b,e,f){return cb(a,e,f)||"mult"+a.length+"_"+a.h.length+"("+b.join(",")+")"};if(b===z.g)return function(b,e,f){return eb(a,e,f)||"cmult"+a.length+"_"+a.h.length+"("+b.join(",")+")"}}function db(a){return function(b,c,e){return ib(a,e)||"dot"+(2<=a&&4>=a?"":a)+"("+b.join(",")+")"}}function hb(a){return N(a)?V("+"):function(b,c,e){return jb(a,c,e)||"add"+S(a)+"("+b.join(",")+")"}}
function fb(a){return N(a)?V("-"):function(b,c,e){return kb(a,c,e)||"sub"+S(a)+"("+b.join(",")+")"}}function Za(a){if(2<=a&&4>=a)return function(b){return"vec"+a+"("+b.join(",")+")"};var b=0;return function(c,e,f){return U(z.L(a),f)||"vec"+a+"("+H(a).map(function(a){return"vec"+a+"("+I(a).map(function(){return++b&&c[b-1]}).join(",")+")"}).join(",")+")"}}
function $a(a,b){return a==b&&2<=a&&4>=a?function(b){return"mat"+a+"("+I(a).map(function(e){return"vec"+a+"("+I(a).map(function(a){return b[a]+"["+e+"]"}).join(",")+")"}).join(",")}:function(c,e,f){return U(L(a,z.L(b)),f)||"cmat"+a+"_"+b+"("+c.join(",")+")"}}function ob(a){return function(b,c,e){return U(z.aa(a),e)||"cvec"+a+"("+Za(a)(b.map(function(a){return"("+a+").x"}),c,e)+","+Za(a)(b.map(function(a){return"("+a+").y"}),c,e)+")"}}
function pb(a){return function(b,c,e){U(z.L(a),e);c=Number(b[1])-1;if(2<=a&&4>=a)return"("+b[0]+")["+c+"]";var f;a:{e=H(a);for(f in e)if(e[f]<=c)c-=e[f];else{f={first:f,second:c};break a}console.error("Accessing index out of range");f=void 0}return"("+b[0]+").a"+f.first+"["+f.second+"]"}}function qb(a){return function(b,c,e){return"vec2("+pb(a)([b[0]+".real",b[1]],c,e)+","+pb(a)([b[0]+".imag",b[1]],c,e)+")"}}
function mb(a){return N(a)?V("*"):function(b,c,e){return lb(a,c,e)||"scalarmult"+S(a)+"("+b.join(",")+")"}}function rb(a){return function(b,c,e){return nb(a,c,e)||"cscalarmult"+S(a)+"("+b.join(",")+")"}};function L(a,b){return{type:"list",length:a,h:b}}var z={F:1,l:2,f:3,g:4,N:5,color:6,O:7,S:8,H:9,image:10,P:L(2,3),R:L(3,3),Y:L(4,3),L:function(a){return L(a,3)},aa:function(a){return L(a,4)},ma:L(2,L(2,3)),na:L(3,L(3,3)),oa:L(4,L(4,3)),da:18};Object.freeze(z);function D(a){return 1<=a&&10>=a?"bool int float complex voidt color point line coordinate2d image".split(" ")[a-1]:"list"===a.type?D(a.h)+"["+a.length+"]":JSON.stringify(a)}function P(a){return function(b){return y(a)+"("+b+")"}}
function V(a){return function(b){return"("+b.join(a)+")"}}function R(a){return a}var W={};W.join=O([[z.O,z.O],z.S,P("cross")]);W.meet=O([[z.S,z.S],z.O,P("cross")]);W["if"]=function(a){if(!a.every(function(a){return a}))return!1;if(2===a.length)return{m:a,s:a[1],o:function(a){return"if("+a[0]+") {"+a[1]+";}"}};if(3===a.length){var b=A(a[1],a[2]);return b?{m:[z.F,b,b],s:b,o:function(a){return"("+a[0]+" ? "+a[1]+" : "+a[2]+")"}}:{m:a,s:z.N,o:function(a){return"if("+a[0]+") {"+a[1]+";} else {"+a[2]+";}"}}}return!1};
W["="]=function(a){a=A(a[0],a[1]);return{m:a,s:a,o:function(a){return a[0]+" = "+a[1]+";"}}};W[";"]=function(a){return{m:a,s:a[1]!==z.N?a[1]:a[0],o:function(a){return a[0]+" ; "+a[1]+";"}}};W.repeat=function(a){return a[0]===z.l?{m:a,s:a[1],o:function(a){return a[0]+" ; "+a[1]+";"}}:!1};W.regional=function(a){return{m:a,s:z.N,o:function(){return""}}};W.sqrt=O([[[z.f],z.g,Q("sqrtf")],[[z.g],z.g,Q("sqrtc")]]);
W.abs=O([[[z.f],z.f,P("abs")],[[z.g],z.f,P("length")],[[z.P],z.f,P("length")],[[z.R],z.f,P("length")],[[z.Y],z.f,P("length")]]);W.abs_infix=W.abs;W.dist=O([[[z.f,z.f],z.f,function(a){return P("abs")(V("-")(a))}],[[z.g,z.g],z.f,function(a){return P("length")(V("-")(a))}],[[z.P,z.P],z.f,function(a){return P("length")(V("-")(a))}],[[z.R,z.R],z.f,function(a){return P("length")(V("-")(a))}],[[z.Y,z.Y],z.f,function(a){return P("length")(V("-")(a))}]]);W.dist_infix=W.dist;
W.sin=O([[[z.f],z.f,P("sin")],[[z.g],z.g,Q("sinc")]]);W.cos=O([[[z.f],z.f,P("cos")],[[z.g],z.g,Q("cosc")]]);W.tan=O([[[z.f],z.f,P("tan")],[[z.g],z.g,Q("tanc")]]);W.exp=O([[[z.f],z.f,P("exp")],[[z.g],z.g,Q("expc")]]);W.arctan=O([[[z.f],z.f,P("atan")],[[z.g],z.g,Q("arctanc")]]);W.log=O([[[z.f],z.g,Q("logr")],[[z.g],z.g,Q("logc")]]);var sb=[2,3,4].map(function(a){return L(a,z.f)}).concat([2,3,4].map(function(a){return L(a,L(a,z.f))})),tb=[z.l,z.f,z.g].concat(sb);
W.add=function(a){var b=O(tb.map(function(a){return[[a,a],a,V("+")]}))(a);if(b)return b;b=a[0];a=a[1];if([b,a].every(function(a){return E(a)||K(a)})&&Ta(b,a))return a=A(M(b),M(a)),{m:[a,a],s:a,o:hb(a)}};W.sub=function(a){var b=O(tb.map(function(a){return[[a,a],a,V("-")]}).concat(tb.map(function(a){return[[z.N,a],a,V("-")]})))(a);if(b)return b;b=a[0];a=a[1];if([b,a].every(function(a){return E(a)||K(a)})&&Ta(b,a))return a=A(M(b),M(a)),{m:[a,a],s:a,o:fb(a)}};W["+"]=W.add;W["-"]=W.sub;
W._=function(a){var b=a[0];return"list"===b.type&&C(b.h,z.f)&&C(a[1],z.l)?(a=M(b),{m:[a,z.l],s:z.f,o:pb(a.length)}):"list"===b.type&&C(b.h,z.g)&&C(a[1],z.l)?(a=Ua(b),{m:[a,z.l],s:z.g,o:qb(a.length)}):!1};
W.mult=function(a){var b=O([[[z.l,z.l],z.l,V("*")],[[z.f,z.f],z.f,V("*")],[[z.g,z.g],z.g,Q("multc")]])(a);if(b)return b;if(2!==a.length)return!1;var b=a[0],c=a[1];if([b,c].every(function(a){return"list"===a.type&&C(a.h,z.f)})&&b.length===c.length)return a=M(b),N(a)?{m:[a,a],s:z.f,o:P("dot")}:{m:[a,a],s:z.f,o:db(b.length)};if(E(b)&&2===F(b)&&E(c)&&1===F(c)&&b.h.length===c.length)return{m:[M(b),M(c)],s:z.L(b.length),o:gb(M(b))};if(K(b)&&2===F(b)&&K(c)&&1===F(c)&&b.h.length===c.length)return{m:[Ua(b),
Ua(c)],s:z.aa(b.length),o:gb(Ua(b))};for(b={C:0};2>b.C;b={W:b.W,C:b.C,Z:b.Z},b.C++){if(C(a[0^b.C],z.f)&&(E(a[1^b.C])||K(a[1^b.C])))return b.W=M(a[1^b.C]),{m:b.C?[b.W,z.f]:[z.f,b.W],s:b.W,o:function(a){return function(b,c,k){return mb(a.W)([b[0^a.C],b[1^a.C]],c,k)}}(b)};if(C(a[0^b.C],z.g)&&K(a[1^b.C]))return b.Z=Ua(a[1^b.C]),{m:b.C?[b.Z,z.g]:[z.g,b.Z],s:b.Z,o:function(a){return function(b,c,k){return rb(a.Z)([b[0^a.C],b[1^a.C]],c,k)}}(b)}}};W["*"]=W.mult;
W.div=function(a){var b=O([[[z.f,z.f],z.f,V("/")],[[z.g,z.g],z.g,Q("divc")]])(a);return b?b:C(a[1],z.f)&&K(a[0])&&(a=M(a[0]),N(a))?{m:[a,z.f],s:a,o:V("/")}:!1};W["/"]=W.div;W.re=O([[[z.g],z.f,Q("realc")]]);W.im=O([[[z.g],z.f,Q("imagc")]]);W.floor=O([[[z.f],z.l,function(a){return"int(floor("+a+"))"}],[[z.g],z.g,P("floor")]]);W.round=O([[[z.f],z.l,function(a){return"int(floor("+a+"+.5))"}],[[z.g],z.g,function(a){return"floor("+a+"+vec2(.5))"}]]);
W.ceil=O([[[z.f],z.l,function(a){return"int(ceil("+a+"))"}],[[z.g],z.g,P("ceil")]]);W.mod=O([[[z.l,z.l],z.l,function(a,b){return"int("+P("mod")("float("+a[0]+"), float("+a[1]+")",b)+")"}],[[z.f,z.f],z.f,P("mod")],[[z.g,z.g],z.g,Q("mod")]]);W.random=O([[[],z.f,Q("random")],[[z.f],z.f,function(a,b){return Q("random")([],b)+"*"+a[0]}],[[z.g],z.g,function(a,b){return"vec2("+Q("random")([],b)+","+Q("random")([],b)+")*"+a[0]}]]);
W.arctan2=O([[[z.f,z.f],z.f,function(a){return"atan("+a[1]+", "+a[0]+")"}],[[z.g,z.g],z.g,Q("arctan2c")],[[z.g],z.f,Q("arctan2vec2")],[[z.P],z.f,Q("arctan2vec2")],[[z.aa(2)],z.g,Q("arctan2cvec2")]]);["red","green","blue","gray","hue"].forEach(function(a){W[a]=O([[[z.f],z.R,Q(a)]])});W.grey=W.gray;W.min=O([[[z.l,z.l],z.l,P("min")],[[z.f,z.f],z.f,P("min")]]);W.max=O([[[z.l,z.l],z.l,P("max")],[[z.f,z.f],z.f,P("max")]]);W.complex=O([[[z.P],z.g,R]]);W.pow=O([[[z.f,z.l],z.f,Q("powi")],[[z.g,z.g],z.g,Q("powc")]]);
W["^"]=W.pow;W.re=O([[[z.g],z.f,function(a){return"("+a+").x"}]]);W.conjugate=O([[[z.g],z.g,Q("conjugate")]]);W.im=O([[[z.g],z.f,function(a){return"("+a+").y"}]]);W.genList=function(a){var b=a.length;return a.every(function(a){return C(a,z.f)})?{m:Array(b).fill(z.f),s:z.L(b),o:Za(b)}:a.every(function(a){return C(a,z.g)})?{m:Array(b).fill(z.g),s:z.aa(b),o:ob(b)}:!1};W["&"]=O([[[z.F,z.F],z.F,V("&&")]]);W["%"]=O([[[z.F,z.F],z.F,V("||")]]);
[">","<",">=","<=","=="].forEach(function(a){W[a]=O([[[z.l,z.l],z.F,V(a)],[[z.f,z.f],z.F,V(a)]])});W.imagergb=O([[[z.image,z.H],z.R,ub],[[z.H,z.H,z.image,z.H],z.R,vb]]);W.imagergba=O([[[z.image,z.H],z.Y,wb],[[z.H,z.H,z.image,z.H],z.Y,xb]]);Object.freeze(W);T.divc=["multc"];T.powc=["expc","multc","logc"];T.sqrtc=["expc","multc","logc"];T.arccosc=["multc","negc","sqrtc","addc","logc"];T.arcsinc=["multc","negc","sqrtc","addc","logc"];T.tanc=["sinc","cosc","divc"];T.arctanc=["logc","addc","multc","subc"];
T.arctan2c=["logc","divc","sqrtc","multc"];T.arctan2vec2c=["arctan2c"];T.hue=["hsv2rgb"];Object.freeze(T);function Ma(a){this.K={};this.B={};this.i={};this.D={};this.j={};this.ga=!1;this.w={};this.v=a;this.A={}}Ma.prototype.add=function(a,b,c){this.mark(a,b);this.j[a].ea[b]||(this.j[a].ea[b]=c(),this.j[a].ca[b]=!0,this.j[a].order.push(b))};Ma.prototype.mark=function(a,b){this.j[a]||(this.j[a]={order:[],ca:{},ea:{}});var c=this.j[a].ca[b]||!1;this.j[a].ca[b]=!0;return c};function yb(a,b){return a.j[b]?a.j[b].order.map(function(c){return a.j[b].ea[c]}).join("\n"):"\n"}
function X(a,b,c,e){if(Xa(c,e)||c===z.da)return b;if(C(c,e)){var f=Ya(e)([c]);if(!f)return console.error("cannot find an implementation for "+D(c)+" -> "+D(e)+", using identity"),b;e=f.o;return e(X(a,b,c,f.m[0]),{},a)}console.error(D(c)+" is no subtype of "+D(e)+" (trying to cast the term "+b+")");return b}
function zb(a,b,c){if(b.isuniform)return a.D[b.uvariable].type;if("variable"===b.ctype){var e=b.name;if("#"===e)return z.P;if(a.i.hasOwnProperty(c)&&a.i[c].hasOwnProperty(e))return a.i[c][e];if(a.i.hasOwnProperty("")&&a.i[""].hasOwnProperty(e))return a.i[""][e]}else if("function"===b.ctype&&a.w.hasOwnProperty(b.oper)){if(a.i.hasOwnProperty("")&&a.i[""].hasOwnProperty(b.oper))return a.i[""][b.oper]}else{if("number"===b.ctype)return 0!==b.value.imag?z.g:(b.value.real|0)===b.value.real?z.l:z.f;if("void"===
b.ctype)return z.N;if("field"===b.ctype)return z.f;if("string"===b.ctype)return z.image;for(var e=Array(b.args.length),f=0;f<b.args.length;f++)e[f]=Y(a,b.args[f],c);a=y(b.oper);c=W[a]?W[a](e):!1;!c&&e.every(function(a){return a})&&console.error("Could not find an implementation for "+a+" with args ("+e.map(D).join(", ")+")");return c?c.s:!1}return!1}function Y(a,b,c){a.ga&&b.hasOwnProperty("computedType")||(b.computedType=zb(a,b,c));return b.computedType}
function Ab(a,b){function c(a,b){e.hasOwnProperty(b)||(e[b]=[]);f.hasOwnProperty(b)||(f[b]={});for(var l in a.args)c(a.args[l],b);if("="===a.oper){var n=a.args[0].name;l=b;-1===e[b].indexOf(n)&&(l="",-1===e[l].indexOf(n)&&(e[l].push(n),f[l][n]=[]));f[l][n].push({J:a.args[1],fa:b})}else if(a.oper&&"regional"===y(a.oper))for(n=0;n<a.args.length;n++)"variable"===a.args[n].ctype&&(l=a.args[n].name,-1===e[b].indexOf(l)&&(e[b].push(l),f[b][l]=[]));else if("function"===a.ctype&&g.hasOwnProperty(a.oper)){l=
a.oper;e.hasOwnProperty(l)||(e[l]=[]);f.hasOwnProperty(l)||(f[l]={});for(n in g[l].arglist){var t=g[l].arglist[n].name;e[l].push(t);f[l].hasOwnProperty(t)||(f[l][t]=[]);f[l][t].push({J:a.args[n],fa:b})}g[l].la||(g[l].la=!0,c(g[l].body,l));-1===e[""].indexOf(l)&&(e[""].push(l),f[""][l]=[{J:g[l].body,fa:l}])}}var e={},f={},g=a.w;c(b,"");a.K=e;a.B=f}
function Bb(a,b){function c(a,b){if(a.hasOwnProperty("dependsOnPixel")&&!0===a.dependsOnPixel)return!0;if("variable"===a.ctype){var e=a.name;return f.hasOwnProperty(b)&&f[b][e]||-1===g[b].indexOf(e)&&f.hasOwnProperty("")&&f[""][e]?a.dependsOnPixel=!0:a.dependsOnPixel=!1}e=["random","verbatimglsl"];if("function"===a.ctype&&-1!=e.indexOf(y(a.oper)))return a.dependsOnPixel=!0;for(var l in a.args)if(c(a.args[l],b))return a.dependsOnPixel=!0;return"function"===a.ctype&&k.hasOwnProperty(a.oper)&&(e=a.oper,
f.hasOwnProperty(e)||(f[e]={}),c(k[e].body,e))?a.dependsOnPixel=!0:"field"===a.ctype?a.dependsOnPixel=c(a.obj,b):!1}function e(a,b){if(c(a,b)){for(var f in a.args)e(a.args[f],b);"field"===a.ctype&&e(a.obj,b);"function"===a.ctype&&k.hasOwnProperty(a.oper)&&(a=a.oper,n.hasOwnProperty(a)||(n[a]=!0,e(k[a].body,a)))}else if("number"!==a.ctype&&"void"!==a.ctype){b=!1;var g,l;for(l in t)!b&&pa(a,t[l].J)&&(b=!0,g=l);b||(g=sa(),t[g]={J:a,type:!1});a.isuniform=!0;a.uvariable=g}}var f={"":{"#":!0}},g=a.K,k=
a.w,m;for(m in a.B)for(var l in a.B[m])f.hasOwnProperty(m)||(f[m]={}),f[m][l]=!0;c(b,"");var n={"":!0},t={};e(b,"");a.D=t}function Cb(a,b){if("function"===b.ctype&&!a.w.hasOwnProperty(b.oper)&&null!==a.v.getMyfunction(b.oper)){var c=b.oper;a.w[c]=oa(a.v.getMyfunction(c));Cb(a,a.w[c].body)}for(var e in b.args)Cb(a,b.args[e])}
function Z(a,b,c,e){if(b.isuniform){b=b.uvariable;var f=a.D[b].type;return e?{code:"",u:b,type:f}:{code:""}}if(";"===b.oper){for(var f={type:z.N,u:""},g="",k=b.args.length-1,m=k;0<=m;m--)"void"===b.args[m].ctype&&k--;for(m=0;m<=k;m++)f=Z(a,b.args[m],c,e&&m===k),g+=f.code;return e?{code:g,u:f.u,type:f.type}:{code:g}}if("="===b.oper)return f=Z(a,b.args[1],c,!0),g=b.args[0].name,b=g+" = "+X(a,f.u,f.type,Y(a,b.args[0],c)),e?{code:f.code,u:b,type:a.i[c][g]}:{code:f.code+b+";\n"};if("repeat$2"===b.oper){if("number"!==
b.args[0].ctype)return console.error("repeat possible only for fixed constant number in GLSL"),!1;f=sa();g=b.args[0].value.real|0;b=Z(a,b.args[1],c,e);m=k="";e&&(m=sa(),k+=S(b.type)+" "+m+";");k=k+("for(int "+f+"=0; "+f+" < "+g+"; "+f+"++) {\n")+b.code;e&&(k+=m+" = "+b.u+";\n");k+="}\n";return e?{code:k,u:m,type:b.type}:{code:k}}if("repeat$3"===b.oper)console.error("TODO");else{if("if$2"===b.oper||"if$3"===b.oper){var m=Z(a,b.args[0],c,!0),l=Z(a,b.args[1],c,e),g=f="",k=Y(a,b,c);e&&(g=sa(),f+=S(k)+
" "+g+";");f+=m.code;f+="if("+m.u+") {\n";f+=l.code;e&&(f+=g+" = "+X(a,l.u,l.type,k)+";\n");"if$3"===b.oper&&(b=Z(a,b.args[2],c,e),f=f+"} else {\n"+b.code,e&&(f+=g+" = "+X(a,b.u,b.type,k)+";\n"));f+="}\n";return e?{code:f,u:g,type:k}:{code:f}}if("function"===b.ctype||"infix"===b.ctype){l=b.oper;if("verbatimglsl"===y(l))return b=a.v.evaluateAndVal(b.args[0]).value,e?{u:b,type:z.da,code:""}:{code:b};f=b.args.map(function(b){return Z(a,b,c,!0)});g=f.map(function(a){return a.type});if(a.w.hasOwnProperty(l)){for(var m=
Db(a,l),k=Array(f.length),n=0;n<f.length;n++)k[n]=a.i[l][a.w[l].arglist[n].name];l=a.i[""][l]}else{l=y(l);if("regional"===l)return e?{u:"",type:z.N,code:""}:{code:""};m=W[l](g);if(!m)return console.error("Could not find an implementation for "+l+"("+g.map(D).join(", ")+").\nReturning empty code"),e?{u:"",type:z.N,code:""}:{code:""};k=m.m;l=m.s;m=m.o}for(var n="",t=Array(f.length),x=0;x<f.length;x++)n+=f[x].code,t[x]=X(a,f[x].u,g[x],k[x]);b=m(t,b.modifs,a);return e?{u:b,type:l,code:n}:{code:n+b+";\n"}}if("number"===
b.ctype)return f=Y(a,b,c),f===z.l?g=b.value.real|0:f===z.f?g=b.value.real:f===z.g&&(g="vec2( "+b.value.real+", "+b.value.imag+")"),e?{u:g,type:f,code:""}:{code:f+";\n"};if("string"===b.ctype)return console.error("Cannot compile strings to WebGL."),!1;if("variable"===b.ctype)return f=Y(a,b,c),b=b.name,"#"===b&&(b="cgl_pixel"),e?{u:b,type:f,code:""}:{code:b+";\n"};if("void"===b.ctype)return e?{u:"",type:z.N,code:""}:{code:""};if("field"===b.ctype)return f=Y(a,b,c),g=Z(a,b.obj,c,!0).u,g+="."+b.key,e?
{u:g,type:f,code:""}:{code:g+";\n"}}console.error("dont know how to this.compile "+JSON.stringify(b))}function Db(a,b){Eb(a,b,a.w[b].arglist.length);return P(b)}
function Eb(a,b,c){if(!a.mark("compiledfunctions",b)){for(var e=a.w[b],f=Array(c),g=0;g<c;g++)f[g]=e.arglist[g].name;c=a.i[""][b]===z.N;var k=S(a.i[""][b])+" "+y(b)+"("+f.map(function(c){return S(a.i[b][c])+" "+c}).join(", ")+"){\n",m;for(m in a.K[b]){for(var g=!0,l=a.K[b][m],n=0;n<f.length;n++)g&=l!==f[n];g&&(k+=S(a.i[b][l])+" "+l+";\n")}e=Z(a,e.body,b,!c);k+=e.code;c||(k+="return "+X(a,e.u,e.type,a.i[""][b])+";\n");k+="}\n";a.add("compiledfunctions",b,function(){return k})}}
function La(a,b){ra=0;var c=b=oa(b);a.ga=!1;Cb(a,c);Ab(a,c);Bb(a,c);for(var e in a.D)a.D[e].type=z.f,c=a.v.evaluateAndVal(a.D[e].J),a.D[e].type=qa(c),console.log("guessed type "+D(a.D[e].type)+" for "+(a.D[e].J.name||a.D[e].J.oper));e=!0;for(var f in a.B){a.i[f]={};for(var g in a.B[f])a.i[f][g]=!1}for(;e;){e=!1;for(var k in a.B)for(var m in a.B[k])for(var l in a.B[k][m])f=Y(a,a.B[k][m][l].J,a.B[k][m][l].fa),g=!1,a.i.hasOwnProperty(k)&&a.i[k].hasOwnProperty(m)&&(g=a.i[k][m]),c=g,f&&(g?C(f,g)?c=g:c=
A(g,f):c=f,c&&c!==g&&(a.i.hasOwnProperty(k)||(a.i[k]={}),a.i[k][m]=c,console.log("variable "+m+" in scope "+k+" got type "+D(c)+" (oltype/othertype is "+D(g)+"/"+D(f)+")"),e=!0))}a.ga=!0;b=Z(a,b,"",!0);k=X(a,b.u,b.type,z.color);C(b.type,z.color)||console.error("expression does not generate a color");m=yb(a,"structs");l=[];for(var n in a.D)a.D[n].type!=z.image&&l.push("uniform "+S(a.D[n].type)+" "+n+";");m+=l.join("\n");n="";for(var t in a.A)for(var x in a.A[t])n+=a.A[t][x].code+"\n";m=m+n+yb(a,"functions");
m+=yb(a,"includedfunctions");for(var J in a.K[""])t=a.K[""][J],a.w.hasOwnProperty(t)||(m+=S(a.i[""][t])+" "+t+";\n");m+=yb(a,"compiledfunctions");m+="void main(void) {\n"+b.code+"gl_FragColor = "+k+";\n}\n";console.log(m);J={};if(a.j.compiledfunctions)for(var G in a.j.compiledfunctions.ca)J[G]=a.v.getMyfunction(G).generation;return{code:m,D:a.D,A:a.A,ba:J}};function Fb(a,b,c,e){this.J=b;this.v=e;this.U=c;this.name=a;this.code="uniform sampler2D _sampler"+a+";\nuniform float _ratio"+a+";\nuniform vec2 _cropfact"+a+";\nuniform bool _repeat"+a+";\nuniform bool _mipmap"+a+";\nvec4 _imagergba"+a+" (vec2 A, vec2 B, vec2 p) {\n  p -= A; B -= A;\n  float b = dot(B,B);\n  p = vec2(dot(p,B),_ratio"+a+"*dot(p,vec2(-B.y,B.x)))/b;\n  if(_repeat"+a+") p = mod(p, vec2(1.));\n  if(_repeat"+a+" && _mipmap"+a+") {\n    vec4 color = vec4(0.);\n    float totalWeight = 0.;\n    for(int dx=0; dx<2; dx++) for(int dy=0; dy<2; dy++) {\n      vec2 delta = .5*vec2(dx, dy);\n      vec2 center = delta+vec2(.5);\n      vec2 tc = fract(p-delta)+delta;\n      float dst = dot(abs(tc-center),vec2(1.));\n      float w = max(.5-dst,0.);\n      w=w*w;\n      color += w * texture2D(_sampler"+
a+", tc*_cropfact"+a+");\n      totalWeight += w;\n    }\n    return color/totalWeight;\n  }\n  if(0. <= p.x && p.x <= 1. && 0. <= p.y && p.y <= 1.)\n    return texture2D(_sampler"+a+", p*_cropfact"+a+");\n  else\n    return vec4(0.);\n  }"}function Pa(a,b){var c=a.v.evaluateAndVal(a.J).value;a="string"===typeof c?a.v.getImage(c,!0):c;return null==a?(console.error("Could not find image "+c+"."),r):Ea(a,b)}
function Gb(a,b,c){c.A.hasOwnProperty(a)||(c.A[a]=[]);var e=c.A[a].length,f;for(f in c.A[a])if(e==c.A[a].length){var g=c.A[a][f].U,k=!0,m;for(m in["interpolation","mipmap","repeat"])k&&(pa(g,b)||(k=!1));k&&(e=f)}f=a+"_"+e;e==c.A[a].length&&c.A[a].push(new Fb(f,c.D[a].J,b,c.v));return f}function xb(a,b,c){return["_imagergba",Gb(a[2],b,c),"(",a[0],",",a[1],",",a[3],")"].join("")}function vb(a,b,c){return["(_imagergba",Gb(a[2],b,c),"(",a[0],",",a[1],",",a[3],").rgb)"].join("")}
function wb(a,b,c){var e=va(c.v),f=wa(c.v);return["_imagergba",Gb(a[0],b,c),"(vec2(",e.x,",",e.y,"),vec2(",f.x,",",f.y,"), ",a[1],")"].join("")}function ub(a,b,c){var e=va(c.v),f=wa(c.v);return["(_imagergba",Gb(a[0],b,c),"(vec2(",e.x,",",e.y,"),vec2(",f.x,",",f.y,"), ",a[1],").rgb)"].join("")};function Hb(a){var b;b=b?b:null;return"list"!==a.ctype?(console.log("argument is not a list"),b):a.value}function Ra(a){var b;b=b?b:[.5,.5,.5];if("number"===a.ctype){var c=Ib(a);if(!isNaN(c))return[c,c,c]}a=Hb(a);return a?3!=a.length?(console.log("Not an RGB color vector"),b):a.map(function(a){return Ib(a)}):b}
function Qa(a){var b;b=void 0===b?Number.NaN:b;if("number"!==a.ctype)return console.log("argument is not a number"),b;b=a.value;a=b.real;b=b.imag;0!==b&&console.log("complex number is not real");b=Math.round(a);b!==a&&console.log("number is not an integer");return b}
function Ib(a){var b;b=void 0===b?Number.NaN:b;b=void 0===b?Number.NaN:b;"number"!==a.ctype?(console.log("argument is not a number"),a=b):(a=a.value,b=a.real,0!==a.imag&&console.log("complex number is not real"),a=b);return 0>a?0:1<a?1:a};function w(a){this.i=a}w.prototype.toString=function(){return this.i};
function Ha(a,b){var c=q;this.i=c.createProgram();this.W=Jb(this,c,c.VERTEX_SHADER,a);Jb(this,c,c.FRAGMENT_SHADER,b);a=this.i;c.linkProgram(a);if(!c.getProgramParameter(a,c.LINK_STATUS))throw new w("Error linking shader:\n"+c.getProgramInfoLog(a));c.validateProgram(a);if(!c.getProgramParameter(a,c.VALIDATE_STATUS))throw new w("Error validating shader:\n"+c.getProgramInfoLog(a));var e=this.i,f,g,k,m={},l,n,t,x;b=c.getProgramParameter(e,c.ACTIVE_UNIFORMS);for(a=0;a<b;++a)if(f=c.getActiveUniform(e,a))if(g=
f.name.replace(/\]/g,"")){for(l=m;k=/[.\[]/.exec(g);)n=g.substr(0,k.index),l.hasOwnProperty(n)?l=l[n]:"."===k[0]?l=l[n]={}:l=l[n]=[],g=g.substr(k.index+1);if(1<f.size){k=f.size;x=Array(k);for(n=0;n<k;++n)t=f.name+"["+n+"]",t=Kb(this,c,t,f),x[n]=t;l[g]=x}else t=Kb(this,c,f.name,f),l[g]=t}this.j=m}
function Jb(a,b,c,e){c=b.createShader(c);b.shaderSource(c,e);b.compileShader(c);if(!b.getShaderParameter(c,b.COMPILE_STATUS))throw console.warn(e.split("\n")),new w("Error compiling shader:\n"+b.getShaderInfoLog(c));b.attachShader(a.i,c);return c}
function Kb(a,b,c,e){a=b.getUniformLocation(a.i,c);switch(e.type){case b.FLOAT:return b.uniform1fv.bind(b,a);case b.FLOAT_VEC2:return b.uniform2fv.bind(b,a);case b.FLOAT_VEC3:return b.uniform3fv.bind(b,a);case b.FLOAT_VEC4:return b.uniform4fv.bind(b,a);case b.BOOL:case b.INT:case b.SAMPLER_2D:case b.SAMPLER_CUBE:return b.uniform1iv.bind(b,a);case b.BOOL_VEC2:case b.INT_VEC2:return b.uniform2iv.bind(b,a);case b.BOOL_VEC3:case b.INT_VEC3:return b.uniform3iv.bind(b,a);case b.BOOL_VEC4:case b.INT_VEC4:return b.uniform4iv.bind(b,
a);case b.FLOAT_MAT2:return b.uniformMatrix2fv.bind(b,a,!1);case b.FLOAT_MAT3:return b.uniformMatrix3fv.bind(b,a,!1);case b.FLOAT_MAT4:return b.uniformMatrix4fv.bind(b,a,!1);default:throw new w("Unknown data type for uniform "+c);}};
}).call(this);//# sourceMappingURL=CindyGL.js.map


