(function(){
'use strict';var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},d="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function ba(a,b){if(b){var c=d;a=a.split(".");for(var e=0;e<a.length-1;e++){var f=a[e];f in c||(c[f]={});c=c[f]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}
ba("String.prototype.repeat",function(a){return a?a:function(a){if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");var b=this;if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var e="";a;)if(a&1&&(e+=b),a>>>=1)b+=b;return e}});function ca(){ca=function(){};d.Symbol||(d.Symbol=da)}var da=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function ea(){ca();var a=d.Symbol.iterator;a||(a=d.Symbol.iterator=d.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(this)}});ea=function(){}}function fa(a){var b=0;return ha(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ha(a){ea();a={next:a};a[d.Symbol.iterator]=function(){return this};return a}
ba("Array.from",function(a){return a?a:function(a,c,e){ea();c=null!=c?c:function(a){return a};var b=[],g=a[Symbol.iterator];if("function"==typeof g)for(a=g.call(a);!(g=a.next()).done;)b.push(c.call(e,g.value));else{g=a.length;for(var k=0;k<g;k++)b.push(c.call(e,a[k]))}return b}});
function ia(a,b){ea();a instanceof String&&(a+="");var c=0,e={next:function(){if(c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e}ba("Array.prototype.keys",function(a){return a?a:function(){return ia(this,function(a){return a})}});
ba("Array.prototype.fill",function(a){return a?a:function(a,c,e){var b=this.length||0;0>c&&(c=Math.max(0,b+c));if(null==e||e>b)e=b;e=Number(e);0>e&&(e=Math.max(0,b+e));for(c=Number(c||0);c<e;c++)this[c]=a;return this}});
var ja={addc:"vec2 addc(vec2 a,vec2 b){\nreturn a+b;\n}\n",addpoints:"vec2 addpoints(vec3 a,vec3 b){\nreturn dehomogenize(a) +dehomogenize(b);\n}\n",arccosc:"vec2 arccosc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=addc(multc(logc(tmp1),vec2(0.0,1.0)),vec2(pi*0.5,0.0));\nreturn erg;\n}\n",arccosf:"vec2 arccosf(float z){\nif(abs(z)<=1.)return vec2(acos(z),0.);\nelse if(z>1.)return vec2(0,log(z+sqrt(z*z-1.)));\nelse return vec2(pi, -log(-z+sqrt(z*z-1.)));\n}\n",
arcsinc:"vec2 arcsinc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=multc(logc(tmp1),vec2(0.0,-1.0));\nreturn erg;\n}\n",arcsinf:"vec2 arcsinf(float z){\nif(abs(z)<=1.)return vec2(asin(z),0.);\nelse if(z>1.)return vec2(pi*.5, -log(z+sqrt(z*z-1.)));\nelse return vec2(-pi*.5,log(-z+sqrt(z*z-1.)));\n}\n",arctan2c:"\n\n\n\nvec2 arctan2c(vec2 x,vec2 y){\nvec2 r=logc(divc(x+vec2(-y.y,y.x),sqrtc(multc(x,x)+multc(y,y))));\nreturn vec2(r.y, -r.x);\n}\n",
arctan2cvec2:"vec2 arctan2cvec2(cvec2 v){\nreturn arctan2c(v.real,v.imag);\n}\n",arctan2vec2:"float arctan2vec2(vec2 v){\nreturn atan(v.y,v.x);\n}\n",arctanc:"vec2 arctanc(vec2 a){\nvec2 t1=logc(addc(multc(a,vec2(0.0,-1.0)),vec2(1.0,0.0)));\nvec2 t2=logc(addc(multc(a,vec2(0.0,1.0)),vec2(1.0,0.0)));\nvec2 erg=multc(subc(t1,t2),vec2(0.0,0.5));\nreturn erg;\n}\n",blue:"vec3 blue(float f)\n{\nreturn vec3(0.,0.,clamp(f,0.,1.));\n}\n",cimag:"float imagc(vec2 a){\nreturn a.y;\n}\n",conjugate:"vec2 conjugate(vec2 a){\nreturn vec2(a.x, -a.y);\n}\n",
copytexture_f:"#ifdef GL_ES\nprecision highp float;\n#endif\n\nuniform sampler2D sampler;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_FragColor=texture2D(sampler,cgl_pixel);\n}\n",copytexture_v:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_Position=vec4(aPos,1.);\ncgl_pixel=aTexCoord;\n}\n",cosc:"vec2 cosc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat i= (imag1+imag2) /2.0;\nfloat r= (real1+real2) /2.0;\n\nreturn vec2(r,i);\n}\n",
creal:"float realc(vec2 a){\nreturn a.x;\n}\n",dehomogenize:"vec2 dehomogenize(vec3 z){\nreturn vec2(z.x,z.y)/z.z;\n}\n",dehomogenizex:"float dehomogenizex(vec3 z){\nreturn z.x/z.z;\n}\n",dehomogenizey:"float dehomogenizey(vec3 z){\nreturn z.y/z.z;\n}\n",det2:"float det2(mat2 a){\nreturn a[0][0]*a[1][1] -a[0][1]*a[1][0];\n}\n",det3:"float det3(mat3 a){\nreturn dot(cross(a[0],a[1]),a[2]);\n}\n",det3v:"float det3v(vec3 a,vec3 b,vec3 c){\nreturn dot(cross(a,b),c);\n}\n",det4:"float det4(mat4 a){\nfloat s00=a[0][0]*a[1][1] -a[0][1]*a[1][0],\ns01=a[0][0]*a[1][2] -a[0][2]*a[1][0],\ns02=a[0][0]*a[1][3] -a[0][3]*a[1][0],\ns03=a[0][1]*a[1][2] -a[0][2]*a[1][1],\ns04=a[0][1]*a[1][3] -a[0][3]*a[1][1],\ns05=a[0][2]*a[1][3] -a[0][3]*a[1][2],\ns06=a[2][0]*a[3][1] -a[2][1]*a[3][0],\ns07=a[2][0]*a[3][2] -a[2][2]*a[3][0],\ns08=a[2][0]*a[3][3] -a[2][3]*a[3][0],\ns09=a[2][1]*a[3][2] -a[2][2]*a[3][1],\ns10=a[2][1]*a[3][3] -a[2][3]*a[3][1],\ns11=a[2][2]*a[3][3] -a[2][3]*a[3][2];\nreturn s00*s11-s01*s10+s02*s09+s03*s08-s04*s07+s05*s06;\n}\n",
divc:"vec2 divc(vec2 a,vec2 b){\nreturn vec2(dot(a,b),dot(a,vec2(-b.y,b.x)))/dot(b,b);\n}\n",divfc:"vec2 divfc(float a,vec2 b){\nreturn a*vec2(b.x,-b.y)/dot(b,b);\n}\n",expc:"vec2 expc(vec2 a){\nfloat n=exp(a.x);\nfloat r=n*cos(a.y);\nfloat i=n*sin(a.y);\nreturn vec2(r,i);\n}\n",float2color:"vec4 float2color(float f)\n{\nreturn vec4(f,f,f,1.);\n}\n",gray:"vec3 gray(float f)\n{\nf=clamp(f,0.,1.);\nreturn vec3(f,f,f);\n}\n",green:"vec3 green(float f)\n{\nreturn vec3(0.,clamp(f,0.,1.),0.);\n}\n",hsv2rgb:"vec3 hsv2rgb(vec3 c)\n{\nvec4 K=vec4(1.0,2.0/3.0,1.0/3.0,3.0);\nvec3 p=abs(fract(c.xxx+K.xyz) *6.0-K.www);\nreturn c.z*mix(K.xxx,clamp(p-K.xxx,0.0,1.0),c.y);\n}\n",
hue:"vec3 hue(float a){\nreturn hsv2rgb(vec3(a,1.,1.));\n}\n",imagc:"float imagc(vec2 a){\nreturn a.y;\n}\n",invc:"vec2 invc(vec2 a){\nfloat n=a.x*a.x+a.y*a.y;\nreturn vec2(a.x/n,-a.y/n);\n}\n",logc:"vec2 logc(vec2 a){\nfloat re=a.x;\nfloat im=a.y;\nfloat s=sqrt(re*re+im*im);\nfloat i=im;\nfloat imag=atan(im,re);\nif(i<0.0){\nimag+= (2.0*pi);\n}\nif(i==0.0&&re<0.0){\nimag=pi;\n}\nif(imag>pi){\nimag-= (2.0*pi);\n};\nfloat real=log(s);\n\nreturn vec2(real,imag);\n}\n",logr:"vec2 logr(float a){\nif(a>=0.)return vec2(log(a),0);\nelse return vec2(log(-a),pi);\n}\n",
mat2complex:"mat4 mat2complex(mat2 a)\n{\nreturn mat4(\nvec4(a[0][0],0,a[0][1],0),\nvec4(0,a[0][0],0,a[0][1]),\nvec4(a[1][0],0,a[1][1],0),\nvec4(0,a[1][0],0,a[1][1])\n);\n}\n",multc:"vec2 multc(vec2 a,vec2 b){\nreturn vec2(dot(a,vec2(b.x,-b.y)),dot(a,b.yx));\n}\n",negc:"vec2 negc(vec2 a){\nreturn vec2(-a.x,-a.y);\n}\n",powc:"vec2 powc(vec2 a,vec2 b){\nreturn(b.x==0. &&b.y==0.) ?vec2(1.,0.) : ((a.x==0. &&a.y==0.) ?vec2(0.) :expc(multc(logc(a),b)));\n}\n",powi:"float powi(float a,int b){\nif(mod(float(b),2.) < .5)\nreturn pow(abs(a),float(b));\nelse\nreturn sign(a)*pow(abs(a),float(b));\n}\n",
random:"uniform float rnd_;\n\nfloat last_rnd= .1231;\nfloat random(){\nfloat a=fract(132422.21*sin(dot(plain_pixel,343433.671228*vec2(.176574+last_rnd, .1131+rnd_))));\nfloat b=fract(last_rnd*2321.2312*sin(dot(plain_pixel+vec2(rnd_,last_rnd),plain_pixel) *43758.5453));\nlast_rnd=fract(rnd_ +last_rnd+a+b);\nreturn last_rnd;\n}\n",randomnormal:"float randomnormal(){\nreturn sqrt(-2. *log(random())) *cos(6.283185307179586*random());\n}\n",realc:"float realc(vec2 a){\nreturn a.x;\n}\n",red:"vec3 red(float f)\n{\nreturn vec3(clamp(f,0.,1.),0.,0.);\n}\n",
rgb2hsv:"vec3 rgb2hsv(vec3 c)\n{\nvec4 K=vec4(0.0, -1.0/3.0,2.0/3.0, -1.0);\nvec4 p=mix(vec4(c.bg,K.wz),vec4(c.gb,K.xy),step(c.b,c.g));\nvec4 q=mix(vec4(p.xyw,c.r),vec4(c.r,p.yzx),step(p.x,c.r));\n\nfloat d=q.x-min(q.w,q.y);\nfloat e=1.0e-10;\nreturn vec3(abs(q.z+ (q.w-q.y) / (6.0*d+e)),d/ (q.x+e),q.x);\n}\n",sinc:"\n\nvec2 sinc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat r= -(imag1-imag2) /2.0;\nfloat i= (real1-real2) /2.0;\n\nreturn vec2(r,i);\n}\n",
sqrtc:"vec2 sqrtc(vec2 a){\nreturn expc(multc(logc(a),vec2(0.5,0.0)));\n}\n",sqrtf:"vec2 sqrtf(float a){\nif(a>=0.)return vec2(sqrt(a),0.);\nelse return vec2(0.,sqrt(-a));\n}\n",standardFragmentHeader:"#ifdef GL_ES\nprecision highp float;\nprecision highp int;\n#endif\n\n#define pi 3.141592653589793\n\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\n",subc:"vec2 subc(vec2 a,vec2 b){\nreturn a-b;\n}\n",subpoints:"vec2 subpoints(vec3 a,vec3 b){\nreturn dehomogenize(a) -dehomogenize(b);\n}\n",tanc:"vec2 tanc(vec2 a){\nvec2 s=sinc(a);\nvec2 c=cosc(a);\nreturn divc(s,c);\n}\n",
vec2complex:"vec4 vec2complex(vec2 a)\n{\nreturn vec4(a.x,0.,a.y,0);\n}\n",vshader:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\nuniform mat3 transformMatrix;\nvoid main(void){\ngl_Position=vec4(aPos,1.);\nplain_pixel=aTexCoord;\nvec3 r=transformMatrix*vec3(plain_pixel,1);\ncgl_pixel=r.xy/r.z;\n}\n"};var ka=!1,h,m,n,la,r,t,w=!1,ma,x=!1,pa=!1,qa=1;
function ra(){function a(c){h.removeEventListener("webglcontextcreationerror",a,!1);c.statusMessage&&(b=c.statusMessage)}if(!ka){h=document.createElement("canvas");h.id="glcanvas";h.style.display="none";h.width=h.height=0;document.body.appendChild(h);m=document.createElement("canvas");m.id="tmpcanvas";m.style.display="none";m.width=m.height=0;document.body.appendChild(m);n=document.createElement("canvas");n.id="dummycanvas";n.style.display="none";n.width=n.height=1;document.body.appendChild(n);la=
{ctype:"image",value:{img:n,width:1,height:1,ready:!0,live:!1,generation:0,whenReady:function(){}}};var b="Unknown";h.addEventListener("webglcontextcreationerror",a,!1);(r=h.getContext("webgl"))||(r=h.getContext("experimental-webgl"));if(!r)throw new sa("Could not obtain a WebGL context.\nReason: "+b);h.removeEventListener("webglcontextcreationerror",a,!1);pa||(x=r.getExtension("OES_texture_float")&&r.getExtension("OES_texture_float_linear"),x||(console.error("Your browser does not suppert OES_texture_float, trying OES_texture_half_float..."),
(w=(ma=r.getExtension("OES_texture_half_float"))&&r.getExtension("OES_texture_half_float_linear"))||console.error("Your browser does not suppert OES_texture_half_float, will use 8-bit textures.")),navigator.userAgent.match(/(iPad|iPhone)/i)&&(console.log("You are  using an iPhone/iPad."),x=w=!1,r.getExtension("OES_texture_half_float")&&r.getExtension("OES_texture_half_float_linear")&&r.getExtension("EXT_color_buffer_half_float")?w=!0:console.error("Your browser does not suppert writing to half_float textures, we will use 8-bit textures.")));
ka=!0}};function ta(a){if(null==a||"object"!=typeof a)return a;if(a instanceof Array){var b=[];for(var c=0,e=a.length;c<e;c++)b[c]=ta(a[c]);return b}if(a instanceof Object){b={};for(c in a)a.hasOwnProperty(c)&&(0<="oper impl args ctype stack name arglist value real imag key obj body".split(" ").indexOf(c)&&(b[c]=ta(a[c])),a.modifs&&(b.modifs=a.modifs));return b}}
function ua(a,b){if(null==a||"object"!=typeof a)return a===b;if(a instanceof Array&&b instanceof Array){if(a.length!=b.length)return!1;for(var c=0,e=a.length;c<e;c++)if(!ua(a[c],b[c]))return!1;return!0}if(a instanceof Object&&b instanceof Object){c="oper impl args ctype stack name modifs arglist value real imag key obj body".split(" ");for(e=0;e<c.length;e++){var f=c[e];if(!ua(a[f],b[f]))return!1}return!0}return!1}function va(a){return-1===a.indexOf("$")?a:a.substr(0,a.indexOf("$"))}
function wa(a){if("boolean"===a.ctype)return y.B;if("number"===a.ctype)return a=a.value,1E-5>Math.abs(a.imag)?(a.real|0)===a.real?y.v:y.f:y.h;if("list"===a.ctype){var b=a.value;if(3===b.length){if("Point"===a.usage)return y.A;if("Line"===a.usage)return y.line}if(0<b.length){for(var c=wa(b[0]),e=1;e<b.length;e++)c=z(c,wa(b[e]));if(c)return{type:"list",length:b.length,parameters:c}}}else{if("string"===a.ctype||"image"===a.ctype)return y.image;if("geo"===a.ctype&&"L"===a.value.kind)return y.line}console.error("Cannot guess type of the following type:");
console.log(a);return!1}var xa=0;function ya(){xa++;return"_h"+xa}function za(a,b){if(a>h.width||b>h.height)h.width=Math.ceil(a),h.height=Math.ceil(b)}function Aa(a,b,c){a=a.getInitialMatrix();b-=a.tx;c+=a.ty;return{x:(b*a.d-c*a.b)/a.det,y:-(-b*a.c+c*a.a)/a.det}}function Ba(a){return Aa(a,0,a.instance.canvas.clientHeight)}function Ca(a){return Aa(a,a.instance.canvas.clientWidth,a.instance.canvas.clientHeight)}var Da=new Float32Array(1),Ea=new Int32Array(Da.buffer);
function Fa(a){Da[0]=a;a=Ea[0];var b=a>>16&32768,c=(a&2147483647)+4096;if(1199570944<=c)return 1199570944<=(a&2147483647)?2139095040>c?b|31744:b|31744|(a&8388607)>>13:b|31743;if(947912704<=c)return b|c-939524096>>13;if(855638016>c)return b;c=(a&2147483647)>>23;return b|(a&8388607|8388608)+(8388608>>>c-102)>>126-c}
function Ga(a){if(x)return new Float32Array(a);if(w){for(var b=new Uint16Array(a.length),c=0;c<a.length;c++)b[c]=Fa(a[c]);return b}b=new Uint8Array(a.length);for(c=0;c<a.length;c++)b[c]=255*a[c];return b}function Ha(a){return x?new Float32Array(a):w?new Uint16Array(a):new Uint8Array(a)}function Ia(){return x?r.FLOAT:w?ma.HALF_FLOAT_OES:r.UNSIGNED_BYTE}
function Ja(a){for(var b=[],c=0;c<a.length;c++)if(x)b.push(a[c]);else if(w){var e=a[c],f=(e&31744)>>10,g=e&1023;b.push((e>>15?-1:1)*(f?31===f?g?NaN:Infinity:Math.pow(2,f-15)*(1+g/1024):g/1024*6.103515625E-5))}else b.push(a[c]/255);return b}function Ka(a){for(var b=1;b<a;)b<<=1;return b};function La(a,b,c){if(a.canvaswrapper){if(!a.ready||a.canvaswrapper.canvas!=la&&a.canvaswrapper.L==a.width&&a.canvaswrapper.G==a.height||(delete a.canvaswrapper,a.canvaswrapper=La(a,b,c)),c){b=a.canvaswrapper;var e=b.i;if(c&&(c.repeat!=e.repeat||c.N!=e.N||c.S!=e.S))for(b.i=c,e=0;2>e;e++)r.bindTexture(r.TEXTURE_2D,b.l[e]),c.N?r.texParameteri(r.TEXTURE_2D,r.TEXTURE_MIN_FILTER,c.S?r.LINEAR_MIPMAP_LINEAR:r.NEAREST_MIPMAP_LINEAR):r.texParameteri(r.TEXTURE_2D,r.TEXTURE_MIN_FILTER,c.S?r.LINEAR:r.NEAREST),
r.texParameteri(r.TEXTURE_2D,r.TEXTURE_MAG_FILTER,c.S?r.LINEAR:r.NEAREST)}}else a.canvaswrapper=new Ma(a.ready?a:la,c||{S:!0,N:!1,repeat:!1}),a.ready||console.log("Image is not ready yet.");return a.canvaswrapper}
function Ma(a,b){this.canvas=a;this.i=b;this.L=a.width;this.G=a.height;Na(this);this.R=0;this.l=[];this.aa=[];this.generation=-1;this.bindTexture();a.drawTo=this.drawTo.bind(this);a.readPixels=this.qa.bind(this);a.cdyUpdate=this.sa.bind(this);a=Ha(this.V*this.M*4);for(var c=0;2>c;c++)this.l[c]=r.createTexture(),r.bindTexture(r.TEXTURE_2D,this.l[c]),r.pixelStorei(r.UNPACK_ALIGNMENT,1),r.texImage2D(r.TEXTURE_2D,0,r.RGBA,this.V,this.M,0,r.RGBA,Ia(),a),b.N?r.texParameteri(r.TEXTURE_2D,r.TEXTURE_MIN_FILTER,
b.S?r.LINEAR_MIPMAP_LINEAR:r.NEAREST_MIPMAP_LINEAR):r.texParameteri(r.TEXTURE_2D,r.TEXTURE_MIN_FILTER,b.S?r.LINEAR:r.NEAREST),r.texParameteri(r.TEXTURE_2D,r.TEXTURE_MAG_FILTER,b.S?r.LINEAR:r.NEAREST),this.aa[c]=r.createFramebuffer(),r.bindFramebuffer(r.FRAMEBUFFER,this.aa[c]),r.framebufferTexture2D(r.FRAMEBUFFER,r.COLOR_ATTACHMENT0,r.TEXTURE_2D,this.l[c],0);this.$=new Oa(ja.copytexture_v,ja.copytexture_f);b=r.createBuffer();r.bindBuffer(r.ARRAY_BUFFER,b);b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,
1,1,0]);a=r.getAttribLocation(this.$.i,"aPos");r.enableVertexAttribArray(a);c=r.getAttribLocation(this.$.i,"aTexCoord");r.enableVertexAttribArray(c);var e=new Float32Array([0,0,1,0,0,1,1,1]),f=b.byteLength;r.bufferData(r.ARRAY_BUFFER,f+e.byteLength,r.STATIC_DRAW);r.bufferSubData(r.ARRAY_BUFFER,0,b);r.bufferSubData(r.ARRAY_BUFFER,f,e);r.vertexAttribPointer(a,3,r.FLOAT,!1,0,0);r.vertexAttribPointer(c,2,r.FLOAT,!1,0,f)}
function Na(a){a.V=Ka(a.L+a.L/2*(a.i.N&&a.i.repeat));a.M=Ka(a.G+a.G/2*(a.i.N&&a.i.repeat))}Ma.prototype.bindTexture=function(){r.bindTexture(r.TEXTURE_2D,this.l[this.R])};Ma.prototype.bindFramebuffer=function(){r.bindFramebuffer(r.FRAMEBUFFER,this.aa[this.R^1]);this.R^=1};
Ma.prototype.sa=function(){if(this.canvas.img.hasOwnProperty("getContext"))var a=this.canvas.img.getContext("2d");else this.canvas.img=document.createElement("canvas"),this.canvas.img.style.display="none",this.canvas.img.width=this.L,this.canvas.img.height=this.G,a=this.canvas.img.getContext("2d");a.clearRect(0,0,this.L,this.G);this.drawTo(a,0,0);this.canvas.img.generation++};
function Pa(a){if(!(a.canvas.live&&(a.canvas.img.webkitDecodedFrameCount||a.canvas.img.i)&&a.ma>=(a.canvas.img.webkitDecodedFrameCount||a.canvas.img.i)||!a.canvas.live&&(!a.canvas.ready||a.generation>=a.canvas.generation))){if(a.L!=a.canvas.width||a.G!=a.canvas.height){a.L=a.canvas.width;a.G=a.canvas.height;Na(a);for(var b=Ha(a.V*a.M*4),c=0;2>c;c++)r.bindTexture(r.TEXTURE_2D,a.l[c]),r.texImage2D(r.TEXTURE_2D,0,r.RGBA,a.V,a.M,0,r.RGBA,Ia(),b)}a.bindTexture();r.pixelStorei(r.UNPACK_FLIP_Y_WEBGL,1);
a.i.repeat?(m.width=a.V,m.height=a.M,b=m.getContext("2d"),b.drawImage(a.canvas.img,0,a.M-a.G),b.drawImage(a.canvas.img,a.L,a.M-a.G),b.drawImage(a.canvas.img,0,a.M-2*a.G),b.drawImage(a.canvas.img,a.L,a.M-2*a.G),r.texSubImage2D(r.TEXTURE_2D,0,0,0,r.RGBA,Ia(),m)):r.texSubImage2D(r.TEXTURE_2D,0,0,0,r.RGBA,Ia(),a.canvas.img);a.i.N&&r.generateMipmap(r.TEXTURE_2D);r.pixelStorei(r.UNPACK_FLIP_Y_WEBGL,0);a.generation=a.canvas.generation;a.ma=Math.min(a.ma+1,a.canvas.img.webkitDecodedFrameCount||a.canvas.img.i)}}
Ma.prototype.drawTo=function(a,b,c){za(this.V,this.M);r.viewport(0,0,this.V,this.M);r.useProgram(this.$.i);r.activeTexture(r.TEXTURE0);r.bindTexture(r.TEXTURE_2D,this.l[this.R]);this.$.l.sampler([0]);r.bindFramebuffer(r.FRAMEBUFFER,null);r.drawArrays(r.TRIANGLE_STRIP,0,4);r.flush();a.drawImage(h,0,h.height-this.G,this.L,this.G,b,c,this.L,this.G)};
Ma.prototype.qa=function(a,b,c,e){r.bindFramebuffer(r.FRAMEBUFFER,this.aa[this.R]);r.framebufferTexture2D(r.FRAMEBUFFER,r.COLOR_ATTACHMENT0,r.TEXTURE_2D,this.l[this.R],0);var f=Ha(c*e*4);r.readPixels(a,this.G-b-e,c,e,r.RGBA,Ia(),f);a=[];for(--e;0<=e;e--)a=a.concat(Ja(f.slice(e*c*4,(e+1)*c*4)));return a};function Qa(a,b){this.C=a;this.R=b;Ra(this)}
function Ra(a){var b=Sa(new Ta(a.C),a.R);a.l=b.D;a.O=b.O;a.ia=b.ia;a.$=ja.standardFragmentHeader+b.code;a.aa=ja.vshader;a.i=new Oa(a.aa,a.$);b=r.createBuffer();r.bindBuffer(r.ARRAY_BUFFER,b);b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,1,0]);var c=r.getAttribLocation(a.i.i,"aPos");r.enableVertexAttribArray(c);a=r.getAttribLocation(a.i.i,"aTexCoord");r.enableVertexAttribArray(a);var e=new Float32Array([0,0,1,0,0,1,1,1]),f=b.byteLength;r.bufferData(r.ARRAY_BUFFER,f+e.byteLength,r.STATIC_DRAW);r.bufferSubData(r.ARRAY_BUFFER,
0,b);r.bufferSubData(r.ARRAY_BUFFER,f,e);r.vertexAttribPointer(c,3,r.FLOAT,!1,0,0);r.vertexAttribPointer(a,2,r.FLOAT,!1,0,f)}
function Ua(a){function b(a,c,e){if(a)if("function"===typeof a)switch(c){case y.h:a([e.value.real,e.value.imag]);break;case y.B:e.value?a([1]):a([0]);break;case y.v:case y.f:a([e.value.real]);break;case y.A:case y.line:"geo"===e.ctype?a(e.value.homog.value.map(function(a){return a.value.real})):"list"===e.ctype&&2===e.value.length?a(e.value.map(function(a){return a.value.real}).concat([1])):"list"===e.ctype&&3===e.value.length&&a(e.value.map(function(a){return a.value.real}));break;default:if("list"===
c.type&&c.parameters===y.f)a(e.value.map(function(a){return a.value.real}));else if("list"===c.type&&"list"===c.parameters.type&&c.parameters.parameters===y.f){for(var f=[],g=0;g<c.length;g++)for(var k=0;k<c.parameters.length;k++)f.push(e.value[g].value[k].value.real);a(f)}else console.error("Don't know how to set uniform of type "+A(c)+", to "+e)}else if("list"===c.type)if(g=Va(c),1===B(c)&&g===y.f){c=Wa(c.length);var l=0;for(f in c)b(a["a"+f],y.ea(c[f]),{ctype:"list",value:C(c[f]).map(function(a){return e.value[l+
a]})}),l+=c[f]}else for(f=0;f<c.length;f++)b(a["a"+f],c.parameters,{ctype:"list",value:e.value[f].value});else console.error("Don't know how to set uniform of type "+A(c)+", to"),console.log(e)}for(var c in a.l){var e=a.C.evaluateAndVal(a.l[c].X),f=a.l[c].type;if(!D(Xa(e),f)){console.log("Type of "+c+" changed ("+A(Xa(e))+" is no subtype of  "+A(f)+"); forcing rebuild.");Ra(a);r.useProgram(a.i.i);Ua(a);return}a.i.l[c]&&b(a.i.l[c],f,e)}[["rnd_",function(){return[Math.random()]}],["_lowerleft",function(){var b=
Ba(a.C);return[b.x,b.y]}],["_lowerright",function(){var b=Ca(a.C);return[b.x,b.y]}]].map(function(b){return a.i.l[b[0]]&&a.i.l[b[0]](b[1]())})}function Ya(a){var b=0,c;for(c in a.O){r.activeTexture(r.TEXTURE0+b);var e=a.O[c],f=e.name;e=Za(e);Pa(e);e.bindTexture();[["_sampler"+f,[b]],["_ratio"+f,[e.L/e.G]],["_cropfact"+f,[e.L/e.V,e.G/e.M]]].map(function(b){return a.i.l[b[0]]&&a.i.l[b[0]](b[1])});b++}};CindyJS.registerPlugin(1,"CindyGL",function(a){function b(b,e,f,g,k,l){if(!b.oa||b.na<qa)b.oa=!0,b.na=qa,b.ra=new Qa(a,b);b=b.ra;a:{for(c in b.ia)if(b.C.getMyfunction(c).generation>b.ia[c]){console.log(c+" is outdated; forcing rebuild.");var c=!1;break a}c=!0}c||Ra(b);var u=k/g;c=e.x+-(f.y-e.y)*u;u=e.y+(f.x-e.x)*u;za(g,k);l?r.viewport(0,0,g,k):r.viewport(0,h.height-k,g,k);r.useProgram(b.i.i);Ua(b);e=[f.x-e.x,c-e.x,e.x,f.y-e.y,u-e.y,e.y,0,0,1];b.i.l.hasOwnProperty("transformMatrix")&&b.i.l.transformMatrix([e[0],
e[3],e[6],e[1],e[4],e[7],e[2],e[5],e[8]]);Ya(b);l?(l.bindFramebuffer(),l.generation=++l.canvas.generation):r.bindFramebuffer(r.FRAMEBUFFER,null);r.drawArrays(r.TRIANGLE_STRIP,0,4);r.flush();l&&(l.generation=Math.max(l.generation,l.canvas.generation+1))}t=a.nada;a.defineFunction("compile",1,function(b){b=Sa(new Ta(a),b[0]);console.log(b);return{ctype:"string",value:b}});a.defineFunction("use8bittextures",0,function(){pa=!0;x=w=!1;console.log("Switching to 8-bit textures mode.");return a.nada});a.defineFunction("forcerecompile",
0,function(){qa++;return t});a.defineFunction("colorplot",1,function(c){ra();var e=a.instance.canvas.clientWidth,f=a.instance.canvas.clientHeight,g=a.instance.canvas.width,k=a.instance.canvas.height;b(c[0],Ba(a),Ca(a),g,k,null);a.instance.canvas.getContext("2d").drawImage(h,0,0,g,k,0,0,e,f);return t});a.defineFunction("colorplot",3,function(c){ra();var e=c[0],f=a.extractPoint(a.evaluateAndVal(c[1])),g=a.extractPoint(a.evaluateAndVal(c[2])),k={x:Math.min(f.x,g.x),y:Math.min(f.y,g.y)},l={x:Math.max(f.x,
g.x),y:Math.min(f.y,g.y)};c=a.instance.canvas.clientWidth;var p=a.instance.canvas.clientHeight,u=a.instance.canvas.width,q=a.instance.canvas.height,v=Aa(a,0,0),H=Ba(a),V=Ca(a);V=Math.abs((f.x-g.x)/(H.x-V.x));v=Math.abs((f.y-g.y)/(v.y-H.y));b(e,k,l,u*V,q*v,null);e=a.instance.canvas.getContext("2d");k=Math.min(f.x,g.x);f=Math.max(f.y,g.y);g=a.getInitialMatrix();e.drawImage(h,0,0,u*V,q*v,k*g.a-f*g.b+g.tx,k*g.c-f*g.d-g.ty,V*c,v*p);return t});a.defineFunction("colorplot",4,function(c){ra();var e=a.extractPoint(a.evaluateAndVal(c[0])),
f=a.extractPoint(a.evaluateAndVal(c[1])),g=a.evaluateAndVal(c[2]);c=c[3];if(!e.ok||!f.ok||"string"!==g.ctype)return t;g=a.getImage(g.value,!0);var k=La(g,a,!1);b(c,e,f,g.width,g.height,k);return t});a.defineFunction("colorplot",2,function(c){ra();var e=Ba(a),f=Ca(a),g=a.evaluateAndVal(c[0]);c=c[1];if("string"!==g.ctype)return t;g=a.getImage(g.value,!0);var k=La(g,a,!1);b(c,e,f,g.width,g.height,k);return t});a.defineFunction("setpixel",4,function(b){var c=a.evaluateAndVal(b[0]);var f=void 0===f?null:
f;if("string"===c.ctype)var g=c.value;else console.log("argument is not a string"),g=f;c=$a(a.evaluateAndVal(b[1]));f=$a(a.evaluateAndVal(b[2]));b=ab(a.evaluateAndVal(b[3]));if(!g)return t;var k=a.getImage(g,!0);k=La(k,a,!1);isFinite(c)&&isFinite(f)&&g&&k&&b&&(k.bindTexture(),g=[b[0],b[1],b[2],1],r.texSubImage2D(r.TEXTURE_2D,0,c,f,1,1,r.RGBA,Ia(),Ga(g)),b=k.canvas.img.getContext("2d"),k=b.createImageData(1,1),k.data.d=g,b.putImageData(k,c,f));return t})});function E(a,b){return{type:"list",length:a,parameters:b}}function Xa(a){return{type:"constant",value:a}}function bb(a){return Xa({ctype:"number",value:{real:a,imag:0}})}var y={B:1,v:2,f:3,h:4,W:5,color:6,A:7,line:8,K:9,image:10,F:E(2,3),J:E(3,3),P:E(4,3),ea:function(a){return E(a,3)},ha:function(a){return E(a,4)},ba:E(2,E(2,3)),ca:E(3,E(3,3)),da:E(4,E(4,3))};Object.freeze(y);
function A(a){return 1<=a&&10>=a?"bool int float complex voidt color point line coordinate2d image".split(" ")[a-1]:"list"===a.type?A(a.parameters)+"["+a.length+"]":"constant"===a.type?"const["+JSON.stringify(a.value.value)+"]":JSON.stringify(a)}function F(a){return"list"===a.type&&F(a.parameters)||D(a,y.f)}function G(a){return"list"===a.type&&G(a.parameters)||D(a,y.h)}function cb(a){return"constant"===a.type&&D(a,y.v)}function I(a){return"constant"===a.type?wa(a.value):a}
function B(a){return"list"===a.type?B(a.parameters)+1:0}function Va(a){return void 0!==a.parameters?Va(a.parameters):a}function db(a,b){return B(a)===B(b)&&(0===B(a)||a.length===b.length&&db(a.parameters,b.parameters))}function J(a){return D(a,y.f)?y.f:D(a,y.h)?y.h:{type:"list",length:a.length,parameters:J(a.parameters)}}function eb(a){return D(a,y.h)?y.h:{type:"list",length:a.length,parameters:eb(a.parameters)}}
function K(a){return a===y.B||a===y.v||a===y.f||a===y.h||a===y.A||a===y.line||"list"===a.type&&a.parameters===y.f&&1<=a.length&&4>=a.length||"list"===a.type&&"list"===a.parameters.type&&a.parameters.parameters===y.f&&a.length===a.parameters.length&&2<=a.length&&4>=a.length}function fb(a){return-1!==[y.B,y.v,y.f,y.h].indexOf(a)}
function gb(a,b){return a===b||"constant"===a.type&&"constant"===b.type&&ua(a.value,b.value)||"list"===a.type&&"list"===b.type&&a.length===b.length&&gb(a.parameters,b.parameters)}
function D(a,b){return gb(a,b)?!0:a?fb(a)&&fb(b)?a<=b:"constant"===b.type?!1:"constant"===a.type?D(wa(a.value),b):b===y.K?D(a,y.h)||D(a,y.F)||D(a,y.A):b===y.A?D(a,y.J)||D(a,y.F):b===y.line?D(a,y.J):b===y.color?D(a,y.f)||"list"===a.type&&(3===a.length||4===a.length)&&D(a.parameters,y.f):"list"===a.type&&"list"===b.type&&a.length===b.length?D(a.parameters,b.parameters):!1:!1}
function z(a,b){if(!a)return b;if(!b||gb(a,b))return a;"constant"===a.type&&(a=wa(a.value));"constant"===b.type&&(b=wa(b.value));return fb(a)&&fb(b)?Math.max(a,b):"list"===a.type&&"list"===b.type&&a.length===b.length&&(b=z(a.parameters,b.parameters))?{type:"list",length:a.length,parameters:b}:!1}
function L(a){return function(b){var c={},e;for(e in a){var f=a[e];c.ga=f[0];if(b.length==c.ga.length&&b.every(function(a){return function(b,c){return D(b,a.ga[c])}}(c)))return{s:c.ga,u:f[1],m:f[2]};c={ga:c.ga}}return!1}}
function hb(a){switch(a){case y.v:return L([[[y.B],y.v,M("int")]]);case y.f:return L([[[y.B],y.f,M("float")],[[y.v],y.f,M("float")]]);case y.h:return L([[[y.f],y.h,function(a){return"vec2("+a+", 0.)"}]]);case y.color:return L([[[y.f],y.color,N("float2color")],[[y.J],y.color,function(a){return"vec4("+a+",1.0)"}],[[y.P],y.color,O]]);case y.A:return L([[[y.F],y.A,function(a){return"vec3("+a+",1.0)"}],[[y.J],y.A,O]]);case y.line:return L([[[y.F],y.line,function(a){return"vec3("+a+",1.0)"}],[[y.J],y.line,
O]]);case y.K:return L([[[y.h],y.K,O],[[y.F],y.K,O],[[y.A],y.K,N("dehomogenize")]]);default:if("list"===a.type)return function(b){var c=b[0],e=hb(a.parameters)([c.parameters]).m;return{s:b,u:a,m:function(b,g,k){return ib(a)(C(a.length).map(function(a){return e([P(c,a)([b],g,k)],g,k)}),g,k)}}}}console.log("no inclusionfunction ->"+A(a)+" implemented yet; using identity...");return function(b){return{s:b,u:a,m:O}}}
function Q(a){switch(a){case y.B:return"bool";case y.v:return"int";case y.f:return"float";case y.h:case y.K:return"vec2";case y.W:return"void";case y.color:return"vec4";case y.A:case y.line:return"vec3"}if("list"===a.type&&a.parameters===y.f)return 1==a.length?"float":"vec"+a.length;if("list"===a.type&&a.parameters===y.h)return"cvec"+a.length;if("list"===a.type&&"list"===a.parameters.type&&a.length===a.parameters.length&&a.parameters.parameters===y.f)switch(a.length){case 2:return"mat2";case 3:return"mat3";
case 4:return"mat4"}if("list"===a.type)return"l"+a.length+"_"+Q(a.parameters);console.error("No WebGL implementation for type "+A(a)+" found")}function jb(a,b){switch(b){case y.B:return Q(b)+"("+a.value+")";case y.v:return""+(a.value.real|0);case y.f:return Q(b)+"("+a.value.real+")";case y.h:return Q(b)+"("+a.value.real+", "+a.value.imag+")";case y.color:return a=a.value.real,"vec4("+a+","+a+","+a+",1.)";default:console.error("Dont know how to paste values of Type "+A(b)+" yet.")}};var R={};function kb(a,b,c){if(!c.mark("includedfunctions",a)){for(var e in R[a])kb(R[a][e],b,c);c.add("includedfunctions",a,function(){return ja[a]})}}function N(a){return function(b,c,e){kb(a,c,e);return M(a)(b)}};function C(a){return Array.from(Array(a).keys())}function Wa(a){return 4>=a?[a]:5==a?[2,3]:Wa(a-4).concat([4])}function lb(a){var b=Va(a),c=B(a);return 1==c&&b===y.f?Wa(a.length).map(function(a,b){return{type:y.ea(a),name:"a"+b}}):1<=c?C(a.length).map(function(b){return{type:a.parameters,name:"a"+b}}):[]}function mb(a,b){if(!K(a)){var c=Q(a);b.add("structs",c,function(){return"struct "+c+" { "+lb(a).map(function(a){return mb(a.type,b)||Q(a.type)+" "+a.name+";"}).join("")+"};"})}}
function nb(a,b,c){if(!K(a)){var e=a.length,f=a.parameters.length;c.add("functions","mult"+e+"_"+f,function(){return Q(y.ea(e))+" mult"+e+"_"+f+"("+Q(a)+" a, "+Q(y.ea(f))+" b){return "+ob(e)(C(e).map(function(a){return pb(f)(["a.a"+a,"b"],b,c)}),b,c)+";}"})}}
function qb(a,b,c){if(!K(a)){var e=a.length,f="sum"+Q(a);c.add("functions",f,function(){return Q(a.parameters)+" "+f+"("+Q(a)+" a){"+(Q(a.parameters)+" res = "+rb(a.parameters,0)([],b,c)+";\n      "+C(e).map(function(e){return"res = "+sb(a.parameters)(["res",P(a,e)(["a",e],b,c)],b,c)+";"}).join("\n")+"\n        return res;\n    }")})}}
function tb(a,b,c){var e=a.length,f=a.parameters.length;c.add("functions","multc"+e+"_"+f,function(){return Q(y.ha(e))+" multc"+e+"_"+f+"("+Q(a)+" a, "+Q(y.ha(f))+" b){\n        return cvec"+e+"("+C(e).map(function(a){return ub(f)(["a.a"+a,"b"],b,c)})+");\n    }\n    "})}function vb(a,b){2<=a&&4>=a||b.add("functions","dot"+a,function(){return"float dot"+a+"(vec"+a+" a, vec"+a+" b) {\n    return "+Wa(a).map(function(a,b){return"dot(a.a"+b+",b.a"+b+")"}).join("+")+"; }\n    "})}
function wb(a,b){b.add("functions","cdot"+a,function(){return"vec2 cdot"+a+"(cvec"+a+" a, cvec"+a+" b) {\n      return "+C(a).map(function(a){return"vec2(dot(a.a"+a+",vec2(b.a"+a+".x,-b.a"+a+".y)), dot(a.a"+a+",b.a"+a+".yx))"}).join("+\n")+";\n    }\n    "})}
function xb(a,b,c){var e="add"+Q(a);c.add("functions",e,function(){return Q(a)+" "+e+"("+Q(a)+" a, "+Q(a)+" b) {\n    return "+Q(a)+"("+lb(a).map(function(a){return Q(a.type)+"("+sb(a.type)(["a."+a.name,"b."+a.name],b,c)+")"}).join(",")+");\n      }"})}
function yb(a,b,c){var e="sub"+Q(a);c.add("functions",e,function(){return Q(a)+" "+e+"("+Q(a)+" a, "+Q(a)+" b) {\n    return "+Q(a)+"("+lb(a).map(function(a){return Q(a.type)+"("+zb(a.type)(["a."+a.name,"b."+a.name],b,c)+")"}).join(",")+");\n    }"})}function Ab(a,b,c){var e="scalarmult"+Q(a);c.add("functions",e,function(){return Q(a)+" "+e+"(float a, "+Q(a)+" b) {\n    return "+Q(a)+"("+lb(a).map(function(a){return Q(a.type)+"("+Bb(a.type)(["a","b."+a.name],b,c)+")"}).join(",")+");\n    }"})}
function Cb(a,b,c){kb("multc",b,c);var e="cscalarmult"+Q(a);c.add("functions",e,function(){return Q(a)+" "+e+"(vec2 a, "+Q(a)+" b) {\n    return "+Q(a)+"("+lb(a).map(function(a){return""+Db(a.type)(["a","b."+a.name],b,c)}).join(",")+");\n    }"})}
function Eb(a){if(a===y.h)return N("multc");if(K(a))return function(a){return S("*")([a[1],a[0]])};var b=Va(a);if(D(b,y.f))return function(b,e,f){return nb(a,e,f)||"mult"+a.length+"_"+a.parameters.length+"("+b.join(",")+")"};if(b===y.h)return function(b,e,f){return tb(a,e,f)||"multc"+a.length+"_"+a.parameters.length+"("+b.join(",")+")"}}function pb(a){return function(b,c,e){return vb(a,e)||"dot"+(2<=a&&4>=a?"":a)+"("+b.join(",")+")"}}
function ub(a){return function(b,c,e){return wb(a,e)||"cdot"+a+"("+b.join(",")+")"}}function sb(a){return K(a)?S("+"):function(b,c,e){return xb(a,c,e)||"add"+Q(a)+"("+b.join(",")+")"}}function zb(a){return K(a)?S("-"):function(b,c,e){return yb(a,c,e)||"sub"+Q(a)+"("+b.join(",")+")"}}function Fb(a){return F(a)&&1==B(a)?function(b,c,e){return pb(a.length)([b[0],ob(a.length)(Array(a.length).fill("1."),c,e)],c,e)}:function(b,c,e){return qb(a,c,e)||"sum"+Q(a)+"("+b.join(",")+")"}}
function ob(a){if(2<=a&&4>=a)return function(b){return"vec"+a+"("+b.join(",")+")"};if(1==a)return function(a){return"float("+a.join(",")+")"};var b=0;return function(c,e,f){return mb(y.ea(a),f)||"vec"+a+"("+Wa(a).map(function(a){return"vec"+a+"("+C(a).map(function(){return++b&&c[b-1]}).join(",")+")"}).join(",")+")"}}function ib(a){return K(a)?function(b){return Q(a)+"("+b.join(",")+")"}:1==B(a)&&a.parameters===y.f?ob(a.length):function(b,c,e){return mb(a,e)||Q(a)+"("+b.join(",")+")"}}
function P(a,b){var c=Va(a);return 1==B(a)&&c===y.f?Gb(a.length,b):K(a)?function(a){return"("+a[0]+")["+b+"]"}:function(a){return"("+a[0]+").a"+b}}function rb(a,b){return K(a)?function(){return Q(a)+"(float("+b+"))"}:function(c,e,f){return ib(a)+"("+lb(a).map(function(a){return rb(a.type,b)(c,e,f)}).join(",")+")"}}
function Gb(a,b){return function(c){if(1==a)return c[0];if(2<=a&&4>=a)return"("+c[0]+")["+b+"]";a:{var e=b;var f=Wa(a),g;for(g in f)if(f[g]<=e)e-=f[g];else{e={first:g,second:e};break a}console.error("Accessing index out of range");e=void 0}return"("+c[0]+").a"+e.first+"["+e.second+"]"}}function Bb(a){return K(a)?S("*"):function(b,c,e){return Ab(a,c,e)||"scalarmult"+Q(a)+"("+b.join(",")+")"}}
function Db(a){return a===y.h?N("multc"):function(b,c,e){return Cb(a,c,e)||"cscalarmult"+Q(a)+"("+b.join(",")+")"}}function Hb(a,b,c){var e="reverse"+Q(a);c.add("functions",e,function(){return Q(a)+" "+e+"("+Q(a)+" a){"+(Q(a.parameters)+" m;\n")+C(Math.floor(a.length/2)).map(function(e){var f=P(a,e)(["a",e],b,c);e=P(a,a.length-1-e)(["a",a.length-1-e],b,c);return"m = "+f+"; "+f+" = "+e+"; "+e+" = m;"}).join("\n")+"return a;\n      }"})}
function Ib(a){return function(b,c,e){return Hb(a,c,e)||"reverse"+Q(a)+"("+b.join(",")+")"}}function Jb(a,b,c){var e="max"+Q(a);c.add("functions",e,function(){return Q(a.parameters)+" "+e+"("+Q(a)+" a){"+(Q(a.parameters)+" m = "+P(a,a.length-1)(["a",a.length-1],b,c)+";\n")+C(a.length-1).map(function(e){return"m = max(m,"+P(a,e)(["a",e],b,c)+");"}).join("\n")+"return m;\n      }"})}function Kb(a){return function(b,c,e){return Jb(a,c,e)||"max"+Q(a)+"("+b.join(",")+")"}}
function Lb(a,b,c){var e="min"+Q(a);c.add("functions",e,function(){return Q(a.parameters)+" "+e+"("+Q(a)+" a){"+(Q(a.parameters)+" m = "+P(a,a.length-1)(["a",a.length-1],b,c)+";\n")+C(a.length-1).map(function(e){return"m = min(m,"+P(a,e)(["a",e],b,c)+");"}).join("\n")+"return m;\n      }"})}function Mb(a){return function(b,c,e){return Lb(a,c,e)||"min"+Q(a)+"("+b.join(",")+")"}}
function Nb(a,b,c){var e="transpose"+Q(a),f=E(a.parameters.length,E(a.length,a.parameters.parameters));c.add("functions",e,function(){return Q(f)+" "+e+"("+Q(a)+" a){return "+ib(f)(C(f.length).map(function(e){return ib(f.parameters)(C(f.parameters.length).map(function(f){return P(a.parameters,e)([P(a,f)(["a",f],b,c),e],b,c)}),b,c)}),b,c)+";}"})}function Ob(a){return function(b,c,e){return Nb(a,c,e)||"transpose"+Q(a)+"("+b.join(",")+")"}};function Pb(a){function b(a,e,k){if(1<e){var f=e/2|0;b(a,f,!k);b(a+f,e-f,k);c(a,e,k)}}function c(a,b,k){if(1<b){var f;for(f=1;f<b;)f<<=1;f>>=1;for(var g=a;g<a+b-f;g++){var u=g,q=g+f;k?e.push([u,q]):e.push([q,u])}c(a,f,k);c(a+f,b-f,k)}}var e=[];b(0,a,!0);return e}
function Qb(a,b,c){var e="sort"+Q(a);c.add("functions",e,function(){return Q(a)+" "+e+"("+Q(a)+" a){"+(Q(a.parameters)+" m;\n")+Pb(a.length).map(function(e){var f=P(a,e[0])(["a",e[0]],b,c);e=P(a,e[1])(["a",e[1]],b,c);return"m = min("+f+","+e+"); "+e+" = max("+f+","+e+"); "+f+" = m;"}).join("\n")+"return a;\n      }"})}function Rb(a){return function(b,c,e){return Qb(a,c,e)||"sort"+Q(a)+"("+b.join(",")+")"}};function M(a){return function(b){return va(a)+"("+b+")"}}function S(a){return function(b){return"("+b.join(a)+")"}}function T(){return function(a){return"("+a.reverse().join("*")+")"}}function O(a){return a}var U={};U.join=L([[[y.A,y.A],y.line,M("cross")]]);U.meet=L([[[y.line,y.line],y.A,M("cross")]]);U.gauss=L([[[y.h],y.F,O]]);U.complex=L([[[y.F],y.h,O],[[y.A],y.h,N("dehomogenize")]]);
U["if"]=function(a){if(!a.every(function(a){return a}))return!1;if(2===a.length)return{s:a,u:a[1],m:function(a){return"if("+a[0]+") {"+a[1]+";}"}};if(3===a.length){var b=z(a[1],a[2]);return b?{s:[y.B,b,b],u:b,m:function(a){return"("+a[0]+" ? "+a[1]+" : "+a[2]+")"}}:{s:a,u:y.W,m:function(a){return"if("+a[0]+") {"+a[1]+";} else {"+a[2]+";}"}}}return!1};U["="]=function(a){a=z(a[0],a[1]);return{s:a,u:a,m:function(a){return a[0]+" = "+a[1]+";"}}};
U[";"]=function(a){return{s:a,u:a[1]!==y.W?a[1]:a[0],m:function(a){return a[0]+" ; "+a[1]+";"}}};U.repeat=function(a){return 2!=a.length&&3!=a.length||!cb(a[0])?!1:{s:a,u:a[a.length-1],m:function(){return""}}};U.forall=function(a){return 2!=a.length&&3!=a.length||"list"!==I(a[0]).type?!1:{s:a,u:a[a.length-1],m:function(){return""}}};U.apply=function(a){return 2!=a.length&&3!=a.length||"list"!==I(a[0]).type?!1:{s:a,u:E(I(a[0]).length,a[a.length-1]),m:function(){return""}}};
U.sum=function(a){return 1==a.length&&(F(a[0])||G(a[0]))?{s:a,u:a[0].parameters,m:Fb(a[0])}:!1};U.regional=function(a){return{s:a,u:y.W,m:function(){return""}}};U.sqrt=L([[[y.f],y.h,N("sqrtf")],[[y.h],y.h,N("sqrtc")]]);U.abs=L([[[y.f],y.f,M("abs")],[[y.h],y.f,M("length")],[[y.F],y.f,M("length")],[[y.J],y.f,M("length")],[[y.P],y.f,M("length")]]);U.abs_infix=U.abs;
U.dist=L([[[y.f,y.f],y.f,function(a){return M("abs")(S("-")(a))}],[[y.h,y.h],y.f,function(a){return M("length")(S("-")(a))}],[[y.F,y.F],y.f,function(a){return M("length")(S("-")(a))}],[[y.J,y.J],y.f,function(a){return M("length")(S("-")(a))}],[[y.P,y.P],y.f,function(a){return M("length")(S("-")(a))}]]);U.dist_infix=U.dist;U.sin=L([[[y.f],y.f,M("sin")],[[y.h],y.h,N("sinc")]]);U.cos=L([[[y.f],y.f,M("cos")],[[y.h],y.h,N("cosc")]]);U.tan=L([[[y.f],y.f,M("tan")],[[y.h],y.h,N("tanc")]]);
U.exp=L([[[y.f],y.f,M("exp")],[[y.h],y.h,N("expc")]]);U.arctan=L([[[y.f],y.f,M("atan")],[[y.h],y.h,N("arctanc")]]);U.arcsin=L([[[y.f],y.h,N("arcsinf")],[[y.h],y.h,N("arcsinc")]]);U.arccos=L([[[y.f],y.h,N("arccosf")],[[y.h],y.h,N("arccosc")]]);U.log=L([[[y.f],y.h,N("logr")],[[y.h],y.h,N("logc")]]);var Sb=[2,3,4].map(function(a){return E(a,y.f)}).concat([2,3,4].map(function(a){return E(a,E(a,y.f))})),Tb=[y.v,y.f,y.h].concat(Sb);
U.add=function(a){var b=L(Tb.map(function(a){return[[a,a],a,S("+")]}).concat([[[y.A,y.A],y.F,N("addpoints")]]))(a);if(b)return b;b=a[0];a=a[1];if([b,a].every(function(a){return F(a)||G(a)})&&db(b,a))return a=z(J(b),J(a)),{s:[a,a],u:a,m:sb(a)}};
U.sub=function(a){var b=L(Tb.map(function(a){return[[a,a],a,S("-")]}).concat(Tb.map(function(a){return[[y.W,a],a,S("-")]})).concat([[[y.A,y.A],y.F,N("subpoints")]]))(a);if(b)return b;b=a[0];a=a[1];if([b,a].every(function(a){return F(a)||G(a)})&&db(b,a))return a=z(J(b),J(a)),{s:[a,a],u:a,m:zb(a)}};U["+"]=U.add;U["-"]=U.sub;
U._=function(a){var b=I(a[0]);if(b===y.A||b===y.line)b=y.J;if("list"===b.type&&cb(a[1])){var c=Number(a[1].value.value.real);return 1<=Math.abs(c)&&Math.abs(c)<=b.length?(0<c&&--c,0>c&&(c=b.length+c),{s:a,u:b.parameters,m:P(b,c)}):{s:a,u:b.parameters,m:function(){return console.error("try to access "+c+"-th Element of "+b.length+"-list "+JSON.stringify(a[0]))}}}return!1};
U.mult=function(a){var b=L([[[y.v,y.v],y.v,S("*")],[[y.f,y.f],y.f,S("*")],[[y.h,y.f],y.h,S("*")],[[y.f,y.h],y.h,S("*")],[[y.h,y.h],y.h,N("multc")],[[y.ba,y.ba],y.ba,T()],[[y.ca,y.ca],y.ca,T()],[[y.da,y.da],y.da,T()],[[y.ba,y.F],y.F,T()],[[y.ca,y.J],y.J,T()],[[y.da,y.P],y.P,T()],[[y.F,y.ba],y.F,T()],[[y.J,y.ca],y.J,T()],[[y.P,y.da],y.P,T()]])(a);if(b)return b;if(2!==a.length)return!1;b=a[0];var c=a[1];if([b,c].every(function(a){return"list"===a.type&&D(a.parameters,y.f)})&&b.length===c.length)return a=
J(b),K(a)?{s:[a,a],u:y.f,m:M("dot")}:{s:[a,a],u:y.f,m:pb(b.length)};if([b,c].every(function(a){return"list"===a.type&&D(a.parameters,y.h)})&&b.length===c.length)return a=eb(b),{s:[a,a],u:y.h,m:ub(b.length)};if(F(b)&&2===B(b)&&F(c)&&1===B(c)&&b.parameters.length===c.length)return{s:[J(b),J(c)],u:y.ea(b.length),m:Eb(J(b))};if(G(b)&&2===B(b)&&G(c)&&1===B(c)&&b.parameters.length===c.length)return{s:[eb(b),eb(c)],u:y.ha(b.length),m:Eb(eb(b))};for(b={H:0};2>b.H;b={Y:b.Y,H:b.H,fa:b.fa},b.H++){if(D(a[0^b.H],
y.f)&&(F(a[1^b.H])||G(a[1^b.H])))return b.Y=J(a[1^b.H]),{s:b.H?[b.Y,y.f]:[y.f,b.Y],u:b.Y,m:function(a){return function(b,c,e){return Bb(a.Y)([b[0^a.H],b[1^a.H]],c,e)}}(b)};if(D(a[0^b.H],y.h)&&G(a[1^b.H]))return b.fa=eb(a[1^b.H]),{s:b.H?[b.fa,y.h]:[y.h,b.fa],u:b.fa,m:function(a){return function(b,c,e){return Db(a.fa)([b[0^a.H],b[1^a.H]],c,e)}}(b)}}};U["*"]=U.mult;
U.div=function(a){var b=L([[[y.f,y.f],y.f,S("/")],[[y.f,y.h],y.h,N("divfc")],[[y.h,y.f],y.h,S("/")],[[y.h,y.h],y.h,N("divc")]])(a);return b?b:D(a[1],y.f)&&G(a[0])&&(a=J(a[0]),K(a))?{s:[a,y.f],u:a,m:S("/")}:!1};U["/"]=U.div;U.re=L([[[y.h],y.f,N("realc")]]);U.im=L([[[y.h],y.f,N("imagc")]]);U.floor=L([[[y.f],y.v,function(a){return"int(floor("+a+"))"}],[[y.h],y.h,M("floor")]]);U.round=L([[[y.f],y.v,function(a){return"int(floor("+a+"+.5))"}],[[y.h],y.h,function(a){return"floor("+a+"+vec2(.5))"}]]);
U.ceil=L([[[y.f],y.v,function(a){return"int(ceil("+a+"))"}],[[y.h],y.h,M("ceil")]]);U.mod=L([[[y.v,y.v],y.v,function(a,b){return"int("+M("mod")("float("+a[0]+"), float("+a[1]+")",b)+")"}],[[y.f,y.f],y.f,M("mod")],[[y.h,y.h],y.h,N("mod")]]);U.random=L([[[],y.f,N("random")],[[y.f],y.f,function(a,b,c){return N("random")([],b,c)+"*"+a[0]}],[[y.h],y.h,function(a,b,c){return"vec2("+N("random")([],b,c)+","+N("random")([],b,c)+")*"+a[0]}]]);
U.randomint=L([[[y.v],y.v,function(a,b,c){return"int(floor("+N("random")([],b,c)+"*float("+a[0]+")))"}],[[y.f],y.v,function(a,b,c){return"int(floor("+N("random")([],b,c)+"*floor("+a[0]+")))"}]]);U.randominteger=U.randomint;U.randombool=L([[[],y.B,function(a,b,c){return"("+N("random")([],b,c)+">.5)"}]]);U.randomnormal=L([[[],y.f,N("randomnormal")]]);
U.arctan2=L([[[y.f,y.f],y.f,function(a){return"atan("+a[1]+", "+a[0]+")"}],[[y.h,y.h],y.h,N("arctan2c")],[[y.h],y.f,N("arctan2vec2")],[[y.F],y.f,N("arctan2vec2")],[[y.ha(2)],y.h,N("arctan2cvec2")]]);["red","green","blue","gray","hue"].forEach(function(a){U[a]=L([[[y.f],y.J,N(a)]])});U.grey=U.gray;U.min=function(a){var b=L([[[y.f,y.f],y.f,M("min")]])(a);if(b)return b;if(1===a.length&&1===B(a[0])&&F(a[0]))return{s:a,u:a[0].parameters,m:Mb(a[0])}};
U.max=function(a){var b=L([[[y.v,y.v],y.v,M("max")],[[y.f,y.f],y.f,M("max")]])(a);if(b)return b;if(1===a.length&&1===B(a[0])&&F(a[0]))return{s:a,u:a[0].parameters,m:Kb(a[0])}};function Ub(a,b){if(!(1>=a))if(2==a)b.add("functions","raise2",function(){return"float raise2(float a) { return a*a; }"});else{Ub(2,b);var c=function(a,b){return 1==b?a:b&1?c(a,b-1)+"*a":"raise2("+c(a,b/2)+")"},e="raise"+a;b.add("functions",e,function(){return"float "+e+"(float a) { return "+c("a",a)+";}"})}}
function Vb(a){return function(b,c,e){return 0==a?"1.":1==a?b[0]:Ub(a,e)||"raise"+a+"("+b[0]+")"}}U.pow=function(a){if(cb(a[1])&&D(a[0],y.f)){var b=Number(a[1].value.value.real);if(0<=b)return{s:[y.f,a[1]],u:y.f,m:Vb(b)}}return L([[[y.f,y.v],y.f,N("powi")],[[y.h,y.h],y.h,N("powc")]])(a)};U["^"]=U.pow;U.re=L([[[y.h],y.f,function(a){return"("+a+").x"}]]);U.conjugate=L([[[y.h],y.h,N("conjugate")]]);U.im=L([[[y.h],y.f,function(a){return"("+a+").y"}]]);
U.genList=function(a){var b=a.length;if(0<b){var c=!1,e;for(e in a)c=z(c,a[e]);if(c)return a=E(b,c),{s:Array(b).fill(c),u:a,m:ib(a)}}return!1};U["&"]=L([[[y.B,y.B],y.B,S("&&")]]);U["%"]=L([[[y.B,y.B],y.B,S("||")]]);"> < >= <= == !=".split(" ").forEach(function(a){U[a]=L([[[y.v,y.v],y.B,S(a)],[[y.f,y.f],y.B,S(a)]])});U["!"]=L([[[y.B],y.B,M("!")],[[y.W,y.B],y.B,function(a){return M("!")([a[1]])}]]);U.not=U["!"];U.imagergb=L([[[y.image,y.K],y.J,Wb],[[y.K,y.K,y.image,y.K],y.J,Xb]]);
U.imagergba=L([[[y.image,y.K],y.P,Yb],[[y.K,y.K,y.image,y.K],y.P,Zb]]);U.reverse=function(a){return 1===a.length&&"list"===a[0].type?{s:a,u:a[0],m:Ib(a[0])}:!1};U.sort=function(a){return 1===a.length&&1===B(a[0])&&F(a[0])?{s:a,u:a[0],m:Rb(a[0])}:!1};U.transpose=function(a){return 1===a.length&&2<=B(a[0])?{s:a,u:E(a[0].parameters.length,E(a[0].length,a[0].parameters.parameters)),m:Ob(a[0])}:!1};U.det=L([[[y.ba],y.f,N("det2")],[[y.ca],y.f,N("det3")],[[y.da],y.f,N("det4")],[[y.A,y.A,y.A],y.f,N("det3v")]]);
Object.freeze(U);R.powc=["expc","multc","logc"];R.sqrtc=["expc","multc","logc"];R.arccosc=["multc","negc","sqrtc","addc","logc"];R.arcsinc=["multc","negc","sqrtc","addc","logc"];R.tanc=["sinc","cosc","divc"];R.arctanc=["logc","addc","multc","subc"];R.arctan2c=["logc","divc","sqrtc","multc"];R.arctan2vec2c=["arctan2c"];R.hue=["hsv2rgb"];R.randomnormal=["random"];R.subpoints=["dehomogenize"];R.addpoints=["dehomogenize"];Object.freeze(R);function Ta(a){this.j={};this.D={};this.i={};this.T=0;this.l={};this.C=a;this.O={}}Ta.prototype.add=function(a,b,c){this.mark(a,b);this.i[a].ka[b]||(this.i[a].ka[b]=c(),this.i[a].ja[b]=!0,this.i[a].order.push(b))};Ta.prototype.mark=function(a,b){this.i[a]||(this.i[a]={order:[],ja:{},ka:{}});var c=this.i[a].ja[b]||!1;this.i[a].ja[b]=!0;return c};function $b(a,b){return a.i[b]?a.i[b].order.map(function(c){return a.i[b].ka[c]}).join("\n"):"\n"}
function W(a,b,c,e){if(gb(c,e))return b;if(D(c,e)){if("constant"===c.type)return jb(c.value,e);var f=hb(e)([c]);if(!f)return console.error("cannot find an implementation for "+A(c)+" -> "+A(e)+", using identity"),b;e=f.m;return e(W(a,b,c,f.s[0]),{},a)}console.error(A(c)+" is no subtype of "+A(e)+" (trying to cast the term "+b+")");return b}function X(a,b,c){a.j[b]||(a.j[b]={});a.j[b].U||(a.j[b].U=[]);a.j[b].w||(a.j[b].w=!1);a.hasOwnProperty("global")||(a.j[b].global=c)}
function ac(a,b){var c=b.I;if(b.isuniform)return a.D[b.uvariable].type;if("variable"===b.ctype)return b=b.name,b=c[b]||b,a.j[b].w;if("function"===b.ctype&&a.l.hasOwnProperty(b.oper))return a.j[c[b.oper]].w;if("number"===b.ctype)return Xa(b);if("void"===b.ctype)return y.W;if("field"===b.ctype){a=I(Y(a,b.obj));if(1==b.key.length){if("list"===a.type)return a.parameters;if(D(a,y.A))return y.f}else if("xy"==b.key&&D(a,y.A))return y.F;if(!a)return!1}else{if("string"===b.ctype)return y.image;if("function"===
b.ctype||"infix"===b.ctype){c=Array(b.args.length);for(var e=!0,f=0;f<b.args.length;f++)c[f]=Y(a,b.args[f]),e&="constant"===c[f].type;if(e&&b.impl)return b={ctype:b.ctype,oper:b.oper,impl:b.impl,args:c.map(function(a){return a.value})},b=a.C.evaluateAndVal(b),Xa(b);a=va(b.oper);e=U[a]?U[a](c):!1;if(!e&&c.every(function(a){return Va(a)}))throw console.error("Could not find an implementation for "+a+" with args ("+c.map(A).join(", ")+")"),console.log(b),"error";return e?e.u:!1}}console.error("Don't know how to compute type of");
console.log(b);return!1}function Y(a,b){if(!b.la||!b.T||a.T>b.T)b.la=ac(a,b),b.T=a.T;return b.la}
function bc(a,b,c){function e(a,b,c){var e={},f;for(f in a)e[f]=a[f];a=ya();X(l,a,!1);g[a].w=c;g[a].pa=!0;e[b]=a;return e}function f(a,b,c,v){a.I=b;for(var q in a.args){var p=v||"repeat$2"===a.oper&&0==q||"repeat$3"===a.oper&&0==q||"_"===a.oper&&1==q,u=b;-1!=["repeat","forall","apply"].indexOf(va(a.oper))&&(1==q?u="repeat$2"===a.oper?e(b,"#",y.v):"repeat$3"===a.oper?e(b,a.args[1].name,y.v):"forall$2"===a.oper||"apply$2"===a.oper?e(b,"#",!1):"forall$3"===a.oper||"apply$3"===a.oper?e(b,a.args[1].name,
!1):b:2==q&&(u=a.args[1].I));f(a.args[q],u,c,p)}"field"===a.ctype&&f(a.obj,b,c,v);"variable"===a.ctype&&(q=a.name,q=b[q]||q,v&&l.j[q]&&(l.j[q].Z=!0));if("="===a.oper)v=a.args[0].name,v=b[v]||v,X(l,v,!0),g[v].U.push(a.args[1]);else if(a.oper&&"regional"===va(a.oper)&&"global"!=c)for(var na in a.args){v=a.args[na].name;var oa=ya();b[v]=oa;k[c].j||(k[c].j=[]);k[c].j.push(oa);X(l,oa,!1)}else if("forall$2"===a.oper||"apply$2"===a.oper||"forall$3"===a.oper||"apply$3"===a.oper)g[2===a.args.length?a.args[1].I["#"]:
a.args[2].I[a.args[1].name]].U.push({ctype:"infix",oper:"_",args:[a.args[0],{ctype:"number",value:{real:1,imag:0}}],I:a.args[0].I});else if("function"===a.ctype&&k.hasOwnProperty(a.oper)){c=a.oper;na=c.replace("$","_");X(l,na,!1);b[c]=na;b={};for(oa in k[c].arglist)q=k[c].arglist[oa].name,p=na+"_"+q,b[q]=p,X(l,p,!1),g[p].U.push(a.args[oa]);k[c].ta||(k[c].ta=!0,f(k[c].body,b,c,v),g[na].U.push(k[c].body))}}var g=a.j,k=a.l,l=a;f(b,c,"global",!1)}
function cc(a,b){function c(a){if(a.hasOwnProperty("dependsOnPixel"))return a.dependsOnPixel;if("variable"===a.ctype){var b=a.name;b=a.I[b]||b;return k[b]?a.dependsOnPixel=!0:a.dependsOnPixel=!1}b="random randomint randominteger randombool randomnormal verbatimglsl".split(" ");if("function"===a.ctype&&-1!=b.indexOf(va(a.oper)))return a.dependsOnPixel=!0;if("repeat$2"===a.oper||"forall$2"===a.oper||"apply$2"===a.oper)return c(a.args[1])?(k[a.args[1].I["#"]]=!0,a.dependsOnPixel=!0):a.dependsOnPixel=
!1;if("repeat$3"===a.oper||"forall$3"===a.oper||"apply$3"===a.oper)return c(a.args[2])?(k[a.args[2].I[a.args[1].name]]=!0,a.args[1].dependsOnPixel=!0,a.dependsOnPixel=!0):a.dependsOnPixel=!1;for(var e in a.args)if(c(a.args[e]))return a.dependsOnPixel=!0;return"function"===a.ctype&&g.hasOwnProperty(a.oper)&&c(g[a.oper].body)?a.dependsOnPixel=!0:"field"===a.ctype?a.dependsOnPixel=c(a.obj):a.dependsOnPixel=!1}function e(a,b){if(c(a)){for(var f in a.args)e(a.args[f],b||"repeat$2"===a.oper&&0==f||"repeat$3"===
a.oper&&0==f||"_"===a.oper&&1==f);"field"===a.ctype&&e(a.obj,b);"function"===a.ctype&&g.hasOwnProperty(a.oper)&&(a=a.oper,p.hasOwnProperty(a)||(p[a]=!0,e(g[a].body,b)))}else if("boolean"!==a.ctype&&"number"!==a.ctype&&"void"!==a.ctype){".."===a.oper&&(b=!0);f=!1;var k;for(k in u)if(!f&&ua(a,u[k].X)){f=!0;var l=k}f||(l=ya(),u[l]={X:a,type:!1,Z:b});u[l].Z=u[l].Z||b;a.isuniform=!0;a.uvariable=l}}var f=a.j,g=a.l,k={cgl_pixel:!0,"cgl_pixel.x":!0,"cgl_pixel.y":!0},l;for(l in f)if(1<=f[l].U.length||f[l].pa)k[l]=
!0;c(b);var p={"":!0},u=a.D;e(b,!1)}function dc(a,b){if("function"===b.ctype&&!a.l.hasOwnProperty(b.oper)&&null!==a.C.getMyfunction(b.oper)){var c=b.oper;a.l[c]=ta(a.C.getMyfunction(c));dc(a,a.l[c].body)}for(var e in b.args)dc(a,b.args[e])}
function ec(a,b){function c(a){var b={},c;for(c in a)b[c]=a[c];return b}function e(a,b){"repeat$2"===a.oper||"forall$2"===a.oper||"apply$2"===a.oper?(b=c(b),b["#"]=!0):"repeat$3"===a.oper||"forall$3"===a.oper||"apply$3"===a.oper?(b=c(b),b[a.args[1].name]=!0):"="===a.oper&&(b[a.args[0].name]=!0);for(var f in a.args)e(a.args[f],b);"field"===a.ctype&&e(a.obj,b);"variable"===a.ctype&&(a=a.name,b[a]||(g[a]=!0))}var f={},g={};e(b,{});X(a,"cgl_pixel",!1);a.j.cgl_pixel.w=y.F;if(1==Object.keys(g).length)f[Object.keys(g)[0]]=
"cgl_pixel";else if(g["#"])f["#"]="cgl_pixel";else if(g.x&&g.y)X(a,"cgl_pixel.x",!1),a.j["cgl_pixel.x"].w=y.f,f.x="cgl_pixel.x",X(a,"cgl_pixel.y",!1),a.j["cgl_pixel.y"].w=y.f,f.y="cgl_pixel.y";else{b=[];for(var k in g)a.C.nada==a.C.evaluateAndVal({ctype:"variable",name:k})&&b.push(k);1==b.length?f[b[0]]="cgl_pixel":g.p?f.p="cgl_pixel":g.z&&(f.z="cgl_pixel")}"cgl_pixel"===f.z&&(a.j.cgl_pixel.w=y.h);return f}
function Z(a,b,c){var e=Y(a,b);if(b.isuniform)return b=b.uvariable,c?{code:"",o:"constant"===e.type?jb(e.value,I(e)):b}:{code:""};if(";"===b.oper){e={o:""};for(var f="",g=b.args.length-1,k=g;0<=k;k--)"void"===b.args[k].ctype&&(g=k-1);for(k=0;k<=g;k++)e=Z(a,b.args[k],c&&k===g),f+=e.code;return c?{code:f,o:e.o}:{code:f}}if("constant"===e.type)return c?{o:jb(e.value,I(e)),code:""}:{code:""};if("="===b.oper)return e=Z(a,b.args[1],!0),b=Z(a,b.args[0],!0).o+" = "+W(a,e.o,Y(a,b.args[1]),Y(a,b.args[0])),
c?{code:e.code,o:b}:{code:e.code+b+";\n"};if("repeat$2"===b.oper||"repeat$3"===b.oper){f=Z(a,b.args[0],!0);if("constant"!==Y(a,b.args[0]).type)return console.error("repeat possible only for fixed constant number in GLSL"),!1;e="repeat$2"===b.oper?b.args[1].I["#"]:b.args[2].I[b.args[1].name];f=Number(f.o);g="";if("constant"===a.j[e].w.type)for(k=1;k<=f;k++){a.j[e].w=bb(k);a.T++;var l=Z(a,b.args["repeat$2"===b.oper?1:2],k===f&&c);g+=l.code;if(k===f&&c)return{code:g,o:l.o}}else if(k="",l=Z(a,b.args["repeat$2"===
b.oper?1:2],c),b=Y(a,b.args["repeat$2"===b.oper?1:2]),c&&(k=ya(),a.j[k]||(X(a,k,!0),a.j[k].w=b)),g=g+("for(int "+e+"=1; "+e+" <= "+f+"; "+e+"++) {\n")+l.code,c&&(g+=k+" = "+l.o+";\n"),g+="}\n",c)return{code:g,o:k};return{code:g}}if("forall$2"===b.oper||"forall$3"===b.oper||"apply$2"===b.oper||"apply$3"===b.oper){var p=Y(a,b.args[0]);if("list"!==p.type&&("constant"!==p.type||"list"!==p.value.ctype))return console.error(b.oper+" only possible for lists"),!1;f=p.length||p.value.value.length;k=2===b.args.length?
b.args[1].I["#"]:b.args[2].I[b.args[1].name];var u=a.j[k].w,q=l="";c&&(q=ya(),l+=Q(e)+" "+q+";\n");"list"===e.type&&mb(e,a);if("constant"===a.j[k].w.type||"constant"===p.type)for(p=a.C.evaluateAndVal(b.args[0]),u=0;u<f;u++)a.j[k].w=Xa(p.value[u]),a.T++,g=Z(a,b.args[2===b.args.length?1:2],c),l+=g.code,"forall$2"===b.oper||"forall$3"===b.oper?u+1===f&&c&&(l+=q+" = "+g.o+";\n"):c&&(l+=P(e,u)([q],[],a)+" = "+g.o+";\n");else{g=Z(a,b.args[2===b.args.length?1:2],c);var v=Z(a,b.args[0],!0);l+=v.code;var H=
v.o;!a.j[H]&&!a.D[H]&&2<=p.length&&(H=ya(),l+=Q(p)+" "+H+" = "+v.o+";\n");a.j[k].global=!0;for(v=0;v<f;v++)l+=k+" = "+P(p,v)([H],[],a)+";\n",l+=g.code,c&&("forall$2"===b.oper||"forall$3"===b.oper?v===f-1&&(l+=q+" = "+g.o+";\n"):l+=P(e,v)([q],[],a)+" = "+g.o+";\n");"list"===u.type&&mb(u,a)}return c?{code:l,o:q}:{code:l}}if("if$2"===b.oper||"if$3"===b.oper){l=Z(a,b.args[0],!0);f=Y(a,b.args[0]);k=g="";q=Z(a,b.args[1],c);c&&(k=ya(),a.j[k]||(X(a,k,!0),a.j[k].w=e));"constant"!=f.type&&(g+=l.code,g+="if("+
l.o+") {\n");if("constant"!=f.type||"constant"==f.type&&f.value.value)g+=q.code,c&&(g+=k+" = "+W(a,q.o,Y(a,b.args[1]),e)+";\n");"if$3"===b.oper&&(l=Z(a,b.args[2],c),"constant"!=f.type&&(g+="} else {\n"),"constant"!=f.type||"constant"==f.type&&!f.value.value)&&(g+=l.code,c&&(g+=k+" = "+W(a,l.o,Y(a,b.args[2]),e)+";\n"));"constant"!=f.type&&(g+="}\n");return c?{code:g,o:k}:{code:g}}if("function"===b.ctype||"infix"===b.ctype){l=b.oper;if("verbatimglsl"===va(l))return b=a.C.evaluateAndVal(b.args[0]).value,
c?{o:b,code:""}:{code:b};e=b.args.map(function(b){return Z(a,b,!0)});f=b.args.map(function(b){return Y(a,b)});if(a.l.hasOwnProperty(l))for(k=fc(a,l),g=Array(e.length),q=0;q<e.length;q++)g[q]=a.j[a.l[l].body.I[a.l[l].arglist[q].name]].w;else{l=va(l);if("regional"===l)return c?{o:"",code:""}:{code:""};k=U[l](f);if(!k)return console.error("Could not find an implementation for "+l+"("+f.map(A).join(", ")+").\nReturning empty code"),c?{o:"",code:""}:{code:""};g=k.s;k=k.m}l="";q=Array(e.length);for(p=0;p<
e.length;p++)l+=e[p].code,q[p]=W(a,e[p].o,f[p],g[p]);b=k(q,b.modifs,a);return c?{o:b,code:l}:{code:l+b+";\n"}}if("variable"===b.ctype)return e=b.name,e=b.I[e]||e,c?{o:e,code:""}:{code:e+";\n"};if("void"===b.ctype)return c?{o:"",code:""}:{code:""};if("field"===b.ctype&&(e=Y(a,b.obj),k={x:0,y:1,z:2,r:0,g:1,b:2,a:3}[b.key],f=!1,g=Z(a,b.obj,!0).o,void 0!=k&&"list"===e.type?f=P(e,k)([g],null,a):"xy"===b.key&&"list"===e.type?(2===e.length&&(f=g),3===e.length&&(f=N("dehomogenize")([W(a,g,e,y.A)],null,a))):
e===y.A&&(k={xy:"dehomogenize",x:"dehomogenizex",y:"dehomogenizey"},k[b.key]&&(f=N(k[b.key])([W(a,g,e,y.A)],null,a))),f))return c?{o:f,code:""}:{code:f+";\n"};console.error("dont know how to this.compile "+JSON.stringify(b))}function fc(a,b){gc(a,b,a.l[b].arglist.length);return M(b.replace("$","_"))}
function gc(a,b,c){if(!a.mark("compiledfunctions",b)){for(var e=a.l[b],f=b.replace("$","_"),g=e.body.I,k=Array(c),l=0;l<c;l++)k[l]=e.arglist[l].name;c=a.j[f].w===y.W;var p=Q(a.j[f].w)+" "+f+"("+k.map(function(b){return Q(a.j[g[b]].w)+" "+g[b]}).join(", ")+"){\n";for(u in e.j)k=e.j[u],p+=Q(a.j[k].w)+" "+k+";\n";var u=Z(a,e.body,!c);e=Y(a,e.body);p+=u.code;c||(p+="return "+W(a,u.o,e,a.j[f].w)+";\n");p+="}\n";a.add("compiledfunctions",b,function(){return p})}}
function Sa(a,b){xa=0;var c=b=ta(b);dc(a,c);bc(a,c,ec(a,c));cc(a,c);for(var e in a.D){c=a.C.evaluateAndVal(a.D[e].X);if(!c.ctype||"undefined"===c.ctype){console.error("can not evaluate:");console.log(a.D[e].X);break}a.D[e].type=a.D[e].Z?Xa(c):wa(c)}e=!0;for(var f in a.j)a.j[f].w=a.j[f].w||!1,a.j[f].Z&&(a.j[f].w=bb(1),a.T++);for(;e;){e=!1;for(var g in a.j)if(!a.j[g].Z)for(var k in a.j[g].U){f=I(Y(a,a.j[g].U[k]));var l=c=a.j[g].w||!1;f&&(c?D(f,c)?l=c:l=z(c,f):l=f,l&&l!==c&&(a.j[g].w=l,a.T++,e=!0))}}for(var p in a.D)"list"===
a.D[p].type.type&&mb(a.D[p].type,a);for(var u in a.j)"list"===a.j[u].w.type&&mb(a.j[u].w,a);g=Z(a,b,!0);k=Y(a,b);b=W(a,g.o,k,y.color);D(k,y.color)||console.error("expression does not generate a color");k=$b(a,"structs");k+=$b(a,"uniforms");p=[];for(var q in a.D)"constant"!=a.D[q].type.type&&a.D[q].type!=y.image&&p.push("uniform "+Q(a.D[q].type)+" "+q+";");k+=p.join("\n");q="";for(var v in a.O)q+=a.O[v].code+"\n";k=k+q+$b(a,"includedfunctions");k+=$b(a,"functions");for(var H in a.j)a.j[H].w&&a.j[H].global&&
(k+=Q(a.j[H].w)+" "+H+";\n");k+=$b(a,"compiledfunctions");k+="void main(void) {\n"+g.code+"gl_FragColor = "+b+";\n}\n";console.log(k);v={};if(a.i.compiledfunctions)for(var V in a.i.compiledfunctions.ja)v[V]=a.C.getMyfunction(V).generation;return{code:k,D:a.D,O:a.O,ia:v}};function hc(a,b,c,e){this.X=b;this.C=e;this.l=c;ic(this);b=this.i;this.name=a;this.code="uniform sampler2D _sampler"+a+";\nuniform float _ratio"+a+";\nuniform vec2 _cropfact"+a+";\nvec4 _imagergba"+a+"(vec2 A, vec2 B, vec2 p) {\n  p -= A; B -= A;\n  float b = dot(B,B);\n  p = vec2(dot(p,B),_ratio"+a+"*dot(p,vec2(-B.y,B.x)))/b;\n  "+(b.repeat?"p = mod(p, vec2(1.));":"")+"\n  "+(b.repeat&&b.N?"vec4 color = vec4(0.);\n    float totalWeight = 0.;\n    for(int dx=0; dx<2; dx++) for(int dy=0; dy<2; dy++) {\n      vec2 delta = .5*vec2(dx, dy);\n      vec2 center = delta+vec2(.5);\n      vec2 tc = fract(p-delta)+delta;\n      float dst = dot(abs(tc-center),vec2(1.));\n      float w = max(.5-dst,0.);\n      w=w*w;\n      color += w * texture2D(_sampler"+
a+", tc*_cropfact"+a+");\n      totalWeight += w;\n    }\n    return color/totalWeight;":b.repeat?"return texture2D(_sampler"+a+", p*_cropfact"+a+");":"if(0. <= p.x && p.x <= 1. && 0. <= p.y && p.y <= 1.)\n          return texture2D(_sampler"+a+", p*_cropfact"+a+");\n       else\n          return vec4(0.);")+"\n  }"}
function ic(a){var b=a.l,c=a.C;b={S:b.hasOwnProperty("interpolate")?c.evaluateAndVal(b.interpolate).value:!0,N:b.hasOwnProperty("mipmap")?c.evaluateAndVal(b.mipmap).value:!1,repeat:b.hasOwnProperty("repeat")?c.evaluateAndVal(b.repeat).value:!1};!a.i||a.i.N==b.N&&a.i.repeat==b.repeat||(console.log("enfore recompilation because texture modifiers changed."),qa++);a.i=b}
function Za(a){var b=a.C.evaluateAndVal(a.X).value,c="string"===typeof b?a.C.getImage(b,!0):b;if(null==c)return console.error("Could not find image "+b+"."),t;ic(a);return La(c,a.C,a.i)}function jc(a,b,c){c.O.hasOwnProperty(a)||(c.O[a]=new hc(a,c.D[a].X,b,c.C));return a}function Zb(a,b,c){return["_imagergba",jc(a[2],b,c),"(",a[0],",",a[1],",",a[3],")"].join("")}function Xb(a,b,c){return["(_imagergba",jc(a[2],b,c),"(",a[0],",",a[1],",",a[3],").rgb)"].join("")}
function Yb(a,b,c){c.add("uniforms","corners",function(){return"uniform vec2 _lowerleft, _lowerright;"});return["_imagergba",jc(a[0],b,c),"(_lowerleft, _lowerright, ",a[1],")"].join("")}function Wb(a,b,c){c.add("uniforms","corners",function(){return"uniform vec2 _lowerleft, _lowerright;"});return["(_imagergba",jc(a[0],b,c),"(_lowerleft, _lowerright, ",a[1],").rgb)"].join("")};function kc(a){var b=void 0===b?null:b;return"list"!==a.ctype?(console.log("argument is not a list"),b):a.value}function ab(a){var b=void 0===b?[.5,.5,.5]:b;if("number"===a.ctype){var c=lc(a);if(!isNaN(c))return[c,c,c]}a=kc(a);return null===a?b:3!=a.length?(console.log("Not an RGB color vector"),b):a.map(function(a){return lc(a)})}
function $a(a){var b=void 0===b?Number.NaN:b;if("number"!==a.ctype)return console.log("argument is not a number"),b;b=a.value;a=b.real;b=b.imag;0!==b&&console.log("complex number is not real");b=Math.round(a);b!==a&&console.log("number is not an integer");return b}
function lc(a){var b=void 0===b?Number.NaN:b;b=void 0===b?Number.NaN:b;"number"!==a.ctype?(console.log("argument is not a number"),a=b):(a=a.value,b=a.real,0!==a.imag&&console.log("complex number is not real"),a=b);return 0>a?0:1<a?1:a};function sa(a){this.message=a}sa.prototype.toString=function(){return this.message};
function Oa(a,b){var c=r;this.i=c.createProgram();c.i&&(a="#version 300 es\n"+a.replace(/attribute/g,"in").replace(/varying/g,"out"),b="#version 300 es\n"+b.replace(/varying/g,"in").replace(/gl_FragColor/g,"FragColor").replace(/texture2D/g,"texture").replace(/precision highp float;/g,"precision highp float;\n#define webgl2 true\nout vec4 FragColor;"));this.Y=mc(this,c,c.VERTEX_SHADER,a);mc(this,c,c.FRAGMENT_SHADER,b);a=this.i;c.linkProgram(a);if(!c.getProgramParameter(a,c.LINK_STATUS))throw new sa("Error linking shader:\n"+
c.getProgramInfoLog(a));c.validateProgram(a);if(!c.getProgramParameter(a,c.VALIDATE_STATUS))throw new sa("Error validating shader:\n"+c.getProgramInfoLog(a));var e=this.i,f,g,k={},l;b=c.getProgramParameter(e,c.ACTIVE_UNIFORMS);for(a=0;a<b;++a){var p=c.getActiveUniform(e,a);if(null!==p&&(f=p.name.replace(/\]/g,""))){for(l=k;null!==(g=/[.\[]/.exec(f));){var u=f.substr(0,g.index);l.hasOwnProperty(u)?l=l[u]:"."===g[0]?l=l[u]={}:l=l[u]=[];f=f.substr(g.index+1)}if(1<p.size){g=p.size;var q=Array(g);for(u=
0;u<g;++u){var v=p.name+"["+u+"]";v=nc(this,c,v,p);q[u]=v}l[f]=q}else v=nc(this,c,p.name,p),l[f]=v}}this.l=k}function mc(a,b,c,e){c=b.createShader(c);b.shaderSource(c,e);b.compileShader(c);if(!b.getShaderParameter(c,b.COMPILE_STATUS))throw console.warn(e.split("\n")),new sa("Error compiling shader:\n"+b.getShaderInfoLog(c));b.attachShader(a.i,c);return c}
function nc(a,b,c,e){a=b.getUniformLocation(a.i,c);switch(e.type){case b.FLOAT:return b.uniform1fv.bind(b,a);case b.FLOAT_VEC2:return b.uniform2fv.bind(b,a);case b.FLOAT_VEC3:return b.uniform3fv.bind(b,a);case b.FLOAT_VEC4:return b.uniform4fv.bind(b,a);case b.BOOL:case b.INT:case b.SAMPLER_2D:case b.SAMPLER_CUBE:return b.uniform1iv.bind(b,a);case b.BOOL_VEC2:case b.INT_VEC2:return b.uniform2iv.bind(b,a);case b.BOOL_VEC3:case b.INT_VEC3:return b.uniform3iv.bind(b,a);case b.BOOL_VEC4:case b.INT_VEC4:return b.uniform4iv.bind(b,
a);case b.FLOAT_MAT2:return b.uniformMatrix2fv.bind(b,a,!1);case b.FLOAT_MAT3:return b.uniformMatrix3fv.bind(b,a,!1);case b.FLOAT_MAT4:return b.uniformMatrix4fv.bind(b,a,!1);default:throw new sa("Unknown data type for uniform "+c);}};
}).call(this);//# sourceMappingURL=CindyGL.js.map


